'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const W=require('../shared/kart/world');const S=require('../shared/kart/simulation');
const roster=[{pid:'a',name:'A',color:'#ff5566'},{pid:'b',name:'B',color:'#55aaff'}];const neutral={steer:0,active:true};
function drive(s){const inputs=new Map();for(const k of s.karts){const n=W.nearest(k.x,k.z),target=W.TRACK[(n.index+4)%W.TRACK.length],desired=Math.atan2(target.x-k.x,target.z-k.z),error=Math.atan2(Math.sin(desired-k.heading),Math.cos(desired-k.heading));inputs.set(k.pid,{active:true,steer:Math.max(-1,Math.min(1,error*1.4))});}S.step(s,inputs,1/60);}
test('two independent drivers complete three laps using real controls',()=>{const s=S.createMatch(roster,'race');for(let i=0;i<14400&&!s.finished;i++)drive(s);assert.equal(s.finished,true);assert.equal(s.results.length,2);for(const k of s.karts){assert.equal(k.finished,true,`kart ${k.pid} did not finish: ${k.lap} laps, ${k.travel} checkpoints`);assert.equal(k.lap,3);assert.equal(k.travel,36);assert.ok(k.finishTime>20&&k.finishTime<240);}assert.ok(s.results[0].finishTime<=s.results[1].finishTime);});
test('skipping checkpoints cannot award a lap',()=>{const s=S.createMatch(roster,'race'),k=s.karts[0];for(const p of [.9,.99,.01,.3,.99,.01]){Object.assign(k,W.point(p));S.step(s,new Map(),1/60);}assert.equal(k.lap,0);assert.equal(k.travel,0);});
test('drift release awards boost and manual boost has cooldown',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0];k.x=0;k.z=0;k.speed=20;for(let i=0;i<55;i++)S.step(s,new Map([['a',{active:true,steer:.35,drift:true}]]),1/60);assert.ok(k.driftCharge>.65);S.step(s,new Map([['a',{active:true,steer:.35,drift:false}]]),1/60);assert.ok(k.boost>.5);S.step(s,new Map([['a',{...neutral,boost:true}]]),1/60);const remaining=k.boostCooldown;assert.ok(remaining>8);S.step(s,new Map([['a',neutral]]),1/60);k.boost=0;S.step(s,new Map([['a',{...neutral,boost:true}]]),1/60);assert.equal(k.boost,0);assert.ok(k.boostCooldown<remaining);});
test('rocket earns kill and victim respawns after three seconds',()=>{const s=S.createMatch(roster,'battle'),[a,b]=s.karts;Object.assign(a,{x:0,z:-8,y:0,heading:0,shield:0,item:'rocket'});Object.assign(b,{x:0,z:4,y:0,heading:Math.PI,shield:0,hp:30});S.step(s,new Map([['a',{active:true,item:true}]]),1/60);for(let i=0;i<40;i++)S.step(s,new Map(),1/60);assert.equal(a.kills,1);assert.equal(b.deaths,1);assert.ok(b.respawn>0);for(let i=0;i<190;i++)S.step(s,new Map(),1/60);assert.equal(b.respawn,0);assert.equal(b.hp,100);});
test('held item does not spend newly collected item',()=>{const s=S.createMatch(roster,'battle'),a=s.karts[0],input=new Map([['a',{active:true,item:true}]]);a.item='shield';S.step(s,input,1/60);a.item='rocket';S.step(s,input,1/60);assert.equal(a.item,'rocket');});
test('four-player simulation stays finite and inactive inputs brake',()=>{const s=S.createMatch([...roster,{pid:'c'},{pid:'d'}],'battle');for(let i=0;i<1200;i++){const inputs=new Map(s.karts.map((k,j)=>[k.pid,{active:true,steer:Math.sin(i*.031+j),drift:i%100<70,boost:i%300===0,item:true}]));S.step(s,inputs,1/60);}for(const k of s.karts)for(const key of ['x','y','z','speed','vx','vz','heading'])assert.ok(Number.isFinite(k[key]),key);for(let i=0;i<100;i++)S.step(s,new Map(),1/60);for(const k of s.karts)assert.equal(k.speed,0);});
test('public snapshots are copies and battle expires at two minutes',()=>{const s=S.createMatch(roster,'battle'),p=S.publicState(s);p.karts[0].hp=1;p.pickups[0].cooldown=99;assert.equal(s.karts[0].hp,100);assert.equal(s.pickups[0].cooldown,0);s.time=119.99;S.step(s,new Map(),1/60);assert.equal(s.finished,true);assert.equal(s.results.length,2);});

test('wrong-way crossing of start cannot take first place',()=>{const s=S.createMatch(roster,'race');Object.assign(s.karts[0],W.point(.99));Object.assign(s.karts[1],W.point(.02));S.step(s,new Map(),1/60);assert.equal(s.karts[1].position,1);assert.equal(s.karts[0].position,2);});
