'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const W=require('../shared/kart/world');const S=require('../shared/kart/simulation');
const roster=[{pid:'a',name:'A',color:'#ff5566'},{pid:'b',name:'B',color:'#55aaff'}];const neutral={steer:0,active:true,throttle:true};
function drive(s){const inputs=new Map();for(const k of s.karts){const n=W.nearest(k.x,k.z),target=W.TRACK[(n.index+4)%W.TRACK.length],desired=Math.atan2(target.x-k.x,target.z-k.z),error=Math.atan2(Math.sin(desired-k.heading),Math.cos(desired-k.heading));inputs.set(k.pid,{active:true,throttle:true,steer:Math.max(-1,Math.min(1,error*1.4))});}S.step(s,inputs,1/60);}
test('two independent drivers complete three laps using real controls',()=>{const s=S.createMatch(roster,'race');for(let i=0;i<14400&&!s.finished;i++)drive(s);assert.equal(s.finished,true);assert.equal(s.results.length,2);for(const k of s.karts){assert.equal(k.finished,true,`kart ${k.pid} did not finish: ${k.lap} laps, ${k.travel} checkpoints`);assert.equal(k.lap,3);assert.equal(k.travel,36);assert.ok(k.finishTime>20&&k.finishTime<240);}assert.ok(s.results[0].finishTime<=s.results[1].finishTime);});
test('skipping checkpoints cannot award a lap',()=>{const s=S.createMatch(roster,'race'),k=s.karts[0];for(const p of [.9,.99,.01,.3,.99,.01]){Object.assign(k,W.point(p));S.step(s,new Map(),1/60);}assert.equal(k.lap,0);assert.equal(k.travel,0);});
test('drift release awards boost and manual boost has cooldown',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0];k.x=0;k.z=0;k.speed=20;for(let i=0;i<55;i++)S.step(s,new Map([['a',{active:true,throttle:true,steer:.35,drift:true}]]),1/60);assert.ok(k.driftCharge>.65);S.step(s,new Map([['a',{active:true,throttle:true,steer:.35,drift:false}]]),1/60);assert.ok(k.boost>.5);S.step(s,new Map([['a',{...neutral,boost:true}]]),1/60);const remaining=k.boostCooldown;assert.ok(remaining>8);S.step(s,new Map([['a',neutral]]),1/60);k.boost=0;S.step(s,new Map([['a',{...neutral,boost:true}]]),1/60);assert.equal(k.boost,0);assert.ok(k.boostCooldown<remaining);});
test('rocket earns kill and victim respawns after three seconds',()=>{const s=S.createMatch(roster,'battle'),[a,b]=s.karts;Object.assign(a,{x:0,z:-8,y:0,heading:0,shield:0,item:'rocket'});Object.assign(b,{x:0,z:4,y:0,heading:Math.PI,shield:0,hp:30});S.step(s,new Map([['a',{active:true,item:true}]]),1/60);for(let i=0;i<40;i++)S.step(s,new Map(),1/60);assert.equal(a.kills,1);assert.equal(b.deaths,1);assert.ok(b.respawn>0);for(let i=0;i<190;i++)S.step(s,new Map(),1/60);assert.equal(b.respawn,0);assert.equal(b.hp,100);});
test('a non-lethal weapon hit removes momentum without stopping the kart',()=>{const s=S.createMatch(roster,'battle'),[a,b]=s.karts;Object.assign(a,{x:-30,z:-30,y:0});Object.assign(b,{x:0,z:0,y:0,heading:0,speed:20,vx:0,vz:20,shield:0});s.projectiles.push({id:s.nextId++,type:'rocket',owner:a.pid,x:0,z:0,y:.7,vx:0,vz:0,vy:0,life:1,age:1});const throttle=new Map([['b',{active:true,throttle:true,steer:0}]]);S.step(s,throttle,1/60);assert.ok(b.stun>0);for(let i=0;i<12;i++)S.step(s,throttle,1/60);assert.ok(b.speed>5,'weapon hit should leave recoverable momentum');assert.ok(b.speed<15,'weapon hit should cause a strong slowdown');});
test('held item does not spend newly collected item',()=>{const s=S.createMatch(roster,'battle'),a=s.karts[0],input=new Map([['a',{active:true,item:true}]]);a.item='shield';S.step(s,input,1/60);a.item='rocket';S.step(s,input,1/60);assert.equal(a.item,'rocket');});
test('a thrown bomb inherits momentum and moves ahead of a fast kart',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0];Object.assign(k,{x:0,z:0,heading:0,speed:37,vx:0,vz:37,item:'bomb'});S.useItem(s,k);const bomb=s.projectiles[0];assert.equal(bomb.type,'bomb');assert.ok(bomb.vz>k.speed,'bomb should retain kart momentum plus its throw impulse');});
test('ground traps released during a hop land on the track',()=>{for(const type of ['banana','nitro']){const s=S.createMatch(roster,'battle'),k=s.karts[0];Object.assign(k,{x:0,z:0,y:2.5,heading:0,item:type});S.useItem(s,k);const trap=s.projectiles[0];assert.equal(trap.type,type);assert.equal(trap.y,W.ground(trap.x,trap.z,'battle',k.y)+.7);}});
test('banana slips, nitro explodes and clock slows rivals',()=>{const s=S.createMatch(roster,'battle'),[a,b]=s.karts;Object.assign(a,{x:-20,z:-20,shield:0});Object.assign(b,{x:0,z:0,y:0,heading:0,speed:20,vx:0,vz:20,shield:0});s.projectiles.push({id:s.nextId++,type:'banana',owner:a.pid,x:0,z:0,y:.7,vx:0,vz:0,vy:0,life:2,age:1});S.step(s,new Map(),1/60);assert.ok(b.slip>2);assert.ok(b.speed<20);Object.assign(b,{x:0,z:0,y:0,hp:100,shield:0,respawn:0});s.projectiles.push({id:s.nextId++,type:'nitro',owner:a.pid,x:0,z:0,y:.7,vx:0,vz:0,vy:0,life:2,age:1});S.step(s,new Map(),1/60);assert.ok(b.hp<100);Object.assign(b,{speed:20,vx:0,vz:20,shield:0,respawn:0,finished:false});a.item='clock';S.useItem(s,a);assert.ok(b.clockSlow>2);assert.ok(b.speed<15);});
test('four-player simulation stays finite and inactive inputs brake',()=>{const s=S.createMatch([...roster,{pid:'c'},{pid:'d'}],'battle');for(let i=0;i<1200;i++){const inputs=new Map(s.karts.map((k,j)=>[k.pid,{active:true,throttle:true,steer:Math.sin(i*.031+j),drift:i%100<70,boost:i%300===0,item:true}]));S.step(s,inputs,1/60);}for(const k of s.karts)for(const key of ['x','y','z','speed','vx','vz','heading'])assert.ok(Number.isFinite(k[key]),key);for(let i=0;i<100;i++)S.step(s,new Map(),1/60);for(const k of s.karts)assert.equal(k.speed,0);});
test('acceleration is progressive and releasing A lets the kart coast',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0],accelerate=new Map([['a',{active:true,throttle:true,steer:0}]]),coast=new Map([['a',{active:true,throttle:false,steer:0}]]);k.x=0;k.z=0;k.heading=0;S.step(s,accelerate,1/60);assert.ok(k.speed>0&&k.speed<1);for(let i=0;i<59;i++)S.step(s,accelerate,1/60);const afterOneSecond=k.speed;assert.ok(afterOneSecond>10&&afterOneSecond<24);for(let i=0;i<60;i++)S.step(s,accelerate,1/60);assert.ok(k.speed>afterOneSecond&&k.speed<=25);const moving=k.speed;Object.assign(k,{x:0,z:0,vx:0,vz:moving,boost:0,padCooldown:2});for(let i=0;i<120;i++)S.step(s,coast,1/60);assert.ok(k.speed<moving);assert.ok(k.speed>moving*.65,'releasing A should preserve momentum');Object.assign(k,{x:0,z:0,vx:0,vz:k.speed,padCooldown:2});for(let i=0;i<600;i++)S.step(s,coast,1/60);assert.equal(k.speed,0);});
test('pressing B hops without consuming the kart momentum',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0];Object.assign(k,{x:0,z:0,heading:0,speed:22,vx:0,vz:22});S.step(s,new Map([['a',{active:true,throttle:false,steer:0,drift:true}]]),1/60);assert.ok(k.y>0);assert.ok(k.vy>0);for(let i=0;i<29;i++)S.step(s,new Map([['a',{active:true,throttle:false,steer:0,drift:true}]]),1/60);assert.ok(k.speed>18,'a jump should coast instead of braking');});
test('holding B with steering turns the hop into a drift',()=>{const s=S.createMatch(roster,'battle'),k=s.karts[0];Object.assign(k,{x:0,z:0,heading:0,speed:18,vx:0,vz:18});const drift=new Map([['a',{active:true,throttle:false,steer:.7,drift:true}]]);for(let i=0;i<20;i++)S.step(s,drift,1/60);assert.ok(k.y>0,'drift should begin with a hop');assert.equal(k.wasDrifting,true);assert.equal(k.driftDir,1);assert.ok(k.driftCharge>0);});
test('a hop can dodge oil and mines on the ground',()=>{const s=S.createMatch(roster,'battle'),[a,b]=s.karts;Object.assign(a,{x:0,z:0,y:0,heading:0,speed:14,vx:0,vz:14,shield:0});Object.assign(b,{x:-30,z:-30,y:0});const hop=new Map([['a',{active:true,throttle:false,steer:0,drift:true}]]);S.step(s,hop,1/60);for(let i=0;i<9;i++)S.step(s,new Map([['a',{active:true,throttle:false,steer:0,drift:false}]]),1/60);assert.ok(a.y>.75);s.projectiles.push({id:s.nextId++,type:'oil',owner:b.pid,x:a.x,z:a.z,y:.7,vx:0,vz:0,vy:0,life:2,age:1});S.step(s,new Map([['a',{active:true,throttle:false,steer:0,drift:false}]]),1/60);assert.equal(a.slip,0);});
test('entering grass smoothly returns the kart to its off-road speed',()=>{const s=S.createMatch(roster.slice(0,1),'race'),k=s.karts[0],start=W.point(.1,10);Object.assign(k,start,{speed:25,vx:Math.sin(start.heading)*25,vz:Math.cos(start.heading)*25,lastGround:start.y});const throttle=new Map([['a',{active:true,throttle:true,steer:0}]]);for(let i=0;i<30;i++)S.step(s,throttle,1/60);assert.ok(k.speed>=11);assert.ok(k.speed<16,'grass should remove excess road speed promptly');});
test('steering is responsive at low speed and heavier at high speed',()=>{const lowMatch=S.createMatch(roster,'battle'),highMatch=S.createMatch(roster,'battle'),low=lowMatch.karts[0],high=highMatch.karts[0];Object.assign(low,{x:0,z:0,heading:0,speed:4,vx:0,vz:4});Object.assign(high,{x:0,z:0,heading:0,speed:24,vx:0,vz:24});const steer=new Map([['a',{active:true,throttle:false,steer:1}]]);for(let i=0;i<20;i++){S.step(lowMatch,steer,1/60);S.step(highMatch,steer,1/60);}assert.ok(low.heading>high.heading,'low-speed steering should turn more sharply');assert.ok(high.vz>0,'high-speed steering should preserve lateral momentum');});
test('kart collisions reduce momentum without stopping either kart',()=>{const s=S.createMatch(roster,'battle'),freeMatch=S.createMatch(roster.slice(0,1),'battle'),[a,b]=s.karts,free=freeMatch.karts[0],coast={active:true,throttle:false,steer:0};Object.assign(a,{x:-1,z:0,y:0,heading:Math.PI/2,speed:20,vx:20,vz:0,shield:0});Object.assign(b,{x:1,z:0,y:0,heading:-Math.PI/2,speed:20,vx:-20,vz:0,shield:0});Object.assign(free,{x:-1,z:0,y:0,heading:Math.PI/2,speed:20,vx:20,vz:0,shield:0});S.step(s,new Map([['a',coast],['b',coast]]),1/60);S.step(freeMatch,new Map([['a',coast]]),1/60);for(const k of [a,b]){assert.ok(k.speed<free.speed,'impact should remove extra momentum');assert.ok(k.speed>5,'impact should not stop the kart');}});
test('race course has varied bends, jump lines and boost choices',()=>{const race=W.map('race');assert.ok(race.ramps.length>=3);assert.ok(race.boosts.length>=4);assert.ok(race.shortcuts.length>=2);const widths=W.TRACK.map((p,i)=>Math.hypot(p.x-W.TRACK[(i+1)%W.TRACK.length].x,p.z-W.TRACK[(i+1)%W.TRACK.length].z));assert.ok(Math.max(...widths)-Math.min(...widths)>.8,'track should contain varied curves instead of a plain oval');});
test('public snapshots are copies and battle expires at two minutes',()=>{const s=S.createMatch(roster,'battle'),p=S.publicState(s);p.karts[0].hp=1;p.pickups[0].cooldown=99;assert.equal(s.karts[0].hp,100);assert.equal(s.pickups[0].cooldown,0);s.time=119.99;S.step(s,new Map(),1/60);assert.equal(s.finished,true);assert.equal(s.results.length,2);});

test('wrong-way crossing of start cannot take first place',()=>{const s=S.createMatch(roster,'race');Object.assign(s.karts[0],W.point(.99));Object.assign(s.karts[1],W.point(.02));S.step(s,new Map(),1/60);assert.equal(s.karts[1].position,1);assert.equal(s.karts[0].position,2);});
