(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.KartWorld=api;})(globalThis,function(){
'use strict';
const ROAD_WIDTH=16;
const TRACK=Array.from({length:96},(_,i)=>{const a=i/96*Math.PI*2;return{x:Math.sin(a)*70,z:Math.cos(a)*45,y:2*(1-Math.cos(a))};});
function nearest(x,z){let best={distance:Infinity};for(let i=0;i<TRACK.length;i++){const a=TRACK[i],b=TRACK[(i+1)%96],dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz))),px=a.x+dx*t,pz=a.z+dz*t,distance=Math.hypot(x-px,z-pz);if(distance<best.distance)best={x:px,z:pz,y:a.y+(b.y-a.y)*t,distance,progress:(i+t)/96%1,heading:Math.atan2(dx,dz),index:i};}return best;}
function point(p,offset=0){const a=p*Math.PI*2,heading=Math.atan2(70*Math.cos(a),-45*Math.sin(a));return{x:Math.sin(a)*70+Math.cos(heading)*offset,z:Math.cos(a)*45-Math.sin(heading)*offset,y:2*(1-Math.cos(a)),heading};}
const race={name:'Circuito Aurora',track:TRACK,width:ROAD_WIDTH,spawns:[point(.012,-3),point(.012,3),point(.001,-3),point(.001,3)],boosts:[point(.19),point(.57),point(.83)],pickups:[.10,.35,.62,.88].flatMap(p=>[point(p,-3),point(p,3)]),ramps:[{...point(.25),width:10,length:9,height:2.6}],barriers:[],hazards:[],platforms:[],shortcuts:[{x:0,z:-36,y:3.8,width:32,depth:7}]};
const battle={name:'Forte Prisma',track:[],width:110,spawns:[{x:-32,z:-32,y:0,heading:.8},{x:32,z:32,y:0,heading:3.9},{x:32,z:-32,y:0,heading:-.8},{x:-32,z:32,y:0,heading:2.4}],boosts:[{x:0,z:32,y:0},{x:0,z:-32,y:0}],pickups:[{x:0,z:0,y:0},{x:-25,z:0,y:0},{x:25,z:0,y:0},{x:0,z:40,y:0},{x:0,z:-40,y:0},{x:0,z:16,y:4}],ramps:[{x:-24,z:16,y:0,width:12,length:16,height:4,heading:Math.PI/2},{x:24,z:16,y:0,width:12,length:16,height:4,heading:-Math.PI/2},{x:0,z:-16,y:0,width:12,length:12,height:3,heading:0}],platforms:[{x:0,z:16,y:4,width:32,depth:12}],barriers:[{x:-55,z:0,width:2,depth:110,height:4},{x:55,z:0,width:2,depth:110,height:4},{x:0,z:-55,width:110,depth:2,height:4},{x:0,z:55,width:110,depth:2,height:4}],hazards:[{x:-37,z:20,radius:6},{x:37,z:-20,radius:6}],shortcuts:[]};
function map(mode){return mode==='battle'?battle:race;}
function ground(x,z,mode,currentY=Infinity){const m=map(mode);let y=mode==='battle'?0:nearest(x,z).y;for(const p of m.platforms)if(Math.abs(x-p.x)<=p.width/2&&Math.abs(z-p.z)<=p.depth/2&&currentY>=p.y-.6)y=Math.max(y,p.y);for(const r of m.ramps){const dx=x-r.x,dz=z-r.z,along=dx*Math.sin(r.heading)+dz*Math.cos(r.heading),side=dx*Math.cos(r.heading)-dz*Math.sin(r.heading);if(Math.abs(side)<r.width/2&&Math.abs(along)<=r.length/2){const ry=r.y+(along/r.length+.5)*r.height;if(currentY>=ry-.8)y=Math.max(y,ry);}}return y;}
return{TRACK,ROAD_WIDTH,map,nearest,ground,point};});
