// Palavras do jogo Impostor, por categoria. pt-BR, coisas do dia a dia e atuais.
// Cada palavra tem uma dica própria (h): mais específica que a categoria, sem entregar a resposta.
// A dica só vai para o impostor, e só no modo "Com dica".
const CATEGORIES = [
  { id: 'comida', name: 'Comida', emoji: '🍕' },
  { id: 'animais', name: 'Animais', emoji: '🐾' },
  { id: 'lugares', name: 'Lugares', emoji: '🗺️' },
  { id: 'objetos', name: 'Objetos', emoji: '📦' },
  { id: 'profissoes', name: 'Profissões', emoji: '👩‍⚕️' },
  { id: 'famosos', name: 'Famosos', emoji: '⭐' },
  { id: 'filmes', name: 'Filmes e Séries', emoji: '🎬' },
  { id: 'esportes', name: 'Esportes', emoji: '⚽' },
  { id: 'marcas', name: 'Marcas', emoji: '🏷️' },
  { id: 'casa', name: 'Coisas de casa', emoji: '🏠' },
  { id: 'internet', name: 'Internet e memes', emoji: '🌐' },
  { id: 'musica', name: 'Música', emoji: '🎵' },
];

const WORDS = {
  comida: [
    { w: 'Pizza', h: 'Comida italiana' },
    { w: 'Brigadeiro', h: 'Doce brasileiro' },
    { w: 'Coxinha', h: 'Salgado de festa' },
    { w: 'Feijoada', h: 'Prato típico brasileiro' },
    { w: 'Pastel', h: 'Salgado de festa' },
    { w: 'Churrasco', h: 'Carne grelhada' },
    { w: 'Lasanha', h: 'Comida italiana' },
    { w: 'Hambúrguer', h: 'Carne grelhada' },
    { w: 'Sushi', h: 'Comida japonesa' },
    { w: 'Pão de Queijo', h: 'Café da manhã' },
    { w: 'Açaí', h: 'Comida de rua' },
    { w: 'Tapioca', h: 'Comida de rua' },
    { w: 'Moqueca', h: 'Prato típico brasileiro' },
    { w: 'Picanha', h: 'Carne grelhada' },
    { w: 'Farofa', h: 'Acompanhamento de prato' },
    { w: 'Cocada', h: 'Doce brasileiro' },
    { w: 'Pudim', h: 'Sobremesa gelada' },
    { w: 'Bolo de Chocolate', h: 'Comida de festa' },
    { w: 'Sorvete', h: 'Sobremesa gelada' },
    { w: 'Salgadinho', h: 'Comida de rua' },
    { w: 'Pipoca', h: 'Comida de festa' },
    { w: 'Cachorro-Quente', h: 'Comida de rua' },
    { w: 'Empada', h: 'Salgado de festa' },
    { w: 'Kibe', h: 'Salgado de festa' },
    { w: 'Esfirra', h: 'Salgado de festa' },
    { w: 'Yakisoba', h: 'Comida japonesa' },
    { w: 'Temaki', h: 'Comida japonesa' },
    { w: 'Lámen', h: 'Comida japonesa' },
    { w: 'Nhoque', h: 'Comida italiana' },
    { w: 'Risoto', h: 'Comida italiana' },
    { w: 'Panqueca', h: 'Café da manhã' },
    { w: 'Waffle', h: 'Café da manhã' },
    { w: 'Torta de Limão', h: 'Sobremesa gelada' },
    { w: 'Mousse', h: 'Sobremesa gelada' },
    { w: 'Paçoca', h: 'Doce brasileiro' },
    { w: 'Quindim', h: 'Doce brasileiro' },
    { w: 'Vatapá', h: 'Prato típico brasileiro' },
    { w: 'Baião de Dois', h: 'Prato típico brasileiro' },
    { w: 'Arroz Carreteiro', h: 'Prato típico brasileiro' },
    { w: 'Escondidinho', h: 'Prato típico brasileiro' },
    { w: 'Strogonoff', h: 'Prato típico brasileiro' },
    { w: 'Maionese', h: 'Acompanhamento de prato' },
    { w: 'Vinagrete', h: 'Acompanhamento de prato' },
    { w: 'Guaraná', h: 'Comida de festa' },
    { w: 'Caldo Verde', h: 'Prato típico brasileiro' },
    { w: 'Canjica', h: 'Doce brasileiro' },
    { w: 'Rabanada', h: 'Doce brasileiro' },
    { w: 'Beijinho', h: 'Doce brasileiro' },
  ],
  animais: [
    { w: 'Cachorro', h: 'Bicho de estimação' },
    { w: 'Gato', h: 'Bicho de estimação' },
    { w: 'Leão', h: 'Animal selvagem' },
    { w: 'Tigre', h: 'Animal selvagem' },
    { w: 'Elefante', h: 'Animal selvagem' },
    { w: 'Girafa', h: 'Animal selvagem' },
    { w: 'Macaco', h: 'Animal da floresta' },
    { w: 'Urso', h: 'Animal da floresta' },
    { w: 'Lobo', h: 'Animal da floresta' },
    { w: 'Raposa', h: 'Animal da floresta' },
    { w: 'Coelho', h: 'Bicho de estimação' },
    { w: 'Cavalo', h: 'Animal de fazenda' },
    { w: 'Vaca', h: 'Animal de fazenda' },
    { w: 'Porco', h: 'Animal de fazenda' },
    { w: 'Galinha', h: 'Animal de fazenda' },
    { w: 'Pato', h: 'Animal de fazenda' },
    { w: 'Tartaruga', h: 'Réptil selvagem' },
    { w: 'Cobra', h: 'Réptil selvagem' },
    { w: 'Jacaré', h: 'Réptil selvagem' },
    { w: 'Tucano', h: 'Ave silvestre' },
    { w: 'Papagaio', h: 'Ave silvestre' },
    { w: 'Arara', h: 'Ave silvestre' },
    { w: 'Coruja', h: 'Ave silvestre' },
    { w: 'Águia', h: 'Ave silvestre' },
    { w: 'Tubarão', h: 'Animal marinho' },
    { w: 'Baleia', h: 'Animal marinho' },
    { w: 'Golfinho', h: 'Animal marinho' },
    { w: 'Polvo', h: 'Animal marinho' },
    { w: 'Peixe-Boi', h: 'Animal marinho' },
    { w: 'Capivara', h: 'Animal brasileiro' },
    { w: 'Onça', h: 'Animal brasileiro' },
    { w: 'Jaguatirica', h: 'Animal brasileiro' },
    { w: 'Preguiça', h: 'Animal brasileiro' },
    { w: 'Tamanduá', h: 'Animal brasileiro' },
    { w: 'Quati', h: 'Animal brasileiro' },
    { w: 'Gambá', h: 'Animal brasileiro' },
    { w: 'Morcego', h: 'Animal pequeno' },
    { w: 'Camundongo', h: 'Animal pequeno' },
    { w: 'Rato', h: 'Animal pequeno' },
    { w: 'Esquilo', h: 'Animal pequeno' },
    { w: 'Zebra', h: 'Animal selvagem' },
    { w: 'Hipopótamo', h: 'Animal selvagem' },
    { w: 'Rinoceronte', h: 'Animal selvagem' },
    { w: 'Panda', h: 'Animal de zoológico' },
    { w: 'Coala', h: 'Animal de zoológico' },
    { w: 'Canguru', h: 'Animal de zoológico' },
    { w: 'Pinguim', h: 'Animal de zoológico' },
    { w: 'Foca', h: 'Animal marinho' },
  ],
  lugares: [
    { w: 'Praia', h: 'Lugar natural' },
    { w: 'Escola', h: 'Lugar de estudo' },
    { w: 'Shopping', h: 'Lugar de compras' },
    { w: 'Hospital', h: 'Lugar de saúde' },
    { w: 'Aeroporto', h: 'Lugar de viagem' },
    { w: 'Academia', h: 'Cuidado pessoal' },
    { w: 'Cinema', h: 'Lugar de lazer' },
    { w: 'Igreja', h: 'Construção histórica' },
    { w: 'Padaria', h: 'Lugar de compras' },
    { w: 'Farmácia', h: 'Lugar de saúde' },
    { w: 'Banco', h: 'Prédio público' },
    { w: 'Praça', h: 'Lugar de lazer' },
    { w: 'Parque', h: 'Lugar de lazer' },
    { w: 'Zoológico', h: 'Lugar de visitação' },
    { w: 'Museu', h: 'Lugar de visitação' },
    { w: 'Biblioteca', h: 'Lugar de estudo' },
    { w: 'Estádio', h: 'Lugar da cidade' },
    { w: 'Restaurante', h: 'Lugar da cidade' },
    { w: 'Supermercado', h: 'Lugar de compras' },
    { w: 'Feira', h: 'Lugar de compras' },
    { w: 'Metrô', h: 'Lugar da cidade' },
    { w: 'Rodoviária', h: 'Lugar de viagem' },
    { w: 'Delegacia', h: 'Prédio público' },
    { w: 'Cartório', h: 'Prédio público' },
    { w: 'Salão de Beleza', h: 'Cuidado pessoal' },
    { w: 'Barbearia', h: 'Cuidado pessoal' },
    { w: 'Consultório', h: 'Lugar de saúde' },
    { w: 'Cachoeira', h: 'Lugar natural' },
    { w: 'Fazenda', h: 'Lugar de moradia' },
    { w: 'Montanha', h: 'Lugar natural' },
    { w: 'Deserto', h: 'Lugar natural' },
    { w: 'Floresta', h: 'Lugar natural' },
    { w: 'Ilha', h: 'Lugar natural' },
    { w: 'Vulcão', h: 'Lugar natural' },
    { w: 'Castelo', h: 'Construção histórica' },
    { w: 'Palácio', h: 'Construção histórica' },
    { w: 'Favela', h: 'Lugar de moradia' },
    { w: 'Condomínio', h: 'Lugar de moradia' },
    { w: 'Universidade', h: 'Lugar de estudo' },
    { w: 'Creche', h: 'Lugar de estudo' },
    { w: 'Cemitério', h: 'Lugar da cidade' },
    { w: 'Presídio', h: 'Prédio público' },
    { w: 'Boate', h: 'Lugar de lazer' },
    { w: 'Feira Livre', h: 'Lugar de compras' },
    { w: 'Camping', h: 'Lugar de lazer' },
    { w: 'Motel', h: 'Lugar de viagem' },
    { w: 'Hotel', h: 'Lugar de viagem' },
    { w: 'Aquário', h: 'Lugar de visitação' },
    { w: 'Piscina', h: 'Lugar de lazer' },
    { w: 'Teatro', h: 'Lugar de lazer' },
  ],
  objetos: [
    { w: 'Celular', h: 'Aparelho eletrônico' },
    { w: 'Carregador', h: 'Acessório eletrônico' },
    { w: 'Fone de Ouvido', h: 'Acessório eletrônico' },
    { w: 'Chave', h: 'Objeto pessoal' },
    { w: 'Óculos', h: 'Objeto pessoal' },
    { w: 'Relógio', h: 'Objeto pessoal' },
    { w: 'Mochila', h: 'Item de viagem' },
    { w: 'Carteira', h: 'Objeto pessoal' },
    { w: 'Guarda-Chuva', h: 'Item de viagem' },
    { w: 'Caneta', h: 'Objeto de escritório' },
    { w: 'Caderno', h: 'Objeto de escritório' },
    { w: 'Livro', h: 'Objeto de escritório' },
    { w: 'Tesoura', h: 'Objeto de escritório' },
    { w: 'Controle Remoto', h: 'Acessório eletrônico' },
    { w: 'Televisão', h: 'Aparelho eletrônico' },
    { w: 'Geladeira', h: 'Eletrodoméstico de cozinha' },
    { w: 'Fogão', h: 'Eletrodoméstico de cozinha' },
    { w: 'Micro-ondas', h: 'Eletrodoméstico de cozinha' },
    { w: 'Liquidificador', h: 'Eletrodoméstico de cozinha' },
    { w: 'Ventilador', h: 'Aparelho eletrônico' },
    { w: 'Espelho', h: 'Coisa de banheiro' },
    { w: 'Escova de Dente', h: 'Coisa de banheiro' },
    { w: 'Sabonete', h: 'Coisa de banheiro' },
    { w: 'Toalha', h: 'Item têxtil' },
    { w: 'Travesseiro', h: 'Item têxtil' },
    { w: 'Cobertor', h: 'Item têxtil' },
    { w: 'Sofá', h: 'Móvel da casa' },
    { w: 'Cadeira', h: 'Móvel da casa' },
    { w: 'Mesa', h: 'Móvel da casa' },
    { w: 'Armário', h: 'Móvel da casa' },
    { w: 'Panela', h: 'Objeto de cozinha' },
    { w: 'Faca', h: 'Objeto de cozinha' },
    { w: 'Garfo', h: 'Objeto de cozinha' },
    { w: 'Colher', h: 'Objeto de cozinha' },
    { w: 'Copo', h: 'Objeto de cozinha' },
    { w: 'Prato', h: 'Objeto de cozinha' },
    { w: 'Vassoura', h: 'Objeto de limpeza' },
    { w: 'Rodo', h: 'Objeto de limpeza' },
    { w: 'Balde', h: 'Objeto de limpeza' },
    { w: 'Mala', h: 'Item de viagem' },
    { w: 'Bicicleta', h: 'Meio de transporte' },
    { w: 'Skate', h: 'Meio de transporte' },
    { w: 'Patins', h: 'Meio de transporte' },
    { w: 'Câmera', h: 'Aparelho eletrônico' },
    { w: 'Pilha', h: 'Acessório eletrônico' },
    { w: 'Fita Adesiva', h: 'Objeto de escritório' },
    { w: 'Chaveiro', h: 'Objeto pessoal' },
    { w: 'Cortina', h: 'Item têxtil' },
    { w: 'Frigideira', h: 'Objeto de cozinha' },
    { w: 'Caneca', h: 'Objeto de cozinha' },
    { w: 'Almofada', h: 'Item têxtil' },
    { w: 'Tablet', h: 'Aparelho eletrônico' },
    { w: 'Pulseira', h: 'Objeto pessoal' },
    { w: 'Freezer', h: 'Eletrodoméstico de cozinha' },
    { w: 'Batedeira', h: 'Eletrodoméstico de cozinha' },
    { w: 'Ar-Condicionado', h: 'Aparelho eletrônico' },
  ],
  profissoes: [
    { w: 'Médico', h: 'Profissão da saúde' },
    { w: 'Enfermeiro', h: 'Profissão da saúde' },
    { w: 'Professor', h: 'Profissão de escritório' },
    { w: 'Advogado', h: 'Profissão de escritório' },
    { w: 'Engenheiro', h: 'Profissão técnica' },
    { w: 'Dentista', h: 'Profissão da saúde' },
    { w: 'Veterinário', h: 'Profissão da saúde' },
    { w: 'Policial', h: 'Profissão de risco' },
    { w: 'Bombeiro', h: 'Profissão de risco' },
    { w: 'Motorista', h: 'Profissão de transporte' },
    { w: 'Piloto', h: 'Profissão de transporte' },
    { w: 'Cozinheiro', h: 'Trabalho da comida' },
    { w: 'Garçom', h: 'Trabalho da comida' },
    { w: 'Cabeleireiro', h: 'Trabalho de estilo' },
    { w: 'Barbeiro', h: 'Trabalho de estilo' },
    { w: 'Eletricista', h: 'Profissão de obra' },
    { w: 'Encanador', h: 'Profissão de obra' },
    { w: 'Pedreiro', h: 'Profissão de obra' },
    { w: 'Pintor', h: 'Profissão de obra' },
    { w: 'Padeiro', h: 'Trabalho da comida' },
    { w: 'Açougueiro', h: 'Trabalho da comida' },
    { w: 'Farmacêutico', h: 'Profissão da saúde' },
    { w: 'Fisioterapeuta', h: 'Profissão da saúde' },
    { w: 'Psicólogo', h: 'Profissão da saúde' },
    { w: 'Nutricionista', h: 'Profissão da saúde' },
    { w: 'Contador', h: 'Profissão de comércio' },
    { w: 'Jornalista', h: 'Trabalho criativo' },
    { w: 'Fotógrafo', h: 'Trabalho criativo' },
    { w: 'Ator', h: 'Trabalho criativo' },
    { w: 'Cantor', h: 'Trabalho criativo' },
    { w: 'Músico', h: 'Trabalho criativo' },
    { w: 'Dançarino', h: 'Trabalho criativo' },
    { w: 'Youtuber', h: 'Profissão da internet' },
    { w: 'Streamer', h: 'Profissão da internet' },
    { w: 'Influenciador', h: 'Profissão da internet' },
    { w: 'Programador', h: 'Profissão técnica' },
    { w: 'Designer', h: 'Profissão técnica' },
    { w: 'Arquiteto', h: 'Profissão técnica' },
    { w: 'Astronauta', h: 'Profissão de risco' },
    { w: 'Marinheiro', h: 'Profissão de transporte' },
    { w: 'Agricultor', h: 'Trabalho manual' },
    { w: 'Pescador', h: 'Trabalho manual' },
    { w: 'Costureira', h: 'Trabalho de estilo' },
    { w: 'Zelador', h: 'Trabalho manual' },
    { w: 'Segurança', h: 'Profissão de risco' },
    { w: 'Recepcionista', h: 'Profissão de escritório' },
    { w: 'Vendedor', h: 'Profissão de comércio' },
    { w: 'Juiz', h: 'Profissão de escritório' },
    { w: 'Economista', h: 'Profissão de comércio' },
  ],
  famosos: [
    { w: 'Anitta', h: 'Cantora brasileira' },
    { w: 'Neymar', h: 'Jogador de futebol' },
    { w: 'Ivete Sangalo', h: 'Cantora brasileira' },
    { w: 'Fátima Bernardes', h: 'Apresentador de TV' },
    { w: 'Silvio Santos', h: 'Apresentador de TV' },
    { w: 'Xuxa', h: 'Apresentador de TV' },
    { w: 'Gusttavo Lima', h: 'Cantor brasileiro' },
    { w: 'Ludmilla', h: 'Cantora brasileira' },
    { w: 'Pabllo Vittar', h: 'Cantora brasileira' },
    { w: 'Whindersson Nunes', h: 'Famoso da internet' },
    { w: 'Luciano Huck', h: 'Apresentador de TV' },
    { w: 'Ana Maria Braga', h: 'Apresentador de TV' },
    { w: 'Marília Mendonça', h: 'Cantora brasileira' },
    { w: 'Roberto Carlos', h: 'Ídolo do passado' },
    { w: 'Caetano Veloso', h: 'Ídolo do passado' },
    { w: 'Gilberto Gil', h: 'Ídolo do passado' },
    { w: 'Sandy', h: 'Cantora brasileira' },
    { w: 'Junior', h: 'Cantor brasileiro' },
    { w: 'Wesley Safadão', h: 'Cantor brasileiro' },
    { w: 'Claudia Leitte', h: 'Cantora brasileira' },
    { w: 'Larissa Manoela', h: 'Celebridade jovem' },
    { w: 'Bruna Marquezine', h: 'Celebridade jovem' },
    { w: 'Sasha Meneghel', h: 'Celebridade jovem' },
    { w: 'Pelé', h: 'Jogador de futebol' },
    { w: 'Ronaldinho Gaúcho', h: 'Jogador de futebol' },
    { w: 'Gabigol', h: 'Jogador de futebol' },
    { w: 'Vini Jr', h: 'Jogador de futebol' },
    { w: 'Rafinha Bastos', h: 'Humorista brasileiro' },
    { w: 'Fábio Porchat', h: 'Humorista brasileiro' },
    { w: 'Tirullipa', h: 'Humorista brasileiro' },
    { w: 'Casimiro', h: 'Famoso da internet' },
    { w: 'Felca', h: 'Famoso da internet' },
    { w: 'Cristiano Ronaldo', h: 'Jogador de futebol' },
    { w: 'Lionel Messi', h: 'Jogador de futebol' },
    { w: 'Taylor Swift', h: 'Cantor internacional' },
    { w: 'Beyoncé', h: 'Cantor internacional' },
    { w: 'Rihanna', h: 'Cantor internacional' },
    { w: 'Ariana Grande', h: 'Cantor internacional' },
    { w: 'Dua Lipa', h: 'Cantor internacional' },
    { w: 'Bad Bunny', h: 'Cantor internacional' },
    { w: 'Shakira', h: 'Cantor internacional' },
    { w: 'Elon Musk', h: 'Personalidade mundial' },
    { w: 'Barack Obama', h: 'Personalidade mundial' },
    { w: 'Oprah Winfrey', h: 'Personalidade mundial' },
    { w: 'Selena Gomez', h: 'Ator internacional' },
    { w: 'Justin Bieber', h: 'Cantor internacional' },
    { w: 'MrBeast', h: 'Famoso da internet' },
    { w: 'Zendaya', h: 'Ator internacional' },
    { w: 'Tom Holland', h: 'Ator internacional' },
  ],
  filmes: [
    { w: 'Vingadores', h: 'Filme de herói' },
    { w: 'Homem-Aranha', h: 'Filme de herói' },
    { w: 'Batman', h: 'Filme de herói' },
    { w: 'Superman', h: 'Filme de herói' },
    { w: 'Star Wars', h: 'Ficção científica' },
    { w: 'Harry Potter', h: 'Filme de fantasia' },
    { w: 'Senhor dos Anéis', h: 'Filme de fantasia' },
    { w: 'Frozen', h: 'Desenho animado' },
    { w: 'Toy Story', h: 'Desenho animado' },
    { w: 'Shrek', h: 'Desenho animado' },
    { w: 'Divertida Mente', h: 'Desenho animado' },
    { w: 'Barbie', h: 'Filme de fantasia' },
    { w: 'Duna', h: 'Ficção científica' },
    { w: 'Coringa', h: 'Filme de drama' },
    { w: 'John Wick', h: 'Filme de ação' },
    { w: 'Matrix', h: 'Ficção científica' },
    { w: 'Jurassic Park', h: 'Filme de ação' },
    { w: 'Velozes e Furiosos', h: 'Filme de ação' },
    { w: 'Missão Impossível', h: 'Filme de ação' },
    { w: 'Stranger Things', h: 'Série de streaming' },
    { w: 'Round 6', h: 'Série de streaming' },
    { w: 'Wandinha', h: 'Série de streaming' },
    { w: 'La Casa de Papel', h: 'Série de streaming' },
    { w: 'Bridgerton', h: 'Série de streaming' },
    { w: 'Friends', h: 'Série de TV' },
    { w: 'The Office', h: 'Série de TV' },
    { w: 'Breaking Bad', h: 'Série de TV' },
    { w: 'Game of Thrones', h: 'Série de TV' },
    { w: 'Vikings', h: 'Série de TV' },
    { w: 'Peaky Blinders', h: 'Série de TV' },
    { w: 'Chaves', h: 'Série de TV' },
    { w: 'A Grande Família', h: 'Série de TV' },
    { w: 'Avatar', h: 'Ficção científica' },
    { w: 'Titanic', h: 'Filme de drama' },
    { w: 'Karatê Kid', h: 'Filme de drama' },
    { w: 'Homem de Ferro', h: 'Filme de herói' },
    { w: 'Pantera Negra', h: 'Filme de herói' },
    { w: 'Mulher Maravilha', h: 'Filme de herói' },
    { w: 'Aquaman', h: 'Filme de herói' },
    { w: 'Minions', h: 'Desenho animado' },
    { w: 'Enrolados', h: 'Desenho animado' },
    { w: 'Aladdin', h: 'Desenho animado' },
    { w: 'Procurando Nemo', h: 'Desenho animado' },
    { w: 'Rei Leão', h: 'Desenho animado' },
    { w: 'Zootopia', h: 'Desenho animado' },
    { w: 'Encanto', h: 'Desenho animado' },
    { w: 'Vaiana', h: 'Desenho animado' },
    { w: 'Wicked', h: 'Filme de fantasia' },
  ],
  esportes: [
    { w: 'Futebol', h: 'Esporte com bola' },
    { w: 'Vôlei', h: 'Esporte com bola' },
    { w: 'Basquete', h: 'Esporte com bola' },
    { w: 'Handebol', h: 'Esporte com bola' },
    { w: 'Tênis', h: 'Esporte de raquete' },
    { w: 'Natação', h: 'Esporte de água' },
    { w: 'Corrida', h: 'Esporte de velocidade' },
    { w: 'Ciclismo', h: 'Esporte de velocidade' },
    { w: 'Skate', h: 'Esporte radical' },
    { w: 'Surfe', h: 'Esporte de água' },
    { w: 'Judô', h: 'Esporte de luta' },
    { w: 'Karatê', h: 'Esporte de luta' },
    { w: 'Boxe', h: 'Esporte de luta' },
    { w: 'MMA', h: 'Esporte de luta' },
    { w: 'Ginástica', h: 'Esporte olímpico' },
    { w: 'Atletismo', h: 'Esporte olímpico' },
    { w: 'Golfe', h: 'Esporte de precisão' },
    { w: 'Beisebol', h: 'Esporte com bola' },
    { w: 'Rúgbi', h: 'Esporte com bola' },
    { w: 'Futsal', h: 'Esporte com bola' },
    { w: 'Vôlei de Praia', h: 'Esporte com bola' },
    { w: 'Xadrez', h: 'Esporte de precisão' },
    { w: 'Sinuca', h: 'Esporte de precisão' },
    { w: 'Boliche', h: 'Esporte de precisão' },
    { w: 'Patinação', h: 'Esporte radical' },
    { w: 'Esgrima', h: 'Esporte olímpico' },
    { w: 'Remo', h: 'Esporte olímpico' },
    { w: 'Vela', h: 'Esporte de água' },
    { w: 'Triatlo', h: 'Esporte de velocidade' },
    { w: 'Maratona', h: 'Esporte de velocidade' },
    { w: 'Capoeira', h: 'Esporte de luta' },
    { w: 'Jiu-Jitsu', h: 'Esporte de luta' },
    { w: 'Taekwondo', h: 'Esporte de luta' },
    { w: 'Halterofilismo', h: 'Esporte olímpico' },
    { w: 'Ginástica Artística', h: 'Esporte olímpico' },
    { w: 'Polo Aquático', h: 'Esporte de água' },
    { w: 'Hipismo', h: 'Esporte olímpico' },
    { w: 'Tiro com Arco', h: 'Esporte olímpico' },
    { w: 'Badminton', h: 'Esporte de raquete' },
    { w: 'Squash', h: 'Esporte de raquete' },
    { w: 'Escalada', h: 'Esporte radical' },
    { w: 'Slackline', h: 'Esporte radical' },
    { w: 'Skimboard', h: 'Esporte radical' },
    { w: 'Motocross', h: 'Esporte de velocidade' },
    { w: 'Fórmula 1', h: 'Esporte de velocidade' },
    { w: 'Vôlei Sentado', h: 'Esporte com bola' },
    { w: 'Futebol Americano', h: 'Esporte com bola' },
    { w: 'Peteca', h: 'Esporte de raquete' },
  ],
  marcas: [
    { w: 'Nike', h: 'Marca esportiva' },
    { w: 'Adidas', h: 'Marca esportiva' },
    { w: 'Puma', h: 'Marca esportiva' },
    { w: 'Coca-Cola', h: 'Marca de bebida' },
    { w: 'Pepsi', h: 'Marca de bebida' },
    { w: 'McDonald\'s', h: 'Marca de lanchonete' },
    { w: 'Burger King', h: 'Marca de lanchonete' },
    { w: 'Habib\'s', h: 'Marca de lanchonete' },
    { w: 'Netflix', h: 'Serviço de streaming' },
    { w: 'Spotify', h: 'Serviço de streaming' },
    { w: 'YouTube', h: 'Serviço de streaming' },
    { w: 'Instagram', h: 'Rede social' },
    { w: 'TikTok', h: 'Rede social' },
    { w: 'WhatsApp', h: 'Rede social' },
    { w: 'Facebook', h: 'Rede social' },
    { w: 'Google', h: 'Marca de eletrônico' },
    { w: 'Apple', h: 'Marca de eletrônico' },
    { w: 'Samsung', h: 'Marca de eletrônico' },
    { w: 'Xiaomi', h: 'Marca de eletrônico' },
    { w: 'Motorola', h: 'Marca de eletrônico' },
    { w: 'Ifood', h: 'Aplicativo de celular' },
    { w: 'Uber', h: 'Aplicativo de celular' },
    { w: '99', h: 'Aplicativo de celular' },
    { w: 'Nubank', h: 'Banco brasileiro' },
    { w: 'Itaú', h: 'Banco brasileiro' },
    { w: 'Bradesco', h: 'Banco brasileiro' },
    { w: 'Havaianas', h: 'Marca brasileira' },
    { w: 'Natura', h: 'Marca brasileira' },
    { w: 'Boticário', h: 'Marca brasileira' },
    { w: 'Americanas', h: 'Loja online' },
    { w: 'Magazine Luiza', h: 'Loja online' },
    { w: 'Casas Bahia', h: 'Loja online' },
    { w: 'Mercado Livre', h: 'Loja online' },
    { w: 'Shopee', h: 'Loja online' },
    { w: 'Amazon', h: 'Loja online' },
    { w: 'Ford', h: 'Marca de veículo' },
    { w: 'Chevrolet', h: 'Marca de veículo' },
    { w: 'Fiat', h: 'Marca de veículo' },
    { w: 'Volkswagen', h: 'Marca de veículo' },
    { w: 'Honda', h: 'Marca de veículo' },
    { w: 'Yamaha', h: 'Marca de veículo' },
    { w: 'Red Bull', h: 'Marca de bebida' },
    { w: 'Guaraná Antarctica', h: 'Marca de bebida' },
    { w: 'Skol', h: 'Marca de cerveja' },
    { w: 'Brahma', h: 'Marca de cerveja' },
    { w: 'Heineken', h: 'Marca de cerveja' },
    { w: 'Lacta', h: 'Marca de alimento' },
    { w: 'Nestlé', h: 'Marca de alimento' },
    { w: 'Danone', h: 'Marca de alimento' },
  ],
  casa: [
    { w: 'Sofá', h: 'Móvel da sala' },
    { w: 'Cama', h: 'Coisa do quarto' },
    { w: 'Travesseiro', h: 'Coisa do quarto' },
    { w: 'Cobertor', h: 'Coisa do quarto' },
    { w: 'Lençol', h: 'Coisa do quarto' },
    { w: 'Cortina', h: 'Item de decoração' },
    { w: 'Tapete', h: 'Item de decoração' },
    { w: 'Almofada', h: 'Item de decoração' },
    { w: 'Espelho', h: 'Item de decoração' },
    { w: 'Armário', h: 'Coisa do quarto' },
    { w: 'Guarda-Roupa', h: 'Coisa do quarto' },
    { w: 'Estante', h: 'Móvel da sala' },
    { w: 'Mesa de Centro', h: 'Móvel da sala' },
    { w: 'Geladeira', h: 'Eletrodoméstico da cozinha' },
    { w: 'Fogão', h: 'Eletrodoméstico da cozinha' },
    { w: 'Micro-ondas', h: 'Eletrodoméstico da cozinha' },
    { w: 'Liquidificador', h: 'Eletrodoméstico da cozinha' },
    { w: 'Máquina de Lavar', h: 'Coisa de lavanderia' },
    { w: 'Ferro de Passar', h: 'Coisa de lavanderia' },
    { w: 'Aspirador de Pó', h: 'Objeto de limpeza' },
    { w: 'Vassoura', h: 'Objeto de limpeza' },
    { w: 'Rodo', h: 'Objeto de limpeza' },
    { w: 'Pia', h: 'Coisa de banheiro' },
    { w: 'Torneira', h: 'Coisa de banheiro' },
    { w: 'Chuveiro', h: 'Coisa de banheiro' },
    { w: 'Vaso Sanitário', h: 'Coisa de banheiro' },
    { w: 'Escova de Dente', h: 'Item pessoal' },
    { w: 'Sabonete', h: 'Item pessoal' },
    { w: 'Shampoo', h: 'Item pessoal' },
    { w: 'Toalha', h: 'Item pessoal' },
    { w: 'Panela', h: 'Utensílio de cozinha' },
    { w: 'Frigideira', h: 'Utensílio de cozinha' },
    { w: 'Faca', h: 'Utensílio de cozinha' },
    { w: 'Garfo', h: 'Utensílio de cozinha' },
    { w: 'Colher', h: 'Utensílio de cozinha' },
    { w: 'Prato', h: 'Utensílio de cozinha' },
    { w: 'Copo', h: 'Utensílio de cozinha' },
    { w: 'Xícara', h: 'Utensílio de cozinha' },
    { w: 'Jarra', h: 'Utensílio de cozinha' },
    { w: 'Luminária', h: 'Aparelho elétrico' },
    { w: 'Ventilador', h: 'Aparelho elétrico' },
    { w: 'Ar-Condicionado', h: 'Aparelho elétrico' },
    { w: 'Controle Remoto', h: 'Coisa de tecnologia' },
    { w: 'Televisão', h: 'Coisa de tecnologia' },
    { w: 'Wi-Fi', h: 'Coisa de tecnologia' },
    { w: 'Tomada', h: 'Coisa de tecnologia' },
    { w: 'Chinelo', h: 'Item pessoal' },
    { w: 'Freezer', h: 'Eletrodoméstico da cozinha' },
    { w: 'Batedeira', h: 'Eletrodoméstico da cozinha' },
    { w: 'Secadora', h: 'Coisa de lavanderia' },
  ],
  internet: [
    { w: 'Meme', h: 'Piada da internet' },
    { w: 'Reels', h: 'Formato de conteúdo' },
    { w: 'Stories', h: 'Formato de conteúdo' },
    { w: 'Live', h: 'Formato de conteúdo' },
    { w: 'TikTok', h: 'Nome de aplicativo' },
    { w: 'Print', h: 'Coisa de mensagem' },
    { w: 'Stalker', h: 'Gente da internet' },
    { w: 'Ship', h: 'Fenômeno da internet' },
    { w: 'Cringe', h: 'Piada da internet' },
    { w: 'Hater', h: 'Gente da internet' },
    { w: 'Fake News', h: 'Fenômeno da internet' },
    { w: 'Deepfake', h: 'Fenômeno da internet' },
    { w: 'Hashtag', h: 'Termo de rede' },
    { w: 'Trend', h: 'Termo de rede' },
    { w: 'Viral', h: 'Termo de rede' },
    { w: 'Bug', h: 'Coisa de tecnologia' },
    { w: 'Lag', h: 'Coisa de tecnologia' },
    { w: 'Wi-Fi', h: 'Coisa de tecnologia' },
    { w: 'Emoji', h: 'Coisa de mensagem' },
    { w: 'Sticker', h: 'Coisa de mensagem' },
    { w: 'Podcast', h: 'Formato de conteúdo' },
    { w: 'Vlog', h: 'Formato de conteúdo' },
    { w: 'Streamer', h: 'Gente da internet' },
    { w: 'Youtuber', h: 'Gente da internet' },
    { w: 'Influenciador', h: 'Gente da internet' },
    { w: 'Cancelamento', h: 'Fenômeno da internet' },
    { w: 'Textão', h: 'Formato de conteúdo' },
    { w: 'Bafão', h: 'Piada da internet' },
    { w: 'Zap', h: 'Nome de aplicativo' },
    { w: 'Grupo de Zap', h: 'Coisa de mensagem' },
    { w: 'Enquete', h: 'Ação de rede' },
    { w: 'Curtida', h: 'Ação de rede' },
    { w: 'Comentário', h: 'Ação de rede' },
    { w: 'Compartilhar', h: 'Ação de rede' },
    { w: 'Seguidor', h: 'Ação de rede' },
    { w: 'Algoritmo', h: 'Termo de rede' },
    { w: 'Feed', h: 'Termo de rede' },
    { w: 'Chat', h: 'Coisa de mensagem' },
    { w: 'Pix', h: 'Nome de aplicativo' },
    { w: 'QR Code', h: 'Coisa de tecnologia' },
    { w: 'VPN', h: 'Coisa de tecnologia' },
    { w: 'FYP', h: 'Termo de rede' },
    { w: 'Reação', h: 'Ação de rede' },
    { w: 'Áudio de Zap', h: 'Coisa de mensagem' },
    { w: 'Nostalgia', h: 'Fenômeno da internet' },
    { w: 'Print da Conversa', h: 'Coisa de mensagem' },
    { w: 'Login', h: 'Coisa de tecnologia' },
    { w: 'Senha', h: 'Coisa de tecnologia' },
    { w: 'Notificação', h: 'Coisa de tecnologia' },
  ],
  musica: [
    { w: 'Funk', h: 'Ritmo brasileiro' },
    { w: 'Sertanejo', h: 'Ritmo brasileiro' },
    { w: 'Pagode', h: 'Ritmo brasileiro' },
    { w: 'Samba', h: 'Ritmo brasileiro' },
    { w: 'Axé', h: 'Ritmo brasileiro' },
    { w: 'Forró', h: 'Ritmo brasileiro' },
    { w: 'MPB', h: 'Ritmo brasileiro' },
    { w: 'Rock', h: 'Ritmo internacional' },
    { w: 'Pop', h: 'Ritmo internacional' },
    { w: 'Rap', h: 'Ritmo internacional' },
    { w: 'Trap', h: 'Ritmo internacional' },
    { w: 'Reggae', h: 'Ritmo internacional' },
    { w: 'Reggaeton', h: 'Ritmo internacional' },
    { w: 'Bossa Nova', h: 'Ritmo brasileiro' },
    { w: 'Piseiro', h: 'Ritmo brasileiro' },
    { w: 'Brega Funk', h: 'Ritmo brasileiro' },
    { w: 'Gospel', h: 'Ritmo internacional' },
    { w: 'Eletrônica', h: 'Ritmo internacional' },
    { w: 'Hip Hop', h: 'Ritmo internacional' },
    { w: 'Arrocha', h: 'Ritmo brasileiro' },
    { w: 'Vanera', h: 'Ritmo brasileiro' },
    { w: 'Sofrência', h: 'Ritmo brasileiro' },
    { w: 'Chorinho', h: 'Ritmo brasileiro' },
    { w: 'Frevo', h: 'Ritmo brasileiro' },
    { w: 'Maracatu', h: 'Ritmo brasileiro' },
    { w: 'K-pop', h: 'Ritmo internacional' },
    { w: 'Jazz', h: 'Ritmo internacional' },
    { w: 'Blues', h: 'Ritmo internacional' },
    { w: 'Heavy Metal', h: 'Ritmo internacional' },
    { w: 'Punk', h: 'Ritmo internacional' },
    { w: 'Ópera', h: 'Ritmo internacional' },
    { w: 'Violão', h: 'Instrumento musical' },
    { w: 'Guitarra', h: 'Instrumento musical' },
    { w: 'Bateria', h: 'Instrumento musical' },
    { w: 'Teclado', h: 'Instrumento musical' },
    { w: 'Microfone', h: 'Instrumento musical' },
    { w: 'Show', h: 'Evento de música' },
    { w: 'Festival', h: 'Evento de música' },
    { w: 'Karaokê', h: 'Evento de música' },
    { w: 'Playlist', h: 'Jeito de ouvir' },
    { w: 'Fone de Ouvido', h: 'Jeito de ouvir' },
    { w: 'Caixa de Som', h: 'Jeito de ouvir' },
    { w: 'Baile Funk', h: 'Evento de música' },
    { w: 'Roda de Samba', h: 'Evento de música' },
    { w: 'Clipe', h: 'Coisa de show' },
    { w: 'Turnê', h: 'Coisa de show' },
    { w: 'DJ', h: 'Coisa de show' },
    { w: 'Banda', h: 'Coisa de show' },
  ],
};

// Pares parecidos para o modo Mister White: [palavra dos inocentes, palavra do Mister White]
const PAIRS = {
  comida: [['Pizza','Lasanha'],['Coxinha','Kibe'],['Feijoada','Strogonoff'],['Pastel','Esfirra'],['Sushi','Temaki'],['Brigadeiro','Beijinho'],['Cocada','Paçoca'],['Bolo de Chocolate','Pudim'],['Sorvete','Açaí'],['Hambúrguer','Cachorro-Quente'],['Churrasco','Picanha'],['Nhoque','Risoto'],['Panqueca','Waffle'],['Quindim','Canjica'],['Mousse','Torta de Limão'],['Yakisoba','Lámen'],['Farofa','Vinagrete'],['Empada','Rabanada']],
  animais: [['Cachorro','Lobo'],['Gato','Onça'],['Leão','Tigre'],['Cavalo','Zebra'],['Vaca','Porco'],['Pato','Galinha'],['Águia','Coruja'],['Arara','Papagaio'],['Tubarão','Golfinho'],['Baleia','Peixe-Boi'],['Capivara','Quati'],['Preguiça','Tamanduá'],['Morcego','Gambá'],['Camundongo','Rato'],['Esquilo','Camundongo'],['Hipopótamo','Rinoceronte'],['Panda','Coala'],['Pinguim','Foca']],
  lugares: [['Praia','Piscina'],['Shopping','Feira'],['Hospital','Consultório'],['Escola','Universidade'],['Cinema','Teatro'],['Padaria','Restaurante'],['Banco','Cartório'],['Parque','Praça'],['Zoológico','Aquário'],['Museu','Biblioteca'],['Estádio','Academia'],['Cachoeira','Fazenda'],['Montanha','Vulcão'],['Deserto','Floresta'],['Castelo','Palácio'],['Favela','Condomínio'],['Presídio','Delegacia'],['Hotel','Motel']],
  objetos: [['Panela','Frigideira'],['Faca','Tesoura'],['Garfo','Colher'],['Copo','Caneca'],['Sofá','Cadeira'],['Mesa','Armário'],['Toalha','Cobertor'],['Travesseiro','Almofada'],['Vassoura','Rodo'],['Balde','Mala'],['Bicicleta','Skate'],['Celular','Tablet'],['Relógio','Pulseira'],['Geladeira','Freezer'],['Fogão','Micro-ondas'],['Liquidificador','Batedeira'],['Ventilador','Ar-Condicionado'],['Chave','Chaveiro']],
  profissoes: [['Médico','Enfermeiro'],['Advogado','Juiz'],['Pedreiro','Eletricista'],['Cabeleireiro','Barbeiro'],['Cozinheiro','Padeiro'],['Ator','Cantor'],['Youtuber','Streamer'],['Programador','Designer'],['Piloto','Motorista'],['Policial','Bombeiro'],['Veterinário','Dentista'],['Fisioterapeuta','Nutricionista'],['Jornalista','Fotógrafo'],['Agricultor','Pescador'],['Arquiteto','Engenheiro'],['Contador','Economista'],['Zelador','Segurança'],['Recepcionista','Vendedor']],
  famosos: [['Anitta','Ludmilla'],['Neymar','Vini Jr'],['Pelé','Ronaldinho Gaúcho'],['Cristiano Ronaldo','Lionel Messi'],['Taylor Swift','Ariana Grande'],['Beyoncé','Rihanna'],['Silvio Santos','Luciano Huck'],['Xuxa','Ana Maria Braga'],['Sandy','Claudia Leitte'],['Caetano Veloso','Gilberto Gil'],['Gusttavo Lima','Wesley Safadão'],['Whindersson Nunes','Fábio Porchat'],['Larissa Manoela','Bruna Marquezine'],['Justin Bieber','Tom Holland'],['Selena Gomez','Zendaya'],['Elon Musk','MrBeast'],['Shakira','Dua Lipa'],['Casimiro','Felca']],
  filmes: [['Vingadores','Homem de Ferro'],['Batman','Superman'],['Homem-Aranha','Pantera Negra'],['Mulher Maravilha','Aquaman'],['Star Wars','Duna'],['Harry Potter','Senhor dos Anéis'],['Frozen','Encanto'],['Toy Story','Shrek'],['Divertida Mente','Procurando Nemo'],['Enrolados','Aladdin'],['Rei Leão','Zootopia'],['John Wick','Matrix'],['Jurassic Park','Velozes e Furiosos'],['Stranger Things','Wandinha'],['La Casa de Papel','Round 6'],['Friends','The Office'],['Breaking Bad','Peaky Blinders'],['Game of Thrones','Vikings']],
  esportes: [['Futebol','Futsal'],['Vôlei','Vôlei de Praia'],['Basquete','Handebol'],['Judô','Jiu-Jitsu'],['Karatê','Taekwondo'],['Boxe','MMA'],['Natação','Polo Aquático'],['Ciclismo','Motocross'],['Skate','Slackline'],['Tênis','Badminton'],['Golfe','Squash'],['Corrida','Maratona'],['Remo','Vela'],['Sinuca','Boliche'],['Atletismo','Ginástica Artística'],['Esgrima','Tiro com Arco'],['Fórmula 1','Motocross'],['Triatlo','Maratona']],
  marcas: [['Nike','Adidas'],['Coca-Cola','Pepsi'],['McDonald\'s','Burger King'],['Instagram','TikTok'],['WhatsApp','Facebook'],['Samsung','Xiaomi'],['Ford','Chevrolet'],['Fiat','Volkswagen'],['Honda','Yamaha'],['Skol','Brahma'],['Nestlé','Danone'],['Americanas','Casas Bahia'],['Magazine Luiza','Mercado Livre'],['Shopee','Amazon'],['Nubank','Itaú'],['Uber','99'],['Natura','Boticário'],['Lacta','Nestlé']],
  casa: [['Cama','Sofá'],['Travesseiro','Almofada'],['Cobertor','Lençol'],['Cortina','Tapete'],['Armário','Guarda-Roupa'],['Estante','Mesa de Centro'],['Geladeira','Freezer'],['Fogão','Micro-ondas'],['Liquidificador','Batedeira'],['Máquina de Lavar','Secadora'],['Ferro de Passar','Aspirador de Pó'],['Vassoura','Rodo'],['Pia','Torneira'],['Chuveiro','Vaso Sanitário'],['Panela','Frigideira'],['Prato','Copo'],['Xícara','Jarra'],['Ventilador','Ar-Condicionado']],
  internet: [['Meme','Trend'],['Reels','TikTok'],['Stories','Live'],['Curtida','Comentário'],['Seguidor','Influenciador'],['Hater','Stalker'],['Fake News','Deepfake'],['Cringe','Bafão'],['Zap','Grupo de Zap'],['Podcast','Vlog'],['Youtuber','Streamer'],['Bug','Lag'],['Login','Senha'],['Emoji','Sticker'],['Pix','QR Code'],['Print','Print da Conversa'],['Feed','Algoritmo'],['Textão','Bafão']],
  musica: [['Funk','Brega Funk'],['Sertanejo','Piseiro'],['Samba','Pagode'],['Axé','Forró'],['Rap','Trap'],['Reggae','Reggaeton'],['Rock','Punk'],['Pop','K-pop'],['Jazz','Blues'],['Chorinho','Frevo'],['Violão','Guitarra'],['Bateria','Teclado'],['Show','Festival'],['Karaokê','Playlist'],['Baile Funk','Roda de Samba'],['Clipe','Turnê'],['DJ','Banda'],['Vanera','Sofrência']],
};

module.exports = { CATEGORIES, WORDS, PAIRS };
