// Lote 5 do Perfil — Pessoas. Cada carta: resposta + 20 dicas (da mais difícil para a mais fácil).
const CARDS5 = {
  P: [
    { answer: 'Charles Chaplin', clues: [
      'Nasci em Londres, em 1889.', 'Minha mãe era cantora de teatro e adoeceu; passei parte da infância num asilo para crianças pobres.', 'Comecei em companhias de teatro mambembe ainda menino.', 'Fui para os Estados Unidos com uma trupe de comédia inglesa.',
      'Assinei com os estúdios Keystone em 1914.', 'Fui um dos fundadores da United Artists.', 'Dirigi, escrevi, produzi e compus a música dos meus próprios filmes.', 'Fiz um discurso final famoso contra a guerra e a ganância.',
      'Fui acusado de simpatias comunistas e proibido de voltar aos Estados Unidos nos anos 50.', 'Passei meus últimos anos na Suíça.', 'Ganhei um Oscar honorário em 1972, com uma ovação de doze minutos.', 'Meu filme sobre a linha de montagem industrial se chama "Tempos Modernos".',
      'Fiz um filme em que satirizo Hitler.', 'Meu personagem tem bigodinho, chapéu-coco e bengala.', 'Ando com os pés virados para fora, gingando.', 'Meu personagem se chama "Carlitos" no Brasil.',
      'Resisti ao cinema falado por muitos anos.', 'Sou o maior nome da comédia do cinema mudo.', 'Morri em 1977, na noite de Natal.', 'Sou um ator e diretor inglês, símbolo do cinema mudo.',
    ] },
    { answer: 'Nelson Mandela', clues: [
      'Nasci em 1918, numa aldeia da África do Sul.', 'Meu nome de nascimento é Rolihlahla; ganhei um nome inglês na escola.', 'Sou da etnia xhosa e da família real thembu.', 'Estudei Direito e abri o primeiro escritório de advocacia negro do meu país.',
      'Entrei para o Congresso Nacional Africano nos anos 40.', 'Fui julgado no processo de Rivonia, em 1964.', 'Fiz um discurso no tribunal dizendo que estava pronto para morrer pelos meus ideais.', 'Passei 18 dos meus anos de prisão numa ilha, quebrando pedra numa pedreira de cal.',
      'A ilha onde fiquei preso se chama Robben Island.', 'Fiquei 27 anos na cadeia.', 'Fui solto em fevereiro de 1990, na frente das câmeras do mundo inteiro.', 'Ganhei o Nobel da Paz em 1993, dividido com Frederik de Klerk.',
      'Fui o primeiro presidente negro do meu país, eleito em 1994.', 'Criei uma comissão de Verdade e Reconciliação em vez de punir meus antigos carcereiros.', 'Entreguei a taça da Copa do Mundo de rúgbi de 1995 vestindo a camisa da seleção.', 'Meu apelido de clã é "Madiba".',
      'Lutei a vida inteira contra o apartheid.', 'Morri em 2013, aos 95 anos.', 'Meu aniversário virou um dia internacional na ONU.', 'Sou o sul-africano mais famoso do mundo.',
    ] },
    { answer: 'Madonna', clues: [
      'Nasci em Michigan, em 1958.', 'Perdi minha mãe aos 5 anos.', 'Estudei dança e larguei a faculdade para tentar a vida em Nova York.', 'Cheguei em Nova York com 35 dólares no bolso.',
      'Toquei bateria e cantei em bandas antes de seguir carreira solo.', 'Meu primeiro disco saiu em 1983.', 'Escrevi um livro de fotos que causou escândalo nos anos 90.', 'Dirigi e estrelei filmes, e ganhei um Globo de Ouro por "Evita".',
      'Meu disco "Ray of Light" ganhou vários Grammys.', 'Adotei filhos no Malaui e mantenho projetos sociais lá.', 'Fiz uma turnê chamada "Blond Ambition".', 'Beijei outras cantoras num prêmio da MTV em 2003.',
      'Meus discos incluem "Like a Virgin", "True Blue" e "Confessions on a Dance Floor".', 'Cantei "Like a Prayer", "Vogue" e "Material Girl".', 'Sou a artista feminina que mais vendeu discos na história.', 'Fiz um show na praia de Copacabana em 2024 para mais de um milhão de pessoas.',
      'Mudo de visual a cada disco: sou conhecida pelas reinvenções.', 'Sou chamada de "Rainha do Pop".', 'Meu nome verdadeiro é o mesmo que meu nome artístico.', 'Sou uma cantora americana e meu nome lembra a mãe de Jesus.',
    ] },
    { answer: 'Walt Disney', clues: [
      'Nasci em Chicago, em 1901.', 'Cresci numa fazenda no Missouri desenhando animais.', 'Menti a idade para dirigir ambulância na Primeira Guerra.', 'Meu primeiro estúdio, o Laugh-O-Gram, faliu.',
      'Perdi os direitos do meu primeiro personagem de sucesso, um coelho chamado Oswald.', 'Meu irmão Roy cuidava do dinheiro da empresa.', 'Fiz o primeiro desenho animado com som sincronizado, em 1928.', 'Ganhei 22 Oscars, o recorde para uma pessoa só.',
      'Lancei o primeiro longa-metragem de animação em cores da história, em 1937.', 'Esse primeiro longa foi "Branca de Neve e os Sete Anões".', 'Fiz "Pinóquio", "Bambi", "Cinderela" e "Dumbo".', 'Dublei meu personagem mais famoso nos primeiros filmes.',
      'Abri um parque na Califórnia em 1955.', 'Estava planejando um segundo parque na Flórida quando morri.', 'Morri em 1966, de câncer no pulmão.', 'Existe uma lenda (falsa) de que meu corpo foi congelado.',
      'Criei o Mickey Mouse.', 'Minha empresa hoje é dona da Marvel, da Pixar e de Star Wars.', 'Meu sobrenome está no nome dos parques mais visitados do mundo.', 'Sou o criador do maior império de desenhos animados do planeta.',
    ] },
    { answer: 'Isaac Newton', clues: [
      'Nasci na Inglaterra no dia de Natal de 1642.', 'Meu pai morreu antes de eu nascer e fui criado pela avó.', 'Estudei em Cambridge, no Trinity College.', 'Quando a peste fechou a universidade, voltei para a fazenda da família e tive meu ano mais criativo.',
      'Construí o primeiro telescópio refletor.', 'Mostrei que a luz branca é feita de várias cores usando um prisma.', 'Briguei feio com Leibniz sobre quem inventou o cálculo primeiro.', 'Fui diretor da Casa da Moeda e cacei falsificadores de moedas.',
      'Fui presidente da Royal Society.', 'Escrevi mais sobre alquimia e religião do que sobre física.', 'Meu livro mais famoso se chama "Principia".', 'Disse que, se enxerguei mais longe, foi por estar sobre ombros de gigantes.',
      'Criei três leis do movimento.', 'Uma das minhas leis diz que a toda ação corresponde uma reação.', 'Expliquei por que a Lua não cai na Terra.', 'A unidade de força leva meu nome.',
      'Formulei a lei da gravitação universal.', 'A história diz que uma maçã caiu perto de mim.', 'Sou um cientista inglês do século 17.', 'Meu nome está ligado à descoberta da gravidade.',
    ] },
    { answer: 'Ronaldo (Fenômeno)', clues: [
      'Nasci em Bento Ribeiro, no Rio de Janeiro, em 1976.', 'Comecei no futsal do Social Ramos.', 'Fui revelado no Cruzeiro, com 17 anos.', 'Fui campeão do mundo sem entrar em campo, em 1994.',
      'Joguei no PSV Eindhoven, na Holanda.', 'Ganhei a Copa América de 1997 e 1999.', 'Passei pelo Barcelona e depois pela Inter de Milão.', 'Tive duas rupturas graves no joelho e voltei a jogar.',
      'Passei mal antes da final da Copa de 1998 e joguei mesmo assim.', 'Ganhei o prêmio de melhor do mundo três vezes.', 'Joguei no Real Madrid no time dos "galácticos".', 'Voltei ao Brasil para jogar no Corinthians.',
      'Comprei o Cruzeiro e virei dono de clube.', 'Fui artilheiro da Copa de 2002 com 8 gols.', 'Usei um corte de cabelo com um tufo na frente na Copa de 2002.', 'Fiz os dois gols da final contra a Alemanha em 2002.',
      'Fui campeão do mundo em 2002.', 'Meu apelido é "Fenômeno".', 'Sou considerado o maior centroavante brasileiro.', 'Sou um Ronaldo brasileiro, e não o português.',
    ] },
    { answer: 'Garrincha', clues: [
      'Nasci em Pau Grande, no interior do Rio de Janeiro, em 1933.', 'Meu nome de batismo é Manuel Francisco dos Santos.', 'Nasci com as pernas tortas e uma mais curta que a outra.', 'Meu apelido é o nome de um passarinho pequeno.',
      'Trabalhei numa fábrica de tecidos antes de ser jogador.', 'Fui reprovado num teste do Vasco por não ter carteira de trabalho.', 'No teste do Botafogo, driblei Nilton Santos com facilidade e fui contratado na hora.', 'Joguei quase toda a carreira no Botafogo.',
      'Meu drible principal era pelo lado direito, sempre para o mesmo lado, e ninguém conseguia parar.', 'A seleção só perdeu uma partida em que eu e Pelé jogamos juntos.', 'Fui eleito o melhor jogador da Copa de 1962.', 'Ganhei duas Copas do Mundo: 1958 e 1962.',
      'Em 1962, Pelé se machucou e eu carreguei o time sozinho.', 'Fui expulso numa Copa e mesmo assim joguei a final.', 'Fui casado com a cantora Elza Soares.', 'Morri em 1983, muito pobre, por causa da bebida.',
      'Sou chamado de "Alegria do Povo".', 'Sou considerado o maior driblador da história do futebol.', 'Sou um ponta-direita brasileiro dos anos 50 e 60.', 'Meu apelido de passarinho é mais conhecido que meu nome.',
    ] },
    { answer: 'Tom Jobim', clues: [
      'Nasci no Rio de Janeiro, em 1927.', 'Meu nome completo é Antônio Carlos Brasileiro de Almeida Jobim.', 'Cresci em Ipanema.', 'Estudei arquitetura antes de escolher a música.',
      'Comecei tocando piano em boates da Zona Sul carioca.', 'Fiz a trilha do filme "Orfeu Negro".', 'Compus com Vinicius de Moraes e Newton Mendonça.', 'Gravei um disco com Frank Sinatra em 1967.',
      'Fui um dos criadores de um gênero musical no fim dos anos 50.', 'Um show no Carnegie Hall em 1962 levou meu estilo para o mundo.', 'Compus "Águas de Março" e "Corcovado".', 'Compus "Chega de Saudade" com Vinicius.',
      'Era apaixonado por pássaros e pela natureza brasileira.', 'Minha música mais tocada nasceu de uma menina que passava a caminho da praia.', 'Compus "Garota de Ipanema".', 'Morri em Nova York, em 1994.',
      'O aeroporto internacional do Rio de Janeiro leva meu nome.', 'Sou o maior nome da bossa nova.', 'Sou um compositor e pianista brasileiro.', 'Meu apelido é "Tom".',
    ] },
    { answer: 'Clarice Lispector', clues: [
      'Nasci na Ucrânia, em 1920, e vim bebê para o Brasil.', 'Minha família fugiu de perseguições e chegou pelo Nordeste.', 'Cresci em Recife e depois no Rio de Janeiro.', 'Meu nome de nascimento é Chaya.',
      'Formei-me em Direito, mas nunca advoguei.', 'Publiquei meu primeiro romance aos 23 anos: "Perto do Coração Selvagem".', 'Fui casada com um diplomata e morei na Itália, na Suíça e nos Estados Unidos.', 'Escrevi crônicas em jornais e cartas famosas para minhas irmãs.',
      'Sofri um incêndio no quarto que queimou minha mão direita.', 'Dei uma entrevista na TV em 1977 em que falo baixo e quase sussurrando.', 'Escrevi "A Paixão Segundo G.H." e "Água Viva".', 'Escrevi contos reunidos em "Laços de Família".',
      'Meu último livro conta a história de Macabéa, uma nordestina em São Paulo.', 'Esse último livro é "A Hora da Estrela".', 'Minha escrita é cheia de silêncios, epifanias e frases estranhas.', 'Morri em 1977, na véspera do meu aniversário de 57 anos.',
      'Tenho uma estátua na praia do Leme, sentada com um cachorro.', 'Sou uma das maiores escritoras da literatura brasileira.', 'Meu primeiro nome é o mesmo de uma cor clara.', 'Sou escritora e meu sobrenome é de origem ucraniana.',
    ] },
    { answer: 'Carmen Miranda', clues: [
      'Nasci em Portugal, em 1909, e vim bebê para o Brasil.', 'Cresci no bairro da Lapa, no Rio de Janeiro.', 'Trabalhei numa loja de chapéus antes de cantar.', 'Comecei gravando sambas e marchinhas nos anos 30.',
      'Fui a primeira brasileira a ter um contrato de rádio como cantora exclusiva.', 'Cantei com o grupo Bando da Lua.', 'Fui para a Broadway em 1939.', 'Assinei contrato com a 20th Century Fox.',
      'Fiz filmes coloridos em Hollywood durante a Segunda Guerra.', 'Fui, por um tempo, a mulher mais bem paga dos Estados Unidos.', 'Fui criticada no Brasil por "americanizar" demais e respondi com a música "Disseram que Voltei Americanizada".', 'Meu figurino veio das baianas do Rio de Janeiro.',
      'Usava turbantes altíssimos e muitas pulseiras.', 'Sou famosa por um chapéu cheio de frutas.', 'Cantei "O Que É Que a Baiana Tem?".', 'Morri em 1955, um dia depois de gravar um programa de TV.',
      'Existe um museu com meu nome no Rio de Janeiro.', 'Sou o maior símbolo do Brasil no cinema americano dos anos 40.', 'Sou cantora e atriz luso-brasileira.', 'Meu visual com frutas na cabeça virou fantasia de Carnaval.',
    ] },
    { answer: 'Oscar Niemeyer', clues: [
      'Nasci no Rio de Janeiro, em 1907.', 'Estudei na Escola Nacional de Belas Artes.', 'Trabalhei de graça no escritório de Lúcio Costa quando comecei.', 'Ajudei a projetar o prédio do Ministério da Educação no Rio, com Le Corbusier por perto.',
      'Meu primeiro conjunto famoso foi na Pampulha, em Belo Horizonte.', 'A igrejinha que projetei na Pampulha ficou anos sem ser consagrada por ser "moderna demais".', 'Fui filiado ao Partido Comunista e me exilei na França na ditadura.', 'Projetei a sede do Partido Comunista Francês em Paris.',
      'Trabalhei no projeto da sede da ONU, em Nova York.', 'Projetei o Memorial da América Latina e o Parque do Ibirapuera, em São Paulo.', 'Projetei o Museu de Arte Contemporânea de Niterói, que parece um disco voador.', 'Dizia que meu material preferido era o concreto armado, porque permitia curvas.',
      'Falava que não me atraía o ângulo reto, mas a curva livre e sensual.', 'Projetei a Catedral, o Congresso e o Palácio da Alvorada.', 'Desenhei os prédios principais de Brasília.', 'Trabalhei até os 104 anos.',
      'Morri em 2012, dez dias antes de completar 105 anos.', 'Sou o arquiteto brasileiro mais conhecido do mundo.', 'Minhas obras são famosas pelas curvas de concreto branco.', 'Sou o arquiteto que desenhou a capital do Brasil.',
    ] },
    { answer: 'Paulo Coelho', clues: [
      'Nasci no Rio de Janeiro, em 1947.', 'Meus pais me internaram três vezes num hospital psiquiátrico quando eu era adolescente.', 'Fui preso e torturado nos anos 70.', 'Trabalhei como jornalista e produtor de discos.',
      'Escrevi letras de música com Raul Seixas.', 'Escrevi as letras de "Gita" e "Sociedade Alternativa".', 'Fiz o Caminho de Santiago de Compostela em 1986.', 'Meu primeiro livro conta essa caminhada e se chama "O Diário de um Mago".',
      'Sou membro da Academia Brasileira de Letras desde 2002.', 'Sou um dos autores mais traduzidos vivos do mundo.', 'Escrevi "Brida", "Veronika Decide Morrer" e "Onze Minutos".', 'Meus livros falam de destino, sinais e "lenda pessoal".',
      'Uso muito o Twitter e falo direto com os leitores.', 'Meu livro mais famoso conta a história de um pastor andaluz chamado Santiago.', 'Esse pastor viaja até as pirâmides do Egito atrás de um tesouro.', 'Meu livro mais vendido é "O Alquimista".',
      'Já vendi mais de 300 milhões de livros.', 'Moro na Europa há muitos anos.', 'Sou o escritor brasileiro mais vendido de todos os tempos.', 'Meu sobrenome é o nome de um animal que anda devagar.',
    ] },
    { answer: 'Getúlio Vargas', clues: [
      'Nasci em São Borja, no Rio Grande do Sul, em 1882.', 'Entrei no Exército jovem e depois estudei Direito.', 'Fui ministro da Fazenda antes de chegar ao poder.', 'Perdi a eleição presidencial de 1930 e assumi o poder por um movimento armado no mesmo ano.',
      'Enfrentei a Revolução Constitucionalista de São Paulo em 1932.', 'Dei um golpe em 1937 e fechei o Congresso.', 'Meu regime autoritário se chamou Estado Novo.', 'Criei o DIP, um departamento de propaganda e censura.',
      'Mandei tropas brasileiras lutarem na Itália na Segunda Guerra.', 'Criei a CLT e o salário mínimo.', 'Criei a Petrobras e a Companhia Siderúrgica Nacional.', 'Fui chamado de "pai dos pobres" por causa das leis trabalhistas.',
      'Fui deposto em 1945 e voltei eleito em 1950.', 'Meu segundo governo terminou numa crise política enorme.', 'Deixei uma carta-testamento dizendo "saio da vida para entrar na história".', 'Me matei com um tiro no peito no Palácio do Catete, em agosto de 1954.',
      'Governei o Brasil por 15 anos seguidos e depois mais 3.', 'O dia do trabalhador virou data de anúncios no meu governo.', 'Sou o político brasileiro mais influente do século 20.', 'Sou um presidente gaúcho conhecido pelo charuto e pelo terno.',
    ] },
    { answer: 'Freddie Mercury', clues: [
      'Nasci em Zanzibar, na África, em 1946.', 'Meu nome de nascimento é Farrokh Bulsara.', 'Minha família é parse, de origem indiana.', 'Estudei em um colégio interno na Índia e aprendi piano lá.',
      'Minha família fugiu para a Inglaterra por causa de uma revolução.', 'Estudei design gráfico e desenhei o brasão da minha banda.', 'Vendia roupas usadas num mercado de Londres antes da fama.', 'Entrei numa banda chamada Smile e mudei o nome dela.',
      'Tinha quatro dentes incisivos a mais, o que ajudava minha voz.', 'Minha extensão vocal passava de três oitavas.', 'Compus "Somebody to Love" e "Don\'t Stop Me Now".', 'Fiz um dueto com a soprano Montserrat Caballé.',
      'Minha apresentação no Live Aid de 1985 é considerada a melhor de todos os tempos.', 'Compus uma música de quase 6 minutos com uma parte de ópera no meio.', 'Essa música é "Bohemian Rhapsody".', 'Anunciei que tinha aids um dia antes de morrer, em 1991.',
      'Minha banda também tem "We Will Rock You" e "We Are the Champions".', 'Sou o vocalista do Queen.', 'Um filme de 2018 sobre mim ganhou o Oscar de melhor ator.', 'Sou o cantor de bigode que cantava com o microfone sem pedestal.',
    ] },
    { answer: 'John Lennon', clues: [
      'Nasci em Liverpool, em 1940, durante a Segunda Guerra.', 'Fui criado por uma tia, a tia Mimi.', 'Minha mãe, Julia, me ensinou banjo e morreu atropelada quando eu tinha 17 anos.', 'Minha primeira banda se chamava The Quarrymen.',
      'Conheci meu principal parceiro de composição numa festa de igreja em 1957.', 'Tocamos em Hamburgo, na Alemanha, antes de estourar.', 'Disse numa entrevista que minha banda era mais popular que Jesus e causei um escândalo.', 'Compus com Paul McCartney; assinávamos as músicas juntos.',
      'Casei com uma artista japonesa em 1969.', 'Fiz um protesto contra a guerra ficando uma semana na cama com minha esposa.', 'Compus "Come Together" e "Strawberry Fields Forever".', 'Minha esposa é Yoko Ono.',
      'Compus um hino pacifista que imagina um mundo sem países e sem religiões.', 'Essa música é "Imagine".', 'Usava óculos redondos pequenos.', 'Fui morto a tiros em Nova York, na porta do meu prédio, em dezembro de 1980.',
      'Meu assassino tinha pedido meu autógrafo horas antes.', 'Sou um dos quatro integrantes dos Beatles.', 'Tem um memorial com meu nome no Central Park chamado Strawberry Fields.', 'Sou o beatle dos óculos redondos, casado com a Yoko.',
    ] },
    { answer: 'Beyoncé', clues: [
      'Nasci em Houston, no Texas, em 1981.', 'Meu pai largou o emprego para ser meu empresário.', 'Comecei num grupo infantil chamado Girl\'s Tyme.', 'Meu grupo perdeu num programa de calouros na TV.',
      'Meu grupo depois virou um trio de enorme sucesso nos anos 90.', 'Meu grupo é o Destiny\'s Child.', 'Meu primeiro disco solo saiu em 2003 e se chama "Dangerously in Love".', 'Sou casada com um rapper e empresário desde 2008.',
      'Meu marido é o Jay-Z.', 'Tenho três filhos, entre eles gêmeos.', 'Lancei um disco surpresa, sem aviso nenhum, em 2013.', 'Fiz um show no festival Coachella em 2018 inspirado nas universidades negras americanas.',
      'Sou a artista com mais Grammys da história.', 'Cantei "Single Ladies", "Halo" e "Crazy in Love".', 'Meu disco "Lemonade" é sobre traição e reconciliação.', 'Meu disco "Cowboy Carter" ganhou o Grammy de álbum do ano em 2025.',
      'Meus fãs se chamam "BeyHive", a colmeia.', 'Sou chamada de "Queen B".', 'Sou uma cantora americana e uma das maiores estrelas pop do mundo.', 'Meu nome começa com B e tem acento no final.',
    ] },
    { answer: 'Marta', clues: [
      'Nasci em Dois Riachos, em Alagoas, em 1986.', 'Cresci muito pobre e jogava bola com os meninos na rua.', 'Peguei um ônibus de três dias sozinha para fazer teste no Rio de Janeiro.', 'Fui aprovada no Vasco da Gama com 14 anos.',
      'Fui jogar na Suécia em 2004, no Umeå.', 'Também joguei nos Estados Unidos, no Orlando Pride.', 'Ganhei a Copa Libertadores feminina.', 'Fui vice-campeã olímpica em 2004 e 2008.',
      'Fui artilheira e melhor jogadora da Copa do Mundo de 2007.', 'Sou embaixadora da ONU Mulheres.', 'Usei uma chuteira sem patrocínio, com a fita cobrindo a marca, para protestar.', 'Fiz um discurso emocionado em 2019 pedindo que as meninas não desistissem do futebol.',
      'Sou a maior artilheira da história das Copas do Mundo, contando homens e mulheres.', 'Joguei em seis Copas do Mundo.', 'Fui eleita a melhor do mundo seis vezes.', 'Ganhei a prata olímpica em Paris 2024 na minha despedida da seleção.',
      'Uso a camisa 10 da seleção brasileira.', 'Sou chamada de "Rainha" e de "Pelé de saias".', 'Sou a maior jogadora de futebol feminino da história.', 'Meu nome tem cinco letras e é o mesmo de uma personagem da Bíblia.',
    ] },
    { answer: 'Zico', clues: [
      'Nasci no Rio de Janeiro, em 1953.', 'Meu nome é Arthur Antunes Coimbra.', 'Sou filho de portugueses e cresci em Quintino.', 'Era muito magro quando cheguei ao clube e fiz um tratamento para ganhar massa.',
      'Meu irmão Edu também foi jogador.', 'Joguei no Udinese, na Itália.', 'Fui ministro dos Esportes no governo Collor.', 'Fui técnico da seleção do Japão e ajudei a criar a liga profissional de lá.',
      'Sou considerado o maior cobrador de falta da história do futebol brasileiro.', 'Ganhei a Libertadores e o Mundial de 1981.', 'Fui eleito o melhor do mundo em 1981 e 1983.', 'Perdi um pênalti na Copa de 1986 contra a França.',
      'Fui o craque da seleção de 1982, que muita gente considera a melhor que não ganhou nada.', 'Sou o maior artilheiro da história do meu clube.', 'Joguei quase toda a carreira no Flamengo.', 'Meu apelido é "Galinho de Quintino".',
      'Sou chamado de "Rei do Maracanã".', 'Sou considerado o melhor jogador brasileiro entre Pelé e Romário.', 'Meu apelido tem quatro letras e começa com Z.', 'Sou um ídolo do Flamengo dos anos 80.',
    ] },
    { answer: 'Batman', clues: [
      'Apareci pela primeira vez numa revista em 1939.', 'Fui criado por Bob Kane e Bill Finger.', 'Meu mordomo se chama Alfred.', 'Meus pais foram mortos num assalto num beco quando eu era criança.',
      'Não tenho nenhum superpoder.', 'Sou dono de uma empresa gigante herdada da família.', 'Minha empresa se chama Wayne Enterprises.', 'Treinei artes marciais pelo mundo antes de voltar para casa.',
      'Moro numa mansão com uma caverna embaixo.', 'Meu ajudante é um garoto de circo chamado Dick Grayson.', 'Minha cidade tem um asilo para criminosos loucos chamado Arkham.', 'Meu maior inimigo tem cabelo verde e um sorriso pintado.',
      'A polícia me chama acendendo um holofote no céu.', 'Moro em Gotham City.', 'Meu nome verdadeiro é Bruce Wayne.', 'Sou chamado de "Cavaleiro das Trevas".',
      'Ando num carro preto blindado.', 'Sou um herói da DC Comics.', 'Minha fantasia imita um animal que voa à noite.', 'Sou o herói-morcego.',
    ] },
    { answer: 'Darth Vader', clues: [
      'Nasci escravo num planeta desértico.', 'Meu planeta natal é Tatooine.', 'Fui encontrado ainda criança por um cavaleiro chamado Qui-Gon Jinn.', 'Meu mestre foi Obi-Wan Kenobi.',
      'Era considerado o "escolhido" de uma antiga profecia.', 'Casei em segredo com uma senadora chamada Padmé.', 'Virei para o lado sombrio com medo de perder minha esposa.', 'Perdi um duelo num planeta de lava e quase morri queimado.',
      'Fui salvo por uma armadura que me mantém vivo.', 'Meu mestre passou a ser o Imperador Palpatine.', 'Cacei e matei quase todos os Jedi.', 'Tenho dois filhos gêmeos que foram escondidos de mim.',
      'Minha filha é a princesa Leia.', 'Minha respiração pesada anuncia minha chegada.', 'Meu sabre de luz é vermelho.', 'Digo ao herói: "Eu sou seu pai".',
      'Meu nome verdadeiro é Anakin Skywalker.', 'Me salvei no fim jogando o Imperador num abismo.', 'Sou o vilão de capacete preto de Star Wars.', 'Meu nome tem "Darth" na frente.',
    ] },
    { answer: 'Charles Darwin', clues: [
      'Nasci na Inglaterra, em 1809, no mesmo dia que Abraham Lincoln.', 'Meu avô Erasmus também era cientista.', 'Comecei estudando medicina, mas desmaiava nas cirurgias.', 'Meu pai queria que eu virasse pastor anglicano.',
      'Embarquei num navio como naturalista aos 22 anos.', 'Meu navio se chamava HMS Beagle.', 'Passei quase cinco anos viajando e passei pelo Brasil.', 'Estudei tartarugas e passarinhos num arquipélago do Pacífico.',
      'Esse arquipélago é Galápagos.', 'Notei que os bicos dos tentilhões mudavam de ilha para ilha.', 'Demorei mais de 20 anos para publicar minha teoria, com medo da reação.', 'Publiquei só quando Alfred Russel Wallace chegou à mesma ideia.',
      'Meu livro saiu em 1859.', 'Meu livro se chama "A Origem das Espécies".', 'Também escrevi sobre a origem do homem.', 'Minha ideia central é a seleção natural.',
      'Fui enterrado na Abadia de Westminster.', 'Sou o pai da teoria da evolução.', 'Sou um naturalista inglês de barba branca comprida.', 'Meu nome é ligado à ideia de que o homem e o macaco têm ancestral comum.',
    ] },
    { answer: 'Whindersson Nunes', clues: [
      'Nasci em Bom Jesus, no Piauí, em 1995.', 'Minha mãe é cabeleireira e meu pai trabalhava com carreto.', 'Comecei postando vídeos em 2013, gravando no quarto.', 'Meu primeiro vídeo era uma paródia de uma música da Anitta.',
      'Fiquei famoso fazendo paródias e imitações de artistas.', 'Já fui o brasileiro com mais inscritos no YouTube.', 'Fiz shows de stand-up no Brasil inteiro e lotei arenas.', 'Atuei em filmes de comédia brasileiros.',
      'Fiz uma turnê internacional para brasileiros que moram fora.', 'Fui casado com a cantora Luísa Sonza.', 'Perdi um filho recém-nascido em 2021 e falei abertamente sobre depressão.', 'Comecei a treinar boxe e fiz lutas beneficentes.',
      'Lutei contra o influenciador Popó em 2024.', 'Sou piauiense e brinco muito com meu sotaque nordestino.', 'Falo direto sobre saúde mental com os seguidores.', 'Sou o humorista mais seguido do Brasil.',
      'Comecei minha carreira no YouTube.', 'Sou humorista, cantor e agora também lutador.', 'Meu primeiro nome é comprido e começa com W.', 'Sou o youtuber humorista mais famoso do Brasil.',
    ] },
    { answer: 'Galvão Bueno', clues: [
      'Nasci no Rio de Janeiro, em 1950.', 'Comecei narrando automobilismo no rádio, na Jovem Pan.', 'Narrei minha primeira Copa do Mundo em 1974, pelo rádio.', 'Fui contratado pela Globo em 1981.',
      'Narrei as vitórias de Ayrton Senna na Fórmula 1.', 'Fiquei famoso pela relação de amizade com o Senna.', 'Chorei ao vivo ao anunciar a morte do Senna, em 1994.', 'Narrei Copas do Mundo por mais de 40 anos.',
      'Tenho uma marca de vinhos com meu nome.', 'Meu bordão inclui "Haja coração!".', 'Digo "Bem, amigos da Rede Globo..." ao abrir a transmissão.', 'Narrei o tetra em 1994 e o penta em 2002.',
      'Me despedi das narrações na Copa do Catar, em 2022.', 'Muita gente reclamava que eu "puxava" para um lado.', 'Sou conhecido por gritar o gol por muito tempo.', 'Fui a voz do esporte na Globo por quatro décadas.',
      'Sou narrador esportivo.', 'Meu sobrenome é o mesmo de um animal de fazenda.', 'Narrei futebol, Fórmula 1 e Olimpíadas.', 'Sou o narrador mais famoso da televisão brasileira.',
    ] },
    { answer: 'Fernanda Montenegro', clues: [
      'Nasci no Rio de Janeiro, em 1929.', 'Meu nome verdadeiro é Arlette Pinheiro.', 'Comecei no rádio aos 15 anos.', 'Fui casada com o ator e diretor Fernando Torres.',
      'Ajudei a fundar o Teatro dos Sete.', 'Estive na primeira novela diária da televisão brasileira.', 'Fiz "Guerra dos Sexos", "Belíssima" e "Passione" na TV.', 'Fiz o papel de Dona Picucha em "Doce de Mãe".',
      'Minha filha também é atriz premiada.', 'Minha filha é Fernanda Torres.', 'Fui a primeira brasileira indicada ao Oscar de melhor atriz.', 'Fui indicada pelo filme "Central do Brasil", de 1998.',
      'No filme, faço uma ex-professora que escreve cartas na estação de trem.', 'Ganhei o Urso de Prata em Berlim por esse papel.', 'Sou chamada de "a grande dama do teatro brasileiro".', 'Fiz uma ponta em "Ainda Estou Aqui", filme da minha filha, em 2024.',
      'Tenho mais de 70 anos de carreira.', 'Sou atriz de teatro, cinema e televisão.', 'Meu sobrenome artístico é o nome de um país.', 'Sou considerada a maior atriz do Brasil.',
    ] },
    { answer: 'Caetano Veloso', clues: [
      'Nasci em Santo Amaro da Purificação, na Bahia, em 1942.', 'Minha irmã também é cantora famosa.', 'Minha irmã é Maria Bethânia.', 'Fui muito influenciado por João Gilberto.',
      'Estudei Filosofia em Salvador.', 'Cheguei ao Sudeste em 1965 para tentar a carreira.', 'Criei um movimento com Gilberto Gil no fim dos anos 60.', 'Esse movimento é o tropicalismo.',
      'Fui preso pela ditadura em 1968 e tive a cabeça raspada.', 'Fiquei exilado em Londres entre 1969 e 1972.', 'Compus "Alegria, Alegria" e "Tropicália".', 'Compus "Sampa", sobre São Paulo.',
      'Compus "Você é Linda" e "Sozinho".', 'Fiz o disco "Livro", premiado com um Grammy.', 'Fiz shows com meus filhos Moreno, Zeca e Tom.', 'Minha música "Coração Vagabundo" virou nome de documentário.',
      'Sou baiano, magro e uso óculos.', 'Sou um dos maiores compositores da MPB.', 'Meu sobrenome é o mesmo de uma marca de bicicleta popular.', 'Sou o cantor baiano criador da Tropicália, irmão da Bethânia.',
    ] },
  ],
};

module.exports = { CARDS5 };
