// Lote 13 do Perfil — Coisas (do dia a dia, apps, comida e internet). Cada carta: resposta + 20 dicas.
const CARDS13 = {
  C: [
    { answer: 'Spotify', clues: [
      'Nasci na Suécia, em 2006.', 'Meus criadores são Daniel Ek e Martin Lorentzon.', 'Fui criado para combater a pirataria de música.', 'Cheguei ao Brasil em 2014.',
      'Pago frações de centavo para os artistas por reprodução.', 'Os músicos reclamam disso até hoje.', 'Minha cor é verde e meu ícone tem três ondas.', 'Tenho uma versão grátis com anúncios.',
      'Meu algoritmo cria uma playlist semanal de descobertas.', 'Essa playlist se chama "Descobertas da Semana".', 'Todo dezembro faço um resumo do ano de cada usuário.', 'Esse resumo se chama "Wrapped" ou "Retrospectiva".',
      'Todo mundo posta a retrospectiva nos stories.', 'Sou o maior serviço de streaming de música do mundo.', 'Também tenho podcasts e audiolivros.', 'O Brasil é um dos meus maiores mercados.',
      'Um dos meus artistas mais ouvidos no mundo é Bad Bunny.', 'Tenho um botão de "curtir" em forma de coração, hoje um "+".', 'Sou o aplicativo verde de música.', 'Meu nome termina com "fy".',
    ] },
    { answer: 'Uber', clues: [
      'Nasci em São Francisco, em 2009.', 'A ideia surgiu numa noite de neve em Paris, sem táxi.', 'Meu criador foi Travis Kalanick, que depois foi afastado por escândalos.', 'No começo eu só tinha carros pretos de luxo.',
      'Cheguei ao Brasil em 2014.', 'Fui recebido com protestos e agressões de taxistas.', 'Fui proibido em várias cidades antes de ser regulamentado.', 'Meu preço sobe quando a demanda aumenta.',
      'Isso se chama "preço dinâmico".', 'Meu motorista e meu passageiro se avaliam com estrelas.', 'Tenho versões com desconto, compartilhada e de luxo.', 'Tenho uma versão para entregar comida.',
      'Essa versão é o Uber Eats, que saiu do Brasil em 2022.', 'Fiz muita gente vender o carro e virar motorista.', 'Meu nome virou verbo: "vou de…".', 'Falam "chamar um…" mesmo quando é do concorrente.',
      'Meu concorrente principal no Brasil é o 99.', 'Meu ícone é preto com o nome em branco.', 'Sou o aplicativo de chamar carro.', 'Meu nome tem quatro letras e vem do alemão "super".',
    ] },
    { answer: 'iFood', clues: [
      'Nasci em 2011, em Osasco, na Grande São Paulo.', 'Comecei como um guia de restaurantes chamado Disk Cook.', 'Sou o maior aplicativo de entrega da América Latina.', 'Faço mais de 100 milhões de pedidos por mês.',
      'Meus entregadores andam de moto e de bicicleta com uma mochila vermelha.', 'Essa mochila é uma "bag" quadrada.', 'Minha cor é vermelha.', 'Meus cupons de desconto viram assunto nos grupos de WhatsApp.',
      'Tenho um clube de assinatura com frete grátis.', 'Esse clube se chama Clube iFood.', 'Também entrego mercado, farmácia e bebida.', 'Faço campanhas com famosos e patrocino programas de TV.',
      'Meus entregadores fazem greves por causa da remuneração.', 'Fui comprado pela holandesa Prosus.', 'Minhas avaliações são de 1 a 5 estrelas.', 'A frase "está a caminho" é minha.',
      'Meu concorrente foi o Rappi.', 'Meu nome começa com "i" minúsculo.', 'Sou o aplicativo de pedir comida.', 'Meu nome tem "Food", comida em inglês.',
    ] },
    { answer: 'Mercado Livre', clues: [
      'Nasci na Argentina, em 1999.', 'Meu criador é Marcos Galperin, que me criou na faculdade em Stanford.', 'Fui inspirado no eBay, que virou meu sócio.', 'Sobrevivi ao estouro da bolha da internet.',
      'Minha cor é amarela.', 'Meu ícone é um aperto de mãos.', 'Sou a empresa mais valiosa da América Latina.', 'Tenho um banco digital chamado Mercado Pago.',
      'Tenho caminhões, aviões e galpões próprios para entregar.', 'Minhas entregas chegam em 24 horas nas capitais.', 'Meu programa de assinatura inclui streaming.', 'Meu nível de reputação usa um termômetro colorido.',
      'Os vendedores "MercadoLíder" têm selo especial.', 'Vendo de parafuso a carro.', 'Minha caixa de papelão tem meu logo em preto.', 'Tenho campanhas com o "Compra Garantida".',
      'Meu concorrente atual mais forte é a Shopee.', 'Meu nome quer dizer que qualquer um pode vender.', 'Sou o site de compras amarelo.', 'Meu nome tem "Mercado" e "Livre".',
    ] },
    { answer: 'Shopee', clues: [
      'Nasci em Singapura, em 2015.', 'Pertenço ao grupo Sea, o mesmo do jogo Free Fire.', 'Cheguei ao Brasil em 2019.', 'Cresci vendendo produtos baratos vindos da China.',
      'Minha cor é laranja.', 'Meu ícone é uma sacola com um S.', 'Tenho jogos e moedas dentro do aplicativo para ganhar desconto.', 'Meus cupons de frete grátis são a minha marca.',
      'Tenho lives de vendas com apresentadores.', 'Meus comerciais têm uma musiquinha grudenta.', 'Muita gente compra coisas que nunca precisou por causa do preço.', 'A "taxa das blusinhas" foi criada por causa de sites como eu.',
      'Passei a ter vendedores brasileiros também.', 'Minhas entregas viajam de avião da Ásia.', 'Meu concorrente chinês é o AliExpress.', 'Meu outro concorrente é a Temu.',
      'Fiz muita gente virar "revendedor" de produtos baratos.', 'Minhas embalagens são um saco plástico laranja.', 'Sou o site laranja de compras baratas.', 'Meu nome vem de "shop", comprar em inglês.',
    ] },
    { answer: 'Nubank', clues: [
      'Nasci em 2013, numa casinha em São Paulo.', 'Meu fundador é um colombiano chamado David Vélez.', 'Ele teve a ideia depois de sofrer para abrir uma conta num banco tradicional.', 'Comecei com um cartão de crédito sem anuidade.',
      'Minha cor é roxa.', 'Meu cartão é roxo e chegava numa caixinha bonita.', 'No começo era preciso convite para entrar.', 'Não tenho agências.',
      'Sou o maior banco digital do mundo em clientes.', 'Tenho mais de 100 milhões de clientes.', 'Abri capital na bolsa de Nova York em 2021.', 'Warren Buffett investiu em mim.',
      'Meu app tem "caixinhas" para guardar dinheiro.', 'Tenho a Nu Conta, empréstimo e investimentos.', 'Meu mascote informal é o "roxinho".', 'Meu atendimento é só pelo aplicativo.',
      'Os bancos grandes copiaram meu modelo.', 'Meu nome mistura "nu" (pelado, sem tarifa) e "bank".', 'Sou o banco roxo.', 'Meu nome começa com Nu.',
    ] },
    { answer: 'Alexa', clues: [
      'Fui lançada em 2014 pela Amazon.', 'Meu nome foi inspirado na Biblioteca de Alexandria.', 'Cheguei ao Brasil em 2019 falando português.', 'Moro dentro de uma caixinha de som redonda.',
      'Essa caixinha se chama Echo.', 'Acendo um anel azul quando alguém fala comigo.', 'Sou ativada quando alguém fala meu nome.', 'Respondo a perguntas, toco música e acendo luzes.',
      'Conto piadas ruins quando pedem.', 'Tenho "habilidades" que se instalam como aplicativos.', 'Já respondi sozinha a coisas na TV que falaram meu nome.', 'Gravo o que ouço e isso preocupa muita gente.',
      'As crianças gostam de me pedir para tocar músicas infantis.', 'Já respondi risadas do nada e assustei usuários.', 'Ganhei uma versão com inteligência artificial em 2025.', 'Sou a maior concorrente da Siri e do Google Assistente.',
      'Meu nome também é um nome de mulher.', 'Sou a assistente de voz da Amazon.', 'Falam "…, toca uma música" comigo.', 'Meu nome tem cinco letras e começa com A.',
    ] },
    { answer: 'Carregador portátil', clues: [
      'Nasci quando os celulares passaram a durar menos que o dia.', 'Sou uma bateria de lítio dentro de uma caixinha.', 'Meu nome em inglês é "power bank".', 'Minha capacidade é medida em miliampère-hora.',
      'Um modelo de 10.000 mAh carrega um celular umas duas vezes.', 'Tenho luzinhas que mostram quanto ainda tenho de carga.', 'Preciso ser carregado antes de sair de casa, e sempre esquecem.', 'Sou proibido na bagagem despachada de avião.',
      'Só posso ir na bagagem de mão, por causa do risco de incêndio.', 'Companhias aéreas proibiram usar-me dentro do voo em 2025.', 'Sou item obrigatório em festival e em show.', 'Sou um dos brindes mais comuns de empresa.',
      'Fico pesado no bolso ou na bolsa.', 'Existo com fio embutido e com carregamento sem fio.', 'Alguns modelos grudam com ímã na traseira do iPhone.', 'Sou o salva-vidas do fim da noite.',
      'Pedir emprestado é comum em bar.', 'Sou a bateria extra do celular.', 'Meu nome tem "portátil".', 'Sou a bateria que se carrega e carrega o celular.',
    ] },
    { answer: 'Patinete elétrico', clues: [
      'Sou o filho do patinete de criança com um motor.', 'Cheguei nas cidades brasileiras em 2018, com empresas de aluguel.', 'Essas empresas me espalhavam pelas calçadas com aplicativo.', 'A Yellow e a Grin foram as primeiras aqui.',
      'Muitos de mim acabaram jogados em rios e lixeiras.', 'Chego a 20 ou 25 km/h.', 'Minha bateria dura em torno de 20 a 40 km.', 'Preciso de capacete, mas quase ninguém usa.',
      'Sou proibido em calçadas em muitas cidades.', 'Tenho um freio na manopla e outro no pé.', 'Sou dobrável para caber no metrô.', 'Sou popular entre entregadores e em condomínios.',
      'Sou muito usado por crianças e adolescentes.', 'Meus acidentes lotaram os pronto-socorros.', 'Minha versão de aluguel se chama "compartilhado".', 'Tenho um guidão e uma plataforma para os dois pés.',
      'Ando sem fazer barulho.', 'Sou um meio de transporte urbano leve.', 'Meu nome tem "elétrico".', 'Sou o patinete que anda sozinho.',
    ] },
    { answer: 'AirPods', clues: [
      'Fui lançado em setembro de 2016, junto com o iPhone 7.', 'Fui apresentado no mesmo evento em que o iPhone perdeu a entrada de fone.', 'Fui muito ridicularizado no começo.', 'Diziam que eu parecia uma escova de dentes cortada.',
      'Virei o produto de áudio mais vendido da história.', 'Meu estojo é branco e abre como uma caixinha de fio dental.', 'Só abrir o estojo perto do iPhone já me conecta.', 'Meu estojo também me carrega.',
      'Minha versão "Pro" tem cancelamento de ruído.', 'Minha versão "Max" é um fone grande, de cabeça.', 'Sou fácil de perder no sofá e no metrô.', 'Muita gente perde só um lado.',
      'Alguns modelos meus tocam sons para serem achados.', 'Uso Bluetooth para conectar.', 'Uso um chip próprio da Apple.', 'Sou branco e sem fio.',
      'Meu nome tem "Air".', 'Sou o fone sem fio da Apple.', 'Meus concorrentes são os "buds" de outras marcas.', 'Meu nome termina com "Pods".',
    ] },
    { answer: 'Smartwatch', clues: [
      'Meus ancestrais foram relógios-calculadora dos anos 80.', 'Minha versão moderna mais famosa saiu em 2015.', 'Essa versão é o Apple Watch.', 'Tenho concorrentes da Samsung, Garmin e Xiaomi.',
      'Meço batimentos cardíacos no pulso.', 'Conto passos e calorias.', 'Aviso quando a pessoa fica muito tempo sentada.', 'Fecho "anéis" de atividade que as pessoas postam no Instagram.',
      'Meço oxigênio no sangue e faço eletrocardiograma.', 'Alguns modelos meus detectam queda e ligam para emergência.', 'Mostro as notificações do celular no pulso.', 'Dá para atender ligação falando com o pulso.',
      'Pago compras por aproximação.', 'Meço o sono de quem dorme comigo.', 'Minha bateria dura um dia e precisa carregar toda noite.', 'Tenho pulseiras trocáveis de todas as cores.',
      'Sou usado por corredores e por quem quer parecer saudável.', 'Sou um relógio com tela sensível ao toque.', 'Meu nome mistura "inteligente" e "relógio" em inglês.', 'Sou o relógio inteligente.',
    ] },
    { answer: 'Coxinha', clues: [
      'Uma lenda diz que nasci na cozinha da princesa Isabel, para um filho dela que só comia coxa de galinha.', 'Historiadores dizem que nasci nas fábricas de São Paulo, como comida barata para operários.', 'Meu formato imita a parte do frango que dá meu nome.', 'Minha massa é feita com farinha de trigo e caldo de galinha.',
      'Alguns fazem minha massa com batata ou mandioca.', 'Meu recheio tradicional é frango desfiado.', 'Minha versão com um queijo cremoso é a mais vendida.', 'Esse queijo é o catupiry.',
      'Sou empanada com farinha de rosca e frita em óleo quente.', 'Sou a rainha das lanchonetes de padaria.', 'Sou o salgadinho mais vendido em festa de aniversário.', 'Existo em tamanho mini para festa.',
      'Tenho versões de carne seca, camarão e jaca.', 'A versão de jaca é para veganos.', 'Já ganhei recheio de brigadeiro em versão doce.', 'Existo em todo boteco e padaria do Brasil.',
      'Meu nome também virou gíria política.', 'Minha ponta fina fica crocante.', 'Sou o salgado brasileiro em forma de gota.', 'Meu nome é o diminutivo de uma parte do frango.',
    ] },
    { answer: 'Pão francês', clues: [
      'Meu nome varia conforme o estado brasileiro.', 'Me chamam de cacetinho, pão de sal, carioquinha, pão jacó e pão careca.', 'Meu nome mais comum veio de padeiros que imitavam pães de Paris no século 19.', 'Na França não existe nada igual a mim.',
      'Sou feito de farinha de trigo, água, sal e fermento.', 'Tenho um corte no meio, feito com lâmina, antes de assar.', 'Meu peso padrão de 50 gramas é regulado por lei em alguns lugares.', 'Sou vendido por quilo ou por unidade.',
      'Meu preço é um termômetro da inflação.', 'Sou assado várias vezes por dia na padaria.', 'Sou melhor quentinho, na hora que sai do forno.', 'Fico duro em poucas horas.',
      'Quando fico velho viro farinha de rosca ou torrada.', 'Meu miolo é branco e macio.', 'Minha casca é dourada e crocante.', 'Sou o pão do café da manhã brasileiro.',
      'Combino com manteiga na chapa.', 'Sou o pão do sanduíche de mortadela.', 'Sou o pãozinho de sal mais comum do Brasil.', 'Meu nome tem o nome de um país.',
    ] },
    { answer: 'Miojo', clues: [
      'Fui inventado no Japão em 1958 por Momofuku Ando.', 'Ele queria alimentar o Japão pobre do pós-guerra.', 'Meu nome oficial é macarrão instantâneo.', 'Minha primeira marca foi Nissin.',
      'Cheguei ao Brasil em 1965 e demorei a pegar.', 'Meu nome brasileiro vem de uma marca da Nissin que virou nome genérico.', 'Sou frito e desidratado, por isso cozinho tão rápido.', 'Fico pronto em 3 minutos.',
      'Meu tempero vem num saquinho de pó.', 'Meus sabores mais vendidos são galinha caipira e carne.', 'Sou o prato oficial de estudante e de fim de mês.', 'Tem gente que me come cru, como salgadinho.',
      'Sou a base do "lámen" japonês, versão sofisticada.', 'Minha versão em copo só precisa de água quente.', 'Tenho versões de picanha, costela e churrasco.', 'Sou pobre em nutrientes e rico em sódio.',
      'Existe um museu meu no Japão.', 'Sou macarrão que fica pronto em minutos.', 'Meu nome tem cinco letras e começa com M.', 'Sou o macarrão instantâneo.',
    ] },
    { answer: 'Nutella', clues: [
      'Nasci na Itália depois da Segunda Guerra, quando faltava cacau.', 'Meu criador foi Pietro Ferrero, um confeiteiro.', 'Ele misturou avelãs, que eram abundantes na região, com pouco chocolate.', 'Meu primeiro nome era Giandujot e eu era vendida em barra.',
      'Ganhei meu nome atual em 1964.', 'Minha empresa também faz Kinder Ovo e Ferrero Rocher.', 'Uso cerca de um quarto das avelãs do mundo.', 'Meu ingrediente principal é açúcar, depois óleo de palma.',
      'Meu pote de vidro vira copo depois de vazio.', 'Tenho um dia mundial em 5 de fevereiro.', 'Sou passada no pão, na panqueca e no crepe.', 'No Brasil virei recheio de pizza, brigadeiro e coxinha doce.',
      'Meu preço subiu tanto que tem quem me chame de "ouro".', 'Sou marrom, brilhante e cremosa.', 'Minha versão de biscoito e de sorvete existem.', 'Uma promoção minha causou brigas em supermercados na França.',
      'Meu rótulo é branco com o nome em preto e vermelho.', 'Sou o creme de avelã mais famoso do mundo.', 'Meu nome termina com "ella".', 'Sou o creme de avelã com chocolate.',
    ] },
    { answer: 'Protetor solar', clues: [
      'Meus ancestrais foram óleos e pastas usadas por egípcios e gregos.', 'Minha versão moderna nasceu nos anos 30 e 40.', 'Um químico austríaco me criou depois de se queimar escalando uma montanha.', 'Nos anos 60 ainda vendiam óleo para bronzear, não para proteger.',
      'Meu número mais importante é o FPS.', 'O FPS diz quantas vezes mais tempo a pele pode ficar no sol.', 'Preciso ser reaplicado a cada duas horas.', 'Preciso ser passado 30 minutos antes de sair.',
      'Tenho versões em creme, gel, spray e bastão.', 'Minha versão para o rosto é mais leve e às vezes tem cor.', 'Sou o principal remédio contra o câncer de pele.', 'A dermatologista manda me usar até em dia nublado.',
      'Faço as pessoas ficarem esbranquiçadas na praia.', 'Sou o item que mais esquece na mochila.', 'Meu cheiro lembra férias e praia.', 'Deixo a areia grudada no corpo.',
      'Minhas marcas famosas incluem Sundown e Nivea.', 'Sou obrigatório no verão brasileiro.', 'Sou o creme contra o sol.', 'Meu nome tem "solar".',
    ] },
    { answer: 'Fogos de artifício', clues: [
      'Nasci na China há mais de mil anos.', 'Meus primeiros modelos eram bambus jogados no fogo, que estouravam.', 'A pólvora me transformou no que sou.', 'Cheguei à Europa com os viajantes da Rota da Seda.',
      'Cada cor minha vem de um metal diferente.', 'O estrôncio me faz vermelho, o cobre azul e o sódio amarelo.', 'Sou produzido em Santo Antônio de Jesus, na Bahia, e em Santo Antônio do Monte, em Minas.', 'Um acidente com meu preparo matou dezenas de mulheres na Bahia em 1998.',
      'Cachorros me odeiam.', 'Ganhei versões silenciosas por causa dos animais.', 'Várias cidades brasileiras proibiram meu barulho.', 'Sou obrigatório na virada do ano.',
      'A queima de Copacabana é a mais famosa do Brasil.', 'Torcedores me soltam quando o time ganha.', 'Sou perigoso: todo ano alguém perde um dedo.', 'Tenho versões de chão, de mão e de tubo.',
      'Minha versão pequena que só faz barulho é a bombinha.', 'Ilumino o céu em festa de São João.', 'Sou o espetáculo de luzes no céu.', 'Meu nome tem "fogos".',
    ] },
    { answer: 'Churrasqueira', clues: [
      'Sou item obrigatório em casa de brasileiro que se preze.', 'Existo de tijolo, de metal, portátil e elétrica.', 'Minha versão elétrica é a preferida de quem mora em apartamento.', 'Minha versão de bafo tem tampa.',
      'Uso carvão, lenha ou gás.', 'Meu carvão demora a acender e todo mundo tem uma técnica.', 'Álcool em cima de mim é a causa de muito acidente.', 'Meu acendedor de papelão vira assunto de debate.',
      'Meu espeto é uma vara de metal.', 'Minha grelha serve para linguiça e pão de alho.', 'Quem me opera vira o "churrasqueiro" e não sai do meu lado.', 'Ele fica com cerveja na mão o tempo todo.',
      'Minha fumaça entra no olho de todo mundo.', 'Perto de mim rola sal grosso e faca afiada.', 'Sou o centro do churrasco de domingo.', 'Sou o centro de área de lazer e varanda gourmet.',
      'Minha versão americana é chamada de "grill" ou "barbecue".', 'Minha versão gaúcha usa fogo de chão.', 'Sou onde se assa a picanha.', 'Meu nome vem de churrasco.',
    ] },
    { answer: 'Energético', clues: [
      'Nasci na Tailândia, como uma bebida para caminhoneiros.', 'Um austríaco provou essa bebida e a adaptou para a Europa em 1987.', 'Essa marca austríaca patrocina carros de Fórmula 1.', 'Ela também patrocina saltos de paraquedas do espaço.',
      'Essa marca é a Red Bull.', 'Meu ingrediente principal é cafeína.', 'Também levo taurina e muito açúcar.', 'Sou vendido em latinhas finas e altas.',
      'Sou proibido para menores em vários países.', 'Sou misturado com vodca nas baladas.', 'Sou a bebida oficial dos gamers.', 'Sou a bebida de quem vira a noite estudando.',
      'Minhas marcas incluem Monster, TNT e Fusion.', 'Meu slogan mais famoso diz que "dá asas".', 'Acelero o coração e dou tremor se exagerar.', 'Sou vendido gelado em todo posto de gasolina.',
      'Tenho versões sem açúcar e com sabor de fruta.', 'Sou uma bebida estimulante.', 'Meu nome vem de "energia".', 'Sou a bebida que promete deixar acordado.',
    ] },
    { answer: 'Selfie', clues: [
      'A primeira foto minha foi tirada em 1839, por Robert Cornelius.', 'Meu nome apareceu num fórum australiano em 2002.', 'Fui eleita a palavra do ano pelo dicionário Oxford em 2013.', 'A câmera frontal do celular me tornou possível.',
      'Minha foto mais famosa foi tirada no Oscar de 2014 por Ellen DeGeneres.', 'Aquela foto quebrou o Twitter e tinha Brad Pitt e Meryl Streep.', 'Ganhei um bastão extensível para ficar mais longe.', 'Esse bastão foi proibido em museus e shows.',
      'Meu ângulo preferido é de cima, levemente inclinado.', 'Meu bico de pato virou moda e depois virou piada.', 'Algumas pessoas morreram tentando me tirar em penhascos e trilhos.', 'Existem espelhos e anéis de luz só para mim.',
      'Os filtros suavizam a pele e aumentam os olhos.', 'Meus dedos em V viraram gesto padrão.', 'Sou a foto que aparece no perfil da rede social.', 'Sou tirada com o braço esticado.',
      'Meu nome em português seria "autorretrato".', 'Meu nome vem de "self", eu mesmo em inglês.', 'Sou a foto que a pessoa tira de si mesma.', 'Meu nome tem seis letras e termina com "ie".',
    ] },
    { answer: 'Meme', clues: [
      'Meu nome foi inventado por Richard Dawkins em 1976.', 'No livro dele, eu era uma ideia que se replica como um gene.', 'Meu nome vem do grego "mimema", imitação.', 'Na internet virei uma piada que se espalha.',
      'Meus primeiros exemplos famosos eram o "dancing baby" e o "Nyan Cat".', 'Minha versão de foto com texto branco em cima e embaixo dominou os anos 2000.', 'Essa fonte é a Impact.', 'Minha versão brasileira mais famosa mostra uma mulher fazendo contas.',
      'Essa mulher é a Nazaré Tedesco, da novela "Senhora do Destino".', 'A Gretchen e o Chaves são outras fontes inesgotáveis de mim.', 'Tenho um formato de vídeo curto com áudio repetido.', 'Vivo no Twitter, no WhatsApp e no TikTok.',
      'Sou usado para comentar futebol, política e novela.', 'Existe uma página chamada "Museu de Memes" na UFF.', 'Meu ciclo de vida é de dias, ou até horas.', 'Quando a empresa me usa em propaganda, já estou velho.',
      'Sou a moeda de troca dos grupos de amigos.', 'Sou uma piada que viraliza.', 'Meu nome tem quatro letras.', 'Sou a imagem engraçada da internet.',
    ] },
    { answer: 'Emoji', clues: [
      'Nasci no Japão em 1999, num celular da operadora NTT Docomo.', 'Meu criador foi Shigetaka Kurita, que desenhou 176 de mim em 12x12 pixels.', 'Meu nome vem de "e" (imagem) e "moji" (caractere) em japonês.', 'Não tenho nada a ver com "emotion", apesar do som parecido.',
      'Antes de mim existiam os emoticons, feitos de sinais :-).', 'Fui padronizado pelo consórcio Unicode em 2010.', 'A Apple me colocou no iPhone em 2011 e virei mundial.', 'Cada empresa me desenha de um jeito um pouco diferente.',
      'Uma versão minha rindo e chorando foi a palavra do ano da Oxford em 2015.', 'Ganhei tons de pele em 2015.', 'Ganhei um filme ruim em 2017.', 'Sou julgado todo ano em um comitê que aprova novos membros.',
      'Existe um mundial de mim: o Emojipedia.', 'Meu dia mundial é 17 de julho, a data do calendário do meu ícone.', 'O mais usado do mundo é o que chora de rir.', 'A berinjela e o pêssego ganharam outros significados.',
      'Os idosos usam a mão rezando e a rosa vermelha.', 'Sou as carinhas amarelas do teclado.', 'Meu nome tem cinco letras e começa com E.', 'Sou a figurinha que substitui palavra no celular.',
    ] },
    { answer: 'QR Code', clues: [
      'Nasci em 1994, numa fábrica de autopeças japonesa.', 'Fui criado pela Denso, do grupo Toyota, para rastrear peças de carro.', 'Meu criador liberou minha patente para uso livre.', 'Meu nome quer dizer "resposta rápida".',
      'Sou um código de barras em duas dimensões.', 'Tenho três quadrados grandes nos cantos para a câmera se orientar.', 'Guardo muito mais informação que um código de barras.', 'Continuo funcionando mesmo com 30% de mim danificado.',
      'Fiquei anos esquecido no Ocidente até a pandemia.', 'Substituí o cardápio de papel dos restaurantes.', 'Sou o caminho mais fácil de fazer um Pix.', 'Apareço na tela do banco para ser lido pelo celular.',
      'Sou o ingresso de show e o bilhete de avião.', 'Sou usado para conectar no Wi-Fi sem digitar senha.', 'Apareço em outdoors, embalagens e camisetas.', 'A TV brasileira me mostra no canto da tela.',
      'Basta apontar a câmera do celular para mim.', 'Sou um quadrado preto e branco cheio de quadradinhos.', 'Meu nome tem duas letras e "Code".', 'Sou o código que se lê com a câmera.',
    ] },
    { answer: 'Podcast', clues: [
      'Meu nome foi inventado por um jornalista britânico em 2004.', 'Meu nome junta iPod com broadcast.', 'A Apple me colocou no iTunes em 2005.', 'No começo eu era um programa de rádio baixado no MP3.',
      'Fiquei anos como nicho de nerds.', 'A série "Serial", de 2014, me tornou fenômeno nos Estados Unidos.', 'O Spotify me comprou com exclusivos milionários, como o Joe Rogan.', 'No Brasil, o Nerdcast foi meu pioneiro.',
      'No Brasil explodi na pandemia, com o Flow.', 'Meus programas de entrevista viraram vídeo no YouTube.', 'Tenho versões de true crime, humor, política e economia.', 'Quase todo famoso hoje tem um.',
      'Sou ouvido no trânsito, na academia e lavando louça.', 'Meu formato de mesa com microfones grandes virou padrão.', 'Os apresentadores leem propaganda no meio do programa.', 'Meus cortes de vídeo viralizam no TikTok.',
      'Meu nome virou verbo: "podcastar".', 'Sou um programa de áudio sob demanda.', 'Meu nome termina com "cast".', 'Sou o programa de conversa que se ouve no celular.',
    ] },
    { answer: 'Roblox', clues: [
      'Nasci em 2006, criado por David Baszucki e Erik Cassel.', 'Meu criador antes fazia simuladores de física para escolas.', 'Não sou um jogo só: sou uma plataforma cheia de jogos.', 'Meus jogos são criados pelos próprios usuários.',
      'Tenho mais de 80 milhões de usuários por dia.', 'A maioria dos meus jogadores tem menos de 16 anos.', 'Minha moeda se chama Robux.', 'Pais gastam fortunas em Robux sem perceber.',
      'Meus personagens são bonecos quadradões.', 'Meus jogos famosos incluem "Adopt Me!" e "Brookhaven".', 'Um dos meus jogos mais populares em 2025 é sobre cultivar plantas.', 'Esse jogo é "Grow a Garden".',
      'Já fui acusado de não proteger crianças de predadores.', 'Fui bloqueado em alguns países.', 'Muitos jovens ganham dinheiro criando jogos dentro de mim.', 'Meu logo é um quadrado inclinado.',
      'Sou mais popular que o Minecraft entre as crianças brasileiras.', 'Sou um jogo de criar jogos.', 'Meu nome mistura "robô" e "blocos".', 'Meu nome tem seis letras e começa com R.',
    ] },
  ],
};

module.exports = { CARDS13 };
