// Lote 9 do Perfil — Série ou Filme (cinema). Cada carta: resposta + 20 dicas.
const CARDS9 = {
  S: [
    { answer: 'Titanic', clues: [
      'Meu diretor mergulhou 12 vezes até os destroços reais para me filmar.', 'Meu orçamento estourou e fui o filme mais caro já feito na época.', 'Meu estúdio achou que eu ia quebrar a empresa.', 'Construíram uma réplica quase inteira do navio no México.',
      'Meu diretor é James Cameron.', 'Ganhei 11 Oscars, empatando o recorde.', 'Meu diretor gritou no palco do Oscar que era "o rei do mundo".', 'A velhinha do começo do filme era uma personagem inventada.',
      'Minha protagonista joga uma joia no mar no final.', 'Essa joia se chama "Coração do Oceano".', 'Meu casal se conhece porque ele impede que ela pule do navio.', 'Tem uma cena de desenho polêmica com um colar.',
      'Minha música-tema é cantada por Céline Dion.', 'Essa música é "My Heart Will Go On".', 'Meus protagonistas são Leonardo DiCaprio e Kate Winslet.', 'Meus personagens se chamam Jack e Rose.',
      'A discussão eterna sobre mim é se cabiam os dois na porta.', 'Fui lançado em 1997.', 'Conto uma história de amor num navio que afunda.', 'Meu nome é o mesmo do navio que bateu no iceberg.',
    ] },
    { answer: 'O Rei Leão', clues: [
      'Fui inspirado em "Hamlet", de Shakespeare.', 'Meu projeto era considerado o "filme B" do estúdio na época.', 'O outro projeto, considerado mais importante, era "Pocahontas".', 'Fui o primeiro filme do meu estúdio com história original, sem livro nem conto de fadas.',
      'Minha trilha foi feita por Hans Zimmer e Elton John.', 'Ganhei dois Oscars, os dois de música.', 'Minha abertura começa com um canto em zulu ao nascer do sol.', 'Minha cena de abertura mostra animais indo até uma pedra grande.',
      'Meu vilão é irmão do rei e tem uma cicatriz no olho.', 'Meu vilão canta uma música cercado de hienas.', 'Meu protagonista foge e é criado por um javali e um suricato.', 'Esses dois amigos ensinam uma filosofia de "sem preocupação".',
      'Essa filosofia se chama "Hakuna Matata".', 'Meu protagonista vê o pai nas nuvens.', 'Meu personagem principal é um filhote de leão.', 'Ele se chama Simba e o pai dele é Mufasa.',
      'Ganhei um remake em computação gráfica em 2019.', 'Virei um musical na Broadway que roda até hoje.', 'Sou uma animação da Disney de 1994.', 'Meu nome fala de um animal que é rei da selva.',
    ] },
    { answer: 'Vingadores: Ultimato', clues: [
      'Fui o encerramento de 22 filmes ligados entre si.', 'Meu estúdio guardou meu roteiro em segredo absoluto.', 'Alguns atores receberam roteiros falsos para não vazar nada.', 'Custei mais de 350 milhões de dólares.',
      'Cheguei a ser o filme de maior bilheteria da história.', 'Meu antecessor terminou com metade do universo virando pó.', 'Minha história começa cinco anos depois desse desastre.', 'Meus heróis usam viagem no tempo para desfazer o que aconteceu.',
      'Um dos meus heróis engorda e passa o filme deprimido jogando videogame.', 'Esse herói é o Thor.', 'A Viúva Negra se sacrifica num planeta chamado Vormir.', 'Uma cena mostra todas as heroínas juntas em campo.',
      'Meu vilão usa uma manopla cheia de joias coloridas.', 'Esse vilão é Thanos.', 'Meu herói principal estala os dedos no final e morre.', 'A frase "Eu sou o Homem de Ferro" fecha essa cena.',
      'O Capitão América ergue o martelo do Thor em mim.', 'Sou da Marvel e estreei em 2019.', 'Meu nome tem dois pontos e a palavra "Ultimato".', 'Sou o filme em que os Vingadores derrotam o Thanos de vez.',
    ] },
    { answer: 'Harry Potter e a Pedra Filosofal', clues: [
      'Meu livro foi recusado por 12 editoras antes de ser publicado.', 'Minha autora escreveu boa parte da história em cafés de Edimburgo.', 'Ela assinou com iniciais porque acharam que meninos não leriam uma autora mulher.', 'Fui lançado no cinema em 2001.',
      'Meu diretor foi Chris Columbus.', 'Meus três protagonistas eram crianças quando começaram a filmar.', 'Nos Estados Unidos meu nome mudou para "Pedra do Feiticeiro".', 'Meu protagonista mora embaixo de uma escada na casa dos tios.',
      'Ele recebe cartas que entram pela casa inteira.', 'Ele compra a varinha numa loja chamada Olivaras.', 'Ele pega um trem numa plataforma que não existe oficialmente.', 'Essa plataforma é a 9¾, na estação King\'s Cross.',
      'Um chapéu decide em qual casa cada aluno vai ficar.', 'Meu protagonista joga um esporte voando de vassoura.', 'Esse esporte é o quadribol.', 'Meu protagonista tem uma cicatriz de raio na testa.',
      'Meus três amigos são Harry, Rony e Hermione.', 'Minha escola de magia se chama Hogwarts.', 'Sou o primeiro filme de uma série de oito.', 'Meu nome tem o nome de um bruxinho de óculos.',
    ] },
    { answer: 'Jurassic Park', clues: [
      'Fui baseado num livro de Michael Crichton, de 1990.', 'Meu diretor comprou os direitos antes mesmo do livro ser publicado.', 'Meu diretor é Steven Spielberg.', 'Misturei bonecos animatrônicos com computação gráfica pioneira.',
      'Ganhei três Oscars técnicos, de efeitos e som.', 'Meu som de dinossauro foi feito com gravações de bichos comuns, como tartarugas e gansos.', 'Minha ilha fica na costa da Costa Rica.', 'Meu cientista extrai DNA de mosquitos presos em âmbar.',
      'Minha frase famosa diz que "a vida encontra um jeito".', 'Meus personagens andam num jipe automático que quebra na hora errada.', 'Uma cena mostra copos d\'água tremendo antes de um bicho gigante chegar.', 'Meu vilão humano rouba embriões num pote de creme de barbear.',
      'Meus predadores inteligentes caçam em bando na cozinha.', 'Esses predadores são os velociraptores.', 'Meu dinossauro maior tem braços pequenos e um rugido famoso.', 'Esse dinossauro é o Tiranossauro Rex.',
      'Meu parque tem um portão enorme de madeira com tochas.', 'Sou de 1993 e virei uma franquia com vários filmes.', 'Sou o filme que mostrou dinossauros de verdade na tela pela primeira vez.', 'Meu nome tem "Jurássico" e "Parque".',
    ] },
    { answer: 'De Volta para o Futuro', clues: [
      'Meu roteiro foi recusado mais de 40 vezes pelos estúdios.', 'Achavam que eu era engraçado demais para a Disney e família demais para os outros.', 'Meu protagonista original foi trocado depois de cinco semanas de filmagem.', 'Michael J. Fox filmava uma série de dia e a mim de madrugada.',
      'Estreei em 1985.', 'Meu carro do tempo era originalmente uma geladeira no roteiro antigo.', 'Meu carro precisa chegar a 88 milhas por hora para viajar.', 'Meu carro é um DeLorean com portas que abrem para cima.',
      'Meu cientista maluco se chama Doc Brown.', 'Meu protagonista viaja para 1955 e quase impede o namoro dos pais.', 'A mãe dele se apaixona por ele por engano.', 'Ele precisa fazer os pais se beijarem num baile do colégio.',
      'Esse baile se chama "Encanto Sob o Mar".', 'Meu protagonista toca "Johnny B. Goode" no palco.', 'Meu final tem um raio caindo numa torre de relógio.', 'Minha continuação vai até 2015 e erra quase todas as previsões.',
      'Nessa continuação existem skates que voam.', 'Meu protagonista se chama Marty McFly.', 'Sou um filme sobre viagem no tempo dos anos 80.', 'Meu nome tem "Futuro" e a ideia de voltar.',
    ] },
    { answer: 'Toy Story', clues: [
      'Fui o primeiro longa-metragem inteiramente feito em computador.', 'Meu estúdio quase faliu antes de me lançar.', 'Steve Jobs era o dono desse estúdio.', 'Esse estúdio é a Pixar.',
      'Meu roteiro foi refeito porque meu protagonista ficou antipático demais na primeira versão.', 'Estreei em 1995.', 'Meu diretor é John Lasseter.', 'Minha história se passa do ponto de vista dos brinquedos.',
      'Os brinquedos congelam quando um humano entra no quarto.', 'Meu vizinho malvado destrói brinquedos e se chama Sid.', 'Um dos meus personagens acha que é um herói de verdade e não um brinquedo.', 'Esse personagem grita "ao infinito e além".',
      'Meu outro protagonista é um caubói de corda nas costas.', 'A corda dele faz ele dizer "tem uma cobra na minha bota".', 'Meus dois personagens principais são Woody e Buzz Lightyear.', 'Meu dono se chama Andy e escreve o nome na sola dos brinquedos.',
      'Ganhei três continuações, a última em 2019.', 'Minha música-tema fala de ser um amigo fiel.', 'Sou a primeira animação da Pixar.', 'Meu nome, em inglês, quer dizer "história de brinquedo".',
    ] },
    { answer: 'Matrix', clues: [
      'Fui dirigido por dois irmãos que hoje são duas irmãs.', 'Minhas diretoras são as Wachowski.', 'Meus atores treinaram kung fu por quatro meses antes de filmar.', 'Inventei uma técnica de câmera que congela a ação e gira em volta.',
      'Essa técnica ficou conhecida como "bullet time".', 'Ganhei quatro Oscars técnicos em 2000.', 'Estreei em 1999.', 'Minha estética é toda verde e preta.',
      'Meu protagonista é um programador que vive uma vida dupla como hacker.', 'Ele recebe a mensagem "siga o coelho branco".', 'Meu mentor oferece duas pílulas ao protagonista.', 'A vermelha mostra a verdade e a azul deixa tudo como estava.',
      'Meus vilões usam terno preto e óculos escuros.', 'Meu vilão principal se chama Agente Smith.', 'Meu protagonista aprende kung fu num download.', 'A frase "eu sei kung fu" é minha.',
      'Meu herói desvia de balas se curvando para trás.', 'Meus personagens são Neo, Trinity e Morpheus.', 'Conto que o mundo real é uma simulação de computador.', 'Meu nome tem seis letras e virou sinônimo de "realidade falsa".',
    ] },
    { answer: 'O Senhor dos Anéis', clues: [
      'Fui baseado nos livros de J.R.R. Tolkien.', 'Meus três filmes foram gravados de uma vez só, em 274 dias.', 'Fui filmado inteiro na Nova Zelândia.', 'Meu diretor é Peter Jackson.',
      'Meu terceiro filme ganhou 11 Oscars, levando todas as categorias em que concorreu.', 'Meu vilão principal quase não aparece: é só um olho em chamas.', 'Esse vilão se chama Sauron.', 'Meu personagem digital foi feito com captura de movimento pioneira.',
      'Esse personagem chama o anel de "meu precioso".', 'Esse personagem é Gollum.', 'Meu grupo de nove heróis se chama Sociedade do Anel.', 'Meu mago cai numa ponte lutando contra um monstro de fogo.',
      'Esse mago é Gandalf e volta depois, todo de branco.', 'Meus protagonistas baixinhos moram no Condado.', 'Esses seres são os hobbits.', 'Meu herói precisa jogar um anel num vulcão.',
      'Esse vulcão é a Montanha da Perdição, em Mordor.', 'Meu protagonista se chama Frodo Bolseiro.', 'Sou uma trilogia de fantasia dos anos 2000.', 'Meu nome fala de um "senhor" e de uma joia redonda.',
    ] },
    { answer: 'Star Wars', clues: [
      'Meu criador quis fazer Flash Gordon e não conseguiu os direitos.', 'Meu criador é George Lucas.', 'Meu estúdio achou que eu ia fracassar.', 'Meu criador abriu mão de parte do salário para ficar com os direitos de brinquedos e ganhou fortunas.',
      'Meu primeiro filme estreou em 1977.', 'Minhas primeiras palavras na tela são "há muito tempo, numa galáxia muito distante".', 'Meu texto de abertura sobe inclinado na tela.', 'Minha trilha foi composta por John Williams.',
      'Meus cavaleiros usam uma espada de luz.', 'Minha força mística tem um lado sombrio.', 'Meu contrabandista tem uma nave velha e um copiloto peludo.', 'Esse copiloto é Chewbacca e a nave é a Millennium Falcon.',
      'Meus robôs são um dourado falante e um baixinho azul e branco.', 'Esses robôs são C-3PO e R2-D2.', 'Meu vilão respira alto e usa capacete preto.', 'Esse vilão é Darth Vader.',
      'Meu dia oficial é 4 de maio, por causa de um trocadilho.', 'Minha frase de despedida é "que a Força esteja com você".', 'Sou uma saga de ficção científica com Jedi e Sith.', 'Meu nome, em inglês, quer dizer "guerra nas estrelas".',
    ] },
    { answer: 'Frozen', clues: [
      'Fui inspirado num conto de Hans Christian Andersen.', 'O estúdio tentou me adaptar por quase 70 anos sem conseguir.', 'Minha vilã original virou heroína durante a produção.', 'Isso aconteceu depois que compuseram uma música para ela.',
      'Essa música mudou todo o meu roteiro.', 'Ganhei o Oscar de melhor animação e de melhor canção em 2014.', 'Estreei em 2013.', 'Minhas protagonistas são duas irmãs princesas.',
      'A mais velha tem poderes de gelo e vive escondida.', 'Ela usa luvas para esconder os poderes.', 'Ela congela o reino sem querer e foge para a montanha.', 'Ela constrói um castelo de gelo cantando.',
      'Meu boneco de neve sonha com o verão.', 'Esse boneco se chama Olaf.', 'Minha rena se chama Sven.', 'Minha música mais famosa fala em "deixar ir" e "livre estou".',
      'Minhas irmãs são Elsa e Anna.', 'Ganhei uma continuação em 2019.', 'Sou uma animação da Disney sobre uma rainha do gelo.', 'Meu nome, em inglês, quer dizer "congelado".',
    ] },
    { answer: 'Shrek', clues: [
      'Fui baseado num livro infantil de William Steig.', 'Minha produção foi cheia de piadas escondidas contra a Disney.', 'Meu reino leva o nome de um executivo rival do meu produtor.', 'Ganhei o primeiro Oscar de melhor animação da história, em 2002.',
      'Estreei em 2001, pela DreamWorks.', 'Meu protagonista original seria dublado por Chris Farley, que morreu antes.', 'Meu protagonista foi então dublado por Mike Myers, com sotaque escocês.', 'Meu protagonista vive num pântano e quer ficar sozinho.',
      'Meu herói diz que ogros são como cebolas, porque têm camadas.', 'Meu vilão é baixinho e se chama Lord Farquaad.', 'Minha princesa vira ogra à noite.', 'Essa princesa é Fiona e sabe lutar kung fu.',
      'Meu personagem falante e chato é um animal de carga.', 'Esse personagem é o Burro, dublado por Eddie Murphy.', 'Minha abertura usa a música "All Star", do Smash Mouth.', 'Minha dublagem brasileira ficou famosa pelas gírias.',
      'Meu Gato de Botas ganhou filmes próprios.', 'Ganhei quatro filmes e virei meme na internet.', 'Sou uma animação sobre um ogro verde.', 'Meu nome tem cinco letras e começa com S.',
    ] },
    { answer: 'Homem-Aranha', clues: [
      'Fui criado por Stan Lee e Steve Ditko em 1962.', 'A editora achou no começo que ninguém ia gostar de um herói adolescente.', 'Meu primeiro filme de sucesso é de 2002, dirigido por Sam Raimi.', 'Já tive três atores diferentes no papel principal em 20 anos.',
      'Esses atores são Tobey Maguire, Andrew Garfield e Tom Holland.', 'Meu filme animado de 2018 ganhou o Oscar de animação.', 'Esse filme animado se chama "No Aranhaverso".', 'Meu protagonista é fotógrafo de um jornal.',
      'Esse jornal é o Clarim Diário.', 'Meu chefe vive gritando e quer fotos minhas.', 'Meu protagonista ganha os poderes de uma aranha radioativa.', 'Meu tio morre e me ensina uma lição pelo resto da vida.',
      'Essa lição diz que "com grandes poderes vêm grandes responsabilidades".', 'Meu beijo mais famoso é de cabeça para baixo, na chuva.', 'Meu vilão do primeiro filme voa numa prancha e usa máscara verde.', 'Esse vilão é o Duende Verde.',
      'Meu protagonista se chama Peter Parker.', 'Minha namorada mais famosa é Mary Jane.', 'Sou um herói da Marvel que solta teias.', 'Meu nome tem um bicho de oito patas.',
    ] },
    { answer: 'Batman: O Cavaleiro das Trevas', clues: [
      'Meu diretor é Christopher Nolan.', 'Sou o segundo filme de uma trilogia começada em 2005.', 'Estreei em 2008.', 'Fui filmado em parte com câmeras IMAX, coisa rara na época.',
      'Meu ator principal criou uma voz rouca que virou piada e marca registrada.', 'Meu vilão principal foi interpretado por um ator que morreu antes da estreia.', 'Esse ator ganhou o Oscar postumamente.', 'Esse ator é Heath Ledger.',
      'Meu vilão improvisou o momento em que bate palmas na cela.', 'Meu vilão pergunta: "por que tão sério?".', 'Meu vilão queima uma montanha de dinheiro.', 'Meu promotor público vira vilão depois de queimar metade do rosto.',
      'Esse promotor é Harvey Dent, o Duas-Caras.', 'Meu herói assume a culpa pelos crimes dele no final.', 'Meu vilão coloca uma bomba em dois navios e faz as pessoas escolherem.', 'Meu herói é chamado de "o cavaleiro das trevas" na última fala.',
      'Meu protagonista é Bruce Wayne.', 'Minha cidade é Gotham.', 'Sou um filme sobre o homem-morcego e o Coringa.', 'Meu nome tem o nome do herói e "Cavaleiro das Trevas".',
    ] },
    { answer: 'Pantera Negra', clues: [
      'Meu personagem apareceu nos quadrinhos em 1966, antes do movimento político de mesmo nome.', 'Meu diretor é Ryan Coogler.', 'Estreei em 2018.', 'Fui o primeiro filme de super-herói indicado ao Oscar de melhor filme.',
      'Ganhei três Oscars, entre eles figurino e direção de arte.', 'Ruth Carter foi a primeira mulher negra a ganhar o Oscar de figurino, por mim.', 'Meu país fictício se esconde do mundo e finge ser pobre.', 'Esse país tem o metal mais valioso do universo Marvel.',
      'Esse metal é o vibranium.', 'Minha guarda real é formada só por mulheres.', 'Essa guarda se chama Dora Milaje.', 'Minha irmã genial é a inventora de toda a tecnologia do reino.',
      'Essa irmã se chama Shuri.', 'Meu vilão é um americano que quer usar as armas do reino pelo mundo.', 'Esse vilão é Killmonger.', 'Meu cumprimento é cruzar os braços no peito.',
      'Esse gesto acompanha o grito "Wakanda para sempre".', 'Meu ator principal, Chadwick Boseman, morreu em 2020.', 'Sou um filme da Marvel sobre um rei africano.', 'Meu nome é o de um felino preto.',
    ] },
    { answer: 'Barbie', clues: [
      'Minha diretora é Greta Gerwig.', 'Fui o filme de maior bilheteria de 2023.', 'Fui lançado no mesmo dia de um filme sobre a bomba atômica.', 'Essa coincidência virou o fenômeno "Barbenheimer".',
      'Minha produção comprou tanta tinta rosa que faltou no mercado mundial.', 'Ganhei o Oscar de melhor canção original em 2024.', 'Essa canção é "What Was I Made For?", de Billie Eilish.', 'Minha protagonista começa a ter pensamentos sobre a morte no meio de uma festa.',
      'Os pés da minha protagonista descem do salto e ficam retos.', 'Minha protagonista precisa ir ao mundo real para se curar.', 'Meu protagonista masculino descobre o patriarcado e adora.', 'Esse personagem tem como profissão "praia".',
      'Meu personagem masculino canta uma música sobre ser suficiente.', 'Essa música é "I\'m Just Ken".', 'Meus protagonistas são interpretados por Margot Robbie e Ryan Gosling.', 'Meus personagens são Barbie e Ken.',
      'Meu mundo é todo cor-de-rosa.', 'Minha empresa fabricante é a Mattel e aparece no filme.', 'Sou um filme de 2023 baseado numa boneca.', 'Meu nome é o nome da boneca loira mais famosa do mundo.',
    ] },
    { answer: 'Divertida Mente', clues: [
      'Meu diretor teve a ideia observando a filha dele mudar de humor na adolescência.', 'Meu diretor é Pete Docter, da Pixar.', 'Consultei psicólogos de verdade para montar minha história.', 'Ganhei o Oscar de melhor animação em 2016.',
      'Estreei em 2015.', 'Minha história se passa quase toda dentro da cabeça de uma menina.', 'Minha protagonista humana se muda de Minnesota para São Francisco.', 'Essa menina se chama Riley.',
      'Minhas personagens são sentimentos que controlam um painel.', 'Minhas bolinhas coloridas são memórias.', 'Meu amigo imaginário é rosa, parte elefante e parte algodão-doce.', 'Esse amigo se chama Bing Bong e se sacrifica.',
      'Minha personagem principal é amarela e otimista.', 'Minha personagem azul ensina que é preciso poder ficar triste.', 'Meus sentimentos principais são Alegria, Tristeza, Raiva, Medo e Nojinho.', 'Minha continuação de 2024 trouxe a Ansiedade.',
      'Essa continuação foi a animação de maior bilheteria da história.', 'Sou uma animação da Pixar sobre emoções.', 'Meu nome brasileiro é um trocadilho com "divertida" e "mente".', 'Meu nome original, em inglês, é "Inside Out".',
    ] },
    { answer: 'Coringa', clues: [
      'Meu diretor é Todd Phillips, conhecido antes por comédias.', 'Fui inspirado em filmes de Scorsese dos anos 70.', 'Ganhei o Leão de Ouro no Festival de Veneza em 2019.', 'Fui o primeiro filme de super-herói com classificação adulta a passar de 1 bilhão.',
      'Meu ator principal perdeu mais de 20 quilos para o papel.', 'Esse ator ganhou o Oscar de melhor ator em 2020.', 'Esse ator é Joaquin Phoenix.', 'Minha trilha foi feita por uma compositora islandesa e também ganhou Oscar.',
      'Meu protagonista tem uma condição que o faz rir sem querer.', 'Meu protagonista trabalha como palhaço de rua e é espancado.', 'Ele cuida da mãe doente num apartamento pequeno.', 'Ele sonha em ser comediante de stand-up.',
      'Ele mata três executivos no metrô e vira símbolo de um protesto.', 'Os manifestantes usam máscaras de palhaço.', 'Ele dança numa escadaria que virou ponto turístico no Bronx.', 'Ele atira num apresentador de TV ao vivo.',
      'Meu protagonista se chama Arthur Fleck.', 'Minha cidade é Gotham.', 'Sou um filme de 2019 sobre o maior vilão do Batman.', 'Meu nome é o do palhaço de cabelo verde.',
    ] },
    { answer: 'Parasita', clues: [
      'Sou um filme sul-coreano de 2019.', 'Meu diretor é Bong Joon-ho.', 'Ganhei a Palma de Ouro em Cannes.', 'Fui o primeiro filme falado em outra língua a ganhar o Oscar de melhor filme.',
      'Ganhei quatro Oscars numa noite só, em 2020.', 'Meu diretor brincou no palco que a legenda é uma "barreira de 2 centímetros".', 'Minha família pobre mora num porão semienterrado.', 'Esse tipo de moradia se chama banjiha na Coreia.',
      'Minha família ganha dinheiro dobrando caixas de pizza.', 'Meu filho começa dando aula de inglês para a filha de uma família rica.', 'Um por um, todos da família pobre se empregam na casa rica mentindo.', 'Existe um porão secreto embaixo da casa dos ricos.',
      'Um homem vive escondido nesse porão há anos.', 'Meu personagem rico reclama do cheiro dos empregados.', 'Meu clímax acontece numa festa de aniversário no jardim.', 'Minha chuva torrencial separa o mundo dos ricos e dos pobres numa cena.',
      'Falo sobre desigualdade social de um jeito que vira suspense.', 'Meu nome é o de um ser que vive às custas de outro.', 'Sou o filme coreano que ganhou o Oscar de melhor filme.', 'Meu nome tem oito letras e começa com P.',
    ] },
    { answer: 'Cidade de Deus', clues: [
      'Fui baseado num livro de Paulo Lins, de 1997.', 'Meus atores foram, em sua maioria, moradores de comunidades sem experiência.', 'Fui dirigido por Fernando Meirelles e Kátia Lund.', 'Estreei em 2002.',
      'Fui indicado a quatro Oscars em 2004, entre eles direção.', 'Minha montagem rápida e minha fotografia amarelada viraram marca.', 'Meu narrador quer ser fotógrafo e escapar da violência.', 'Esse narrador se chama Buscapé.',
      'Minha abertura mostra uma galinha fugindo de uma perseguição.', 'Meu conjunto habitacional fica na Zona Oeste do Rio.', 'Conto três décadas de história de uma favela carioca.', 'Meu vilão cresce e vira o dono do morro.',
      'Esse personagem muda de nome de Dadinho para Zé Pequeno.', 'A frase "Dadinho é o cacete, meu nome agora é Zé Pequeno" é minha.', 'Meu outro personagem, Bené, é o "bacana" da favela.', 'Mané Galinha vira o rival de Zé Pequeno.',
      'Meu filme gerou uma série de TV chamada "Cidade dos Homens".', 'Ganhei uma continuação em série em 2024.', 'Sou o filme brasileiro mais famoso no exterior.', 'Meu nome é o de um bairro do Rio de Janeiro.',
    ] },
    { answer: 'Tropa de Elite', clues: [
      'Fui baseado no livro "Elite da Tropa", escrito por dois ex-policiais e um antropólogo.', 'Meu diretor é José Padilha.', 'Estreei em 2007.', 'Vazei em DVD pirata antes da estreia e milhões de pessoas me viram assim.',
      'Ganhei o Urso de Ouro no Festival de Berlim.', 'Minha história se passa em 1997, na véspera de uma visita do papa ao Rio.', 'Meu protagonista é um capitão que quer sair da corporação.', 'Ele procura um substituto e acompanha dois novatos.',
      'Esses novatos se chamam Neto e Matias.', 'Meu protagonista narra o filme inteiro com voz cansada e irônica.', 'Meu batalhão tem uma caveira com uma faca e duas pistolas no símbolo.', 'Meu batalhão é o BOPE.',
      'Minha música-tema tem letra em português e batida de rap militar.', 'Essa música é "Tropa de Elite", do Tihuana.', 'Meu personagem manda "pedir para sair" durante os treinamentos.', 'Meu protagonista se chama Capitão Nascimento, vivido por Wagner Moura.',
      'Minha continuação, de 2010, foi a maior bilheteria da história do cinema brasileiro.', 'Minha frase mais repetida é "põe na conta do papa".', 'Sou um filme brasileiro sobre policiais do BOPE.', 'Meu nome tem "Tropa" e "Elite".',
    ] },
    { answer: 'Ainda Estou Aqui', clues: [
      'Fui baseado num livro de memórias de Marcelo Rubens Paiva.', 'Meu diretor é Walter Salles.', 'Ele já tinha dirigido "Central do Brasil" e "Diários de Motocicleta".', 'Estreei em 2024.',
      'Ganhei o prêmio de melhor roteiro no Festival de Veneza.', 'Minha história se passa no Rio de Janeiro a partir de 1970.', 'Conto a história de uma família de classe média durante a ditadura.', 'O pai da família é levado por agentes e nunca mais volta.',
      'Esse pai é o ex-deputado Rubens Paiva.', 'Minha protagonista é a mãe que cria cinco filhos e luta por respostas.', 'Ela só recebeu o atestado de óbito do marido 25 anos depois.', 'Minha protagonista é Eunice Paiva, que virou advogada aos 48 anos.',
      'Minha atriz principal ganhou o Globo de Ouro de melhor atriz em drama.', 'Essa atriz é Fernanda Torres.', 'A mãe dela faz a mesma personagem idosa numa cena.', 'Essa mãe é Fernanda Montenegro.',
      'Ganhei o Oscar de melhor filme internacional em 2025.', 'Sou o primeiro Oscar de filme da história do Brasil.', 'Sou um filme brasileiro sobre um desaparecido político.', 'Meu nome tem quatro palavras e começa com "Ainda".',
    ] },
    { answer: 'Central do Brasil', clues: [
      'Fui dirigido por Walter Salles.', 'Estreei em 1998.', 'Ganhei o Urso de Ouro no Festival de Berlim.', 'Fui indicado a dois Oscars: filme estrangeiro e atriz.',
      'Minha atriz principal foi a primeira brasileira indicada ao Oscar de melhor atriz.', 'Essa atriz é Fernanda Montenegro.', 'Minha protagonista escreve cartas para analfabetos numa estação de trem.', 'Ela cobra pelas cartas e joga fora boa parte delas.',
      'Um menino perde a mãe atropelada logo no começo.', 'Esse menino se chama Josué.', 'Minha protagonista quase vende o menino e depois se arrepende.', 'Os dois fogem juntos numa viagem de ônibus.',
      'A viagem vai do Rio até o sertão do Nordeste.', 'O menino procura o pai, que nunca conheceu.', 'Eles passam por uma romaria de fé no meio do caminho.', 'Minha protagonista se chama Dora.',
      'Meu nome é o de uma estação de trem no centro do Rio.', 'Sou considerado um marco da retomada do cinema brasileiro.', 'Sou um filme de estrada sobre uma velha ranzinza e um menino.', 'Meu nome tem "Central" e o nome do país.',
    ] },
    { answer: 'Meu Malvado Favorito', clues: [
      'Sou uma animação da Illumination, de 2010.', 'Meu estúdio é conhecido por fazer filmes baratos que faturam muito.', 'Meu protagonista é um vilão que quer roubar a Lua.', 'Ele mora numa casa preta com um laboratório subterrâneo.',
      'Meu protagonista tem um cachorro chamado Kyle.', 'Meu cientista velho se chama Doutor Nefário.', 'Meu protagonista adota três meninas de um orfanato só para usá-las num plano.', 'As meninas se chamam Margo, Edith e Agnes.',
      'A menor delas ganha um unicórnio de pelúcia e grita que ele é fofo.', 'Meu protagonista acaba virando pai de verdade.', 'Meu protagonista tem sotaque do leste europeu e é dublado por Steve Carell.', 'Esse protagonista se chama Gru.',
      'Meus ajudantes são pequenos, amarelos e falam uma língua inventada.', 'Eles usam óculos de proteção e macacão azul.', 'Esses ajudantes viraram tema de filmes próprios.', 'Esses ajudantes são os Minions.',
      'Minha franquia passou de 5 bilhões de dólares em bilheteria.', 'Virei o rei dos memes de tio no WhatsApp.', 'Sou uma animação sobre um vilão que adota três meninas.', 'Meu nome tem "Malvado" e "Favorito".',
    ] },
    { answer: 'Velozes e Furiosos', clues: [
      'Comecei como um filme pequeno sobre roubo de aparelhos de DVD em caminhões.', 'Meu primeiro filme é de 2001.', 'Fui inspirado numa reportagem sobre rachas em Nova York.', 'Comecei como filme de corrida e virei filme de espionagem com carros.',
      'Meus carros já foram lançados de avião e de arranha-céu.', 'Um dos meus filmes literalmente vai ao espaço.', 'Um dos meus atores morreu num acidente de carro durante a produção.', 'Esse ator é Paul Walker.',
      'A despedida dele virou uma cena de dois carros se separando na estrada.', 'A música dessa despedida é "See You Again".', 'Meu protagonista dirige um Dodge Charger preto do pai.', 'Meu protagonista fala o tempo todo sobre uma coisa só.',
      'Essa coisa é a família.', 'Meu protagonista é interpretado por Vin Diesel.', 'Esse protagonista se chama Dominic Toretto.', 'Meu policial infiltrado vira melhor amigo dele.',
      'Meus filmes têm churrasco no quintal no final.', 'Já passei de dez filmes na franquia.', 'Sou uma série de filmes sobre carros e roubos.', 'Meu nome tem dois adjetivos ligados por "e".',
    ] },
  ],
};

module.exports = { CARDS9 };
