// Cartas do Perfil (lote 4): atualidades, filmes, séries, música, internet.
const CARDS4 = {
  P: [
    { answer: 'Virginia Fonseca', clues: [
      'Nasci nos Estados Unidos, em 1999, mas cresci em Goiás.', 'Comecei fazendo vídeos no YouTube ainda adolescente.', 'Namorei um youtuber famoso antes do meu casamento.', 'Casei com um cantor sertanejo, filho de um dos maiores nomes do sertanejo.',
      'Meu ex-marido se chama Zé Felipe.', 'Meu ex-sogro é o Leonardo.', 'Tenho três filhos: Maria Alice, Maria Flor e José Leonardo.', 'Tenho uma marca de maquiagem que fatura milhões.',
      'Tenho mais de 50 milhões de seguidores no Instagram.', 'Fiz lives de venda que quebraram recordes.', 'Apresentei um programa de TV no SBT.', 'Fui rainha de bateria da Grande Rio.',
      'Moro em Goiânia numa mansão gigante.', 'Meu nome tem o nome de um estado americano.', 'Sou uma das maiores influenciadoras do Brasil.', 'Sou influenciadora e empresária.',
      'Minha separação em 2025 parou a internet.', 'Meu nome começa com V e tem 8 letras.', 'Meu sobrenome começa com F.', 'Sou a influenciadora mais seguida do Brasil.',
    ] },
    { answer: 'Vini Jr.', clues: [
      'Nasci em São Gonçalo, no Rio de Janeiro, em 2000.', 'Fui revelado pelo Flamengo.', 'Fui vendido por 45 milhões de euros antes de completar 18 anos.', 'Fui campeão da Champions League em 2022 e 2024.',
      'Fiz o gol do título da Champions de 2022 contra o Liverpool.', 'Sofro ataques racistas nos estádios da Espanha.', 'Minha luta contra o racismo virou causa mundial.', 'Fui eleito o melhor jogador do mundo pela FIFA em 2024.',
      'Fiquei em segundo na Bola de Ouro de 2024 e não fui à cerimônia.', 'Uso a camisa 7 do Real Madrid.', 'Minha dança na comemoração irrita os rivais.', 'Sou ponta-esquerda.',
      'Tenho um instituto que ajuda crianças em São Gonçalo.', 'Sou torcedor do Flamengo.', 'Meu nome completo tem "Paixão" no meio.', 'Sou o principal jogador da Seleção hoje.',
      'Meu apelido tem 4 letras.', 'Meu apelido tem um "Jr." no fim.', 'Meu nome começa com V.', 'Sou o brasileiro do Real Madrid.',
    ] },
    { answer: 'Rebeca Andrade', clues: [
      'Nasci em Guarulhos, em 1999.', 'Tenho sete irmãos e minha mãe era empregada doméstica.', 'Andava 2 horas de ônibus para treinar.', 'Rompi o ligamento do joelho três vezes.',
      'Quase desisti do esporte por causa das lesões.', 'Meu técnico se chama Francisco Porath.', 'Ganhei minha primeira medalha olímpica em Tóquio, em 2021.', 'Fui a primeira brasileira a ganhar uma medalha na ginástica olímpica.',
      'Ganhei ouro no salto em Tóquio.', 'Fui campeã mundial do individual geral em 2022.', 'Ganhei quatro medalhas nas Olimpíadas de Paris.', 'Venci Simone Biles no solo em Paris.',
      'Simone Biles se curvou para mim no pódio.', 'Minha coreografia de solo usa "Baile de Favela".', 'Sou a maior medalhista olímpica do Brasil.', 'Sou ginasta.',
      'Meu primeiro nome começa com R e tem 6 letras.', 'Meu sobrenome é comum e começa com A.', 'Sou a rainha da ginástica brasileira.', 'Sou a ginasta do "Baile de Favela".',
    ] },
    { answer: 'Bruno Mars', clues: [
      'Nasci no Havaí, em 1985.', 'Meu nome verdadeiro é Peter Gene Hernandez.', 'Imitava Elvis Presley aos 4 anos.', 'Meu apelido veio de um lutador de luta livre, o Bruno Sammartino.',
      'Meu sobrenome artístico veio de uma brincadeira de que eu era "de outro planeta".', 'Comecei como compositor para outros artistas.', 'Fiquei famoso com "Just the Way You Are".', 'Cantei "Uptown Funk" com Mark Ronson.',
      'Cantei "24K Magic" e "That\'s What I Like".', 'Toquei no Super Bowl duas vezes.', 'Fiz um dueto com Anderson .Paak, o Silk Sonic.', 'Cantei "Die With a Smile" com Lady Gaga.',
      'Sou apaixonado pelo Brasil e fiz shows no Rio, em São Paulo e em Brasília.', 'Os brasileiros me chamam de "Bruninho".', 'Danço de terno e chapéu.', 'Sou baixinho e cheio de gingado.',
      'Dizem que sou "brasileiro honorário".', 'Meu sobrenome artístico é um planeta.', 'Meu primeiro nome artístico é comum no Brasil.', 'Sou o cantor do "Uptown Funk".',
    ] },
    { answer: 'Lady Gaga', clues: [
      'Nasci em Nova York, em 1986.', 'Meu nome verdadeiro é Stefani Germanotta.', 'Meu nome artístico veio da música "Radio Ga Ga", do Queen.', 'Toco piano desde os 4 anos.',
      'Fiquei famosa com "Just Dance" e "Poker Face".', 'Usei um vestido de carne crua num prêmio.', 'Cantei "Bad Romance" e "Telephone".', 'Meus fãs são os "little monsters".',
      'Ganhei um Oscar pela música "Shallow".', 'Atuei em "Nasce uma Estrela" com Bradley Cooper.', 'Fui a Harley Quinn no segundo filme do Coringa.', 'Cantei jazz com Tony Bennett.',
      'Fiz um show grátis em Copacabana em 2025, para mais de 2 milhões de pessoas.', 'Cantei "Die With a Smile" com Bruno Mars.', 'Sou chamada de "Mother Monster".', 'Sou a cantora do "Poker Face".',
      'Meu nome artístico começa com "Lady".', 'Meu nome artístico tem 8 letras.', 'Meu sobrenome artístico repete uma sílaba.', 'Sou a cantora dos figurinos malucos.',
    ] },
    { answer: 'Pedro Pascal', clues: [
      'Nasci em Santiago, no Chile, em 1975.', 'Minha família fugiu da ditadura de Pinochet quando eu era bebê.', 'Cresci nos Estados Unidos.', 'Fiz papéis pequenos por 20 anos antes de ficar famoso.',
      'Fui Oberyn Martell em "Game of Thrones" e morri com a cabeça esmagada.', 'Fui o agente Javier Peña em "Narcos".', 'Uso um capacete que nunca tiro numa série de "Star Wars".', 'Sou o Mandaloriano.',
      'Cuido de um bebê verde chamado Grogu.', 'Fui Joel em "The Last of Us".', 'Fui o Reed Richards no "Quarteto Fantástico".', 'Fiz "Gladiador II" e "Guerra Civil".',
      'Sou chamado de "papai da internet".', 'Sou o ator mais querido de Hollywood hoje.', 'Sou chileno e americano.', 'Meu sobrenome é o de um filósofo francês.',
      'Meu primeiro nome é muito comum no Brasil.', 'Meu nome tem 11 letras.', 'Meu nome começa com P.', 'Sou o ator do Mandaloriano e de "The Last of Us".',
    ] },
    { answer: 'Fernanda Torres', clues: [
      'Nasci no Rio de Janeiro, em 1965.', 'Sou filha de dois atores famosos.', 'Minha mãe fez "Central do Brasil".', 'Meu pai era um ator de teatro famoso.',
      'Ganhei o prêmio de melhor atriz em Cannes aos 20 anos, por "Eu Sei Que Vou Te Amar".', 'Fiz Vani em "Os Normais", com Luiz Fernando Guimarães.', 'Fiz Fátima em "Tapas & Beijos".', 'Escrevi os romances "Fim" e "A Glória e Seu Cortejo de Horrores".',
      'Escrevo crônicas para jornal.', 'Fiz Eunice Paiva num filme sobre a ditadura.', 'Ganhei o Globo de Ouro de melhor atriz em 2025.', 'Fui indicada ao Oscar de melhor atriz em 2025.',
      'Meu filme "Ainda Estou Aqui" ganhou o Oscar de filme internacional.', 'Fui a primeira brasileira a ganhar um Globo de Ouro de atuação.', 'Minha mãe é Fernanda Montenegro.', 'Sou atriz e escritora.',
      'Meu sobrenome é o mesmo de uma cidade de Portugal.', 'Meu primeiro nome é o feminino de Fernando.', 'Minha mãe e eu temos o mesmo primeiro nome.', 'Sou a atriz de "Ainda Estou Aqui".',
    ] },
    { answer: 'Elon Musk', clues: [
      'Nasci na África do Sul, em 1971.', 'Vendi meu primeiro jogo de computador aos 12 anos.', 'Me mudei para o Canadá e depois para os Estados Unidos.', 'Fundei uma empresa que virou o PayPal.',
      'Fundei uma empresa de foguetes em 2002.', 'Meus foguetes pousam de volta em pé.', 'Minha empresa de carros elétricos tem o nome de um inventor sérvio.', 'Sou dono da Tesla e da SpaceX.',
      'Quero colonizar Marte.', 'Tenho mais de dez filhos, um deles chamado X Æ A-12.', 'Comprei o Twitter e mudei o nome para X.', 'Faço piadas com criptomoedas na internet.',
      'Trabalhei no governo Trump cortando gastos.', 'Tenho uma empresa de chips no cérebro, a Neuralink.', 'Já fui a pessoa mais rica do mundo.', 'Meus satélites de internet se chamam Starlink.',
      'Meu primeiro nome tem 4 letras.', 'Meu sobrenome significa "almíscar", um cheiro forte de animal.', 'Meu nome começa com E.', 'Sou o dono da Tesla.',
    ] },
    { answer: 'Wandinha', clues: [
      'Nasci em 1938, num desenho de jornal de Charles Addams.', 'Meu nome em inglês vem de "Wednesday", quarta-feira.', 'Sou de uma família estranha e mórbida.', 'Meus pais se chamam Gomez e Mortícia.',
      'Meu irmão se chama Feioso.', 'Tenho um tio careca chamado Chico.', 'Tenho uma mão sem corpo que me ajuda, a Mãozinha.', 'Christina Ricci me interpretou nos anos 90.',
      'Ganhei uma série na Netflix em 2022.', 'Estudo numa escola chamada Nunca Mais.', 'Minha dança na série virou febre no TikTok.', 'Tim Burton dirigiu minha série.',
      'Jenna Ortega me interpreta.', 'Uso tranças pretas e nunca sorrio.', 'Tenho uma amiga colorida chamada Enid.', 'Meu vestido é preto com gola branca.',
      'Sou a filha da Família Addams.', 'Meu nome em português é o de um dia da semana com "inha".', 'Meu nome começa com W.', 'Sou a garota gótica da Netflix.',
    ] },
    { answer: 'Ana Castela', clues: [
      'Nasci em Amambai, no Mato Grosso do Sul, em 2003.', 'Cresci em Londrina, no Paraná.', 'Comecei postando vídeos cantando na internet.', 'Meu primeiro sucesso foi "Pipoco", em 2022.',
      'Sou chamada de "Boiadeira".', 'Meu estilo é o "agronejo".', 'Canto com chapéu e botas.', 'Cantei "Nosso Quadro" e "Solteiro Forçado".',
      'Namorei o cantor Gustavo Mioto.', 'Fui a artista mais ouvida do Brasil no Spotify em 2023.', 'Cantei "Boiadeira Internacional".', 'Sou a nova rainha do sertanejo.',
      'Fiz parceria com Luan Santana e com Gusttavo Lima.', 'Tenho um chapéu como marca registrada.', 'Sou uma cantora sertaneja jovem.', 'Meu sobrenome artístico é o de uma região da Espanha.',
      'Meu primeiro nome tem 3 letras.', 'Meu nome começa com A.', 'Meu apelido tem a ver com boi.', 'Sou a cantora do "Pipoco".',
    ] },
    { answer: 'Gusttavo Lima', clues: [
      'Nasci em Sete Lagoas, Minas Gerais, em 1989.', 'Meu nome verdadeiro é Nivaldo Batista Lima.', 'Comecei tocando em bandas de baile.', 'Fiquei famoso com "Inventor dos Amores", com Jorge & Mateus.',
      'Minha música "Balada" virou hit mundial em 2012, com o "tchê tcherere tchê tchê".', 'Sou chamado de "Embaixador".', 'Sou casado com a modelo Andressa Suita.', 'Tenho dois filhos: Gabriel e Samuel.',
      'Fiz lives gigantes na pandemia, com cerveja na mão.', 'Cantei "Bloqueado" e "Termina Comigo Antes".', 'Tenho jatinhos e uma coleção de carros.', 'Fiz uma festa de aniversário com show do Roberto Carlos.',
      'Meu nome artístico tem dois "t".', 'Sou um cantor sertanejo.', 'Sou dono de uma gravadora chamada Balada Music.', 'Já falaram que eu seria candidato a presidente.',
      'Meu apelido é "Embaixador" e canto "Balada".', 'Meu primeiro nome artístico começa com G.', 'Meu sobrenome é o mesmo da capital do Peru.', 'Sou o cantor do "tchê tcherere".',
    ] },
    { answer: 'Mbappé', clues: [
      'Nasci em Bondy, perto de Paris, em 1998.', 'Meu pai é camaronês e minha mãe, argelina.', 'Fui revelado pelo Monaco.', 'Fui campeão francês com o Monaco aos 18 anos.',
      'Fui para o PSG em 2017 por 180 milhões de euros.', 'Fui campeão do mundo em 2018 aos 19 anos.', 'Fui o primeiro adolescente a marcar numa final de Copa desde Pelé.', 'Fiz três gols na final da Copa de 2022 e perdi.',
      'Sou o maior artilheiro da história do PSG.', 'Fui para o Real Madrid em 2024 de graça.', 'Comemoro de braços cruzados.', 'Sou um dos jogadores mais rápidos do mundo.',
      'Tenho uma fundação para crianças.', 'Sou o capitão da seleção francesa.', 'Sou chamado de "Tartaruga Ninja" pelos amigos.', 'Uso a camisa 10 da França.',
      'Meu primeiro nome é Kylian.', 'Meu sobrenome começa com M e tem 6 letras.', 'Sou francês.', 'Sou o atacante francês do Real Madrid.',
    ] },
  ],
  L: [
    { answer: 'Catar', clues: [
      'Sou uma península no Golfo Pérsico.', 'Sou menor que o estado de Sergipe.', 'Fui protetorado britânico até 1971.', 'Fiquei rico com gás natural.',
      'Sou um dos países mais ricos do mundo por pessoa.', 'Minha capital é Doha.', 'Tenho a rede de TV Al Jazeera.', 'Minha companhia aérea é uma das melhores do mundo.',
      'Menos de 15% dos meus moradores são nativos.', 'Fui acusado de maltratar os operários que construíram meus estádios.', 'Sediei uma Copa do Mundo em novembro e dezembro.', 'Fui o primeiro país árabe a sediar uma Copa.',
      'Proibi cerveja nos estádios da Copa.', 'A Argentina foi campeã em mim, em 2022.', 'Meu emir vestiu Messi com um manto preto na final.', 'Sou um país árabe.',
      'Meu nome tem 5 letras e começa com C.', 'Meu nome termina com "tar".', 'Sou o país da Copa de 2022.', 'Sou o país da Copa de Messi.',
    ] },
    { answer: 'Jericoacoara', clues: [
      'Era uma vila de pescadores sem luz elétrica até 1998.', 'Meu nome vem do tupi: "tartaruga" ou "buraco de jacaré".', 'Minhas ruas são de areia.', 'Fico a 300 km de Fortaleza.',
      'Chega-se a mim de buggy ou jipe 4x4.', 'Fui eleita uma das dez praias mais bonitas do mundo pelo Washington Post.', 'Tenho uma duna onde todo mundo vê o pôr do sol.', 'A Duna do Pôr do Sol é meu ritual diário.',
      'Tenho uma pedra com um buraco, a Pedra Furada.', 'Tenho lagoas de água doce, como a Lagoa do Paraíso.', 'Tenho redes dentro da água.', 'Sou o paraíso do kitesurf.',
      'Sou um parque nacional.', 'Fico no Ceará.', 'Meu apelido é "Jeri".', 'Sou uma praia de areia e vento.',
      'Meu nome é comprido e difícil de escrever.', 'Meu nome tem 12 letras.', 'Meu nome começa com J.', 'Sou a praia mais famosa do Ceará.',
    ] },
    { answer: 'Coreia do Sul', clues: [
      'Fui dividida em dois em 1945.', 'Vivi uma guerra terrível de 1950 a 1953.', 'Era mais pobre que o Brasil nos anos 60.', 'Virei um "tigre asiático".',
      'A Samsung e a Hyundai nasceram em mim.', 'Sediei a Copa de 2002, com o Japão.', 'Meu vizinho de cima tem bomba atômica e um ditador.', 'Minha capital é Seul.',
      'Meu prato mais famoso é o kimchi, repolho fermentado.', 'Meu filme "Parasita" ganhou o Oscar.', 'Minha série "Round 6" foi a mais vista da Netflix.', 'Meus grupos de música têm dezenas de fãs no Brasil.',
      'O BTS e o Blackpink são meus.', 'Minha música é chamada de K-pop.', 'Minhas novelas são os doramas.', 'Meus cosméticos são o "K-beauty".',
      'Sou a metade capitalista de uma península.', 'Meu nome tem "do Sul".', 'Meu nome começa com C.', 'Sou o país do K-pop.',
    ] },
    { answer: 'Metaverso', clues: [
      'Meu nome foi criado num romance de ficção de 1992, "Snow Crash".', 'Sou um mundo virtual onde as pessoas vivem com avatares.', 'Second Life foi minha primeira versão popular, em 2003.', 'Mark Zuckerberg apostou tudo em mim.',
      'O Facebook mudou o nome da empresa por minha causa.', 'A Meta gastou bilhões de dólares em mim.', 'Meus avatares no começo não tinham pernas.', 'Sou acessado com óculos de realidade virtual.',
      'Roblox e Fortnite são meus parentes.', 'Já vendi terrenos virtuais por milhões.', 'Shows de artistas aconteceram dentro de mim.', 'Fui a palavra da moda em 2021 e 2022.',
      'Depois de mim, a moda virou a inteligência artificial.', 'Muita gente diz que fracassei.', 'Sou um mundo digital.', 'Meu nome começa com "Meta".',
      'Meu nome termina com "verso".', 'Meu nome tem 9 letras.', 'Sou o universo virtual.', 'Sou o lugar que só existe no computador.',
    ] },
    { answer: 'Coachella', clues: [
      'Nasci em 1999, num deserto da Califórnia.', 'Aconteço em dois fins de semana de abril.', 'Meu palco fica num campo de polo em Indio.', 'Sou o festival dos influenciadores e das roupas boho.',
      'Beyoncé fez um show histórico em mim em 2018.', 'O show da Beyoncé virou o documentário "Homecoming".', 'Um holograma do Tupac apareceu em mim.', 'Anitta foi a primeira brasileira solo a cantar em mim.',
      'Ludmilla e Pabllo Vittar também cantaram em mim.', 'Lady Gaga foi minha atração em 2025.', 'Minha roda-gigante aparece em todas as fotos.', 'Meus ingressos custam mais de 500 dólares.',
      'Sou transmitido no YouTube.', 'Sou o festival de música mais famoso do mundo.', 'Fico nos Estados Unidos.', 'Aconteço no deserto.',
      'Meu nome vem de um vale da Califórnia.', 'Meu nome tem 9 letras e começa com C.', 'Meu nome termina com "ella".', 'Sou o festival da Califórnia.',
    ] },
    { answer: 'Ucrânia', clues: [
      'Fui o celeiro da União Soviética.', 'Meu nome significa "terra da fronteira".', 'Fiquei independente em 1991.', 'Chernobyl fica em mim.',
      'Minha capital tem cúpulas douradas e se chama Kiev.', 'Andriy Shevchenko é meu maior jogador.', 'Tive uma revolução laranja em 2004.', 'Perdi a Crimeia em 2014.',
      'Meu presidente era um comediante de TV.', 'Meu presidente se chama Zelensky.', 'Fui invadida pela Rússia em fevereiro de 2022.', 'Minha bandeira é azul e amarela, como o céu e o trigo.',
      'Recebo armas dos Estados Unidos e da Europa.', 'Milhões de meus habitantes fugiram para a Polônia.', 'Sou o maior país inteiramente na Europa.', 'Faço fronteira com a Rússia.',
      'Vivo uma guerra desde 2022.', 'Meu nome tem 7 letras e começa com U.', 'Meu nome termina com "ânia".', 'Sou o país invadido pela Rússia.',
    ] },
    { answer: 'Allianz Parque', clues: [
      'Fui inaugurado em 2014, no lugar de um estádio de 1917.', 'Fui construído onde ficava o Palestra Itália.', 'Tenho o nome de uma seguradora alemã.', 'Fico na Zona Oeste de São Paulo, perto da Barra Funda.',
      'Sou verde por dentro.', 'Sou a casa do Palmeiras.', 'Recebo shows de Paul McCartney, Coldplay e Taylor Swift.', 'Tenho uma pista de shows e um teto de vidro.',
      'Fui construído pela WTorre.', 'Recebi jogos de Libertadores e finais de Paulistão.', 'Meu apelido entre os torcedores é "Arena".', 'Meu gramado sintético causou polêmica.',
      'Fico ao lado da Sociedade Esportiva Palmeiras.', 'Sou o estádio mais moderno de São Paulo.', 'Recebo mais de 40 mil pessoas.', 'Sou o estádio do Verdão.',
      'Meu nome tem o nome de uma empresa de seguros.', 'Meu nome começa com A.', 'Meu nome termina com "Parque".', 'Sou a arena do Palmeiras.',
    ] },
    { answer: 'Bali', clues: [
      'Sou uma ilha de um país muçulmano, mas sou hindu.', 'Tenho mais de 20 mil templos.', 'Fico na Indonésia.', 'Tenho vulcões ativos e terraços de arroz.',
      'Minha cidade das artes se chama Ubud.', 'Julia Roberts se encontrou em mim em "Comer, Rezar, Amar".', 'Sou o destino dos nômades digitais.', 'Sou o paraíso do surfe e da ioga.',
      'Tenho um templo dentro do mar, o Tanah Lot.', 'Tenho uma floresta cheia de macacos.', 'Meus balanços sobre o precipício viram fotos de Instagram.', 'Fui atingida por um atentado terrorista em 2002.',
      'Meus habitantes fazem oferendas de flores todo dia.', 'Sou a ilha dos deuses.', 'Fico no sudeste da Ásia.', 'Sou uma ilha tropical.',
      'Meu nome tem 4 letras.', 'Meu nome começa com B.', 'Meu nome termina com "li".', 'Sou a ilha dos influenciadores.',
    ] },
    { answer: 'Estádio do Morumbi', clues: [
      'Fui inaugurado em 1960, ainda incompleto.', 'Meu nome oficial homenageia Cícero Pompeu de Toledo.', 'Fui o maior estádio particular do mundo.', 'Fico na Zona Sul de São Paulo.',
      'Sou a casa do São Paulo Futebol Clube.', 'Fui palco de finais de Libertadores e Mundiais.', 'Não recebi jogos da Copa de 2014.', 'Recebi shows de Michael Jackson, Madonna e Coldplay.',
      'Fui a abertura da Copa América de 2019.', 'Recebi shows do Bruno Mars em 2024.', 'Vendi meu nome para uma empresa em 2024 e virei MorumBIS.', 'Meu apelido tem a ver com chocolate desde 2024.',
      'Sou de concreto e tenho quase 70 anos.', 'Tenho o nome de um bairro nobre de São Paulo.', 'Sou o estádio do Tricolor paulista.', 'Cabe 66 mil pessoas em mim.',
      'Meu nome começa com "Estádio".', 'Meu nome termina com "umbi".', 'Sou o estádio do São Paulo.', 'Meu apelido novo termina com "BIS".',
    ] },
    { answer: 'Arena do Grêmio', clues: [
      'Fui inaugurada em dezembro de 2012.', 'Substituí o Estádio Olímpico Monumental.', 'Fico no bairro Humaitá, em Porto Alegre.', 'Fui construída pela OAS.',
      'Sou azul, preta e branca.', 'Tenho a Geral, uma arquibancada em pé.', 'Em mim joga o Tricolor gaúcho.', 'Sou a casa do Grêmio.',
      'Fui alagada pela enchente de 2024.', 'A enchente me deixou meses sem jogos.', 'Recebi shows de Paul McCartney e Guns N\' Roses.', 'Sou uma das arenas mais modernas do Brasil.',
      'Tenho um estacionamento gigante e uma zona comercial.', 'Fico na capital do Rio Grande do Sul.', 'Sou uma arena de futebol.', 'Cabe 55 mil pessoas em mim.',
      'Meu nome tem "Arena".', 'Meu nome termina com o nome de um clube gaúcho.', 'Meu nome começa com A.', 'Sou a arena do Imortal.',
    ] },
    { answer: 'Nova Zelândia', clues: [
      'Fui o último grande território habitado pelos humanos.', 'Meu povo nativo são os maoris.', 'Fui o primeiro país a dar voto às mulheres, em 1893.', 'Tenho mais ovelhas que gente.',
      'Minha ave símbolo não voa e se chama kiwi.', 'Meus habitantes são chamados de "kiwis".', 'Meu time de rúgbi é o All Blacks.', 'Meu time faz uma dança de guerra antes dos jogos, o haka.',
      'Os filmes de "O Senhor dos Anéis" foram filmados em mim.', 'A Terra Média fica em mim.', 'Tenho vulcões, geleiras e fiordes.', 'Minha capital é Wellington, mas a maior cidade é Auckland.',
      'Sou vizinha da Austrália, mas não gosto de ser confundida.', 'Fui governada por Jacinda Ardern.', 'Sou o primeiro país a ver o Ano Novo.', 'Tenho duas ilhas principais.',
      'Fico na Oceania.', 'Meu nome tem "Nova".', 'Meu nome termina com "lândia".', 'Sou o país dos All Blacks.',
    ] },
    { answer: 'Rock in Rio', clues: [
      'Nasci em 1985, na Zona Oeste do Rio.', 'Fui criado pelo empresário Roberto Medina.', 'Minha primeira edição teve Queen, Iron Maiden e AC/DC.', 'Fiz edições em Lisboa, Madri e Las Vegas.',
      'Minha Cidade do Rock fica na Barra da Tijuca.', 'Tenho uma tirolesa e uma roda-gigante.', 'Meu jingle diz "eu vou estar lá".', 'Meu slogan é "por um mundo melhor".',
      'Tenho um Palco Mundo e um Palco Sunset.', 'Meus ingressos esgotam em minutos.', 'Recebi Beyoncé, Rihanna e Bruce Springsteen.', 'Recebi Katy Perry, Bruno Mars e Iron Maiden várias vezes.',
      'Aconteço a cada dois anos, em setembro.', 'Sou o maior festival de música do Brasil.', 'Meu nome tem o nome de uma cidade.', 'Meu irmão em São Paulo se chama The Town.',
      'Meu nome tem "Rock".', 'Meu nome tem três palavras.', 'Meu nome começa com R.', 'Sou o festival do Rio.',
    ] },
  ],
  C: [
    { answer: 'ChatGPT', clues: [
      'Nasci em 30 de novembro de 2022.', 'Cheguei a 100 milhões de usuários em dois meses, um recorde.', 'Fui criado pela OpenAI.', 'Sam Altman é o chefe da minha empresa.',
      'Fui treinado lendo boa parte da internet.', 'Respondo em texto, como uma conversa.', 'Escrevo redações, códigos e poemas.', 'Às vezes invento fatos com toda a confiança.',
      'Professores me odiaram no começo.', 'Tenho versões numeradas: 3.5, 4, 4o, 5.', 'Minha empresa tem o Microsoft como parceira.', 'Meus concorrentes são o Gemini, o Claude e o Copilot.',
      'Posso ver imagens e ouvir voz.', 'Sou uma inteligência artificial.', 'Meu nome tem "Chat".', 'Meu nome tem "GPT".',
      'Meu nome tem 7 letras.', 'Meu nome começa com C.', 'Sou o robô de conversa mais famoso do mundo.', 'Sou o chat da inteligência artificial.',
    ] },
    { answer: 'TikTok', clues: [
      'Nasci na China, em 2016, com o nome de Douyin.', 'Comprei o aplicativo Musical.ly em 2018.', 'Minha dona é a ByteDance.', 'Meu algoritmo é considerado o mais viciante do mundo.',
      'Fui o aplicativo mais baixado do mundo em 2020.', 'Os Estados Unidos ameaçam me banir.', 'Fui banido na Índia.', 'Minhas dancinhas viraram febre na pandemia.',
      'Charli D\'Amelio ficou famosa em mim.', 'Lancei músicas de sucesso, como "Old Town Road".', 'Meus vídeos são curtos e verticais.', 'Tenho uma aba "Para Você".',
      'Meu logo é uma nota musical.', 'Sou o aplicativo dos adolescentes.', 'Tenho uma loja dentro de mim.', 'Sou o concorrente do Reels e do Shorts.',
      'Meu nome imita o som de um relógio.', 'Meu nome tem 6 letras.', 'Meu nome começa com T.', 'Sou o aplicativo de vídeos curtos.',
    ] },
    { answer: 'Copo Stanley', clues: [
      'Minha marca nasceu em 1913, para operários e trabalhadores.', 'Meu criador inventou a garrafa térmica de aço.', 'Meu modelo famoso, o "Quencher", saiu em 2016 e quase foi descontinuado.', 'Um blog de mães me salvou.',
      'Viralizei no TikTok em 2023.', 'Um vídeo mostrou que sobrevivi a um incêndio de carro, ainda com gelo dentro.', 'Filas se formaram nas lojas para me comprar.', 'Sou vendido em dezenas de cores.',
      'Custo mais de 200 reais.', 'Tenho uma alça e um canudo.', 'Cabe 1,2 litro em mim.', 'Mantenho a bebida gelada por horas.',
      'Sou de aço inoxidável.', 'Sou levado para a academia e para o trabalho.', 'Virei símbolo de status.', 'Sou um copo térmico.',
      'Meu nome tem o nome da marca.', 'Meu nome começa com "Copo".', 'Minha marca começa com S.', 'Sou o copo térmico da moda.',
    ] },
    { answer: 'Ozempic', clues: [
      'Fui criado para tratar diabetes tipo 2.', 'Sou uma injeção semanal.', 'Minha substância se chama semaglutida.', 'Sou fabricado por uma empresa dinamarquesa, a Novo Nordisk.',
      'Imito um hormônio do intestino que dá saciedade.', 'Faço a pessoa sentir menos fome.', 'Celebridades me usaram para emagrecer.', 'Elon Musk disse que me usou.',
      'Sumi das farmácias por causa da procura.', 'Meu irmão para emagrecer se chama Wegovy.', 'Meu concorrente se chama Mounjaro.', 'Dizem que mudei o rosto das celebridades.',
      'Custo mais de mil reais por mês.', 'Causo enjoo e náusea.', 'Sou um remédio.', 'Sou a "caneta" de emagrecer.',
      'Meu nome tem 7 letras.', 'Meu nome começa com O.', 'Meu nome termina com "pic".', 'Sou a injeção de emagrecer mais famosa.',
    ] },
    { answer: 'Pix', clues: [
      'Nasci em novembro de 2020.', 'Fui criado pelo Banco Central do Brasil.', 'Funciono 24 horas, todos os dias.', 'Sou gratuito para pessoas físicas.',
      'Uso chaves: CPF, telefone, e-mail ou aleatória.', 'Acabei com a DOC e enfraqueci a TED.', 'Sou copiado por outros países.', 'Sou usado até por camelôs e feirantes.',
      'Tenho um QR code.', 'O dinheiro cai na hora.', 'Fui usado em golpes de "falso sequestro".', 'Tenho limite noturno para evitar golpes.',
      'Virei verbo: "me faz um".', 'Sou mais usado que o cartão de débito.', 'Tenho versão para pagar depois: o parcelado.', 'Sou um sistema de pagamento.',
      'Meu nome tem 3 letras.', 'Meu nome começa com P.', 'Meu nome termina com X.', 'Sou o pagamento instantâneo do Brasil.',
    ] },
    { answer: 'Air fryer', clues: [
      'Fui inventada na Holanda e lançada pela Philips em 2010.', 'Meu nome em inglês significa "fritadeira de ar".', 'Não uso óleo, ou uso muito pouco.', 'Sou um mini forno com ventilador potente.',
      'Cozinho com ar quente circulando rápido.', 'Fiquei famosa no Brasil na pandemia.', 'Sou o eletrodoméstico mais vendido das Black Fridays.', 'Faço batata frita "sem culpa".',
      'Faço pão de queijo e frango crocante.', 'Tenho um cesto com furinhos.', 'Existem grupos de receitas minhas com milhões de pessoas.', 'Fiz o forno tradicional ficar esquecido.',
      'Minha marca mais vendida no Brasil é a Mondial.', 'Existo em versão com duas gavetas.', 'Fico na bancada da cozinha.', 'Sou um eletrodoméstico.',
      'Meu nome é em inglês.', 'Meu nome tem "air".', 'Meu nome começa com A.', 'Sou a fritadeira sem óleo.',
    ] },
    { answer: 'Crocs', clues: [
      'Nasci em 2002, no Colorado, feito para velejar.', 'Meu nome vem de um réptil que vive na terra e na água.', 'Sou feito de uma espuma chamada Croslite.', 'Tenho furos em cima.',
      'Fui eleito o sapato mais feio do mundo várias vezes.', 'Médicos e enfermeiros me adoram.', 'Tenho enfeites chamados "jibbitz" para os furos.', 'Fiz parcerias com Balenciaga e Justin Bieber.',
      'Virei moda entre adolescentes na pandemia.', 'Sou usado com meias, para desespero de alguns.', 'Tenho uma tira atrás que pode ficar em "modo esportivo".', 'Sou vendido em cores berrantes.',
      'Sou leve e lavável.', 'Sou um calçado de borracha.', 'Sou o sapato que as pessoas amam ou odeiam.', 'Meu nome é o de um bicho.',
      'Meu nome tem 5 letras.', 'Meu nome começa com C.', 'Meu nome termina com S.', 'Sou o sapato de furinhos.',
    ] },
    { answer: 'Netflix', clues: [
      'Nasci em 1997, alugando DVDs pelo correio.', 'Ofereci me vender para a Blockbuster e fui rejeitada.', 'Comecei a transmitir vídeos pela internet em 2007.', 'Cheguei ao Brasil em 2011.',
      'Minha primeira série própria foi "House of Cards".', 'Meu som de abertura é "tudum".', 'Fiz "Stranger Things" e "La Casa de Papel".', 'Fiz "Round 6", minha série mais vista.',
      'Fiz "Wandinha" e "Bridgerton".', 'Proibi o compartilhamento de senha.', 'Tenho um plano com anúncios.', 'Tenho mais de 300 milhões de assinantes.',
      'Meu logo é um N vermelho.', 'Meu concorrente é o Disney+ e o Prime Video.', 'Faço a "maratona" de séries existir.', 'Sou um serviço de streaming.',
      'Meu nome junta "net" e "cinema".', 'Meu nome tem 7 letras.', 'Meu nome começa com N.', 'Sou o streaming vermelho.',
    ] },
    { answer: 'Labubu', clues: [
      'Nasci em 2015, num livro infantil de um artista de Hong Kong.', 'Meu criador se chama Kasing Lung.', 'Sou uma criatura peluda com orelhas de coelho e nove dentes.', 'Sou vendido pela empresa chinesa Pop Mart.',
      'Venho em caixas surpresa: você não sabe qual vai vir.', 'A Lisa, do Blackpink, me pendurou na bolsa e virei febre.', 'Rihanna e Dua Lipa me usaram como chaveiro.', 'Filas e brigas aconteceram nas lojas por minha causa.',
      'Sou vendido por milhares de reais em versões raras.', 'Sou falsificado como "Lafufu".', 'Virei febre no Brasil em 2025.', 'Sou pendurado em bolsas de grife.',
      'Pareço fofo e assustador ao mesmo tempo.', 'Sou um boneco de vinil.', 'Sou um chaveiro de pelúcia.', 'Sou um monstrinho sorridente.',
      'Meu nome tem 6 letras.', 'Meu nome começa com L.', 'Meu nome repete "bu".', 'Sou o monstrinho da moda.',
    ] },
    { answer: 'Bitcoin', clues: [
      'Nasci em 2009, criado por alguém que ninguém sabe quem é.', 'Meu criador usa o nome Satoshi Nakamoto.', 'Fui descrito num artigo de 9 páginas em 2008.', 'Minha primeira compra foi de duas pizzas por 10 mil unidades minhas.',
      'Uso uma tecnologia chamada blockchain.', 'Sou "minerado" por computadores que gastam muita energia.', 'Só vão existir 21 milhões de mim.', 'Não tenho banco central nem governo.',
      'Meu preço já passou de 100 mil dólares.', 'Já caí 80% várias vezes.', 'El Salvador me adotou como moeda oficial.', 'Sou o sonho dos "cripto bros".',
      'Meu símbolo é um B com dois traços.', 'Sou guardado em carteiras digitais.', 'Fui usado na "deep web".', 'Sou uma moeda digital.',
      'Sou a criptomoeda mais famosa.', 'Meu nome tem 7 letras.', 'Meu nome começa com B.', 'Meu nome termina com "coin".',
    ] },
    { answer: 'Barbie', clues: [
      'Nasci em 1959, criada por Ruth Handler.', 'Fui inspirada numa boneca alemã chamada Lilli.', 'Meu nome vem da filha da minha criadora, Barbara.', 'Meu namorado se chama Ken, nome do filho dela.',
      'Já tive mais de 200 profissões.', 'Fui astronauta antes de os homens irem à Lua.', 'Sou fabricada pela Mattel.', 'Meu corpo foi criticado por ser irreal.',
      'Minha casa dos sonhos é cor-de-rosa.', 'Tenho uma irmã chamada Skipper.', 'Um filme sobre mim em 2023 faturou 1,4 bilhão de dólares.', 'Margot Robbie me interpretou.',
      'Ryan Gosling foi o Ken no meu filme.', 'Meu filme estreou junto com "Oppenheimer" e virou "Barbenheimer".', 'Sou a boneca mais famosa do mundo.', 'Sou loira e magra.',
      'Minha cor é o rosa.', 'Meu nome tem 6 letras.', 'Meu nome começa com B.', 'Sou a boneca da Mattel.',
    ] },
    { answer: 'Stranger Things', clues: [
      'Nasci em 2016, criada pelos irmãos Duffer.', 'Me passo numa cidade fictícia chamada Hawkins.', 'Me passo nos anos 80.', 'Uma menina com poderes aparece na floresta.',
      'A menina se chama Eleven e adora waffles.', 'Um menino chamado Will some no primeiro episódio.', 'Existe um mundo paralelo, o Mundo Invertido.', 'Meus monstros são o Demogorgon e o Vecna.',
      'Meus meninos jogam Dungeons & Dragons.', 'Uma mãe se comunica com luzes de Natal na parede.', 'O xerife Hopper é o herói adulto.', 'Coloquei a música "Running Up That Hill" de volta nas paradas.',
      'Millie Bobby Brown ficou famosa comigo.', 'Sou uma série da Netflix.', 'Minha última temporada saiu em 2025.', 'Sou uma série de terror e nostalgia.',
      'Meu nome é em inglês.', 'Meu nome tem duas palavras.', 'Meu nome começa com S.', 'Sou a série do Mundo Invertido.',
    ] },
  ],
  A: [
    { answer: '2023', clues: [
      'Neste ano o rei Charles III foi coroado.', 'O submarino Titan implodiu perto do Titanic em mim.', 'Em mim o Twitter virou X.', 'Em mim a Argentina elegeu Javier Milei.',
      'A guerra entre Israel e o Hamas começou em outubro de mim.', 'O Threads, concorrente do Twitter, nasceu em mim.', 'Em mim o Brasil viu a invasão dos Três Poderes, em 8 de janeiro.', 'Lula tomou posse pela terceira vez em mim.',
      'A Copa do Mundo feminina foi na Austrália e Nova Zelândia.', 'A Espanha ganhou a Copa feminina em mim.', 'Taylor Swift fez shows no Brasil e uma fã morreu de calor.', 'Ana Castela foi a artista mais ouvida do Brasil em mim.',
      'Dois filmes muito diferentes estrearam no mesmo dia em julho de mim.', 'Um filme rosa e um filme sobre a bomba atômica dividiram o cinema.', 'Sou o ano do "Barbenheimer".', 'Sou o ano da coroação de Charles.',
      'Sou um ano ímpar da década de 2020.', 'Meus dígitos são 2, 0, 2 e 3.', 'Vim depois da Copa do Catar.', 'Termino com 23.',
    ] },
    { answer: '2024', clues: [
      'Neste ano Donald Trump foi eleito de novo.', 'Trump levou um tiro na orelha num comício em mim.', 'Joe Biden desistiu da reeleição em mim.', 'Um apagão mundial de computadores derrubou aeroportos em julho de mim.',
      'Madonna fez um show grátis em Copacabana em maio de mim.', 'O Rio Grande do Sul sofreu a maior enchente da história em mim.', 'Porto Alegre ficou debaixo d\'água.', 'Silvio Santos morreu em agosto de mim.',
      'O Botafogo ganhou a Libertadores e o Brasileirão em mim.', 'Vini Jr. foi eleito o melhor do mundo pela FIFA.', 'As Olimpíadas foram em Paris.', 'A abertura das Olimpíadas foi no rio Sena, de barco.',
      'Rebeca Andrade ganhou quatro medalhas em Paris.', 'Simone Biles se curvou para Rebeca no pódio.', 'Sou o ano das Olimpíadas de Paris.', 'Sou o ano da enchente do Rio Grande do Sul.',
      'Sou um ano bissexto.', 'Meus dígitos são 2, 0, 2 e 4.', 'Sou um ano par da década de 2020.', 'Termino com 24.',
    ] },
    { answer: '2019', clues: [
      'Neste ano a catedral de Notre-Dame pegou fogo.', 'A primeira foto de um buraco negro foi divulgada em mim.', 'Greta Thunberg discursou na ONU: "how dare you?".', '"Vingadores: Ultimato" virou a maior bilheteria da história em mim.',
      'O filme "Coringa" de Joaquin Phoenix é de mim.', '"Game of Thrones" acabou em mim, com fãs revoltados.', 'O Disney+ foi lançado em mim.', 'Em mim Jair Bolsonaro tomou posse.',
      'A barragem de Brumadinho rompeu em janeiro de mim.', 'A Amazônia queimou e o "dia virou noite" em São Paulo.', 'O Flamengo ganhou a Libertadores e o Brasileirão em mim, com Jorge Jesus.', 'Gabigol fez dois gols no fim da final da Libertadores.',
      'A Copa América foi no Brasil e o Brasil ganhou.', 'Um vírus apareceu na China em dezembro de mim.', 'Fui o último ano antes da pandemia.', 'Sou o ano do fim de "Game of Thrones".',
      'Sou o último ano da década de 2010.', 'Meus dígitos são 2, 0, 1 e 9.', 'Sou um ano ímpar.', 'Termino com 19.',
    ] },
    { answer: '2018', clues: [
      'Neste ano o príncipe Harry casou com Meghan Markle.', 'Doze meninos ficaram presos numa caverna na Tailândia e foram salvos.', 'Stephen Hawking morreu em mim.', 'O filme "Pantera Negra" estreou em mim.',
      'O Fortnite virou febre em mim.', 'O Museu Nacional, no Rio, pegou fogo em mim.', 'Marielle Franco foi assassinada em março de mim.', 'Jair Bolsonaro foi eleito presidente em mim.',
      'Bolsonaro levou uma facada em Juiz de Fora durante a campanha.', 'Lula foi preso em abril de mim.', 'A Copa do Mundo foi na Rússia.', 'Neymar rolou no gramado e virou meme.',
      'O Brasil perdeu para a Bélgica nas quartas.', 'A França venceu a Croácia na final.', 'Mbappé brilhou aos 19 anos.', 'Sou o ano da Copa da Rússia.',
      'Sou um ano par da década de 2010.', 'Meus dígitos são 2, 0, 1 e 8.', 'Sou o ano da eleição de Bolsonaro.', 'Termino com 18.',
    ] },
    { answer: '2017', clues: [
      'Neste ano Donald Trump tomou posse pela primeira vez.', 'O movimento #MeToo explodiu em mim, com o caso Harvey Weinstein.', 'O filme "La La Land" recebeu o Oscar por engano, que era de "Moonlight".', 'O eclipse solar total atravessou os Estados Unidos.',
      'O primeiro filme da "Mulher-Maravilha" estreou em mim.', 'O "fidget spinner" virou febre em mim.', 'A música "Despacito" dominou o mundo em mim.', 'Em mim Michel Temer era presidente do Brasil.',
      'A reforma trabalhista foi aprovada em mim.', 'A Chapecoense jogou de novo depois da tragédia.', 'O Grêmio ganhou a Libertadores em mim.', 'O Corinthians foi campeão brasileiro em mim.',
      'Em mim o Brasil viveu a greve geral de abril.', 'A JBS gravou Temer e o Brasil parou em maio.', 'Sou o ano do "Despacito".', 'Sou o ano do primeiro mandato de Trump.',
      'Sou um ano ímpar da década de 2010.', 'Meus dígitos são 2, 0, 1 e 7.', 'Sou o ano do fidget spinner.', 'Termino com 17.',
    ] },
    { answer: '2013', clues: [
      'Neste ano o papa Bento XVI renunciou.', 'Um argentino virou papa e escolheu o nome Francisco.', 'Nelson Mandela morreu em dezembro de mim.', 'Edward Snowden revelou a espionagem americana em mim.',
      'O filme "Frozen" estreou em mim.', 'A música "Harlem Shake" virou febre em mim.', 'Em mim o papa Francisco visitou o Brasil, na Jornada da Juventude.', 'A boate Kiss pegou fogo em Santa Maria em janeiro de mim.',
      'O Brasil parou com protestos em junho de mim.', 'Os protestos começaram por 20 centavos na passagem.', 'A Copa das Confederações foi no Brasil em mim.', 'O Brasil venceu a Espanha por 3 a 0 na final.',
      'O Atlético Mineiro ganhou sua primeira Libertadores em mim.', 'Neymar foi para o Barcelona em mim.', 'Sou o ano das "Jornadas de Junho".', 'Sou o ano do papa Francisco.',
      'Sou um ano ímpar da década de 2010.', 'Meus dígitos são 2, 0, 1 e 3.', 'Sou o ano dos protestos dos 20 centavos.', 'Termino com 13.',
    ] },
    { answer: '2011', clues: [
      'Neste ano Osama bin Laden foi morto no Paquistão.', 'Um tsunami atingiu o Japão e a usina de Fukushima.', 'A Primavera Árabe derrubou ditadores em mim.', 'Steve Jobs morreu em outubro de mim.',
      'Amy Winehouse morreu em julho de mim.', 'O príncipe William casou com Kate Middleton em mim.', 'O último filme de Harry Potter estreou em mim.', 'Dilma Rousseff tomou posse em mim.',
      'A Netflix chegou ao Brasil em mim.', 'A música "Ai Se Eu Te Pego", de Michel Teló, virou hit mundial.', 'Neymar ganhou a Libertadores com o Santos em mim.', 'O Santos venceu o Peñarol na final.',
      'A tragédia da Região Serrana do Rio matou 900 pessoas em mim.', 'O massacre de Realengo aconteceu em mim.', 'Sou o ano do "Ai Se Eu Te Pego".', 'Sou o ano da morte de Bin Laden.',
      'Sou um ano ímpar da década de 2010.', 'Meus dígitos são 2, 0, 1 e 1.', 'Sou o primeiro ano do governo Dilma.', 'Termino com 11.',
    ] },
    { answer: '2006', clues: [
      'Neste ano Plutão deixou de ser planeta.', 'O Twitter foi criado em mim.', 'O Google comprou o YouTube em mim.', 'Saddam Hussein foi executado em dezembro de mim.',
      'O filme "O Diabo Veste Prada" é de mim.', 'A Nintendo lançou o Wii em mim.', 'Em mim Lula foi reeleito, contra Geraldo Alckmin.', 'O Internacional ganhou a Libertadores e o Mundial em mim.',
      'O Inter venceu o Barcelona de Ronaldinho no Mundial.', 'A Copa do Mundo foi na Alemanha.', 'O Brasil tinha o "quadrado mágico" e decepcionou.', 'Zidane deu uma cabeçada em Materazzi na final.',
      'A Itália venceu a França nos pênaltis.', 'O Brasil caiu para a França de Zidane nas quartas.', 'Sou o ano da cabeçada de Zidane.', 'Sou o ano do Twitter.',
      'Sou um ano par da década de 2000.', 'Meus dígitos são 2, 0, 0 e 6.', 'Sou o ano do Mundial do Inter.', 'Termino com 06.',
    ] },
    { answer: '2009', clues: [
      'Neste ano Barack Obama tomou posse.', 'Um avião pousou no rio Hudson, em Nova York, sem mortes.', 'A gripe suína, H1N1, virou pandemia em mim.', 'O filme "Avatar" virou a maior bilheteria da história em mim.',
      'Usain Bolt fez 9,58 nos 100 metros em mim.', 'Michael Jackson morreu em junho de mim.', 'O voo 447 da Air France caiu no Atlântico, saindo do Rio.', 'O Rio foi escolhido para sediar as Olimpíadas de 2016.',
      'Lula chorou com a escolha do Rio.', 'O WhatsApp foi criado em mim.', 'O Bitcoin foi lançado em mim.', 'O Corinthians contratou Ronaldo Fenômeno em mim.',
      'O Flamengo foi campeão brasileiro com Adriano em mim.', 'O Estudiantes venceu o Cruzeiro na Libertadores.', 'Sou o ano da morte de Michael Jackson.', 'Sou o ano de "Avatar".',
      'Sou o último ano da década de 2000.', 'Meus dígitos são 2, 0, 0 e 9.', 'Sou um ano ímpar.', 'Termino com 09.',
    ] },
    { answer: '2015', clues: [
      'Neste ano o jornal Charlie Hebdo foi atacado em Paris.', 'Ataques terroristas mataram 130 pessoas em Paris em novembro de mim.', 'O Acordo de Paris sobre o clima foi assinado em mim.', 'Os Estados Unidos aprovaram o casamento gay em todo o país.',
      'A foto do vestido azul e preto ou branco e dourado dividiu a internet.', 'O "Star Wars: O Despertar da Força" estreou em mim.', 'O Windows 10 foi lançado em mim.', 'Em mim a barragem de Mariana rompeu.',
      'A lama da Samarco desceu o rio Doce até o mar.', 'O impeachment de Dilma foi aberto em dezembro de mim.', 'A Lava Jato prendeu Marcelo Odebrecht em mim.', 'O Corinthians foi campeão brasileiro em mim.',
      'O Brasil vivia uma recessão forte em mim.', 'O zika vírus assustou as grávidas em mim.', 'Sou o ano da tragédia de Mariana.', 'Sou o ano do vestido azul ou dourado.',
      'Sou um ano ímpar da década de 2010.', 'Meus dígitos são 2, 0, 1 e 5.', 'Sou o ano dos ataques em Paris.', 'Termino com 15.',
    ] },
    { answer: '2000', clues: [
      'Todo mundo tinha medo do "bug do milênio" no meu começo.', 'Nada aconteceu com os computadores.', 'Vladimir Putin virou presidente da Rússia em mim.', 'O PlayStation 2 foi lançado em mim.',
      'O filme "Gladiador" é de mim.', 'A bolha da internet estourou em mim.', 'George W. Bush foi eleito depois de uma recontagem na Flórida.', 'O Big Brother chegou à TV em vários países.',
      'O Brasil comemorou 500 anos do descobrimento em mim.', 'A comemoração em Porto Seguro teve protestos de indígenas.', 'Fernando Henrique Cardoso era presidente.', 'As Olimpíadas foram em Sydney.',
      'O Brasil perdeu para Camarões nas Olimpíadas.', 'O Corinthians ganhou o primeiro Mundial de Clubes da FIFA, em mim.', 'Sou o ano da virada do milênio.', 'Sou o ano dos 500 anos do Brasil.',
      'Termino com dois zeros.', 'Meus dígitos somam 2.', 'Sou um ano redondo.', 'Sou o ano que começou o século 21 para o povo.',
    ] },
    { answer: '2003', clues: [
      'Neste ano os Estados Unidos invadiram o Iraque.', 'O ônibus espacial Columbia explodiu na volta em mim.', 'O Skype foi criado em mim.', 'O filme "Procurando Nemo" estreou em mim.',
      'O último "Senhor dos Anéis" ganhou 11 Oscars.', 'O MySpace foi criado em mim.', 'A Concorde fez seu último voo em mim.', 'Em mim Lula tomou posse pela primeira vez.',
      'O Fome Zero foi lançado em mim.', 'Em mim a Seleção Brasileira era a atual campeã do mundo.', 'O Cruzeiro ganhou a tríplice coroa em mim.', 'O Boca Juniors ganhou a Libertadores contra o Santos.',
      'Em mim o Brasil vivia a era Lula 1.', 'A novela "Mulheres Apaixonadas" era sucesso.', 'Sou o ano da posse de Lula.', 'Sou o ano da invasão do Iraque.',
      'Sou um ano ímpar da década de 2000.', 'Meus dígitos são 2, 0, 0 e 3.', 'Sou o ano do "Procurando Nemo".', 'Termino com 03.',
    ] },
  ],
};
module.exports = { CARDS4 };
