// Lote 11 do Perfil — Série ou Filme (filmes recentes, franquias e animações). Cada carta: resposta + 20 dicas.
const CARDS11 = {
  S: [
    { answer: 'Oppenheimer', clues: [
      'Meu diretor é Christopher Nolan.', 'Fui baseado na biografia "Prometeu Americano".', 'Fui filmado em IMAX, com algumas partes em preto e branco.', 'Não usei computação gráfica para a explosão principal.',
      'Estreei em julho de 2023, no mesmo dia que "Barbie".', 'Ganhei 7 Oscars em 2024, entre eles melhor filme e diretor.', 'Meu ator principal ganhou o Oscar de melhor ator.', 'Esse ator é Cillian Murphy.',
      'Robert Downey Jr. ganhou o Oscar de coadjuvante por mim.', 'Minha história se passa num laboratório secreto no deserto do Novo México.', 'Esse laboratório fica em Los Alamos.', 'Meu projeto secreto se chamava Projeto Manhattan.',
      'Meu teste da bomba se chamou Trinity.', 'Meu protagonista cita "agora eu me tornei a morte, o destruidor de mundos".', 'Meu protagonista foi perseguido depois por suspeita de comunismo.', 'Albert Einstein aparece em cenas rápidas.',
      'Conto a história do físico que liderou a criação da bomba atômica.', 'Meu protagonista usa chapéu de aba larga e cachimbo.', 'Sou um filme de 3 horas sobre o "pai da bomba atômica".', 'Meu nome é o sobrenome de um físico.',
    ] },
    { answer: 'Duna', clues: [
      'Fui baseado no livro de Frank Herbert, de 1965.', 'Uma versão minha de 1984, de David Lynch, foi um fracasso.', 'Alejandro Jodorowsky tentou me filmar nos anos 70 e não conseguiu.', 'Minha versão atual é dirigida por Denis Villeneuve.',
      'Minha primeira parte estreou em 2021 e a segunda em 2024.', 'Ganhei 6 Oscars técnicos pela primeira parte.', 'Minha trilha é de Hans Zimmer.', 'Meu planeta é um deserto sem fim.',
      'Esse planeta se chama Arrakis.', 'Meu planeta produz a substância mais valiosa do universo.', 'Essa substância é a "especiaria", que deixa os olhos azuis.', 'Meus vermes gigantes vivem embaixo da areia.',
      'Meus vilões são carecas e gordos: a casa Harkonnen.', 'Meu povo do deserto se chama Fremen.', 'Minha heroína Fremen é vivida por Zendaya.', 'Meu protagonista é o herdeiro da casa Atreides.',
      'Ele é vivido por Timothée Chalamet.', 'Meu protagonista se chama Paul Atreides.', 'Sou uma ficção científica de deserto e vermes gigantes.', 'Meu nome é um monte de areia.',
    ] },
    { answer: 'Interestelar', clues: [
      'Meu diretor é Christopher Nolan.', 'Estreei em 2014.', 'Meu físico consultor ganhou o Nobel depois e virou produtor executivo.', 'Esse físico é Kip Thorne.',
      'Minha imagem de buraco negro foi tão precisa que gerou artigos científicos.', 'Ganhei o Oscar de efeitos visuais.', 'Minha trilha de órgão de igreja é de Hans Zimmer.', 'Minha Terra está morrendo por causa de tempestades de poeira e pragas.',
      'Meu protagonista é um ex-piloto que virou fazendeiro de milho.', 'Ele deixa a filha para viajar por um buraco de minhoca perto de Saturno.', 'Meu planeta de água tem ondas do tamanho de montanhas.', 'Uma hora nesse planeta equivale a sete anos na Terra.',
      'Meu robô parece uma barra de metal e tem senso de humor ajustável.', 'Esse robô se chama TARS.', 'Matt Damon faz um cientista covarde num planeta gelado.', 'Meu protagonista cai num buraco negro e manda mensagens pela estante da filha.',
      'Meu protagonista é vivido por Matthew McConaughey.', 'Ele se chama Cooper e a filha dele, Murph.', 'Sou uma ficção científica sobre tempo, gravidade e amor.', 'Meu nome fala de viajar entre as estrelas.',
    ] },
    { answer: 'Top Gun: Maverick', clues: [
      'Sou a continuação de um filme de 1986.', 'Demorei 36 anos para sair.', 'Minha estreia foi adiada dois anos por causa da pandemia.', 'Meu ator principal se recusou a me lançar direto em streaming.',
      'Meus atores voaram de verdade em caças F-18 para as cenas.', 'Estreei em 2022 e passei de 1,4 bilhão de dólares.', 'Fui o maior sucesso da carreira do meu protagonista.', 'Meu protagonista é Tom Cruise.',
      'Meu personagem ainda é capitão depois de 30 anos, porque nunca quis subir de posto.', 'Ele volta para treinar jovens pilotos numa missão impossível.', 'Um dos alunos é filho do antigo parceiro dele, que morreu no primeiro filme.', 'Esse aluno é apelidado de "Rooster".',
      'Val Kilmer volta como Iceman, mesmo doente de verdade.', 'Meu jogo de futebol na praia repete a cena de vôlei do original.', 'Minha música de abertura é "Danger Zone", como no original.', 'Lady Gaga canta "Hold My Hand" na minha trilha.',
      'Meu protagonista anda de moto ao lado da pista de decolagem.', 'Meu protagonista se chama Pete Mitchell, apelido "Maverick".', 'Sou o filme dos pilotos de caça da Marinha americana.', 'Meu nome tem "Top Gun" e um apelido.',
    ] },
    { answer: 'Avatar', clues: [
      'Meu diretor esperou mais de 10 anos até a tecnologia permitir me filmar.', 'Meu diretor é James Cameron.', 'Estreei em dezembro de 2009.', 'Fui o filme de maior bilheteria da história por quase uma década.',
      'Popularizei o cinema 3D moderno.', 'Minha continuação, "O Caminho da Água", saiu em 2022.', 'Minha lua fica no sistema de Alpha Centauri.', 'Essa lua se chama Pandora.',
      'Minha floresta brilha à noite.', 'Meu minério valioso se chama "unobtainium".', 'Meus nativos são azuis e têm 3 metros de altura.', 'Esse povo se chama Na\'vi.',
      'Meus nativos conectam o rabo aos animais para controlá-los.', 'Meu protagonista é um fuzileiro paraplégico.', 'Ele controla um corpo alienígena feito em laboratório.', 'Meu protagonista se chama Jake Sully.',
      'Minha heroína alienígena se chama Neytiri.', 'Meu vilão é um coronel cheio de cicatrizes.', 'Sou o filme dos alienígenas azuis.', 'Meu nome também é a palavra para a foto de perfil em redes sociais.',
    ] },
    { answer: 'Piratas do Caribe', clues: [
      'Fui baseado num brinquedo de parque da Disney.', 'Ninguém acreditava que um filme de pirata daria certo em 2003.', 'Meu ator principal se inspirou no guitarrista Keith Richards.', 'O estúdio achou que ele estava bêbado nas gravações.',
      'Meu primeiro filme se chama "A Maldição do Pérola Negra".', 'Meu navio principal tem velas pretas.', 'Meus piratas amaldiçoados viram esqueletos sob a luz da lua.', 'Meu vilão do primeiro filme é o Capitão Barbossa.',
      'Meu segundo vilão tem tentáculos no rosto e um coração guardado num baú.', 'Esse vilão é Davy Jones.', 'Meu ferreiro que vira pirata é vivido por Orlando Bloom.', 'Minha filha do governador é vivida por Keira Knightley.',
      'Meu protagonista anda cambaleando, com muitas bugigangas no cabelo.', 'Ele tem uma bússola que aponta para o que a pessoa mais quer.', 'Meu protagonista é vivido por Johnny Depp.', 'Ele se chama Capitão Jack Sparrow.',
      'Ganhei cinco filmes entre 2003 e 2017.', 'Minha música-tema de Hans Zimmer é reconhecida em segundos.', 'Sou a franquia de piratas da Disney.', 'Meu nome tem "Piratas" e um mar da América Central.',
    ] },
    { answer: 'Missão: Impossível', clues: [
      'Fui baseado numa série de TV dos anos 60.', 'Meu primeiro filme é de 1996, dirigido por Brian De Palma.', 'Meu ator principal faz as próprias acrobacias, por mais perigosas que sejam.', 'Ele se pendurou no lado de fora de um avião decolando.',
      'Ele escalou o prédio mais alto do mundo, em Dubai.', 'Ele pulou de moto de um penhasco na Noruega.', 'Meu ator principal é Tom Cruise.', 'Minha música-tema começa com um pavio aceso.',
      'Meu agente recebe missões em gravações que se autodestroem em 5 segundos.', 'Minha agência secreta se chama IMF.', 'Meus agentes usam máscaras que imitam perfeitamente outra pessoa.', 'Minha cena mais famosa tem o herói pendurado por cabos num cofre.',
      'Meu hacker gordinho é vivido por Simon Pegg.', 'Meu diretor dos filmes mais recentes é Christopher McQuarrie.', 'Meu filme de 2025 se chama "O Acerto Final".', 'Meu protagonista se chama Ethan Hunt.',
      'Já são oito filmes na franquia.', 'A frase "sua missão, caso decida aceitá-la" é minha.', 'Sou a franquia de espionagem do Tom Cruise.', 'Meu nome tem dois pontos e a palavra "Impossível".',
    ] },
    { answer: 'John Wick', clues: [
      'Meu primeiro filme, de 2014, foi feito com orçamento pequeno.', 'Meus diretores eram dublês de "Matrix".', 'Meu ator principal também foi o Neo de "Matrix".', 'Meu estilo de luta mistura judô, jiu-jítsu e tiro à queima-roupa.',
      'Esse estilo foi apelidado de "gun fu".', 'Meu protagonista é um assassino aposentado.', 'Ele volta à ativa depois que matam o cachorro dele.', 'O cachorro era o último presente da esposa falecida.',
      'Meu protagonista é chamado de "Baba Yaga", o bicho-papão.', 'Meu hotel para assassinos tem regras: não se pode matar lá dentro.', 'Esse hotel se chama Continental.', 'Minha moeda são moedas de ouro especiais.',
      'Minha organização secreta é a "Alta Cúpula".', 'Meu protagonista usa terno preto e nunca perde o carro Mustang.', 'Meu quarto filme, de 2023, tem quase 3 horas de tiros.', 'Meu protagonista é vivido por Keanu Reeves.',
      'Meu spin-off de 2025 se chama "Bailarina".', 'Meu personagem fala pouco e mata muito.', 'Sou a franquia do assassino que vingou o cachorro.', 'Meu nome é o nome do protagonista.',
    ] },
    { answer: 'Deadpool', clues: [
      'Fui criado nos quadrinhos em 1991 como paródia de um personagem da DC.', 'Meu ator lutou 11 anos para conseguir fazer meu filme.', 'Um teste de cena vazou na internet e forçou o estúdio a me aprovar.', 'Meu primeiro filme é de 2016 e tem classificação adulta.',
      'Fui o filme adulto de maior bilheteria da história na época.', 'Meu ator principal é Ryan Reynolds.', 'Meu protagonista sabe que está num filme e fala com o público.', 'Isso se chama "quebrar a quarta parede".',
      'Meu protagonista tem câncer e faz um experimento que o deixa imortal e deformado.', 'Meu uniforme é vermelho para "não mostrar o sangue".', 'Meu personagem tem uma boca que não para de falar.', 'Meu taxista se chama Dopinder.',
      'Meu terceiro filme, de 2024, me juntou com o Wolverine.', 'Nesse filme os dois se xingam e se matam ao som de músicas pop.', 'Hugh Jackman voltou a usar o uniforme amarelo por mim.', 'Fui o primeiro filme adulto da Marvel Studios.',
      'Meu nome verdadeiro é Wade Wilson.', 'Meu apelido é "o mercenário tagarela".', 'Sou o anti-herói vermelho da Marvel que faz piada de tudo.', 'Meu nome tem "Dead" e "pool".',
    ] },
    { answer: 'Guardiões da Galáxia', clues: [
      'Meus personagens eram quase desconhecidos até 2014.', 'Meu diretor foi demitido por tuítes antigos e depois recontratado.', 'Esse diretor é James Gunn, que hoje comanda a DC.', 'Minha trilha sonora vem de uma fita cassete dos anos 70 e 80.',
      'Essa fita se chama "Awesome Mix".', 'Meu protagonista foi sequestrado da Terra quando criança.', 'Ele se chama Peter Quill e quer ser chamado de "Senhor das Estrelas".', 'Meu protagonista é vivido por Chris Pratt.',
      'Minha assassina verde é filha adotiva do Thanos.', 'Ela se chama Gamora.', 'Meu guaxinim geneticamente modificado adora armas grandes.', 'Ele se chama Rocket.',
      'Minha árvore só fala três palavras.', 'Essas palavras são "eu sou Groot".', 'Meu grandalhão tatuado não entende metáforas: Drax.', 'Minha ninhada inclui Nebula e Mantis também.',
      'Meu terceiro filme, de 2023, conta a origem do Rocket.', 'Meu bebê Groot dança na primeira cena pós-créditos.', 'Sou o time espacial mais engraçado da Marvel.', 'Meu nome tem "Guardiões" e "Galáxia".',
    ] },
    { answer: 'Homem de Ferro', clues: [
      'Fui o primeiro filme do Universo Cinematográfico da Marvel.', 'Estreei em 2008.', 'Meu ator principal estava sem crédito em Hollywood por causa de vícios.', 'Meu estúdio arriscou tudo nele.',
      'Esse ator é Robert Downey Jr.', 'Meu diretor foi Jon Favreau, que também faz o motorista Happy.', 'Minha cena pós-créditos apresentou Nick Fury e a "Iniciativa Vingadores".', 'Meu protagonista é bilionário, gênio, playboy e filantropo.',
      'Ele fabrica armas e é sequestrado no Afeganistão.', 'Ele constrói a primeira armadura numa caverna, com sucata.', 'Ele tem um reator no peito para não morrer.', 'Minha inteligência artificial se chama JARVIS.',
      'Minha secretária vira CEO e namorada: Pepper Potts.', 'Meu protagonista anuncia sua identidade numa coletiva de imprensa.', 'Ele diz "eu sou o Homem de Ferro" no final.', 'Minha armadura é vermelha e dourada.',
      'Meu protagonista morre em "Ultimato" salvando o universo.', 'Meu protagonista se chama Tony Stark.', 'Sou o herói da Marvel de armadura voadora.', 'Meu nome tem um metal.',
    ] },
    { answer: 'Mulher-Maravilha', clues: [
      'Fui criada em 1941 por um psicólogo que também inventou o detector de mentiras.', 'Esse psicólogo é William Moulton Marston.', 'Sou a super-heroína mais antiga ainda em atividade.', 'Meu filme de 2017 foi dirigido por Patty Jenkins.',
      'Fui o primeiro grande filme de super-heroína dirigido por uma mulher.', 'Minha atriz é israelense e foi Miss Israel.', 'Essa atriz é Gal Gadot.', 'Fui esculpida em argila por minha mãe, segundo a versão antiga.',
      'Sou filha de Zeus na versão do cinema.', 'Sou uma princesa amazona de uma ilha só de mulheres.', 'Essa ilha se chama Themyscira.', 'Meu laço obriga quem toca nele a dizer a verdade.',
      'Meus braceletes desviam balas.', 'Minha história de 2017 se passa na Primeira Guerra.', 'Meu par romântico é o piloto Steve Trevor.', 'Minha cena de atravessar a "terra de ninguém" virou a mais famosa.',
      'Minha continuação se passa em 1984.', 'Meu nome verdadeiro é Diana Prince.', 'Sou a heroína da DC com laço da verdade.', 'Meu nome tem "Mulher" e "Maravilha".',
    ] },
    { answer: 'Encanto', clues: [
      'Sou uma animação da Disney de 2021.', 'Minha história se passa na Colômbia.', 'Minhas músicas são de Lin-Manuel Miranda, o mesmo de "Hamilton".', 'Ganhei o Oscar de melhor animação em 2022.',
      'Minha família mora numa casa mágica que se mexe.', 'Cada membro da família ganha um dom mágico quando criança.', 'Um tem força, uma faz flores brotarem, outra ouve tudo.', 'Minha protagonista é a única sem dom.',
      'Ela usa óculos e se chama Mirabel.', 'Minha avó guarda uma vela mágica que mantém o milagre.', 'Meu tio tem visões do futuro e foi excluído pela família.', 'Ninguém fala sobre ele.',
      'Esse tio se chama Bruno.', 'Minha música mais famosa é justamente sobre ele.', 'Essa música é "We Don\'t Talk About Bruno", que bateu recorde nas paradas.', 'Minha irmã forte carrega burros e se sente pressionada.',
      'Essa irmã canta "Surface Pressure".', 'Minha vila fica escondida entre montanhas.', 'Sou a animação da família mágica colombiana.', 'Meu nome tem sete letras e começa com E.',
    ] },
    { answer: 'Moana', clues: [
      'Sou uma animação da Disney de 2016.', 'Na Europa mudei de nome para "Vaiana" por causa de uma marca registrada.', 'Minha história se passa na Polinésia.', 'Minhas músicas são de Lin-Manuel Miranda.',
      'Minha protagonista é filha do chefe de uma ilha.', 'O oceano a escolhe quando ela é bebê.', 'Minha protagonista não é chamada de princesa, e ela mesma brinca com isso.', 'Ela precisa devolver uma pedra verde a uma deusa.',
      'Essa pedra é o coração de Te Fiti.', 'Meu semideus é grande, tatuado e convencido.', 'As tatuagens dele se mexem.', 'Ele tem um anzol mágico e vira animais.',
      'Esse semideus é Maui, dublado por Dwayne "The Rock" Johnson.', 'Meu galo bobo se chama Heihei.', 'Meu caranguejo gigante e brilhante canta "Shiny".', 'Minha música mais famosa é "How Far I\'ll Go".',
      'Minha continuação saiu em 2024.', 'Uma versão minha com atores reais está em produção.', 'Sou a animação da navegadora polinésia.', 'Meu nome tem cinco letras e começa com M.',
    ] },
    { answer: 'Zootopia', clues: [
      'Sou uma animação da Disney de 2016.', 'Ganhei o Oscar de melhor animação em 2017.', 'Minha cidade é dividida em bairros com climas diferentes.', 'Tem um bairro de tundra, um de floresta tropical e um de deserto.',
      'Meus habitantes são todos animais que andam e falam.', 'Predadores e presas vivem juntos em paz, até que…', 'Minha protagonista é uma coelha que sonha ser policial.', 'Ela é a primeira coelha da polícia e é rebaixada a guarda de trânsito.',
      'Meu outro protagonista é uma raposa vigarista.', 'Ela se chama Judy Hopps e ele, Nick Wilde.', 'Meu chefe de polícia é um búfalo.', 'Meu DMV (Detran) é operado por preguiças.',
      'A preguiça mais lenta se chama Flash.', 'Meu mafioso é um musaranho minúsculo chamado Mr. Big.', 'Minha cantora pop é uma gazela dublada pela Shakira.', 'Minha música-tema é "Try Everything".',
      'Falo sobre preconceito de um jeito que criança entende.', 'Minha continuação saiu em 2025.', 'Sou a animação da cidade dos animais.', 'Meu nome mistura "zoo" e "utopia".',
    ] },
    { answer: 'Procurando Nemo', clues: [
      'Sou uma animação da Pixar de 2003.', 'Ganhei o Oscar de melhor animação.', 'Minha história se passa na Grande Barreira de Corais, na Austrália.', 'Meu protagonista é um peixe-palhaço superprotetor.',
      'Ele perdeu a esposa e quase todos os ovos para uma barracuda.', 'O único filhote que sobrou tem uma nadadeira menor.', 'Esse filhote é capturado por um mergulhador.', 'Ele vai parar num aquário de dentista em Sydney.',
      'Meu pai atravessa o oceano atrás do filho.', 'Ele é ajudado por uma peixe azul com perda de memória.', 'Essa peixe se chama Dory e diz "continue a nadar".', 'Ela fala "baleiês".',
      'Meus tubarões fazem um grupo de apoio: "peixe é amigo, não comida".', 'Meu tubarão se chama Bruce.', 'Minhas tartarugas surfam na corrente marítima e dizem "cara".', 'Meu peixe do aquário é obcecado por bolhas.',
      'Dory ganhou um filme próprio em 2016.', 'Meu pai se chama Marlin.', 'Sou a animação do peixe-palhaço perdido.', 'Meu nome tem "Procurando" e o nome do peixinho.',
    ] },
    { answer: 'Os Incríveis', clues: [
      'Sou uma animação da Pixar de 2004.', 'Meu diretor é Brad Bird, que depois fez "Ratatouille".', 'Ganhei o Oscar de melhor animação.', 'Minha história se passa numa versão retrô dos anos 60.',
      'Meus super-heróis foram proibidos de usar poderes.', 'Minha família finge ser normal no subúrbio.', 'Meu pai trabalha numa seguradora e odeia o emprego.', 'Ele é forte e se chama Sr. Incrível.',
      'Minha mãe é elástica e se chama Mulher-Elástico.', 'Minha filha fica invisível e faz campos de força: Violeta.', 'Meu filho é velocista e se chama Flecha.', 'Meu bebê Zezé revela poderes só no final.',
      'Minha estilista de heróis é baixinha e proíbe capas.', 'Ela se chama Edna Mode: "sem capas!".', 'Meu vilão é um fã rejeitado que virou inventor.', 'Ele se chama Síndrome.',
      'Meu amigo de gelo se chama Gelado.', 'Minha continuação saiu 14 anos depois, em 2018.', 'Sou a animação da família de super-heróis.', 'Meu nome tem um adjetivo que diz que a família é impressionante.',
    ] },
    { answer: 'Up: Altas Aventuras', clues: [
      'Sou uma animação da Pixar de 2009.', 'Fui o primeiro filme de animação a abrir o Festival de Cannes.', 'Ganhei o Oscar de animação e de trilha sonora.', 'Meus primeiros 10 minutos fazem todo mundo chorar.',
      'Esses minutos contam uma vida inteira de casal sem falas.', 'Meu protagonista é um viúvo ranzinza de 78 anos.', 'Ele vai perder a casa para uma construtora.', 'Ele amarra milhares de balões na casa e voa.',
      'Um escoteiro gordinho vai junto sem querer.', 'Esse escoteiro se chama Russell.', 'Meu destino é uma cachoeira na América do Sul.', 'Essa cachoeira se chama Paraíso das Cachoeiras.',
      'Meu cachorro tem uma coleira que traduz os pensamentos dele.', 'Ele se distrai gritando "esquilo!".', 'Esse cachorro se chama Dug.', 'Minha ave colorida gigante se chama Kevin, e é fêmea.',
      'Meu vilão é o explorador que o protagonista admirava na infância.', 'Meu protagonista se chama Carl Fredricksen.', 'Sou a animação da casa que voa com balões.', 'Meu nome tem "Up" e "Altas Aventuras".',
    ] },
    { answer: 'Cinquenta Tons de Cinza', clues: [
      'Nasci como fanfic de "Crepúsculo" na internet.', 'Minha autora assinou como E. L. James.', 'Meu livro vendeu mais de 150 milhões de cópias.', 'Fui chamado de "pornô para mães".',
      'Meu filme estreou no Dia dos Namorados americano de 2015.', 'Minha diretora foi Sam Taylor-Johnson.', 'Minha protagonista é uma estudante tímida de literatura.', 'Ela entrevista um bilionário para o jornal da faculdade.',
      'O bilionário tem 27 anos e um quarto especial.', 'Esse quarto é chamado de "quarto vermelho".', 'Ele quer que ela assine um contrato.', 'Ele voa de helicóptero e toca piano à noite.',
      'Meu casal é vivido por Dakota Johnson e Jamie Dornan.', 'Meus personagens são Anastasia Steele e Christian Grey.', 'Minha trilha tem "Love Me Like You Do", da Ellie Goulding.', 'Ganhei duas continuações: "Mais Escuros" e "Liberdade".',
      'Meu sobrenome do protagonista é o mesmo da cor do título.', 'Sou um romance erótico que virou fenômeno.', 'Meu nome tem um número e uma cor.', 'Meu nome começa com "Cinquenta".',
    ] },
    { answer: 'Crepúsculo', clues: [
      'Minha autora sonhou com a cena do prado e escreveu o livro.', 'Minha autora é Stephenie Meyer.', 'Meu primeiro filme é de 2008.', 'Minha história se passa numa cidade chuvosa de Washington.',
      'Essa cidade se chama Forks.', 'Meus vampiros brilham no sol em vez de queimar.', 'Meus vampiros "vegetarianos" só bebem sangue de animal.', 'Minha protagonista se muda para a casa do pai, que é xerife.',
      'Ela se apaixona por um colega pálido de 17 anos há 100 anos.', 'Meu rival é um lobisomem indígena que não usa camisa.', 'Os fãs se dividiam entre "Team Edward" e "Team Jacob".', 'Meu casal principal é vivido por Kristen Stewart e Robert Pattinson.',
      'Os dois namoraram de verdade.', 'Meus personagens são Bella Swan, Edward Cullen e Jacob Black.', 'Meu jogo de beisebol de vampiros é ao som de Muse.', 'Meu bebê meio vampira se chama Renesmee.',
      'Minha saga tem cinco filmes.', 'Meu nome é a hora do dia entre o sol e a noite.', 'Sou a saga de vampiros adolescentes.', 'Meu nome tem dez letras e começa com C.',
    ] },
    { answer: 'Jogos Vorazes', clues: [
      'Fui baseado nos livros de Suzanne Collins.', 'A autora teve a ideia trocando de canal entre reality show e notícias de guerra.', 'Meu primeiro filme é de 2012.', 'Minha história se passa num país futuro chamado Panem.',
      'Minha capital rica controla 12 distritos pobres.', 'Todo ano cada distrito manda um menino e uma menina para lutar até a morte.', 'Isso é transmitido na TV como entretenimento.', 'Minha protagonista se oferece no lugar da irmã.',
      'Ela é do Distrito 12 e caça com arco e flecha.', 'Ela é chamada de "a garota em chamas".', 'Meu gesto de rebeldia é três dedos levantados.', 'Meu assobio de quatro notas é o do tordo.',
      'Meu apresentador de TV tem cabelo azul: Caesar Flickerman.', 'Meu vilão é o presidente Snow.', 'Minha protagonista é vivida por Jennifer Lawrence.', 'Ela se chama Katniss Everdeen.',
      'Meu triângulo amoroso tem Peeta e Gale.', 'Ganhei um prequel em 2023 sobre o jovem Snow.', 'Sou a saga do reality show mortal.', 'Meu nome tem "Jogos" e "Vorazes".',
    ] },
    { answer: 'Um Filme Minecraft', clues: [
      'Fui baseado no videogame mais vendido da história.', 'Estreei em abril de 2025.', 'Meu diretor é Jared Hess, de "Napoleon Dynamite".', 'Fui detonado pela crítica e adorado pelas crianças.',
      'Meu público gritava e jogava pipoca nas sessões.', 'Isso virou um problema para os cinemas.', 'Jack Black interpreta um personagem que virou meme.', 'Jason Momoa faz um ex-campeão de fliperama com jaqueta rosa.',
      'Meu mundo é todo feito de blocos.', 'Meus personagens caem num portal e vão parar no mundo do jogo.', 'Meu personagem Steve grita os nomes das coisas.', 'A frase "chicken jockey" fez os cinemas explodirem.',
      'Meus vilões são porcos humanoides de outra dimensão.', 'Esses porcos são os piglins e o chefe deles é Malgosha.', 'Meus zumbis e creepers explodem nas cenas noturnas.', 'Meu personagem ganha uma picareta de diamante.',
      'Meu jogo original foi criado por um sueco chamado Notch.', 'Passei de 900 milhões de dólares em bilheteria.', 'Sou o filme do jogo de blocos.', 'Meu nome tem "Filme" e o nome de um jogo de construir.',
    ] },
    { answer: 'Super Mario Bros. O Filme', clues: [
      'Fui feito pela Illumination, o estúdio dos Minions.', 'Estreei em abril de 2023.', 'Fui a maior bilheteria de um filme baseado em videogame.', 'Meu protagonista foi dublado por Chris Pratt, o que gerou polêmica.',
      'Meu vilão foi dublado por Jack Black e canta uma música de amor.', 'Essa música é "Peaches".', 'Meus protagonistas são dois irmãos encanadores do Brooklyn.', 'Eles caem num cano e vão parar num reino de cogumelos.',
      'Meu vilão é uma tartaruga gigante com espinhos.', 'Esse vilão é o Bowser.', 'Minha princesa é a Peach, e ela não precisa ser salva.', 'Meu macaco enorme se chama Donkey Kong.',
      'Minha cena de corrida na Rainbow Road vem do Mario Kart.', 'Meu cogumelo azul fala com voz de criança: Toad.', 'Meu primeiro filme, de 1993, foi um fracasso enorme.', 'Meu jogo original é de 1985.',
      'Minha continuação está marcada para 2026.', 'Meu protagonista tem bigode, boné vermelho e macacão azul.', 'Sou o filme do encanador da Nintendo.', 'Meu nome tem "Super Mario".',
    ] },
    { answer: 'Sonic', clues: [
      'Meu personagem foi criado pela Sega em 1991 para competir com o Mario.', 'Meu primeiro trailer de filme foi tão feio que o estúdio refez meu visual.', 'Os fãs reclamaram dos meus dentes humanos e a estreia foi adiada.', 'Meu primeiro filme estreou em 2020.',
      'Meu vilão é um cientista com bigode enorme.', 'Ele é vivido por Jim Carrey.', 'Esse vilão é o Dr. Robotnik, ou Eggman.', 'Meu protagonista é azul e corre mais rápido que o som.',
      'Ele coleta anéis dourados.', 'Ele mora escondido numa cidadezinha de Montana.', 'Meu policial amigo se chama Tom.', 'Minha raposa de duas caudas se chama Tails.',
      'Meu rival vermelho é forte e sério: Knuckles.', 'Meu terceiro filme, de 2024, apresentou o Shadow.', 'Keanu Reeves dublou o Shadow.', 'Meu jogo original era para o Mega Drive.',
      'Minha frase é "gotta go fast".', 'Meu personagem é um ouriço.', 'Sou o ouriço azul da Sega.', 'Meu nome tem cinco letras e começa com S.',
    ] },
    { answer: 'Wicked', clues: [
      'Sou baseado num musical da Broadway de 2003.', 'O musical é baseado num livro de Gregory Maguire.', 'Conto a história antes de "O Mágico de Oz".', 'Meu filme estreou em novembro de 2024.',
      'Minhas atrizes cantaram ao vivo durante as filmagens.', 'Minhas duas protagonistas são vividas por Cynthia Erivo e Ariana Grande.', 'Minha protagonista nasceu com a pele verde.', 'Ela é rejeitada por todos e vira a "Bruxa Má do Oeste".',
      'Minha outra protagonista é loira, popular e adora rosa.', 'Ela vira a "Bruxa Boa".', 'Elas são Elphaba e Glinda.', 'As duas viram amigas na escola de magia.',
      'Essa escola se chama Shiz.', 'Meu Mágico de Oz é vivido por Jeff Goldblum.', 'Minha música mais famosa termina com a bruxa voando na vassoura.', 'Essa música é "Defying Gravity".',
      'Fui indicado a 10 Oscars.', 'Minha segunda parte saiu em novembro de 2025.', 'Sou o musical da bruxa verde.', 'Meu nome, em inglês, quer dizer "malvada".',
    ] },
  ],
};

module.exports = { CARDS11 };
