// Lote 6 do Perfil — Lugares. Cada carta: resposta + 20 dicas (da mais difícil para a mais fácil).
const CARDS6 = {
  L: [
    { answer: 'Cristo Redentor', clues: [
      'A ideia de me construir apareceu ainda no século 19, mas só saiu do papel nos anos 1920.', 'A Igreja Católica fez uma campanha de doações para me erguer.', 'Fui projetado pelo engenheiro Heitor da Silva Costa.', 'O escultor francês Paul Landowski fez o modelo do meu rosto e das minhas mãos.',
      'O escultor romeno Gheorghe Leonida esculpiu meu rosto.', 'Levei cerca de cinco anos para ficar pronto.', 'Fui inaugurado em 12 de outubro de 1931.', 'Sou feito de concreto armado revestido de pedra-sabão.',
      'Tenho 30 metros de altura, mais 8 metros de pedestal.', 'Meus braços abertos medem 28 metros de ponta a ponta.', 'Fico a 710 metros acima do nível do mar.', 'Levo raios várias vezes por ano e já perdi pedaços do dedo.',
      'Dá para chegar em mim de trem, de van ou subindo 220 degraus.', 'O trem que sobe até mim atravessa a Floresta da Tijuca.', 'Fui eleito uma das Sete Maravilhas do Mundo Moderno em 2007.', 'Fico no alto do Morro do Corcovado.',
      'Sou iluminado de cores diferentes em campanhas e datas especiais.', 'Sou o cartão-postal mais famoso do Rio de Janeiro.', 'Sou uma estátua de braços abertos sobre a cidade.', 'Represento Jesus Cristo abraçando a cidade.',
    ] },
    { answer: 'Ouro Preto', clues: [
      'Fui fundada no fim do século 17, durante uma corrida do ouro.', 'Meu primeiro nome foi Vila Rica.', 'Recebi milhares de portugueses atrás de metal precioso.', 'Aqui aconteceu a Guerra dos Emboabas.',
      'Fui capital da capitania de Minas Gerais.', 'Meus mineradores se revoltaram contra a cobrança do quinto e da derrama.', 'A conspiração de 1789 nasceu aqui.', 'Tiradentes era um dos meus conspiradores.',
      'Perdi o posto de capital para Belo Horizonte em 1897.', 'Tenho igrejas cheias de ouro por dentro.', 'Aleijadinho esculpiu meus altares e fachadas.', 'Minha igreja de São Francisco de Assis é obra-prima do barroco.',
      'Minhas ruas são de pedra e muito íngremes.', 'Tenho repúblicas estudantis famosas nos casarões antigos.', 'Minha universidade federal é uma escola de minas tradicional.', 'Fui a primeira cidade brasileira a virar Patrimônio Mundial da Unesco, em 1980.',
      'Meu Carnaval e minha Semana Santa atraem muita gente.', 'Fico no interior de Minas Gerais.', 'Meu nome é uma cor mais um metal.', 'Sou a cidade histórica mineira do ciclo do ouro.',
    ] },
    { answer: 'Recife', clues: [
      'Comecei como um porto ligado a um engenho de açúcar.', 'Fui ocupada pelos holandeses entre 1630 e 1654.', 'Maurício de Nassau me governou e mandou construir pontes e jardins.', 'Tive a primeira sinagoga das Américas.',
      'Minha sinagoga é a Kahal Zur Israel, na rua do Bom Jesus.', 'A Insurreição Pernambucana expulsou os holandeses daqui.', 'Fui palco da Revolução Pernambucana de 1817.', 'Meu nome vem das barreiras de arenito que protegem a costa.',
      'Sou cortada por dois rios: o Capibaribe e o Beberibe.', 'Sou chamada de "Veneza brasileira" por causa das pontes.', 'Tenho um bairro portuário revitalizado cheio de bares e tecnologia.', 'Meu polo de tecnologia se chama Porto Digital.',
      'Meu Carnaval começa com um bloco gigante na madrugada de sábado.', 'Esse bloco é o Galo da Madrugada, o maior do mundo.', 'Meu ritmo típico é o frevo, dançado com sombrinha.', 'Chico Science e a manguebeat nasceram aqui.',
      'Faço divisa com Olinda.', 'Tenho tubarões que impedem o banho em algumas praias.', 'Sou a capital de Pernambuco.', 'Meu nome tem seis letras e começa com R.',
    ] },
    { answer: 'Manaus', clues: [
      'Nasci de um forte português construído em 1669.', 'Meu antigo nome era Barra do Rio Negro.', 'Fiquei riquíssima entre 1890 e 1910.', 'Minha riqueza veio da extração do látex.',
      'Nessa época eu tinha bondes elétricos antes de muitas capitais europeias.', 'Contam que meus barões mandavam roupa lavar em Lisboa.', 'Perdi a riqueza quando os ingleses levaram sementes de seringueira para a Ásia.', 'Ganhei uma zona franca em 1967 para atrair indústrias.',
      'Monto boa parte dos eletrônicos e motos vendidos no Brasil.', 'Tenho um teatro luxuoso inaugurado em 1896.', 'Meu teatro tem uma cúpula com 36 mil peças de cerâmica nas cores da bandeira.', 'Meu teatro se chama Teatro Amazonas.',
      'Fui sede de jogos da Copa do Mundo de 2014.', 'Fico na margem esquerda do Rio Negro.', 'Perto de mim as águas escuras e barrentas correm lado a lado sem se misturar.', 'Esse fenômeno é o Encontro das Águas.',
      'Sou a maior cidade da Amazônia.', 'Só se chega em mim de avião ou de barco.', 'Sou a capital do Amazonas.', 'Meu nome tem seis letras e começa com M.',
    ] },
    { answer: 'Curitiba', clues: [
      'Fui fundada em 1693 como uma vila de tropeiros e mineradores.', 'Meu nome vem do tupi e significa algo como "muito pinhão".', 'Recebi muitos imigrantes alemães, poloneses, italianos e ucranianos.', 'Tenho bosques temáticos dedicados a esses povos.',
      'Nos anos 70 fiz um plano urbano que virou referência mundial.', 'Jaime Lerner foi meu prefeito e arquiteto desse plano.', 'Criei uma das primeiras ruas exclusivas de pedestres do Brasil.', 'Minha Rua XV de Novembro virou calçadão em 1972.',
      'Inventei um sistema de ônibus rápido copiado por várias cidades.', 'Minhas estações de ônibus são tubos de vidro.', 'Tenho uma estufa de vidro num parque famoso.', 'Meu Jardim Botânico tem uma estufa art nouveau nos cartões-postais.',
      'Tenho um museu com um prédio em forma de olho.', 'Esse museu leva o nome de Oscar Niemeyer.', 'Minha ópera fica dentro de uma antiga pedreira.', 'Sou conhecida pela coleta seletiva de lixo desde os anos 80.',
      'Faz frio aqui e às vezes a temperatura chega perto de zero.', 'Meus times são Coritiba, Athletico e Paraná.', 'Sou a capital do Paraná.', 'Sou famosa por ser organizada, arborizada e fria.',
    ] },
    { answer: 'Belo Horizonte', clues: [
      'Fui construída do zero para ser capital.', 'Antes de mim existia aqui o arraial de Curral del Rei.', 'Fui inaugurada em 12 de dezembro de 1897.', 'Substituí Ouro Preto como capital do estado.',
      'Fui planejada com ruas em xadrez e avenidas na diagonal.', 'Uma avenida circular delimita meu centro planejado.', 'Essa avenida é a Avenida do Contorno.', 'Nos anos 40 ganhei um conjunto moderno projetado por Niemeyer.',
      'Esse conjunto fica em volta de uma lagoa artificial.', 'Minha lagoa se chama Pampulha.', 'Minha igrejinha de São Francisco tem painéis de Portinari.', 'Estou cercada por serras, entre elas a Serra do Curral.',
      'Meu mercado central vende queijo, cachaça e pimenta.', 'Meu bar é assunto sério: sou conhecida como a capital dos botecos.', 'Meus times de futebol são o Atlético e o Cruzeiro.', 'Meu estádio principal é o Mineirão.',
      'Aqui o Brasil perdeu de 7 a 1 em 2014.', 'Meu apelido é "BH".', 'Sou a capital de Minas Gerais.', 'Meu nome tem duas palavras e quer dizer uma vista bonita.',
    ] },
    { answer: 'Florianópolis', clues: [
      'Fui fundada por Francisco Dias Velho em 1673.', 'Meu primeiro nome foi Nossa Senhora do Desterro.', 'Recebi muitos casais açorianos no século 18.', 'Ganhei meu nome atual em 1894, em homenagem a um presidente.',
      'Esse presidente é Floriano Peixoto.', 'A troca de nome foi polêmica porque ele reprimiu uma revolta aqui.', 'Sou formada por uma parte continental e uma ilha.', 'Duas pontes ligam minhas duas partes.',
      'Minha ponte mais famosa é pênsil e ficou décadas fechada para reforma.', 'Essa ponte é a Hercílio Luz.', 'Tenho mais de 40 praias.', 'Minhas praias do norte são calmas e as do leste têm ondas fortes.',
      'Sou point de surfe: a Joaquina é minha praia mais famosa.', 'Tenho uma lagoa enorme no meio da ilha.', 'Minha lagoa se chama Lagoa da Conceição.', 'Tenho dunas onde se pratica sandboard.',
      'Sou apelidada de "Ilha da Magia".', 'Minha comida típica tem muito camarão e ostra.', 'Sou a capital de Santa Catarina.', 'Sou uma capital brasileira que fica quase toda numa ilha.',
    ] },
    { answer: 'Portugal', clues: [
      'Nasci como condado no século 11 e virei reino em 1143.', 'Meu primeiro rei foi Afonso Henriques.', 'Financiei viagens que abriram o caminho marítimo para as Índias.', 'Vasco da Gama e Fernão de Magalhães saíram daqui.',
      'Um tratado de 1494 dividiu o mundo entre mim e a Espanha.', 'Esse tratado é o de Tordesilhas.', 'Um terremoto seguido de tsunami destruiu minha capital em 1755.', 'Minha família real fugiu para o Brasil em 1808.',
      'Perdi meu maior território colonial em 1822.', 'Minha ditadura durou de 1933 a 1974.', 'Minha revolução de 1974 aconteceu quase sem tiros, com flores nos fuzis.', 'Essa revolução se chama Revolução dos Cravos.',
      'Entrei na União Europeia em 1986.', 'Minha música típica é triste e se canta em casas escuras.', 'Essa música é o fado, e Amália Rodrigues foi sua maior voz.', 'Meu prato mais conhecido usa bacalhau e tem centenas de receitas.',
      'Meu doce mais famoso é o pastel de nata, de Belém.', 'Ganhei a Eurocopa de 2016 com Cristiano Ronaldo.', 'Minhas cidades principais são Lisboa e Porto.', 'Sou o país europeu que colonizou o Brasil.',
    ] },
    { answer: 'Argentina', clues: [
      'Meu nome vem da palavra latina para prata.', 'Declarei independência da Espanha em 1816.', 'José de San Martín é meu libertador.', 'Recebi milhões de imigrantes italianos e espanhóis.',
      'Minha ex-primeira-dama Evita virou personagem de musical.', 'Tive uma ditadura militar entre 1976 e 1983.', 'Perdi uma guerra por umas ilhas do Atlântico Sul em 1982.', 'Essas ilhas são as Malvinas, ou Falklands.',
      'Minhas mães de uma praça protestam até hoje pelos desaparecidos.', 'Tive uma crise econômica enorme em 2001, com cinco presidentes numa semana.', 'Minha planície de criação de gado se chama Pampa.', 'Meu chá amargo se toma numa cuia com bomba.',
      'Minha dança típica é o tango.', 'Meu vinho mais famoso é o Malbec, de Mendoza.', 'Minha carne assada se chama asado.', 'Ganhei três Copas do Mundo: 1978, 1986 e 2022.',
      'Sou o país de Maradona e de Messi.', 'Minha capital é Buenos Aires.', 'Faço fronteira com o Brasil pelo sul.', 'Sou o maior rival do Brasil no futebol.',
    ] },
    { answer: 'México', clues: [
      'Fui casa de civilizações como os olmecas, maias e astecas.', 'Minha capital foi construída sobre um lago, chamada Tenochtitlán.', 'Hernán Cortés me conquistou em 1521.', 'Meu último imperador asteca foi Montezuma.',
      'Declarei independência da Espanha em 1810, num grito de um padre.', 'Perdi metade do meu território para os Estados Unidos no século 19.', 'Minha revolução começou em 1910, com Pancho Villa e Zapata.', 'Meus murais revolucionários foram pintados por Diego Rivera.',
      'Frida Kahlo é minha pintora mais famosa.', 'Tenho pirâmides em Teotihuacán e Chichén Itzá.', 'Minha bebida destilada mais famosa vem de uma planta azul.', 'Essa bebida é a tequila.',
      'Minha comida típica tem tortilha, feijão e pimenta.', 'Meu prato mais conhecido no mundo é o taco.', 'Minha música de rua é tocada por grupos com chapéus grandes.', 'Esses grupos são os mariachis.',
      'Celebro os mortos com caveiras coloridas em 2 de novembro.', 'Sediei as Copas de 1970 e 1986, as duas ganhas pelo Brasil e pela Argentina.', 'Minha capital tem o mesmo nome do país.', 'Fico entre os Estados Unidos e a América Central.',
    ] },
    { answer: 'Espanha', clues: [
      'Fui ocupada pelos mouros por quase 800 anos.', 'Minha reconquista terminou em 1492, com a queda de Granada.', 'No mesmo ano financiei a viagem de Cristóvão Colombo.', 'Meus reis católicos eram Fernando e Isabel.',
      'Tive uma guerra civil entre 1936 e 1939.', 'Fui governada por Franco até 1975.', 'Voltei a ser monarquia parlamentar depois disso.', 'Tenho regiões que falam catalão, basco e galego.',
      'A Catalunha tentou se separar de mim num referendo em 2017.', 'Meu arquiteto mais famoso deixou uma igreja inacabada em Barcelona.', 'Esse arquiteto é Antoni Gaudí, e a igreja é a Sagrada Família.', 'Meus pintores incluem Velázquez, Goya, Picasso e Dalí.',
      'Meu museu principal em Madri é o Prado.', 'Tenho uma festa em que touros correm pelas ruas de Pamplona.', 'Meu prato mais conhecido leva arroz e açafrão.', 'Esse prato é a paella.',
      'Ganhei a Copa do Mundo de 2010.', 'Meus clubes de futebol incluem Real Madrid e Barcelona.', 'Minha capital é Madri.', 'Divido a Península Ibérica com Portugal.',
    ] },
    { answer: 'Canadá', clues: [
      'Meu nome vem de uma palavra indígena que significa "aldeia".', 'Fui disputada entre franceses e ingleses no século 18.', 'Virei confederação em 1º de julho de 1867.', 'Ainda tenho o rei do Reino Unido como chefe de Estado formal.',
      'Tenho duas línguas oficiais.', 'Uma das minhas províncias fala francês e já tentou se separar duas vezes.', 'Essa província é o Quebec.', 'Sou o segundo maior país do mundo em área.',
      'Faço a maior fronteira terrestre não militarizada do planeta.', 'Meu vizinho do sul são os Estados Unidos.', 'Minha polícia montada usa casaco vermelho e chapéu de aba larga.', 'Produzo quase todo o xarope de bordo do mundo.',
      'Meu esporte nacional de inverno é o hóquei no gelo.', 'Divido umas cataratas enormes com meu vizinho.', 'Essas cataratas são as do Niágara.', 'Minhas cidades principais são Toronto, Montreal e Vancouver.',
      'Minha capital é Ottawa.', 'Minha bandeira é vermelha e branca com uma folha no meio.', 'Faz muito frio aqui no inverno.', 'Sou o país da folha de bordo, acima dos Estados Unidos.',
    ] },
    { answer: 'África do Sul', clues: [
      'Fui colonizada por holandeses a partir de 1652.', 'Meus colonos holandeses foram chamados de bôeres.', 'Os ingleses me tomaram e travaram duas guerras contra os bôeres.', 'Tenho 11 línguas oficiais.',
      'Uma das minhas línguas, o africâner, veio do holandês.', 'Instituí um sistema oficial de segregação racial em 1948.', 'Esse sistema se chama apartheid.', 'Meu maior líder da resistência ficou 27 anos preso.',
      'Esse líder é Nelson Mandela.', 'Fiz minhas primeiras eleições livres em 1994.', 'Sou chamada de "nação arco-íris".', 'Tenho três capitais: Pretória, Cidade do Cabo e Bloemfontein.',
      'Tenho uma montanha de topo plano sobre uma cidade litorânea.', 'Essa montanha é a Table Mountain, na Cidade do Cabo.', 'Meu parque nacional Kruger é famoso pelos safáris.', 'Sou grande produtora de ouro e diamantes.',
      'Sediei a Copa do Mundo de 2010.', 'A vuvuzela ficou famosa nessa Copa.', 'Fico na ponta sul do meu continente.', 'Meu nome já diz onde fico no mapa da África.',
    ] },
    { answer: 'Rússia', clues: [
      'Comecei como um principado em Kiev, no século 9.', 'Fui invadida pelos mongóis no século 13.', 'Pedro, o Grande, me modernizou e fundou uma cidade nova no Báltico.', 'Essa cidade é São Petersburgo.',
      'Catarina, a Grande, expandiu meu território no século 18.', 'Derrotei Napoleão em 1812 usando o inverno a meu favor.', 'Minha revolução de 1917 derrubou o czar Nicolau II.', 'Virei o centro de um bloco chamado União Soviética.',
      'Perdi cerca de 25 milhões de pessoas na Segunda Guerra.', 'Coloquei o primeiro satélite e o primeiro homem no espaço.', 'Meu cosmonauta pioneiro foi Yuri Gagarin.', 'Meu bloco se desfez em 1991.',
      'Sou o maior país do mundo em área.', 'Tenho 11 fusos horários.', 'Minha bebida típica é a vodca e meu prato inclui o borscht.', 'Minha praça principal tem uma igreja de cúpulas coloridas.',
      'Essa praça é a Vermelha e a igreja é a Catedral de São Basílio.', 'Meu palácio-governo se chama Kremlin.', 'Minha capital é Moscou.', 'Sou o país gigante entre a Europa e a Ásia.',
    ] },
    { answer: 'China', clues: [
      'Minha civilização tem mais de quatro mil anos.', 'Fui unificada pelo primeiro imperador em 221 a.C.', 'Esse imperador foi enterrado com um exército de terracota.', 'Inventei o papel, a pólvora, a bússola e a imprensa.',
      'Perdi Hong Kong para os ingleses numa guerra por causa do ópio.', 'Minha revolução comunista venceu em 1949.', 'Meu líder revolucionário foi Mao Tsé-Tung.', 'Abri minha economia a partir de 1978, com Deng Xiaoping.',
      'Tive uma política que limitava as famílias a um filho só.', 'Recuperei Hong Kong em 1997.', 'Sediei as Olimpíadas de 2008.', 'A pandemia de covid-19 começou na minha cidade de Wuhan.',
      'Sou o país mais populoso ou o segundo, disputando com a Índia.', 'Tenho a maior fabricação industrial do planeta.', 'Meu animal símbolo é o panda.', 'Tenho uma muralha gigantesca no norte.',
      'Minha praça principal em Pequim é a Tiananmen.', 'Minha capital é Pequim e minha maior cidade é Xangai.', 'Minha comida usa muito arroz e é comida com hashi.', 'Sou o país asiático da Muralha e do panda.',
    ] },
    { answer: 'Chile', clues: [
      'Fui colonizada pelos espanhóis a partir de 1541.', 'Meu povo mapuche resistiu à colonização por séculos.', 'Bernardo O\'Higgins é meu libertador.', 'Elegi um presidente socialista em 1970.',
      'Esse presidente foi Salvador Allende.', 'Sofri um golpe militar em 11 de setembro de 1973.', 'Meu ditador governou até 1990.', 'Esse ditador foi Augusto Pinochet.',
      'Tenho dois Prêmios Nobel de Literatura: Gabriela Mistral e Pablo Neruda.', 'Sou o maior produtor de cobre do mundo.', 'Resgatei 33 mineiros presos a 700 metros de profundidade em 2010.', 'Tenho o deserto mais seco do planeta no meu norte.',
      'Esse deserto é o Atacama.', 'Tenho geleiras e fiordes no extremo sul, na Patagônia.', 'Sou muito comprida e muito estreita.', 'Tenho mais de 4 mil quilômetros de norte a sul.',
      'A Cordilheira dos Andes me separa da Argentina.', 'Sou dona da Ilha de Páscoa.', 'Minha capital é Santiago.', 'Sou o país fino e comprido do lado do Pacífico.',
    ] },
    { answer: 'Monte Everest', clues: [
      'Fui medido pela primeira vez em 1856, numa expedição britânica.', 'Meu nome ocidental homenageia um topógrafo inglês.', 'Os tibetanos me chamam de Chomolungma.', 'Os nepaleses me chamam de Sagarmatha.',
      'Fico na fronteira entre dois países.', 'Esses países são o Nepal e a China (Tibete).', 'Faço parte da cordilheira do Himalaia.', 'Cresço alguns milímetros por ano por causa do choque de placas tectônicas.',
      'Acima de 8 mil metros existe uma faixa apelidada de "zona da morte".', 'Meu acampamento-base fica a cerca de 5.300 metros.', 'A maioria dos escaladores precisa de oxigênio engarrafado.', 'Os guias sherpas carregam quase todo o equipamento.',
      'Fui escalado pela primeira vez em 1953.', 'Os primeiros a chegar ao meu topo foram Edmund Hillary e Tenzing Norgay.', 'Mais de 300 pessoas já morreram tentando me subir.', 'Tenho um problema sério de lixo deixado pelas expedições.',
      'Tenho 8.849 metros de altura.', 'Formam-se filas na minha última subida em dias de bom tempo.', 'Sou a montanha mais alta do mundo.', 'Meu nome tem "Monte" na frente e começa com E.',
    ] },
    { answer: 'Vaticano', clues: [
      'Fico numa colina onde antes havia um circo romano.', 'A tradição diz que o apóstolo Pedro foi enterrado aqui.', 'Fui território dos Estados Pontifícios até 1870.', 'Virei um Estado independente em 1929, por um tratado com a Itália.',
      'Esse tratado é o de Latrão, assinado com Mussolini.', 'Tenho pouco mais de 800 habitantes.', 'Minha guarda usa uniforme colorido e é formada por suíços.', 'Emito meus próprios selos, moedas e placas de carro.',
      'Tenho a maior igreja católica do mundo.', 'Michelangelo projetou a cúpula dessa igreja.', 'Michelangelo também pintou o teto de uma capela minha.', 'Essa capela é a Sistina.',
      'Meus cardeais se trancam nessa capela para escolher o novo líder.', 'Uma fumaça branca anuncia a escolha.', 'Minha praça em forma de elipse foi projetada por Bernini.', 'Minha basílica é a de São Pedro.',
      'Sou o menor país do mundo.', 'Fico inteiramente dentro de Roma.', 'Meu chefe de Estado é o Papa.', 'Sou a sede da Igreja Católica.',
    ] },
    { answer: 'Times Square', clues: [
      'Antes de 1904 eu me chamava Longacre Square.', 'Mudei de nome quando um jornal mudou sua sede para cá.', 'Esse jornal é o The New York Times.', 'Ganhei minha primeira propaganda luminosa em 1904.',
      'Fiquei decadente e perigosa nos anos 70 e 80.', 'Fui "limpa" nos anos 90, na gestão do prefeito Giuliani.', 'Existem regras que obrigam meus prédios a ter painéis luminosos.', 'Recebo cerca de 300 mil pessoas por dia.',
      'Tenho um degrau vermelho onde todo mundo senta para tirar foto.', 'Meus artistas de rua se fantasiam de personagens para cobrar por fotos.', 'Tenho um cruzamento em X entre duas avenidas.', 'Essas avenidas são a Broadway e a Sétima.',
      'Sou o coração do distrito dos teatros musicais.', 'Uma foto famosa de 1945 mostra um marinheiro beijando uma enfermeira aqui.', 'Todo 31 de dezembro uma bola de cristal desce aqui na virada.', 'Sou apelidada de "a encruzilhada do mundo".',
      'Fico no bairro de Manhattan.', 'Sou coberta de telões e letreiros de neon.', 'Fico em Nova York.', 'Meu nome tem o nome de um jornal e a palavra "praça" em inglês.',
    ] },
    { answer: 'Estátua da Liberdade', clues: [
      'Fui uma ideia do jurista francês Édouard de Laboulaye.', 'Fui um presente da França para marcar 100 anos de uma independência.', 'Meu escultor foi Frédéric Auguste Bartholdi.', 'Minha estrutura interna de ferro foi projetada por Gustave Eiffel.',
      'Fui montada em Paris, desmontada em 350 peças e enviada de navio.', 'Fui inaugurada em 28 de outubro de 1886.', 'Sou feita de placas de cobre.', 'Era marrom no começo e fiquei verde pela oxidação.',
      'Meu nome oficial é "A Liberdade Iluminando o Mundo".', 'Tenho 7 pontas na coroa, uma para cada continente e mar.', 'Meu pedestal foi pago por uma campanha popular num jornal.', 'Seguro uma tábua com a data 4 de julho de 1776.',
      'Tenho correntes quebradas aos meus pés.', 'Fui o primeiro símbolo que os imigrantes viam ao chegar de navio.', 'Fico numa ilha perto da Ellis Island.', 'Levanto uma tocha com o braço direito.',
      'Meço 93 metros com o pedestal.', 'Sou Patrimônio Mundial da Unesco desde 1984.', 'Fico em Nova York.', 'Sou a estátua verde com coroa e tocha.',
    ] },
    { answer: 'Coliseu', clues: [
      'Fui construído no lugar de um lago do palácio de Nero.', 'Comecei a ser erguido no ano 72, pelo imperador Vespasiano.', 'Fui inaugurado em 80 d.C. com 100 dias de jogos.', 'Meu nome oficial é Anfiteatro Flaviano.',
      'Meu apelido vem de uma estátua colossal que ficava ao lado.', 'Cabiam entre 50 e 80 mil pessoas nas minhas arquibancadas.', 'Tinha um toldo gigante manobrado por marinheiros para dar sombra.', 'Embaixo da minha arena havia túneis e elevadores para animais.',
      'Esses subterrâneos se chamam hipogeu.', 'Meus espetáculos incluíam caçadas a feras e execuções.', 'Meus lutadores mais famosos eram os gladiadores.', 'Deixei de ser usado para jogos no século 6.',
      'Fui usado como pedreira na Idade Média, e daí vem parte das minhas ruínas.', 'Terremotos derrubaram todo o meu lado sul.', 'Fui eleito uma das Sete Maravilhas do Mundo Moderno em 2007.', 'Sou iluminado quando uma pena de morte é revogada em algum país.',
      'Sou o maior anfiteatro já construído.', 'Sou o símbolo mais famoso do Império Romano.', 'Fico em Roma.', 'Sou a arena redonda em ruínas onde lutavam os gladiadores.',
    ] },
    { answer: 'Chapada Diamantina', clues: [
      'Ganhei fama no século 19 por causa do garimpo.', 'Meu nome vem das pedras preciosas encontradas nos meus rios.', 'Minhas cidades históricas nasceram do garimpo, como Lençóis e Mucugê.', 'O garimpo acabou quando descobriram diamantes na África do Sul.',
      'Virei parque nacional em 1985.', 'Meu parque tem mais de 150 mil hectares.', 'Meu relevo é feito de serras antigas e chapadas de arenito.', 'Tenho grutas com águas azuis iluminadas pelo sol do meio-dia.',
      'Uma dessas grutas é o Poço Azul.', 'Tenho uma caverna gigante chamada Gruta da Lapa Doce.', 'Tenho um morro que parece uma pedra deitada e é ponto de trilha.', 'Meu vale mais famoso se percorre em três dias de caminhada.',
      'Esse vale é o Vale do Pati.', 'Tenho uma das cachoeiras mais altas do Brasil, com quase 380 metros.', 'Essa cachoeira é a Cachoeira da Fumaça.', 'Meu morro em forma de mesa se chama Morro do Pai Inácio.',
      'Sou destino de trekking, rapel e banho de cachoeira.', 'Fico no centro de um estado do Nordeste.', 'Fico na Bahia.', 'Meu nome tem "Chapada" e o nome de uma pedra preciosa.',
    ] },
    { answer: 'Porto de Galinhas', clues: [
      'Meu nome vem de um tempo em que o tráfico de escravizados já era proibido.', 'Contam que os traficantes avisavam a chegada dizendo que havia "galinhas novas".', 'Essas "galinhas" eram angolanas, uma espécie de ave da região.', 'Eu era uma vila de pescadores até os anos 90.',
      'Minhas jangadas coloridas levam turistas até o mar.', 'Minha maré baixa é o momento certo do passeio.', 'Formo piscinas naturais de água morna nos recifes.', 'Os peixes coloridos comem na mão dos visitantes.',
      'Tenho estátuas de galinhas coloridas espalhadas pelas ruas.', 'Minhas ruas centrais são de areia e cheias de lojinhas.', 'Já fui eleita várias vezes a melhor praia do Brasil por uma revista de turismo.', 'Perto de mim ficam as praias de Maracaípe e Cupe.',
      'Maracaípe é point de surfe e tem um projeto de proteção de cavalos-marinhos.', 'Fico no município de Ipojuca.', 'Fico a cerca de 60 km de Recife.', 'Meus resorts all inclusive são muito procurados por famílias.',
      'Sou um dos destinos mais vendidos do turismo brasileiro.', 'Fico no litoral sul de Pernambuco.', 'Sou famosa pelas piscinas naturais e pelas jangadas.', 'Meu nome tem "Porto" e o nome de um bicho de galinheiro.',
    ] },
    { answer: 'Antártica', clues: [
      'Fui avistada pela primeira vez em 1820.', 'Meu nome vem do grego e significa "oposto ao Ártico".', 'Amundsen chegou ao meu polo em dezembro de 1911.', 'Scott chegou 34 dias depois e morreu na volta.',
      'Shackleton naufragou aqui e salvou toda a tripulação.', 'Sou governada por um tratado internacional assinado em 1959.', 'Esse tratado proíbe atividade militar e mineração aqui.', 'Não tenho população nativa nem governo próprio.',
      'Só vivem aqui cientistas em bases de pesquisa.', 'O Brasil tem uma base chamada Comandante Ferraz.', 'Registrei a temperatura mais baixa da Terra: -89 °C.', 'Guardo cerca de 70% de toda a água doce do planeta.',
      'Sou tecnicamente um deserto, porque quase não chove aqui.', 'Meu gelo tem, em média, quase 2 km de espessura.', 'Tenho um buraco na camada de ozônio acima de mim.', 'Meus animais mais famosos são pinguins e focas.',
      'No verão o sol não se põe aqui.', 'Sou o continente mais frio, seco e ventoso.', 'Fico no extremo sul do planeta.', 'Sou o continente do Polo Sul.',
    ] },
  ],
};

module.exports = { CARDS6 };
