// Lote 12 do Perfil — Pessoas (famosos atuais, internet e personagens). Cada carta: resposta + 20 dicas.
const CARDS12 = {
  P: [
    { answer: 'Dua Lipa', clues: [
      'Nasci em Londres, em 1995, filha de pais albaneses do Kosovo.', 'Meu nome significa "amor" em albanês.', 'Morei no Kosovo na adolescência e voltei sozinha para Londres aos 15 anos.', 'Trabalhei como modelo e garçonete antes da música.',
      'Meu pai era vocalista de uma banda de rock no Kosovo.', 'Meu primeiro disco saiu em 2017.', 'Ganhei o Grammy de artista revelação em 2019.', 'Meu segundo disco resgatou o som disco dos anos 70 e 80.',
      'Esse disco é "Future Nostalgia", lançado no começo da pandemia.', 'Minha música "New Rules" tem uma coreografia num hotel.', 'Minhas músicas incluem "Don\'t Start Now" e "Levitating".', 'Fiz uma participação no filme "Barbie" como uma sereia.',
      'Cantei "Dance the Night" na trilha da Barbie.', 'Tenho um clube do livro e um podcast.', 'Meu disco de 2024 se chama "Radical Optimism".', 'Fiz shows no Rock in Rio e no Lollapalooza Brasil.',
      'Sou noiva do ator Callum Turner.', 'Sou uma cantora pop britânica de voz grave.', 'Meu nome e sobrenome têm três letras e quatro letras.', 'Meu primeiro nome quer dizer "amor".',
    ] },
    { answer: 'Billie Eilish', clues: [
      'Nasci em Los Angeles, em 2001.', 'Fui educada em casa, sem escola.', 'Meu irmão produz todas as minhas músicas no quarto dele.', 'Meu irmão se chama Finneas.',
      'Gravei minha primeira música aos 13 anos para uma aula de dança.', 'Essa música é "Ocean Eyes".', 'Meu primeiro disco saiu em 2019, quando eu tinha 17 anos.', 'Ganhei os quatro principais Grammys numa noite só, em 2020.',
      'Fui a pessoa mais jovem a conseguir isso.', 'Sussurro em vez de gritar nas minhas músicas.', 'Usava roupas enormes para ninguém comentar meu corpo.', 'Tinha o cabelo verde e preto no auge da fama.',
      'Cantei o tema de um filme de James Bond e ganhei um Oscar por ele.', 'Ganhei meu segundo Oscar pela música do filme "Barbie".', 'Minha música mais famosa tem um "duh" no refrão.', 'Essa música é "Bad Guy".',
      'Meu disco de 2024 se chama "Hit Me Hard and Soft".', 'Minha música "Birds of a Feather" virou hit tardio.', 'Sou uma cantora americana de pop sombrio.', 'Meu nome tem "Billie" e um sobrenome irlandês.',
    ] },
    { answer: 'Dwayne Johnson', clues: [
      'Nasci na Califórnia, em 1972, com sangue samoano e afro-canadense.', 'Meu pai e meu avô foram lutadores de luta livre.', 'Joguei futebol americano na Universidade de Miami e fui campeão.', 'Não consegui entrar na NFL e fui jogar no Canadá.',
      'Fui cortado do time canadense com 7 dólares no bolso.', 'Entrei na WWE nos anos 90 e virei o maior campeão da época.', 'Meu bordão era "consegue sentir o cheiro do que eu estou cozinhando?".', 'Levantava a sobrancelha como marca registrada.',
      'Meu primeiro grande filme foi "O Escorpião Rei".', 'Fui o ator mais bem pago do mundo várias vezes.', 'Entrei na franquia "Velozes e Furiosos" como o agente Hobbs.', 'Dublei o semideus Maui em "Moana".',
      'Fiz "Jumanji" e "Adão Negro".', 'Tenho uma marca de tequila.', 'Acordo às 4 da manhã para treinar e como panquecas gigantes no "cheat day".', 'Sou dono de uma liga de futebol americano.',
      'Sou careca e tenho uma tatuagem samoana enorme no braço.', 'Meu apelido vem de uma pedra.', 'Sou o ator e lutador conhecido como "The Rock".', 'Meu primeiro nome é Dwayne.',
    ] },
    { answer: 'Keanu Reeves', clues: [
      'Nasci em Beirute, no Líbano, em 1964.', 'Meu nome significa "brisa fresca sobre as montanhas" em havaiano.', 'Cresci no Canadá e queria ser jogador de hóquei.', 'Fiquei famoso jovem em "Bill & Ted".',
      'Fiz um policial surfista em "Caçadores de Emoção".', 'Dirigi um ônibus que não podia parar em "Velocidade Máxima".', 'Perdi meu melhor amigo, River Phoenix, em 1993.', 'Perdi uma filha e depois a namorada num acidente de carro.',
      'Sou conhecido por ser gentil com fãs e dar dinheiro para a equipe dos filmes.', 'Uma foto minha triste comendo num banco virou meme.', 'Toco baixo numa banda chamada Dogstar.', 'Tenho uma marca de motos.',
      'Tomei a pílula vermelha e descobri que o mundo era uma simulação.', 'Fui o Neo em "Matrix".', 'Voltei a matar centenas de pessoas para vingar meu cachorro.', 'Fui o John Wick.',
      'Dublei o Shadow no filme "Sonic 3".', 'Namoro a artista Alexandra Grant, de cabelo grisalho.', 'Sou o ator canadense mais querido da internet.', 'Meu primeiro nome é havaiano e começa com K.',
    ] },
    { answer: 'Zendaya', clues: [
      'Nasci em Oakland, na Califórnia, em 1996.', 'Meu nome vem de uma palavra shona que significa "agradecer".', 'Comecei como modelo e dançarina de fundo em comerciais.', 'Fiquei famosa numa série do Disney Channel.',
      'Essa série é "No Ritmo", com Bella Thorne.', 'Fiz uma personagem drogada numa série adulta da HBO.', 'Essa série é "Euphoria".', 'Ganhei o Emmy de melhor atriz duas vezes por ela.',
      'Fui a mais jovem a ganhar esse prêmio.', 'Fiz a MJ nos filmes do Homem-Aranha.', 'Namoro o Homem-Aranha na vida real.', 'Meu namorado é Tom Holland.',
      'Fiz a heroína Fremen Chani em "Duna".', 'Fiz uma tenista num triângulo amoroso no filme "Rivais".', 'Fiz a trapezista em "O Rei do Show".', 'Sou famosa pelos looks de tapete vermelho.',
      'Meu estilista Law Roach transforma cada estreia num desfile.', 'Uso só um nome, sem sobrenome.', 'Sou atriz e cantora americana.', 'Meu nome tem sete letras e começa com Z.',
    ] },
    { answer: 'Timothée Chalamet', clues: [
      'Nasci em Nova York, em 1995, filho de pai francês.', 'Tenho dupla cidadania e falo francês fluente.', 'Estudei na mesma escola de artes da Nicki Minaj e da Ansel Elgort.', 'Fui indicado ao Oscar aos 22 anos por um romance na Itália.',
      'Esse filme é "Me Chame pelo Seu Nome".', 'Fui o Laurie em "Adoráveis Mulheres".', 'Fiz um adolescente viciado em "Beautiful Boy".', 'Fui o Paul Atreides em "Duna".',
      'Fiz o Willy Wonka jovem em "Wonka".', 'Interpretei Bob Dylan e cantei de verdade no filme.', 'Esse filme é "Um Completo Desconhecido".', 'Apareci de surpresa num concurso de sósias meus em Nova York.',
      'Namoro Kylie Jenner.', 'Sou conhecido pelos cabelos cacheados e pelo estilo nos tapetes vermelhos.', 'Uso ternos brilhantes e roupas sem camisa por baixo.', 'Ganhei o SAG Award de melhor ator em 2025.',
      'Sou o galã da minha geração, segundo a internet.', 'Sou ator americano-francês.', 'Meu primeiro nome é Timothée, com acento.', 'Meu sobrenome começa com Ch.',
    ] },
    { answer: 'Sabrina Carpenter', clues: [
      'Nasci na Pensilvânia, em 1999.', 'Comecei postando covers no YouTube aos 10 anos.', 'Fiquei famosa numa série do Disney Channel.', 'Essa série é "Girl Meets World".',
      'Lancei quatro discos antes de explodir de verdade.', 'Abri os shows da Eras Tour da Taylor Swift.', 'Estourei em 2024 com uma música sobre café.', 'Essa música é "Espresso".',
      'Emendei com "Please Please Please" e "Taste".', 'Ganhei dois Grammys em 2025.', 'Meu disco de 2024 se chama "Short n\' Sweet".', 'Meu disco de 2025 se chama "Man\'s Best Friend".',
      'Improviso uma frase diferente de "Nonsense" em cada show.', 'Minhas letras são cheias de duplo sentido.', 'Tenho 1,52 m e brinco com isso o tempo todo.', 'Meu ex-namorado é o ator Barry Keoghan.',
      'Fiz show no Lollapalooza Brasil em 2025.', 'Uso cabelo loiro com franja e vestidos curtos.', 'Sou uma cantora pop americana baixinha.', 'Meu sobrenome é a profissão de quem trabalha com madeira, em inglês.',
    ] },
    { answer: 'Luísa Sonza', clues: [
      'Nasci em Tuparendi, no interior do Rio Grande do Sul, em 1998.', 'Comecei cantando em casamentos com 7 anos.', 'Postava covers na internet antes da fama.', 'Fui casada com um youtuber humorista.',
      'Esse humorista é Whindersson Nunes.', 'Meu primeiro disco se chama "Pandora".', 'Fiz sucesso com "Braba" e "Anaconda".', 'Cantei "Cachorrinhas" e "Chico".',
      'A música "Chico" era sobre um namorado influenciador que me traiu.', 'Fiz um disco em que cada faixa era um capítulo de uma história.', 'Esse disco se chama "Escândalo Íntimo".', 'Fiz uma parceria com a Demi Lovato.',
      'Fui técnica do programa "The Voice+" na Globo.', 'Fiz feat com Pabllo Vittar e Anitta.', 'Falo abertamente sobre o Rio Grande do Sul e fiz show beneficente na enchente.', 'Tenho cabelo loiro e vim do interior gaúcho.',
      'Sou amiga do cantor Jão e já fiz música com ele.', 'Sou cantora pop brasileira.', 'Meu sobrenome tem cinco letras e começa com S.', 'Meu primeiro nome tem acento no i.',
    ] },
    { answer: 'Ludmilla', clues: [
      'Nasci em Duque de Caxias, no Rio de Janeiro, em 1995.', 'Comecei cantando funk com outro nome artístico.', 'Esse nome era MC Beyoncé, e tive que trocar por questões legais.', 'Meu primeiro hit foi "Fala Mal de Mim", em 2012.',
      'Cantei "Hoje" e "Cheguei".', 'Fui a primeira mulher negra a atingir 1 bilhão de streams no Spotify na América Latina.', 'Fiz um projeto de pagode chamado "Numanice".', 'Nele canto músicas românticas em rodas de samba.',
      'Sou casada com uma dançarina que era do meu balé.', 'Minha esposa é a Brunna Gonçalves.', 'Tivemos uma filha por fertilização em 2025.', 'Fiz a música "Maldivas" e "Rainha da Favela".',
      'Fui a primeira brasileira a se apresentar no palco principal do Coachella.', 'Beijei minha esposa no palco do Coachella.', 'Sou conhecida pelas perucas coloridas e cabelos longos.', 'Já briguei publicamente com Anitta.',
      'Fui indicada ao Grammy Latino várias vezes.', 'Sou cantora de funk, pop e pagode.', 'Meu nome tem oito letras e começa com L.', 'Sou a cantora do "Numanice".',
    ] },
    { answer: 'Pabllo Vittar', clues: [
      'Nasci em São Luís, no Maranhão, em 1994.', 'Cresci em Santa Inês, criado pela mãe.', 'Meu nome artístico usa dois L.', 'Comecei a cantar em bares e barzinhos de Uberlândia.',
      'Fiquei famoso com um cover de "Lean On" da Major Lazer.', 'Fiz "Corpo Sensual" e "K.O.".', 'Cantei "Sua Cara" com Anitta e Major Lazer.', 'Meu clipe de "Sua Cara" foi gravado no deserto de Marrocos.',
      'Fui a primeira drag queen indicada ao Grammy Latino.', 'Fui a drag queen mais seguida do mundo nas redes.', 'Fiz feat com Charli XCX e Rina Sawayama.', 'Fiz um disco de forró e brega chamado "Batidão Tropical".',
      'Já cantei no Coachella.', 'Sou conhecido pelas pernas e pelos figurinos de show.', 'Sou embaixador do Prêmio Multishow.', 'Tenho um irmão gêmeo que não é famoso.',
      'Sou drag queen e cantor.', 'Meu nome artístico tem Pabllo com dois L.', 'Meu sobrenome artístico é Vittar.', 'Sou a drag queen mais famosa do Brasil.',
    ] },
    { answer: 'Felipe Neto', clues: [
      'Nasci no Rio de Janeiro, em 1988.', 'Comecei no YouTube em 2010 com vídeos de opinião.', 'Meu primeiro canal se chamava "Não Faz Sentido".', 'Fundei uma empresa de canais chamada Paramaker.',
      'Mudei o estilo e virei o youtuber das crianças, com vídeos de brincadeiras e reações.', 'Já fui o brasileiro com mais inscritos no YouTube.', 'Tenho mais de 40 milhões de inscritos.', 'Fui capa da revista Time em 2020 como uma das pessoas mais influentes.',
      'Doei respiradores para hospitais na pandemia.', 'Fui perseguido por políticos e virei ativista contra a extrema direita.', 'Distribuí livros que a censura de Rio tentava tirar de uma bienal.', 'Meu irmão Luccas Neto também é youtuber.',
      'Ele faz vídeos infantis e lotava cinema com filmes próprios.', 'Fui dono de um time de eSports.', 'Tenho um sotaque carioca bem forte e fala rápida.', 'Faço "reacts" de vídeos de outros criadores.',
      'Sou um dos maiores youtubers do Brasil.', 'Meu sobrenome é Neto.', 'Meu irmão também tem o sobrenome Neto e faz vídeo infantil.', 'Meu primeiro nome começa com F.',
    ] },
    { answer: 'Casimiro', clues: [
      'Nasci no Rio de Janeiro, em 1993.', 'Trabalhei na redação do site do Esporte Interativo.', 'Comecei a fazer lives na Twitch em 2020, durante a pandemia.', 'Reagia a vídeos de futebol e a telejornais antigos.',
      'Meu grito de gol virou som de meme.', 'Fiz a live mais assistida da Twitch no Brasil em 2021.', 'Meu bordão é "CAZÉ!".', 'Meu canal se chama CazéTV.',
      'Transmiti a Copa do Mundo de 2022 e as Olimpíadas de 2024 de graça no YouTube.', 'Bati recordes mundiais de audiência no YouTube com esses jogos.', 'Transmiti o Mundial de Clubes de 2025.', 'Sou torcedor do Vasco e sofro em público.',
      'Meu apelido no corte de cabelo era "cortes do Casimiro".', 'Minha live enche de comentaristas e ex-jogadores convidados.', 'Sou conhecido por comer na live e falar de futebol.', 'Meu cabelo é grande e encaracolado, e minha barba também.',
      'Sou o streamer de futebol mais famoso do Brasil.', 'Meu nome artístico é o meu primeiro nome.', 'Meu nome tem oito letras e começa com C.', 'Sou o dono da CazéTV.',
    ] },
    { answer: 'Ana Maria Braga', clues: [
      'Nasci em São Joaquim da Barra, em São Paulo, em 1949.', 'Sou formada em Biologia.', 'Comecei na TV como locutora de publicidade.', 'Trabalhei na Record com o programa "Note e Anote".',
      'Fui para a Globo em 1999.', 'Apresento um programa matinal há mais de 25 anos.', 'Meu programa se chama "Mais Você".', 'Meu companheiro de bancada é um papagaio de pelúcia.',
      'Esse papagaio se chama Louro José e "morreu" em 2020 com o intérprete.', 'Ele foi substituído pelo filho, Louro Mané.', 'Já me fantasiei de Wandinha, de Marge Simpson e de Carmen Miranda ao vivo.', 'Já apareci vestida de Chapolin e de Gato de Botas.',
      'Já fiz gafes ao vivo que viraram memes, como "que isso, gente".', 'Já mostrei receitas e limpei fogão ao vivo.', 'Tive câncer de pulmão e falei sobre isso na TV.', 'Sou conhecida pelas roupas coloridas e pelo cabelo louro.',
      'Ganhei o apelido de "Namaria".', 'Casei aos 74 anos com um jornalista.', 'Sou apresentadora do café da manhã da Globo.', 'Meu nome tem Ana, Maria e Braga.',
    ] },
    { answer: 'Faustão', clues: [
      'Nasci em Campinas, em 1950.', 'Meu nome verdadeiro é Fausto Corrêa da Silva.', 'Comecei como repórter esportivo de rádio.', 'Fiz o programa "Perdidos na Noite" na Band.',
      'Fui para a Globo em 1989.', 'Meu programa dominical durou 32 anos.', 'Esse programa se chama "Domingão do Faustão".', 'Minha "Dança dos Famosos" revelou dançarinos e casais.',
      'Meu quadro de vídeos de acidentes se chamava "Vídeo Cassetadas".', 'Minha frase era "olha o que a natureza fez".', 'Meu bordão de rebolar era "se joga, minha filha".', 'Eu gritava "errou!" nos jogos com o público.',
      'Comia nas gravações e virou piada.', 'Saí da Globo em 2021 e fui para a Band.', 'Fiz um transplante de coração em 2023 e de rim em 2024.', 'Fiz um transplante de fígado em 2025.',
      'Sou apresentador de TV há mais de 50 anos.', 'Meu nome artístico é o meu nome com aumentativo.', 'Meu apelido termina em "ão".', 'Meu programa era o "Domingão".',
    ] },
    { answer: 'Rayssa Leal', clues: [
      'Nasci em Imperatriz, no Maranhão, em 2008.', 'Um vídeo meu aos 7 anos viralizou no mundo.', 'Nesse vídeo eu pulo uma escada vestida de fada com asinhas.', 'Tony Hawk compartilhou esse vídeo.',
      'Meu apelido vem dessa fantasia.', 'Sou chamada de "Fadinha".', 'Ganhei a prata em Tóquio 2020 com 13 anos.', 'Fui a medalhista mais jovem da história do Brasil.',
      'Ganhei o bronze em Paris 2024.', 'Já fui campeã mundial e da Liga Mundial de Street.', 'Meu skate é a modalidade "street", de rua.', 'Falo com sotaque maranhense forte e faço piada com isso.',
      'Já ganhei mais de 1 milhão de dólares em prêmios antes dos 16.', 'Meu ídolo é a Leticia Bufoni.', 'Sou patrocinada pela Nike e pela Monster.', 'Uso tranças coloridas e roupa larga.',
      'Sou skatista brasileira.', 'Sou a "Fadinha do skate".', 'Meu nome tem "Rayssa".', 'Meu sobrenome é Leal.',
    ] },
    { answer: 'Gabriel Medina', clues: [
      'Nasci em São Sebastião, no litoral de São Paulo, em 1993.', 'Comecei a competir com 9 anos.', 'Fui criado pelo padrasto, que era meu treinador.', 'Me tornei o primeiro brasileiro campeão mundial do meu esporte, em 2014.',
      'Ganhei mais dois títulos: 2018 e 2021.', 'Esse esporte é o surfe.', 'Vim de Maresias, praia famosa do litoral norte paulista.', 'Rompi com minha família por causa de um casamento e depois fizemos as pazes.',
      'Fui casado com a Yasmin Brunet.', 'Ganhei o bronze nas Olimpíadas de Paris 2024.', 'Minha foto flutuando no ar apontando para o céu viralizou em Paris.', 'Foi a foto mais famosa daquelas Olimpíadas.',
      'Tirei a maior nota da história olímpica: 9,90.', 'Sou o "Chosen One", como me chamaram no exterior.', 'Namoro a Isabella Arantes.', 'Sou tricampeão mundial de surfe.',
      'Meu apelido é "Gabi Medina".', 'Divido o topo do surfe brasileiro com Italo Ferreira e Filipe Toledo.', 'Sou surfista brasileiro.', 'Meu sobrenome é o nome de uma cidade sagrada do Islã.',
    ] },
    { answer: 'Marília Mendonça', clues: [
      'Nasci em Cristianópolis, em Goiás, em 1995.', 'Cresci em Goiânia.', 'Comecei escrevendo músicas para outros artistas aos 12 anos.', 'Compus para Cristiano Araújo e João Neto & Frederico.',
      'Meu primeiro DVD saiu em 2016.', 'Cantei "Infiel" e "Eu Sei de Cor".', 'Cantei "Todo Mundo Vai Sofrer".', 'Cantei "Graveto" e "Supera".',
      'Ganhei o Grammy Latino de melhor álbum sertanejo em 2019.', 'Fui a artista mais ouvida do Brasil no Spotify em 2019 e 2020.', 'Fiz lives gigantes durante a pandemia.', 'Formei o projeto "Patroas" com as gêmeas Maiara & Maraisa.',
      'Fui chamada de "Rainha da Sofrência".', 'Cantava sobre traição e ressaca de amor.', 'Tinha um filho pequeno chamado Léo.', 'Morri num acidente de avião em Minas Gerais, em novembro de 2021.',
      'Morri aos 26 anos e o país parou.', 'Meus discos póstumos continuam batendo recordes.', 'Sou a maior cantora sertaneja da história.', 'Meu nome tem Marília e Mendonça.',
    ] },
    { answer: 'Alok', clues: [
      'Nasci em Goiânia, em 1991.', 'Meus pais são DJs de música eletrônica psicodélica.', 'Tenho um irmão gêmeo chamado Bhaskar, que também é DJ.', 'Comecei a tocar aos 12 anos em festas dos meus pais.',
      'Meu nome significa "luz" em sânscrito.', 'Fiz sucesso mundial com "Hear Me Now".', 'Também fiz "Ocean" e "Never Let Me Go".', 'Sou o DJ brasileiro mais bem colocado no ranking mundial.',
      'Fiquei em 4º lugar no ranking da DJ Mag.', 'Toco em festivais como Tomorrowland e Lollapalooza.', 'Sou casado com a médica Romana Novais.', 'Tenho um instituto que doa milhões para projetos sociais.',
      'Fiz um show com música indígena e povos originários no Rock in Rio.', 'Fiz a música "Deep Down" e trilhas para a Fórmula 1.', 'Já toquei no palco de abertura de um Grammy Latino.', 'Uso cabelo comprido e roupas largas.',
      'Sou DJ e produtor de música eletrônica.', 'Meu nome tem quatro letras.', 'Meu nome começa com A e termina com K.', 'Sou o DJ brasileiro mais famoso do mundo.',
    ] },
    { answer: 'Jão', clues: [
      'Nasci em Américo Brasiliense, no interior de São Paulo, em 1994.', 'Meu nome completo é João Vitor Romania Balbino.', 'Comecei postando covers no YouTube.', 'Meu primeiro disco se chama "Lobos", de 2018.',
      'Meus discos seguintes são "Anti-Herói", "Pirata" e "SUPER".', 'Cantei "Vou Morrer Sozinho" e "Idiota".', 'Cantei "Me Lambe" e "Alinhamento Milenar".', 'Faço turnês com nomes como "Superturnê".',
      'Cantei no Rock in Rio, no Lollapalooza e lotei estádios.', 'Fiz feat com Anitta em "Pilantra".', 'Ganhei o Grammy Latino de melhor álbum pop em português.', 'Sou conhecido por chorar no palco e pelos shows teatrais.',
      'Meus fãs choram de emoção nos shows.', 'Uso terno, maquiagem e roupas de alfaiataria nos shows.', 'Sou amigo de Luísa Sonza.', 'Sou a maior estrela pop masculina do Brasil hoje.',
      'Meu nome artístico é uma abreviação do meu nome.', 'Meu nome tem três letras e um til.', 'Meu nome começa com J.', 'Sou cantor pop brasileiro.',
    ] },
    { answer: 'Ronaldinho Gaúcho', clues: [
      'Nasci em Porto Alegre, em 1980.', 'Cresci na Vila Nova, no bairro Cristal.', 'Meu pai morreu afogado na piscina de casa quando eu tinha 8 anos.', 'Meu irmão Assis também foi jogador.',
      'Fui revelado no Grêmio.', 'Ganhei apelido para diferenciar de outro Ronaldo da seleção.', 'Joguei no Paris Saint-Germain antes de estourar.', 'Fui campeão do mundo em 2002.',
      'Fiz um gol de falta por cobertura no goleiro Seaman na Copa de 2002.', 'Fui aplaudido de pé pela torcida do Real Madrid no Bernabéu.', 'Fui eleito melhor do mundo em 2004 e 2005.', 'Ganhei a Champions League pelo Barcelona em 2006.',
      'Ganhei a Libertadores pelo Atlético Mineiro em 2013.', 'Fiquei preso no Paraguai em 2020 por passaporte falso.', 'Sou conhecido pelo sorriso e pelo dente da frente.', 'Meu drible mais famoso é a "elástico".',
      'Joguei no Milan, no Flamengo e no Querétaro.', 'Sou o Ronaldinho que não é o Fenômeno.', 'Meu apelido diz de que estado eu sou.', 'Sou o Ronaldinho do sorriso.',
    ] },
    { answer: 'Pikachu', clues: [
      'Nasci em 1996, num jogo de Game Boy.', 'Meu nome mistura o som de faísca com o som de rato em japonês.', 'Sou o número 25 de uma lista de 151.', 'Não fui feito para ser o mascote, mas a série de TV me escolheu.',
      'Meu treinador na TV se chama Ash Ketchum.', 'Ele queria ser mestre e nunca me colocou numa bolinha.', 'Ando no ombro dele.', 'Sou do tipo elétrico.',
      'Guardo eletricidade nas bochechas vermelhas.', 'Meu rabo tem formato de raio.', 'Só falo meu próprio nome.', 'Evoluo com uma pedra do trovão.',
      'Minha evolução se chama Raichu.', 'Ryan Reynolds fez minha voz num filme de detetive.', 'Esse filme é "Detetive Pikachu".', 'Sou amarelo com pontas pretas nas orelhas.',
      'Meu golpe mais famoso é o choque do trovão.', 'Sou o Pokémon mais famoso do mundo.', 'Sou o rato elétrico amarelo.', 'Meu nome termina com "chu".',
    ] },
    { answer: 'Hello Kitty', clues: [
      'Nasci no Japão, em 1974, numa carteirinha de moedas.', 'Fui criada pela designer Yuko Shimizu para a empresa Sanrio.', 'Segundo minha empresa, eu não sou uma gata: sou uma menininha.', 'Moro em Londres, segundo minha biografia oficial.',
      'Tenho uma irmã gêmea chamada Mimmy.', 'Meu sobrenome oficial é White.', 'Não tenho boca.', 'Isso é para que cada pessoa projete a própria emoção em mim.',
      'Uso um laço vermelho na orelha esquerda.', 'Peso o mesmo que três maçãs.', 'Sou embaixadora oficial do turismo do Japão.', 'Tenho um parque temático em Tóquio chamado Puroland.',
      'Estampo desde lancheiras até aviões da EVA Air.', 'Minha marca fatura bilhões por ano só de licenças.', 'Completei 50 anos em 2024.', 'Sou branca com bigodes pretos.',
      'Meu nome tem "Olá" em inglês.', 'Sou a personagem japonesa mais fofa do mundo.', 'Meu nome tem "Kitty".', 'Sou a gatinha sem boca.',
    ] },
    { answer: 'Wolverine', clues: [
      'Apareci pela primeira vez numa revista do Hulk em 1974.', 'Sou canadense.', 'Nasci no século 19 e quase não envelheço.', 'Meu nome verdadeiro é James Howlett.',
      'Uso o nome Logan.', 'Tenho cura acelerada: qualquer ferida fecha em segundos.', 'Meu esqueleto foi coberto com um metal indestrutível numa experiência.', 'Esse metal é o adamantium.',
      'Tenho três garras em cada mão.', 'Sou baixinho nos quadrinhos, mas alto no cinema.', 'Meu ator me interpretou por 17 anos seguidos.', 'Esse ator é Hugh Jackman.',
      'Meu filme de despedida, "Logan", de 2017, fez todo mundo chorar.', 'Voltei em 2024 num filme com o Deadpool.', 'Usei o uniforme amarelo e azul pela primeira vez nesse filme.', 'Sou membro dos X-Men.',
      'Meu líder é o Professor Xavier.', 'Tenho costeletas e cabelo pontudo.', 'Sou o mutante das garras.', 'Meu nome é o de um animal parecido com um carcaju.',
    ] },
    { answer: 'Rihanna', clues: [
      'Nasci em Barbados, em 1988.', 'Meu nome verdadeiro é Robyn Rihanna Fenty.', 'Fui descoberta por um produtor de férias na minha ilha.', 'Assinei com a gravadora do Jay-Z aos 16 anos.',
      'Meu primeiro hit foi "Pon de Replay".', 'Minha música de guarda-chuva virou hino.', 'Essa música é "Umbrella".', 'Cantei "Diamonds", "We Found Love" e "Work".',
      'Sou embaixadora oficial de Barbados.', 'Fundei uma marca de maquiagem com 40 tons de base.', 'Essa marca é a Fenty Beauty.', 'Virei bilionária por causa dela, e não da música.',
      'Tenho uma marca de lingerie chamada Savage X Fenty.', 'Não lanço um disco desde 2016.', 'Meus fãs imploram por um disco novo há anos.', 'Cantei no Super Bowl de 2023 grávida.',
      'Tenho três filhos com o rapper A$AP Rocky.', 'Sou cantora e empresária de Barbados.', 'Meu nome tem sete letras e começa com R.', 'Sou a cantora do "Umbrella".',
    ] },
    { answer: 'Lewis Hamilton', clues: [
      'Nasci em Stevenage, na Inglaterra, em 1985.', 'Meu pai teve três empregos para pagar meu kart.', 'Sou o primeiro e único piloto negro da Fórmula 1.', 'Fui apoiado pela McLaren desde os 13 anos.',
      'Estreei na Fórmula 1 em 2007 e quase fui campeão no primeiro ano.', 'Ganhei meu primeiro título em 2008, na última curva da última corrida.', 'Fui para a Mercedes em 2013.', 'Ganhei seis títulos pela Mercedes.',
      'Sou heptacampeão, empatado com Michael Schumacher.', 'Perdi o oitavo título na última volta de 2021, em Abu Dhabi.', 'Sou vegano e ativista ambiental.', 'Tenho um buldogue chamado Roscoe que é famoso.',
      'Sou "Sir": fui condecorado cavaleiro pela rainha.', 'Uso o número 44.', 'Sou o piloto com mais vitórias da história da Fórmula 1.', 'Troquei a Mercedes pela Ferrari em 2025.',
      'Sou conhecido por looks de moda extravagantes no paddock.', 'Aparece no Met Gala todo ano.', 'Sou piloto britânico de Fórmula 1.', 'Meu nome tem "Lewis" e "Hamilton".',
    ] },
  ],
};

module.exports = { CARDS12 };
