// Lote 7 do Perfil — Coisas. Cada carta: resposta + 20 dicas (da mais difícil para a mais fácil).
const CARDS7 = {
  C: [
    { answer: 'Geladeira', clues: [
      'Antes de mim as pessoas usavam poços, neve e caixas com blocos de gelo.', 'Existia um comércio mundial de blocos de gelo cortados de lagos congelados.', 'O primeiro modelo doméstico elétrico apareceu em 1913.', 'A General Electric lançou um modelo popular em 1927.',
      'Funciono por compressão de um gás que evapora e esfria.', 'Meus primeiros gases eram tóxicos e às vezes matavam famílias dormindo.', 'Depois usaram CFC, que acabou proibido por destruir a camada de ozônio.', 'Meu motor fica atrás ou embaixo e esquenta.',
      'Meu barulhinho de vez em quando é o compressor ligando.', 'A parte de baixo é mais quente que a de cima.', 'Tenho uma borracha em volta da porta que precisa vedar direito.', 'Tenho um irmão menor e mais frio embutido em mim.',
      'Esse irmão é o freezer.', 'Alguns modelos meus soltam água pela porta.', 'Sou o eletrodoméstico que mais gasta energia numa casa comum.', 'Meu degelo automático virou padrão nos modelos "frost free".',
      'Sou coberta de ímãs de viagem e bilhetes.', 'Fico ligada 24 horas por dia, o ano inteiro.', 'Guardo comida para não estragar.', 'Sou o eletrodoméstico branco e alto da cozinha.',
    ] },
    { answer: 'Chuveiro elétrico', clues: [
      'Sou uma invenção quase exclusiva do Brasil.', 'Fui popularizado aqui a partir dos anos 40.', 'Quase não existo na Europa nem nos Estados Unidos.', 'Estrangeiros se assustam ao me ver e acham que vão tomar choque.',
      'Funciono com uma resistência de metal dentro de uma câmara.', 'A água passa direto pela resistência ligada na energia.', 'Preciso de um fio grosso e de um disjuntor só meu.', 'Sou uma das principais causas de pico de consumo no país no fim da tarde.',
      'Quando o registro está muito aberto, saio morno.', 'Tenho posições como inverno, verão e desligado.', 'Trocar minha resistência é um conserto barato e comum.', 'Uma resistência queimada faz a água sair fria de repente.',
      'Sou proibido em várias normas de outros países por questão de segurança.', 'Meus modelos novos têm controle eletrônico de temperatura.', 'A alternativa a mim é o aquecedor a gás.', 'Estou preso na parede acima da cabeça.',
      'Meu apelido é "chuveirinho" quando é o modelo simples.', 'Consumo muita eletricidade em pouco tempo.', 'Esquento a água na hora do banho.', 'Sou o chuveiro que funciona na tomada.',
    ] },
    { answer: 'Televisão', clues: [
      'Minha primeira demonstração pública foi feita por John Logie Baird em 1926.', 'Meus primeiros modelos usavam um disco giratório mecânico.', 'Depois passei a usar um tubo de raios catódicos.', 'Fui apresentada ao grande público na Feira Mundial de Nova York, em 1939.',
      'Cheguei ao Brasil em 1950, trazida por Assis Chateaubriand.', 'Minha primeira emissora brasileira foi a TV Tupi.', 'No começo tudo aqui era ao vivo, inclusive os comerciais.', 'Ganhei cores no Brasil em 1972.',
      'A primeira transmissão em cores no Brasil foi a Festa da Uva, em Caxias do Sul.', 'Meus modelos antigos eram enormes e pesadíssimos.', 'Fiquei fina quando surgiram o plasma e o LCD.', 'Meu sinal virou digital no Brasil a partir de 2007.',
      'Minha programação da tarde inventou um formato chamado novela.', 'Sou controlada por um aparelhinho que sempre some no sofá.', 'Ganhei aplicativos e virei "smart".', 'Já fui chamada de "babá eletrônica".',
      'Fico na sala, na frente do sofá.', 'Antes eu precisava de antena e de bater na lateral quando chiava.', 'Todo mundo se reúne em frente a mim para ver jogo.', 'Sou o aparelho que mostra imagem e som na sala.',
    ] },
    { answer: 'Computador', clues: [
      'Meu ancestral mecânico foi projetado por Charles Babbage no século 19.', 'Ada Lovelace escreveu o primeiro algoritmo pensando nessa máquina.', 'Alan Turing descreveu meu modelo teórico em 1936.', 'O ENIAC, de 1946, pesava 30 toneladas e ocupava uma sala inteira.',
      'Meus primeiros modelos usavam válvulas que queimavam toda hora.', 'O transístor e depois o chip me deixaram pequeno.', 'A Apple e a IBM me levaram para as casas nos anos 70 e 80.', 'Meu "cérebro" é o processador.',
      'Minha memória de trabalho se chama RAM e apaga quando desligo.', 'Guardo arquivos em disco rígido ou SSD.', 'Preciso de um sistema operacional para funcionar.', 'Os mais usados são Windows, macOS e Linux.',
      'Fico lento quando abro muitas abas.', 'Meu conserto mais famoso é desligar e ligar de novo.', 'Sou controlado por teclado e mouse.', 'Existo em versão de mesa e em versão portátil.',
      'A portátil se chama notebook ou laptop.', 'Sem mim não existiria internet nem trabalho de escritório moderno.', 'Trabalho com números em código binário, só zeros e uns.', 'Sou a máquina com tela, teclado e mouse.',
    ] },
    { answer: 'Livro', clues: [
      'Meus ancestrais foram tabuinhas de argila e rolos de papiro.', 'Os romanos me deram formato de páginas costuradas, chamado códice.', 'Na Idade Média eu era copiado à mão por monges.', 'Uma cópia minha podia custar o preço de uma casa.',
      'Gutenberg mudou tudo por volta de 1450.', 'Ele inventou os tipos móveis de metal.', 'O primeiro que ele imprimiu foi uma Bíblia.', 'Fiquei barato e a leitura deixou de ser privilégio.',
      'Fui censurado e queimado em várias ditaduras.', 'A Igreja mantinha uma lista dos que eram proibidos.', 'Minha versão eletrônica cabe num aparelhinho de tinta digital.', 'Tenho um código de barras chamado ISBN.',
      'Tenho lombada, orelha, capa e sumário.', 'A parte que quase ninguém lê é a das notas de rodapé.', 'Tenho tipos: romance, biografia, didático, infantil.', 'O mais vendido da história é a Bíblia.',
      'Sou guardado em prateleiras e em bibliotecas.', 'Muita gente compra e deixa parado na estante.', 'Sou feito de papel com páginas coladas ou costuradas.', 'Sou o objeto que se lê virando páginas.',
    ] },
    { answer: 'Elevador', clues: [
      'Arquimedes teria construído uma versão minha com cordas e polias.', 'Nos palácios antigos eu era puxado por escravizados ou animais.', 'Meu grande problema sempre foi a corda arrebentar.', 'Elisha Otis resolveu isso em 1853.',
      'Ele criou um freio de segurança e o demonstrou cortando a corda em público.', 'Sem essa invenção não existiriam arranha-céus.', 'O primeiro modelo comercial de passageiros foi instalado em Nova York em 1857.', 'Meus primeiros modelos eram movidos a vapor ou a água sob pressão.',
      'Antigamente tinha uma pessoa dentro de mim só para me operar.', 'Essa pessoa era o ascensorista.', 'Meu contrapeso sobe quando a cabine desce.', 'Tenho cabos de aço redundantes e freio de emergência.',
      'Tem prédio que pula o número 13 nos meus botões.', 'Minha música ambiente virou piada e ganhou até um nome de gênero.', 'Prédios antigos no Brasil tinham um só para "serviço".', 'Meu botão mais apertado sem função real é o de fechar a porta.',
      'Todo mundo fica em silêncio olhando para os números dentro de mim.', 'Alguns modelos meus são panorâmicos, com parede de vidro.', 'Sou obrigatório em prédios acima de certa altura.', 'Levo pessoas de um andar a outro.',
    ] },
    { answer: 'Metrô', clues: [
      'A primeira linha do mundo abriu em Londres em 1863.', 'Essa primeira linha era puxada por locomotivas a vapor, e era sufocante.', 'A eletrificação resolveu o problema da fumaça.', 'Meu nome vem de "metropolitano".',
      'Em Nova York me chamam de subway; em Londres, de tube.', 'Fui usado como abrigo antiaéreo em Londres na Segunda Guerra.', 'O mapa de Londres desenhado por Harry Beck virou modelo para todos.', 'Esse mapa não respeita distâncias reais, só a ordem das estações.',
      'A primeira linha brasileira abriu em São Paulo em 1974.', 'A linha azul de São Paulo foi a pioneira do país.', 'Também existo no Rio, em Brasília, Recife, Salvador, Belo Horizonte e Fortaleza.', 'Tenho catracas, bilhete e cartão recarregável.',
      'Em algumas cidades tenho vagão exclusivo para mulheres.', 'Minha porta abre dos dois lados dependendo da estação.', 'Meu maior problema é o horário de pico.', 'Meu aviso mais repetido é "atenção ao vão entre o trem e a plataforma".',
      'Ando sobre trilhos, quase sempre embaixo da terra.', 'Sou o transporte urbano mais rápido nas grandes cidades.', 'Tenho estações com escadas rolantes e mapas coloridos por linha.', 'Sou o trem que passa por baixo da cidade.',
    ] },
    { answer: 'Vacina', clues: [
      'Na China e na Turquia já se usava uma prática parecida com pó de varíola.', 'Edward Jenner fez a experiência decisiva em 1796.', 'Ele usou pus de varíola bovina num menino de 8 anos.', 'Meu nome vem do latim "vacca", por causa das vacas.',
      'Louis Pasteur desenvolveu versões contra raiva e antraz.', 'Funciono ensinando o corpo a reconhecer um invasor antes dele atacar.', 'Uso o vírus morto, enfraquecido ou só um pedaço dele.', 'Levei à erradicação de uma doença no mundo inteiro em 1980.',
      'Essa doença é a varíola.', 'No Brasil, em 1904, houve uma revolta contra a minha obrigatoriedade.', 'Essa foi a Revolta da Vacina, no Rio de Janeiro.', 'O Zé Gotinha virou meu garoto-propaganda em 1986.',
      'A versão contra a poliomielite se toma em gotinhas na boca.', 'O Brasil tem um programa nacional gratuito que é referência mundial.', 'As tecnologias de RNA mensageiro me deixaram muito mais rápida de produzir.', 'Fui feita em tempo recorde contra a covid-19.',
      'Quando muita gente me toma, protege até quem não pode tomar.', 'Isso se chama imunidade de rebanho.', 'Sou aplicada quase sempre com uma agulha no braço.', 'Sou a injeção que evita doenças.',
    ] },
    { answer: 'Feijoada', clues: [
      'Minha origem lendária diz que nasci nas senzalas, mas historiadores discordam.', 'Pratos de feijão com carne de porco já existiam em Portugal, Espanha e França.', 'Meu registro em restaurante do Rio aparece no século 19.', 'Naquela época eu era anunciada como prato "à brasileira" nos jornais.',
      'Virei símbolo nacional no movimento modernista e na era Vargas.', 'Levo feijão preto no Rio e feijão marrom em outras regiões.', 'Uso partes do porco que antes eram descartadas.', 'Entre elas orelha, pé, rabo e costelinha.',
      'Também levo paio, linguiça e carne-seca.', 'A carne salgada precisa de molho de véspera para dessalgar.', 'Sou servida com arroz branco.', 'Meu acompanhamento de folha é a couve refogada bem fininha.',
      'Levo farofa e torresmo por cima.', 'Sou servida com laranja para ajudar na digestão.', 'Meu caldo combina com uma dose de cachaça antes.', 'Sou tradicional aos sábados nos restaurantes.',
      'Depois de mim ninguém consegue trabalhar direito.', 'Existe uma versão minha "light", que ninguém aprova de verdade.', 'Sou considerada o prato nacional do Brasil.', 'Sou o prato de feijão preto com carnes de porco.',
    ] },
    { answer: 'Brigadeiro', clues: [
      'Nasci em São Paulo nos anos 1940.', 'Fui criado durante uma campanha eleitoral do pós-guerra.', 'Levo o nome da patente de um candidato à presidência.', 'Esse candidato foi Eduardo Gomes, da Força Aérea.',
      'A lenda diz que as senhoras vendiam doces para financiar a campanha dele.', 'Ele perdeu a eleição, mas o doce ficou.', 'Meus ingredientes ficaram simples porque leite fresco era escassa na época.', 'Levo leite condensado, chocolate em pó e manteiga.',
      'O ponto certo é quando desgruda do fundo da panela.', 'Se passar do ponto, endurece; se faltar, escorre.', 'Minha versão mole se come de colher direto da panela.', 'Minha prima branca leva coco e se chama beijinho.',
      'Minha prima de amendoim é o cajuzinho.', 'Sou enrolado à mão com as mãos untadas.', 'Sou coberto de granulado de chocolate.', 'Fico em forminhas de papel.',
      'Não existe festa de aniversário infantil sem mim.', 'Virei gourmet e ganhou lojas especializadas.', 'Sou uma bolinha marrom e doce.', 'Sou o doce brasileiro de leite condensado com chocolate.',
    ] },
    { answer: 'Pão de queijo', clues: [
      'Minha origem provável está nas fazendas mineiras do século 18.', 'Nasci quando faltava trigo e sobrava um pó feito de mandioca.', 'As cozinheiras escravizadas assavam bolinhas desse pó no forno a lenha.', 'No começo eu nem levava queijo.',
      'Ganhei queijo quando a produção de leite cresceu em Minas.', 'Meu ingrediente principal é o polvilho.', 'Existo em duas versões: polvilho doce e polvilho azedo.', 'O polvilho azedo me deixa mais crocante por fora.',
      'Não levo glúten nenhum.', 'Uso queijo meia-cura ou canastra na receita tradicional.', 'Virei produto industrializado congelado nos anos 90.', 'Sou vendido em quilo em padarias e em aeroportos.',
      'Ganhei fama internacional e existo até em Nova York e Tóquio.', 'Fico oco por dentro quando dá certo.', 'Sou servido bem quente, direto do forno.', 'Combino com café preto.',
      'Sou o café da manhã típico de Minas Gerais.', 'Tenho até um dia nacional, em 17 de agosto.', 'Sou uma bolinha assada, dourada e elástica.', 'Meu nome tem "pão" e o nome de um laticínio.',
    ] },
    { answer: 'Açaí', clues: [
      'Meu nome vem do tupi "ïwasa\'i", que significa "fruta que chora".', 'Sou o fruto de uma palmeira amazônica.', 'Nasço em cachos com centenas de bolinhas roxas.', 'Quase tudo em mim é caroço: só uma casca fina é aproveitada.',
      'Para virar polpa preciso ser amolecido em água morna.', 'No Pará sou comido salgado.', 'Lá me servem com farinha de mandioca, peixe frito ou camarão.', 'Sou considerado comida, não sobremesa, no Norte.',
      'Fui levado ao Sudeste por surfistas e lutadores de jiu-jítsu nos anos 90.', 'No Sul e no Sudeste virei tigela doce e congelada.', 'Ganhei granola, banana e leite condensado por cima.', 'Sou vendido na tigela, no copo ou no cone.',
      'Sou rico em antioxidantes e em gordura boa.', 'Viraram moda os selos de "superalimento" com meu nome.', 'Sou uma das principais fontes de renda de ribeirinhos do Pará.', 'Quem colhe sobe na palmeira com os pés amarrados.',
      'Minha cor é roxo bem escuro.', 'Se derramar na roupa branca, não sai.', 'Sou uma fruta amazônica que virou febre nas academias.', 'Meu nome tem quatro letras e acento no final.',
    ] },
    { answer: 'Guaraná', clues: [
      'Sou uma planta trepadeira nativa da Amazônia.', 'A lenda dos Sateré-Mawé conta que nasci dos olhos de uma criança enterrada.', 'Minha semente aberta parece um olho humano.', 'Os indígenas raspavam meu bastão seco numa língua de peixe.',
      'Tenho mais cafeína que o café, por peso.', 'Fui usado como remédio e estimulante muito antes de virar refrigerante.', 'Meu maior produtor é o município de Maués, no Amazonas.', 'Meu refrigerante nasceu em 1921, criado por um farmacêutico gaúcho.',
      'Esse farmacêutico foi Pedro Baptista de Andrade, em Santa Catarina.', 'Uma marca famosa minha foi comprada pela Antarctica em 1921.', 'Sou o único sabor de refrigerante realmente brasileiro que virou grande marca.', 'Também existo em xarope, pó e cápsula.',
      'Meu refrigerante é o segundo mais vendido do Brasil, depois da cola.', 'Marcas minhas famosas incluem Antarctica, Kuat e Jesus.', 'Sou obrigatório em churrasco e em festa de criança.', 'Estrangeiros estranham meu sabor e depois viciam.',
      'Minha cor é âmbar, meio amarelada.', 'Combino com o "chorinho" de limão que algumas pessoas pedem.', 'Sou o refrigerante brasileiro feito de uma fruta amazônica.', 'Meu nome tem sete letras e acento no final.',
    ] },
    { answer: 'Cachaça', clues: [
      'Nasci nos engenhos de açúcar do Brasil colônia, no século 16.', 'Comecei como uma espuma fermentada dada aos escravizados.', 'Fui proibida por Portugal em 1649 para proteger a bagaceira portuguesa.', 'Essa proibição gerou a Revolta da Cachaça, no Rio de Janeiro.',
      'Virei moeda de troca no comércio de escravizados.', 'Fui símbolo de resistência nacional na Semana de Arte Moderna.', 'Tenho mais de 2 mil nomes populares diferentes.', 'Entre eles pinga, branquinha, marvada, água que passarinho não bebe.',
      'Sou feita do caldo fresco da cana, e não do melaço.', 'É isso que me diferencia do rum.', 'Minha graduação alcoólica vai de 38 a 48 graus.', 'Posso ser envelhecida em barris de madeiras brasileiras, como amburana.',
      'Minhas cidades famosas de produção são Salinas, em Minas, e Paraty.', 'Sou o destilado mais consumido do Brasil.', 'Sou base do coquetel nacional com limão, açúcar e gelo.', 'Esse coquetel é a caipirinha.',
      'Minha versão artesanal é feita em alambique de cobre.', 'A industrial é feita em coluna de destilação.', 'Sou uma bebida destilada de cana-de-açúcar.', 'Meu apelido mais comum é "pinga".',
    ] },
    { answer: 'WhatsApp', clues: [
      'Fui criado em 2009 por dois ex-funcionários do Yahoo.', 'Eles são Jan Koum e Brian Acton.', 'Um deles tinha sido recusado numa vaga no Facebook antes.', 'Meu nome é um trocadilho com "what\'s up".',
      'No começo eu era só um app de status, sem mensagens.', 'Cobrei uma assinatura de 1 dólar por ano nos primeiros tempos.', 'Fui comprado em 2014 por 19 bilhões de dólares.', 'Quem me comprou foi o Facebook, hoje Meta.',
      'Adotei criptografia de ponta a ponta em 2016.', 'Fui bloqueado no Brasil algumas vezes por decisão judicial.', 'Meus grupos de família viraram piada nacional.', 'Sou o principal caminho de correntes e notícias falsas no Brasil.',
      'Tenho recado de voz que muita gente odeia receber.', 'Meus dois tiques azuis dizem que a mensagem foi lida.', 'Tem gente que desliga essa confirmação de propósito.', 'Ganhei status que somem em 24 horas.',
      'Meu ícone é verde com um telefone dentro de um balão.', 'Sou usado por mais de 90% dos brasileiros com celular.', 'Sirvo para mandar mensagem, foto, áudio e fazer chamadas.', 'Sou o aplicativo verde de mensagens.',
    ] },
    { answer: 'Instagram', clues: [
      'Nasci em 2010, criado por Kevin Systrom e Mike Krieger.', 'Um dos meus criadores é brasileiro.', 'Meu projeto original se chamava Burbn e era sobre check-ins.', 'Meu nome junta "instant camera" e "telegram".',
      'Ganhei 25 mil usuários no primeiro dia.', 'No começo eu só existia no iPhone.', 'Fui comprado em 2012 por 1 bilhão de dólares.', 'Quem me comprou foi o Facebook.',
      'Minhas fotos eram obrigatoriamente quadradas até 2015.', 'Meus filtros vintage foram minha marca registrada.', 'Copiei os stories de um concorrente em 2016.', 'Esse concorrente é o Snapchat.',
      'Criei os Reels para responder a outro concorrente.', 'Esse outro concorrente é o TikTok.', 'Escondi a contagem de curtidas por causa de estudos sobre saúde mental.', 'Sou acusado de piorar a autoestima de adolescentes.',
      'Virei ferramenta de trabalho para influenciadores e lojas.', 'Meu ícone é uma câmera colorida em degradê.', 'Sirvo para postar foto, story e vídeo curto.', 'Sou a rede social das fotos, apelidada de "Insta".',
    ] },
    { answer: 'YouTube', clues: [
      'Fui criado em 2005 por três ex-funcionários do PayPal.', 'Meus criadores são Chad Hurley, Steve Chen e Jawed Karim.', 'A ideia teria surgido da dificuldade de compartilhar vídeos de uma festa.', 'Meu primeiro vídeo foi postado em abril de 2005.',
      'Esse vídeo se chama "Me at the zoo" e tem 18 segundos.', 'No começo eu era pensado como um site de namoro por vídeo.', 'Fui comprado em 2006 por 1,65 bilhão de dólares.', 'Quem me comprou foi o Google.',
      'Criei um programa de divisão de receita com criadores em 2007.', 'Minha placa de prata vai para quem passa de 100 mil inscritos.', 'A de ouro é para 1 milhão e a de diamante para 10 milhões.', 'O vídeo mais visto por muito tempo foi "Despacito".',
      'Hoje o mais visto é uma música infantil sobre um tubarão.', 'Essa música é "Baby Shark".', 'Meu canal com mais inscritos é o MrBeast.', 'Tenho versão paga sem anúncios e versão para crianças.',
      'Sou o segundo site mais acessado do mundo.', 'Meu ícone é um retângulo vermelho com um "play" branco.', 'Sou onde se assiste a tutoriais, clipes e vlogs.', 'Sou o site de vídeos do Google.',
    ] },
    { answer: 'Google', clues: [
      'Nasci em 1998 numa garagem em Menlo Park, na Califórnia.', 'Meus criadores eram dois doutorandos de Stanford.', 'Eles são Larry Page e Sergey Brin.', 'Meu projeto inicial se chamava BackRub.',
      'Meu nome é um erro de digitação de "googol", o número 1 seguido de 100 zeros.', 'Meu algoritmo original ordenava sites pelos links que apontavam para eles.', 'Esse algoritmo é o PageRank.', 'Meu lema informal era "não seja mau".',
      'Comprei o YouTube em 2006 e o Android em 2005.', 'Minha empresa-mãe se chama Alphabet desde 2015.', 'Meus rabiscos na página inicial se chamam doodles.', 'Meu navegador é o Chrome e meu e-mail é o Gmail.',
      'Meu carro fotografa ruas do mundo inteiro.', 'Esse serviço é o Street View.', 'Meu mapa quase acabou com o GPS de porta-luvas.', 'Meu nome virou verbo em vários idiomas.',
      'Detenho mais de 90% das buscas na internet.', 'Ganho dinheiro quase todo com publicidade.', 'Minha página inicial é branca, com uma caixinha no meio.', 'Sou o site de buscas mais usado do mundo.',
    ] },
    { answer: 'iPhone', clues: [
      'Fui anunciado em 9 de janeiro de 2007.', 'Fui apresentado como "três produtos em um": iPod, telefone e internet.', 'Steve Jobs me apresentou num palco em São Francisco.', 'Cheguei às lojas em junho de 2007.',
      'Meu primeiro modelo não tinha loja de aplicativos.', 'Minha loja de apps só apareceu em 2008.', 'Não tinha nem copiar e colar no começo.', 'Matei o teclado físico que dominava os celulares da época.',
      'A Nokia e a BlackBerry riram de mim e sumiram depois.', 'Meu sistema operacional se chama iOS.', 'Tirei o fone de ouvido com fio no modelo 7 e todo mundo reclamou.', 'Tirei o carregador da caixa em 2020.',
      'Meu botão redondo virou reconhecimento facial.', 'Minha marca é uma maçã mordida.', 'Sou fabricado principalmente na China, pela Foxconn.', 'Sou o produto mais lucrativo da história da tecnologia.',
      'Sou vendido no Brasil por um preço muito acima do de fora.', 'Minha empresa é a Apple.', 'Sou um celular de luxo com número no nome.', 'Meu nome começa com "i" minúsculo.',
    ] },
    { answer: 'PlayStation', clues: [
      'Nasci de uma parceria fracassada entre duas empresas japonesas.', 'A Nintendo desistiu do projeto e a outra empresa seguiu sozinha.', 'Essa outra empresa é a Sony.', 'Meu primeiro modelo saiu no Japão em dezembro de 1994.',
      'Fui o primeiro console a vender mais de 100 milhões de unidades.', 'Usei CD quando os concorrentes ainda usavam cartucho.', 'Meu controle ganhou dois analógicos e ficou padrão no mercado.', 'Esse controle se chama DualShock.',
      'Meu segundo modelo também tocava DVD, o que o tornou barato no Brasil.', 'Meu segundo modelo é o console mais vendido da história.', 'Meu quarto modelo dominou a geração contra o Xbox One.', 'Meu botão de confirmar é o X no Ocidente e o círculo no Japão.',
      'Meus exclusivos incluem "God of War" e "The Last of Us".', 'Meu mascote informal foi um bicho chamado Crash Bandicoot.', 'Meu serviço online se chama PlayStation Plus.', 'Meu modelo atual é o 5, lançado em 2020.',
      'Meus símbolos são triângulo, círculo, xis e quadrado.', 'Sou japonês e fabricado pela Sony.', 'Sou um videogame de mesa ligado na TV.', 'Meu apelido é "PS".',
    ] },
    { answer: 'Lego', clues: [
      'Nasci na Dinamarca, numa marcenaria, em 1932.', 'Meu criador foi o carpinteiro Ole Kirk Christiansen.', 'No começo eu era feito de madeira.', 'Meu nome vem de "leg godt", que significa "brinque bem" em dinamarquês.',
      'Por coincidência, meu nome também significa "eu monto" em latim.', 'Comecei a usar plástico em 1947.', 'Patenteei meu formato atual de encaixe em 1958.', 'Uma peça de 1958 ainda encaixa numa peça fabricada hoje.',
      'Meus bonequinhos ganharam mãos e rosto em 1978.', 'Quase quebrei no começo dos anos 2000, por espalhar demais os produtos.', 'Me salvei com licenças de Star Wars e Harry Potter.', 'Sou hoje o maior fabricante de brinquedos do mundo.',
      'Tenho parques temáticos com meu nome.', 'Meu filme de 2014 foi um sucesso de bilheteria.', 'Existem competições mundiais de robótica com meu nome.', 'Sou o pesadelo de qualquer pai que anda descalço à noite.',
      'Sou vendido em caixas com manual de montagem.', 'Sou feito de plástico ABS colorido.', 'Minhas peças têm pinos em cima e tubos embaixo.', 'Sou o bloquinho de montar dinamarquês.',
    ] },
    { answer: 'Skate', clues: [
      'Nasci na Califórnia nos anos 50.', 'Fui inventado por surfistas em dias sem onda.', 'Meus primeiros modelos eram caixotes com rodinhas de patins.', 'Meu apelido inicial era "surfe de calçada".',
      'Uma seca em 1976 esvaziou piscinas na Califórnia e criou um novo estilo.', 'Os Z-Boys, de Dogtown, popularizaram esse estilo nas piscinas.', 'As rodas de poliuretano, nos anos 70, mudaram tudo.', 'Alan Gelfand inventou em 1978 o pulo sem usar as mãos.',
      'Esse pulo se chama ollie.', 'Rodney Mullen levou o ollie para o chão e criou dezenas de manobras.', 'Tony Hawk fez o primeiro "900" numa competição em 1999.', 'Um videogame com o nome do Tony Hawk me popularizou nos anos 2000.',
      'Fui proibido em várias praças e escadarias por causa dos danos.', 'Meu piso tem lixa por cima para o pé não escorregar.', 'Minha parte de metal que segura as rodas se chama truck.', 'Virei esporte olímpico em Tóquio 2020.',
      'O Brasil ganhou várias medalhas nele com Rayssa Leal e Pedro Barros.', 'Rayssa é chamada de "Fadinha".', 'Ando sobre quatro rodas com um pé empurrando.', 'Sou a tábua com rodinhas usada em pistas e rampas.',
    ] },
    { answer: 'Piano', clues: [
      'Fui inventado por volta de 1700, em Florença.', 'Meu inventor foi Bartolomeo Cristofori.', 'Ele trabalhava para a família Médici.', 'Meu nome completo original era "gravicembalo col piano e forte".',
      'Esse nome quer dizer "cravo com suave e forte".', 'Substituí o cravo justamente porque permitia tocar mais forte ou mais fraco.', 'Meu som nasce de martelinhos que batem em cordas.', 'Tenho mais de 200 cordas esticadas com muitas toneladas de tensão.',
      'Meu corpo de cauda tem forma de asa.', 'Minha versão vertical foi feita para caber em casas.', 'Tenho normalmente três pedais.', 'O pedal da direita segura o som depois que solto a tecla.',
      'Beethoven, Chopin e Liszt escreveram minhas obras mais famosas.', 'Preciso ser afinado por um profissional algumas vezes por ano.', 'Tenho 88 teclas.', 'Minhas teclas pretas vêm em grupos de duas e de três.',
      'Minhas teclas brancas eram de marfim antigamente.', 'Minha versão eletrônica se chama teclado.', 'Sou tocado sentado, com as duas mãos.', 'Sou o instrumento grande e preto de teclas brancas e pretas.',
    ] },
    { answer: 'Caneta', clues: [
      'Meus ancestrais foram penas de ganso mergulhadas em tinta.', 'Antes disso, usavam-se caniços cortados no Egito.', 'A pena de metal com fenda apareceu no século 19.', 'O grande problema sempre foi vazar tinta no bolso.',
      'Meu tipo mais famoso foi inventado por um jornalista húngaro.', 'Ele se chamava László Bíró.', 'Ele se inspirou na tinta de jornal, que secava rápido.', 'Ele patenteou a invenção em 1938 e fugiu da guerra para a Argentina.',
      'Por isso em vários países meu nome é "biro" ou "birome".', 'A Força Aérea britânica me adotou porque eu não vazava em altitude.', 'Marcel Bich comprou a patente e me deixou barata.', 'A marca dele é a Bic, e o modelo laranja de 1950 é o mais vendido do mundo.',
      'Já foram vendidos mais de 100 bilhões de exemplares desse modelo.', 'Minha ponta é uma esferinha de metal que gira.', 'Minha tampa tem um furo por causa de acidentes com crianças.', 'Sumo da mesa de todo mundo sem explicação.',
      'Sou emprestada e nunca devolvida.', 'Minhas cores mais comuns são azul, preta e vermelha.', 'Sirvo para escrever em papel.', 'Sou o objeto fino que a gente segura para escrever.',
    ] },
    { answer: 'Máquina de lavar', clues: [
      'Antes de mim se lavava roupa no rio, batendo em pedras.', 'Depois vieram as tábuas de esfregar e os tanques.', 'Minha primeira patente americana é de 1797.', 'Minhas primeiras versões eram manuais, com manivela.',
      'Ganhei motor elétrico por volta de 1908.', 'A Maytag e a Whirlpool fizeram meus modelos populares.', 'Sou apontada por economistas como uma das invenções que mais libertaram mulheres.', 'O economista Hans Rosling fez uma palestra famosa em minha homenagem.',
      'Meu ciclo separa lavagem, enxágue e centrifugação.', 'Minha centrifugação gira a mais de mil rotações por minuto.', 'Existo com abertura em cima e com abertura na frente.', 'A de abertura frontal gasta menos água.',
      'Minha versão que também seca se chama lava e seca.', 'Meu filtro precisa ser limpo ou entope.', 'Meu maior mistério é o sumiço de uma meia por lavagem.', 'Danço pela área de serviço quando fica desbalanceada.',
      'Preciso de sabão em pó ou líquido para funcionar.', 'Sou o eletrodoméstico da área de serviço.', 'Fico girando roupa dentro de água.', 'Sou a máquina que lava as roupas.',
    ] },
  ],
};

module.exports = { CARDS7 };
