// Lote 10 do Perfil — Série ou Filme (séries, novelas, desenhos e animes). Cada carta: resposta + 20 dicas.
const CARDS10 = {
  S: [
    { answer: 'Friends', clues: [
      'Meu título provisório era "Insomnia Cafe".', 'Meus seis atores negociaram salário em grupo e chegaram a 1 milhão de dólares por episódio.', 'Estreei em 1994 e terminei em 2004.', 'Tive 10 temporadas e 236 episódios.',
      'Meu último episódio foi visto por 52 milhões de pessoas nos Estados Unidos.', 'Minha abertura tem os personagens dançando numa fonte.', 'Minha música-tema é "I\'ll Be There for You", dos The Rembrandts.', 'Meu apartamento principal é roxo e tem uma moldura amarela na porta.',
      'Meu café se chama Central Perk.', 'Um dos meus personagens é paleontólogo e teve um macaco.', 'Outro é chef e virou o mais engraçado da turma.', 'Outra é maluca, toca violão e canta sobre um gato fedido.',
      'Essa música é "Smelly Cat".', 'Meu casal principal vivia num "we were on a break".', 'Meu personagem mulherengo pergunta "How you doin\'?".', 'Meu elenco é Rachel, Monica, Phoebe, Joey, Chandler e Ross.',
      'Matthew Perry, meu Chandler, morreu em 2023.', 'Sou uma sitcom sobre seis amigos em Nova York.', 'Meu nome, em inglês, quer dizer "amigos".', 'Meu nome tem sete letras e começa com F.',
    ] },
    { answer: 'Stranger Things', clues: [
      'Meus criadores são irmãos gêmeos que assinam como Duffer Brothers.', 'Meu roteiro foi recusado por mais de 15 emissoras antes da Netflix.', 'Estreei em julho de 2016.', 'Minha história se passa nos anos 80, numa cidade de Indiana.',
      'Essa cidade se chama Hawkins.', 'Minha inspiração vem de Spielberg, Stephen King e Dungeons & Dragons.', 'Um menino desaparece no primeiro episódio.', 'Esse menino é Will Byers.',
      'A mãe dele se comunica com ele por luzes de Natal na parede.', 'Uma menina de cabeça raspada aparece com poderes e um número tatuado.', 'Ela adora waffles congelados.', 'Ela se chama Eleven, ou "Onze".',
      'Minha dimensão paralela é escura e cheia de partículas no ar.', 'Essa dimensão é o "Mundo Invertido".', 'Meu monstro da primeira temporada é o Demogorgon.', 'Meu vilão da quarta temporada é o Vecna.',
      'Kate Bush voltou às paradas por minha causa com "Running Up That Hill".', 'Meu personagem Steve virou o "babá" da turma.', 'Sou a série da Netflix sobre crianças, monstros e anos 80.', 'Meu nome, em inglês, quer dizer "coisas estranhas".',
    ] },
    { answer: 'Breaking Bad', clues: [
      'Meu criador é Vince Gilligan, ex-roteirista de Arquivo X.', 'Estreei em 2008 na AMC.', 'Minha história se passa em Albuquerque, no Novo México.', 'Tive 5 temporadas e 62 episódios.',
      'Meu criador definiu a série como transformar "Mr. Chips em Scarface".', 'Meu protagonista é professor de química de escola.', 'Ele descobre um câncer de pulmão no primeiro episódio.', 'Ele começa a fabricar drogas para deixar dinheiro para a família.',
      'O produto dele é azul, de tão puro.', 'Meu protagonista adota o nome falso "Heisenberg".', 'Ele diz "I am the one who knocks".', 'Ele diz "Say my name".',
      'Meu cunhado é agente do DEA e demora anos para desconfiar.', 'Meu vilão mais frio é dono de uma rede de frango frito.', 'Essa rede é Los Pollos Hermanos e o dono é Gus Fring.', 'Meu parceiro jovem diz "yeah, science!" e chama todos de "bitch".',
      'Meus protagonistas são Walter White e Jesse Pinkman.', 'Meu advogado ganhou uma série própria: "Better Call Saul".', 'Sou a série sobre o professor que vira traficante.', 'Meu nome, em inglês, é uma gíria para "sair da linha".',
    ] },
    { answer: 'Game of Thrones', clues: [
      'Fui baseada nos livros "As Crônicas de Gelo e Fogo", de George R.R. Martin.', 'Estreei em 2011 na HBO.', 'Fui filmada na Irlanda do Norte, Croácia, Islândia e Espanha.', 'Meus episódios finais custaram mais de 15 milhões de dólares cada.',
      'Minha última temporada, de 2019, foi detestada pelos fãs.', 'Meu mapa animado na abertura muda conforme os lugares do episódio.', 'Meu continente principal se chama Westeros.', 'Meu lema mais famoso é "o inverno está chegando".',
      'Meu protagonista aparente perde a cabeça na primeira temporada.', 'Esse personagem é Ned Stark.', 'Meu "Casamento Vermelho" traumatizou o mundo inteiro.', 'Minha rainha loira tem três dragões.',
      'Ela é chamada de "Mãe dos Dragões" e se chama Daenerys.', 'Meu anão espertíssimo é Tyrion Lannister.', 'Meu herói que "não sabe de nada" é Jon Snow.', 'Meu muro de gelo gigante protege contra os Caminhantes Brancos.',
      'Meu trono é feito de espadas derretidas.', 'Meu prequel se chama "A Casa do Dragão".', 'Sou a série de fantasia da HBO com dragões e traições.', 'Meu nome, em inglês, quer dizer "jogo dos tronos".',
    ] },
    { answer: 'Round 6', clues: [
      'Meu criador demorou mais de 10 anos para conseguir produzir a série.', 'Ele vendeu o notebook para pagar contas enquanto escrevia meu roteiro.', 'Sou uma série sul-coreana lançada em setembro de 2021.', 'Virei a série mais vista da história da Netflix em poucas semanas.',
      'Meu nome original é "Squid Game", ou "jogo da lula".', 'Meus participantes são pessoas endividadas.', 'São 456 jogadores no total.', 'Meus guardas usam macacão rosa e máscara com círculo, triângulo ou quadrado.',
      'Meus jogadores usam uniforme verde numerado.', 'O prêmio fica num cofre de vidro pendurado no teto.', 'Meu primeiro jogo tem uma boneca gigante que canta.', 'Quem se mexe quando a boneca vira é eliminado com tiro.',
      'Esse jogo é "batatinha frita 1, 2, 3".', 'Meu jogo de biscoito de açúcar com formas virou desafio na internet.', 'Meu jogador 001 é um velhinho que não é o que parece.', 'Meu protagonista é o jogador 456.',
      'Minha segunda temporada saiu em dezembro de 2024.', 'Meu cartão de convite tem os três símbolos geométricos.', 'Sou a série coreana dos jogos mortais.', 'Meu nome brasileiro tem um número.',
    ] },
    { answer: 'La Casa de Papel', clues: [
      'Sou uma série espanhola que estreou em 2017 na TV aberta da Espanha.', 'Fui um fracasso de audiência e quase fui cancelada.', 'A Netflix me comprou, reeditou e me transformou em fenômeno mundial.', 'Meu nome original quer dizer "a casa de papel".',
      'Em inglês me chamam de "Money Heist".', 'Meus assaltantes usam codinomes de cidades.', 'Entre eles Tóquio, Berlim, Nairóbi, Rio, Denver e Helsinque.', 'Minha narradora é a personagem Tóquio.',
      'Meu cérebro por trás do plano é chamado de "O Professor".', 'Meu primeiro assalto é na Casa da Moeda da Espanha.', 'Os assaltantes não roubam dinheiro: imprimem dinheiro novo.', 'Meu segundo grande assalto é no Banco da Espanha.',
      'Minha canção antiga italiana virou hino de protesto.', 'Essa canção é "Bella Ciao".', 'Meus assaltantes usam macacão vermelho.', 'Eles usam máscaras de um pintor espanhol de bigode.',
      'Esse pintor é Salvador Dalí.', 'Tive 5 partes e terminei em 2021.', 'Sou a série espanhola do assalto e das máscaras.', 'Meu nome tem "Casa" e "Papel".',
    ] },
    { answer: 'The Office', clues: [
      'Sou um remake de uma série inglesa de Ricky Gervais.', 'Minha versão americana estreou em 2005 na NBC.', 'Sou filmada como um falso documentário, com olhares para a câmera.', 'Minha empresa vende papel numa cidade da Pensilvânia.',
      'Essa empresa é a Dunder Mifflin, em Scranton.', 'Tive 9 temporadas e 201 episódios.', 'Meu chefe se acha o "melhor chefe do mundo" e tem uma caneca dizendo isso.', 'Ele diz "that\'s what she said" o tempo todo.',
      'Esse chefe é Michael Scott, vivido por Steve Carell.', 'Meu vendedor esquisito cria beterraba e adora artes marciais.', 'Esse vendedor é Dwight Schrute.', 'Meu casal principal namora devagar e casa na sexta temporada.',
      'Esse casal é Jim e Pam.', 'Jim coloca o grampeador do Dwight em gelatina no primeiro episódio.', 'Meu contador Kevin derruba um panelão de chili.', 'Minha abertura tem um piano simples e cenas de Scranton.',
      'Sou uma das séries mais assistidas em streaming até hoje.', 'Sou uma comédia de escritório.', 'Meu nome, em inglês, quer dizer "o escritório".', 'Meu nome tem duas palavras e começa com "The".',
    ] },
    { answer: "Grey's Anatomy", clues: [
      'Meu nome é um trocadilho com um famoso livro de anatomia.', 'Minha criadora é Shonda Rhimes.', 'Estreei em 2005 na ABC.', 'Já passei de 20 temporadas e sou a série médica mais longa da TV americana.',
      'Meu hospital fica em Seattle.', 'Esse hospital já mudou de nome várias vezes: Seattle Grace, Grey-Sloan…', 'Meus médicos têm apelidos como "McDreamy" e "McSteamy".', 'Um dos meus episódios mais famosos tem uma bomba dentro de um paciente.',
      'Já tive tiroteio, acidente de avião e afogamento no hospital.', 'Meu casal principal ficou junto depois de um "pick me, choose me, love me".', 'Meu médico charmoso morreu num acidente de carro na temporada 11.', 'Esse médico é Derek Shepherd.',
      'Minha personagem Cristina Yang é a melhor amiga da protagonista.', 'A protagonista diz que a amiga é a "pessoa dela".', 'Minha protagonista é filha de uma cirurgiã famosa.', 'Ela se chama Meredith Grey.',
      'Minha frase de fim de episódio quase sempre é uma reflexão da narradora.', 'Sou a série de médicos com mais drama e romance da TV.', 'Meu nome tem o sobrenome da protagonista.', 'Meu nome tem "Anatomia" em inglês.',
    ] },
    { answer: 'Os Simpsons', clues: [
      'Nasci como esquetes curtos num programa de variedades em 1987.', 'Meu criador é Matt Groening.', 'Ele desenhou a família na sala de espera do produtor, em minutos.', 'Estreei como série própria em dezembro de 1989.',
      'Sou a série de ficção mais longa da TV americana.', 'Já passei de 35 temporadas e 780 episódios.', 'Minha cidade nunca revela em que estado fica.', 'Essa cidade é Springfield.',
      'Meu pai trabalha numa usina nuclear e dorme no serviço.', 'Meu chefe da usina é um velho maléfico chamado Sr. Burns.', 'Meu vizinho é evangélico e sempre gentil: Ned Flanders.', 'Meu bar se chama Moe\'s.',
      'Minha abertura termina com a família correndo para o sofá.', 'Meu filho escreve castigos na lousa na abertura.', 'Meu pai grita "D\'oh!".', 'Minha filha toca saxofone e é vegetariana.',
      'Meus personagens são amarelos e têm quatro dedos.', 'Sou famoso por "prever" o futuro, como a eleição de Trump.', 'Meus personagens são Homer, Marge, Bart, Lisa e Maggie.', 'Meu nome é o sobrenome da família amarela.',
    ] },
    { answer: 'Chaves', clues: [
      'Fui criado, escrito e estrelado por Roberto Gómez Bolaños.', 'Ele assinava como "Chespirito", um trocadilho com Shakespeare.', 'Estreei no México em 1971.', 'Cheguei ao Brasil em 1984, pelo SBT.',
      'Passei décadas em reprise no Brasil e ganhei mais fãs aqui do que no México.', 'Minha história se passa numa vila com pátio no meio.', 'Meu protagonista mora dentro de um barril.', 'Meu protagonista tem 8 anos e diz que "sem querer querendo".',
      'Meu protagonista chora com um chorinho engasgado e diz "pi-pi-pi-pi".', 'Meu vizinho ruivo e bochechudo usa suspensórios.', 'Esse vizinho é o Quico e a mãe dele é a Dona Florinda.', 'Meu velho ranzinza sempre apanha da Dona Florinda.',
      'Esse velho é o Seu Madruga, que nunca paga o aluguel.', 'Minha menina de sardas e tranças se chama Chiquinha.', 'Meu dono da vila é o Seu Barriga.', 'Meu protagonista sonha com um sanduíche de presunto.',
      'Meu criador também fez o super-herói Chapolin.', 'Minha frase "isso, isso, isso" é do protagonista.', 'Sou a série mexicana do menino do barril.', 'Meu nome tem seis letras e começa com C.',
    ] },
    { answer: 'Bridgerton', clues: [
      'Fui baseada nos livros de Julia Quinn.', 'Sou produzida pela Shonda Rhimes para a Netflix.', 'Estreei no Natal de 2020.', 'Minha história se passa na Londres do começo do século 19.',
      'Meu elenco mistura raças de propósito numa Inglaterra fictícia.', 'Minha trilha tem músicas pop tocadas em versões de quarteto de cordas.', 'Minha narradora é uma escritora anônima de fofocas.', 'Ela se chama Lady Whistledown.',
      'Minha rainha adora fofoca e usa perucas gigantes.', 'Minha família principal tem oito filhos em ordem alfabética.', 'Cada temporada conta o romance de um irmão diferente.', 'Meu duque da primeira temporada é Simon Basset.',
      'Meu casal da segunda temporada é Anthony e Kate.', 'Meu casal da terceira é Penelope e Colin.', 'Minhas cenas de baile e de "temporada social" viraram moda.', 'Meu spin-off conta a história da rainha Charlotte.',
      'Sou uma série de época, de romance e muito figurino.', 'Meu nome é o sobrenome da família da série.', 'Sou o romance de época mais visto da Netflix.', 'Meu nome termina com "ton".',
    ] },
    { answer: 'The Walking Dead', clues: [
      'Fui baseada nos quadrinhos de Robert Kirkman.', 'Estreei no Halloween de 2010, na AMC.', 'Meu primeiro episódio foi dirigido por Frank Darabont.', 'Tive 11 temporadas e terminei em 2022.',
      'Minha história se passa na Geórgia, nos Estados Unidos.', 'Meu protagonista acorda de um coma num hospital vazio.', 'Ele é xerife e anda de chapéu.', 'Esse protagonista é Rick Grimes.',
      'Meus mortos são chamados de "walkers", nunca de "zumbis".', 'Meu caçador de besta virou o favorito dos fãs.', 'Esse personagem é Daryl Dixon.', 'Minha guerreira usa katana e anda com dois zumbis acorrentados.',
      'Essa guerreira é Michonne.', 'Meu vilão usa um taco de beisebol com arame farpado.', 'O taco se chama Lucille e o vilão é Negan.', 'Minha prisão, minha fazenda e meu Alexandria são fases da série.',
      'Ganhei vários spin-offs, como "Fear the Walking Dead".', 'Sou a série de zumbis mais famosa da TV.', 'Meu nome, em inglês, quer dizer "os mortos que andam".', 'Meu nome tem três palavras e começa com "The".',
    ] },
    { answer: 'Bob Esponja', clues: [
      'Meu criador era biólogo marinho antes de virar animador.', 'Ele se chamava Stephen Hillenburg e morreu em 2018.', 'Estreei em 1999 na Nickelodeon.', 'Meu nome original ia ser "SpongeBoy", mas já estava registrado.',
      'Minha cidade fica no fundo do mar e se chama Fenda do Biquíni.', 'Meu protagonista mora num abacaxi.', 'Meu protagonista trabalha numa lanchonete.', 'Essa lanchonete é a Siri Cascudo.',
      'Meu dono da lanchonete é um caranguejo pão-duro.', 'Esse dono é o Seu Sirigueijo.', 'Meu vilão minúsculo quer roubar a fórmula do hambúrguer.', 'Esse vilão é o Plankton.',
      'Meu vizinho ranzinza toca clarinete e se chama Lula Molusco.', 'Meu melhor amigo é uma estrela-do-mar rosa e bobinha.', 'Esse amigo é o Patrick.', 'Minha esquilo usa capacete de mergulho e se chama Sandy.',
      'Meu caracol de estimação mia e se chama Gary.', 'Meu protagonista ri com um "ha-ha-ha" nasal.', 'Sou o desenho da esponja amarela de calça quadrada.', 'Meu nome tem "Bob" e o nome de um bicho do mar.',
    ] },
    { answer: 'Naruto', clues: [
      'Fui criado por Masashi Kishimoto.', 'Meu mangá começou em 1999 na revista Shonen Jump.', 'Meu anime estreou em 2002.', 'Minha segunda parte se chama "Shippuden".',
      'Meu protagonista tem um monstro selado dentro dele.', 'Esse monstro é uma raposa de nove caudas.', 'Meu protagonista cresce sozinho e rejeitado pela vila.', 'Minha vila se chama Konoha, a Vila da Folha.',
      'Meu protagonista sonha em ser o líder da vila, o Hokage.', 'Meu protagonista corre com os braços para trás.', 'Meu rival tem cabelo preto e um clã dizimado.', 'Esse rival é Sasuke Uchiha.',
      'Minha personagem de cabelo rosa é Sakura.', 'Meu professor lê livros adultos e usa máscara.', 'Esse professor é Kakashi.', 'Meu protagonista come lámen o tempo todo.',
      'Meu protagonista termina a frase com "dattebayo" no original.', 'Meu filho ganhou uma série própria chamada "Boruto".', 'Sou o anime do ninja loiro de laranja.', 'Meu nome é o nome do ninja protagonista.',
    ] },
    { answer: 'One Piece', clues: [
      'Fui criado por Eiichiro Oda.', 'Meu mangá começou em 1997 e ainda não acabou.', 'Sou o mangá mais vendido da história, com mais de 500 milhões de cópias.', 'Meu anime já passou de 1.100 episódios.',
      'Ganhei uma versão com atores de verdade na Netflix em 2023.', 'Meu protagonista comeu uma fruta que deu poderes a ele.', 'Essas frutas se chamam Akuma no Mi, ou frutas do diabo.', 'Quem come uma delas nunca mais consegue nadar.',
      'Meu protagonista tem corpo de borracha.', 'Ele usa um chapéu de palha que ganhou de um pirata.', 'Ele quer ser o Rei dos Piratas.', 'Meu tesouro lendário dá nome à série.',
      'Meu espadachim usa três espadas, uma na boca.', 'Esse espadachim é o Zoro.', 'Minha navegadora ruiva é a Nami.', 'Meu médico é uma rena falante chamada Chopper.',
      'Meu navio se chama Going Merry e depois Thousand Sunny.', 'Meu protagonista se chama Monkey D. Luffy.', 'Sou o anime dos piratas do chapéu de palha.', 'Meu nome, em inglês, quer dizer "uma peça".',
    ] },
    { answer: 'Dragon Ball', clues: [
      'Fui criado por Akira Toriyama, que morreu em 2024.', 'Fui inspirado numa lenda chinesa chamada "Jornada ao Oeste".', 'Meu mangá começou em 1984.', 'Minha segunda fase se chama "Z" e é a mais famosa.',
      'Minha terceira fase, "GT", não foi feita pelo criador.', 'Cheguei ao Brasil na TV aberta nos anos 90, pela Band e depois pela Globo.', 'Meu nome vem de sete esferas que realizam um desejo.', 'Quem junta as esferas invoca um dragão chamado Shenlong.',
      'Meu protagonista é um alienígena criado na Terra como humano.', 'A raça dele se chama Saiyajin.', 'Ele fica loiro quando se transforma.', 'Essa transformação é o Super Saiyajin.',
      'Meu golpe mais famoso é gritado enquanto se juntam as mãos.', 'Esse golpe é o Kamehameha.', 'Meu rival orgulhoso é o príncipe Vegeta.', 'Meus vilões incluem Freeza, Cell e Majin Boo.',
      'Meu protagonista aprende a lutar com o Mestre Kame.', 'Meu protagonista se chama Goku.', 'Sou o anime das esferas do dragão.', 'Meu nome, em inglês, quer dizer "bola de dragão".',
    ] },
    { answer: 'The Last of Us', clues: [
      'Fui baseada num videogame da Naughty Dog, de 2013.', 'Meu jogo é considerado um dos melhores de todos os tempos.', 'Minha série estreou na HBO em janeiro de 2023.', 'Meu criador na TV é Craig Mazin, de "Chernobyl".',
      'Minha epidemia é causada por um fungo, e não por um vírus.', 'Esse fungo existe de verdade e infecta formigas: o Cordyceps.', 'Meus infectados fazem estalos com a boca.', 'Esses infectados são os "estaladores".',
      'Meu terceiro episódio conta uma história de amor de dois homens e virou o mais elogiado.', 'Meu protagonista é um contrabandista que perdeu a filha.', 'Ele precisa levar uma menina imune pelo país.', 'Essa menina se chama Ellie.',
      'Meu protagonista se chama Joel.', 'Meus atores principais são Pedro Pascal e Bella Ramsey.', 'Minha segunda temporada, de 2025, matou um personagem principal e chocou o público.', 'Meu jogo tem um golfe que ninguém esqueceu.',
      'Meu cenário é os Estados Unidos 20 anos depois do fim do mundo.', 'Sou a série da HBO baseada em videogame.', 'Meu nome, em inglês, quer dizer "os últimos de nós".', 'Meu nome tem quatro palavras e começa com "The".',
    ] },
    { answer: 'Peaky Blinders', clues: [
      'Sou uma série britânica criada por Steven Knight.', 'Estreei em 2013 na BBC.', 'Minha história se passa em Birmingham depois da Primeira Guerra.', 'Meu nome vem de uma gangue que existiu de verdade.',
      'A lenda diz que a gangue escondia lâminas nas boinas.', 'Minha família principal é de origem cigana.', 'Meus personagens usam ternos, sobretudo e corte de cabelo raspado dos lados.', 'Esse corte virou moda no mundo inteiro por minha causa.',
      'Minha trilha sonora mistura rock moderno com cenário antigo.', 'Minha música de abertura é "Red Right Hand", de Nick Cave.', 'Meu protagonista voltou da guerra traumatizado e não dorme.', 'Ele fuma o tempo inteiro e tem olhos azuis marcantes.',
      'Meu protagonista é interpretado por Cillian Murphy.', 'Esse protagonista se chama Thomas Shelby.', 'Minha tia Polly cuida das contas e da família.', 'Meu inspetor vilão da primeira temporada é vivido por Sam Neill.',
      'Tive 6 temporadas e terminei em 2022.', 'Ganhei um filme de encerramento na Netflix.', 'Sou a série da gangue inglesa de boina.', 'Meu nome tem "Peaky" e "Blinders".',
    ] },
    { answer: 'Black Mirror', clues: [
      'Meu criador é o jornalista e humorista Charlie Brooker.', 'Estreei em 2011 no Channel 4, na Inglaterra.', 'A Netflix me comprou a partir da terceira temporada.', 'Cada episódio meu tem uma história e um elenco diferentes.',
      'Meu nome se refere à tela desligada de um celular ou TV.', 'Meu primeiro episódio envolve o primeiro-ministro e um porco.', 'Fiz um episódio interativo em que o público escolhe o rumo.', 'Esse episódio é "Bandersnatch".',
      'Tenho um episódio em que todo mundo avalia todo mundo com notas de 1 a 5.', 'Esse episódio é "Nosedive", com Bryce Dallas Howard.', 'Tenho um episódio de amor numa cidade virtual dos anos 80.', 'Esse episódio é "San Junipero" e ganhou o Emmy.',
      'Tenho um episódio com abelhas robôs assassinas.', 'Tenho um episódio em que as pessoas gravam tudo o que veem com um implante.', 'Minhas histórias falam de tecnologia dando errado.', 'Quando algo estranho acontece com tecnologia, dizem que "parece episódio meu".',
      'Sou uma antologia de ficção científica.', 'Meu nome, em inglês, quer dizer "espelho preto".', 'Sou a série sobre o lado sombrio da tecnologia.', 'Meu nome tem duas palavras e a primeira é uma cor.',
    ] },
    { answer: 'Emily em Paris', clues: [
      'Meu criador é Darren Star, o mesmo de "Sex and the City".', 'Estreei na Netflix em outubro de 2020.', 'Fui muito criticada pelos franceses por caricaturar a França.', 'Ganhei indicação ao Globo de Ouro e ao Emmy mesmo assim.',
      'Minha protagonista é uma americana de Chicago.', 'Ela trabalha com marketing e vai para a Europa sem falar a língua.', 'Ela trabalha numa agência chamada Savoir.', 'A chefe francesa dela é a Sylvie, que a despreza.',
      'Minha protagonista posta tudo no Instagram e ganha seguidores.', 'Meu vizinho de baixo é um chef bonitão chamado Gabriel.', 'Minha melhor amiga é chinesa e cantora: Mindy.', 'Meu figurino colorido e exagerado virou assunto.',
      'Minha protagonista usa boina e roupas estampadas.', 'Minha quarta temporada mudou o cenário para Roma.', 'Minha protagonista é interpretada por Lily Collins.', 'A protagonista dá nome à série.',
      'Sou a série de comédia romântica sobre uma americana na França.', 'Meu nome tem o nome da protagonista e uma capital.', 'Meu nome termina com o nome da cidade da Torre Eiffel.', 'Meu nome começa com "Emily".',
    ] },
    { answer: 'Sintonia', clues: [
      'Fui criada pelo KondZilla, produtor de clipes de funk.', 'Sou uma série brasileira da Netflix, lançada em 2019.', 'Minha história se passa na periferia de São Paulo.', 'Meus três protagonistas são amigos de infância da mesma quebrada.',
      'Um deles quer ser MC de funk.', 'Outra é evangélica e quer ser advogada.', 'O terceiro entra para o tráfico.', 'Meus protagonistas são Doni, Rita e Nando.',
      'Minha música é funk e minha história tem igreja e crime.', 'Meu título fala de estar em sintonia apesar dos caminhos diferentes.', 'Minha atriz principal é Bruna Mascarenhas.', 'Meu MC é vivido por Jottapê.',
      'Minha série mostra o "fluxo" dos bailes de rua.', 'Tive 5 temporadas e terminei em 2024.', 'Sou uma das séries brasileiras mais vistas da Netflix.', 'Meu nome também é uma palavra ligada a rádio.',
      'Sou a série do funk, da fé e da favela.', 'Meu nome tem oito letras.', 'Meu nome começa com S e termina com A.', 'Sou a série brasileira do KondZilla.',
    ] },
    { answer: 'Avenida Brasil', clues: [
      'Fui escrita por João Emanuel Carneiro.', 'Fui exibida pela Globo em 2012.', 'Fui vendida para mais de 130 países.', 'Meu último capítulo levou o presidente da República a adiar um comício.',
      'Minha história se passa no subúrbio carioca, num bairro fictício chamado Divino.', 'Minha vilã abandona a enteada num lixão.', 'A enteada cresce, muda de nome e volta para se vingar.', 'A vilã se casou com um ex-jogador de futebol.',
      'Esse jogador se chama Tufão.', 'Minha vilã tem uma mãe ranzinha chamada Muricy.', 'Minha vilã grita "oi, oi, oi!" ao chegar em casa.', 'Meu bordão "abandona, Rita!" virou meme.',
      'Meu personagem Adauto puxa o cabelo e a Suelen namora dois ao mesmo tempo.', 'Meu apelido de "novela das nove" nunca combinou tanto com uma novela.', 'Minha vilã foi vivida por Adriana Esteves.', 'A protagonista foi vivida por Débora Falabella.',
      'Minha vilã se chama Carminha, e a protagonista, Nina.', 'Meu último capítulo teve a pergunta "quem matou Max?".', 'Sou a novela da Carminha.', 'Meu nome é o de uma avenida do Rio de Janeiro.',
    ] },
    { answer: 'Vale Tudo', clues: [
      'Fui escrita originalmente por Gilberto Braga em 1988.', 'Ganhei um remake na Globo em 2025, escrito por Manuela Dias.', 'Meu tema é a ética e a corrupção no Brasil.', 'Minha pergunta central é se vale a pena ser honesto no país.',
      'Minha protagonista é uma cozinheira honesta que vende sanduíches na praia.', 'A filha dela é golpista e quer subir na vida de qualquer jeito.', 'Minha vilã principal é uma empresária rica e cruel.', 'Essa vilã foi vivida por Beatriz Segall e, no remake, por Debora Bloch.',
      'Meu mistério final foi "quem matou Odete Roitman?".', 'Esse mistério parou o Brasil em 1988 e de novo em 2025.', 'Minha vilã já foi morta e voltou viva no remake.', 'Minha personagem Maria de Fátima virou sinônimo de golpista.',
      'Minha protagonista se chama Raquel.', 'Minha vinheta original era cantada por Gal Costa: "Brasil".', 'No remake, Taís Araújo é a Raquel e Bella Campos é a Maria de Fátima.', 'Meu personagem Marco Aurélio foge do país num avião.',
      'Sou a novela em que a vilã é assassinada.', 'Meu nome fala que qualquer coisa é permitida.', 'Sou a novela da Odete Roitman.', 'Meu nome tem duas palavras e começa com "Vale".',
    ] },
    { answer: 'Malhação', clues: [
      'Estreei em 1995 na Globo, passando à tarde.', 'Meu cenário original era uma academia de ginástica no Rio.', 'Essa academia se chamava Malhação Club.', 'Depois passei a me passar num colégio, o Múltipla Escolha.',
      'Fui a novela mais longa da TV brasileira, com 27 temporadas.', 'Fui exibida por 25 anos seguidos.', 'Revelei dezenas de atores que hoje são famosos.', 'Fernanda Paes Leme, Bruna Marquezine e Marina Ruy Barbosa passaram por mim.',
      'Cada temporada tinha um subtítulo, como "Viva a Diferença" e "Sonhos".', 'Meu casal Mocotó e Bruna, e depois Bianca e Duca, marcaram gerações.', 'Meu vilão adolescente clássico era o Cabeção.', 'Minha vinheta trocava de música a cada temporada.',
      'Sou lembrada como "novela teen".', 'Minha turma tinha o "pega" no corredor do colégio.', 'Passava às 17h30 e todo adolescente assistia ao chegar da escola.', 'Fui interrompida em 2020 pela pandemia e não voltei.',
      'Meu nome vem de exercício físico.', 'Sou a novela de adolescentes da Globo.', 'Meu nome tem oito letras e começa com M.', 'Meu nome é sinônimo de "puxar ferro".',
    ] },
    { answer: 'Todo Mundo Odeia o Chris', clues: [
      'Fui inspirada na infância de um comediante americano.', 'Esse comediante é Chris Rock, que também me narra.', 'Estreei em 2005 nos Estados Unidos.', 'Minha história se passa no Brooklyn dos anos 80.',
      'Minha família mora num bairro chamado Bed-Stuy.', 'Meu pai trabalha em dois empregos e sabe o preço de tudo.', 'Ele diz "isso é 2 dólares de leite derramado no chão".', 'Minha mãe ameaça "isso é coisa de gente branca" e "não preciso desse emprego".',
      'Meu pai se chama Julius e minha mãe, Rochelle.', 'Meu irmão Drew é bom em tudo e a irmã Tonya é mimada.', 'Meu valentão da escola se chama Caruso.', 'Meu melhor amigo é o Greg, que é magro e branco.',
      'Meu vizinho do lado é o "Sr. Omar", que diz "trágico!".', 'Meu protagonista é o único negro numa escola de brancos.', 'No Brasil passei tanto na Record que virei parte da cultura pop.', 'Minha dublagem brasileira tem frases como "era só o que faltava".',
      'Tive 4 temporadas e terminei em 2009.', 'Sou uma sitcom sobre um adolescente negro nos anos 80.', 'Meu nome diz que ninguém gosta do protagonista.', 'Meu nome termina com o nome do protagonista.',
    ] },
  ],
};

module.exports = { CARDS10 };
