// Mais cartas do Perfil (lote 3). Mesma regra: 20 dicas, nenhuma entrega a resposta inteira.
const CARDS3 = {
  P: [
    { answer: 'Lionel Messi', clues: [
      'Nasci em Rosário, na Argentina, em 1987.', 'Tive um problema de crescimento e precisei de hormônios.', 'Um clube espanhol pagou meu tratamento e me levou aos 13 anos.', 'Meu primeiro contrato foi escrito num guardanapo.',
      'Cresci na La Masia, a escola do Barcelona.', 'Joguei 17 anos no Barcelona.', 'Fui campeão olímpico em 2008, em Pequim.', 'Ganhei oito Bolas de Ouro, o recorde.',
      'Sou chamado de "La Pulga", a pulga.', 'Fui para o PSG em 2021, chorando na despedida.', 'Joguei no Inter Miami, nos Estados Unidos.', 'Ganhei a Copa América de 2021 no Maracanã.',
      'Ganhei a Copa do Mundo de 2022, no Catar.', 'Fui o melhor jogador da Copa do Catar.', 'Uso a camisa 10 da Argentina.', 'Sou canhoto.',
      'Meu rival eterno é um português musculoso.', 'Meu primeiro nome termina com "el".', 'Meu sobrenome tem 5 letras e começa com M.', 'Sou o maior jogador argentino da história.',
    ] },
    { answer: 'Gisele Bündchen', clues: [
      'Nasci em Horizontina, no Rio Grande do Sul, em 1980.', 'Sou descendente de alemães e tenho cinco irmãs.', 'Fui descoberta num shopping em São Paulo, aos 13 anos.', 'Queria ser jogadora de vôlei.',
      'Fui a "modelo do ano" da Vogue em 1999.', 'Fui a primeira modelo brasileira de fama mundial.', 'Desfilei para a Victoria\'s Secret por anos.', 'Fui a modelo mais bem paga do mundo por 15 anos.',
      'Namorei Leonardo DiCaprio.', 'Fui casada com um quarterback de futebol americano.', 'Meu ex-marido se chama Tom Brady.', 'Tenho uma filha chamada Vivian e um filho chamado Benjamin.',
      'Andei na abertura das Olimpíadas do Rio, ao som de "Garota de Ipanema".', 'Sou ativista ambiental.', 'Escrevi um livro chamado "Aprendizados".', 'Sou chamada de "Gigi".',
      'Meu sobrenome é alemão e tem trema.', 'Meu primeiro nome começa com G e tem 6 letras.', 'Sou uma modelo gaúcha.', 'Sou a modelo brasileira mais famosa do mundo.',
    ] },
    { answer: 'Machado de Assis', clues: [
      'Nasci no Rio de Janeiro, em 1839, no Morro do Livramento.', 'Meu pai era pintor de paredes e minha mãe, lavadeira portuguesa.', 'Era neto de escravos alforriados.', 'Era gago e tinha epilepsia.',
      'Aprendi francês com um padeiro.', 'Comecei como aprendiz de tipógrafo.', 'Fui funcionário público a vida toda.', 'Casei com uma portuguesa chamada Carolina.',
      'Fundei a Academia Brasileira de Letras e fui o primeiro presidente.', 'Escrevi "Dom Casmurro", com o ciúme de Bentinho por Capitu.', 'Criei um defunto que escreve as próprias memórias.', 'Escrevi "Memórias Póstumas de Brás Cubas".',
      'Escrevi o conto "O Alienista".', 'Escrevi "Quincas Borba" e a filosofia do "Humanitismo".', 'Sou chamado de "Bruxo do Cosme Velho".', 'Sou o maior escritor brasileiro.',
      'Minha cadeira na Academia é a número 23.', 'Meu sobrenome é o de um santo e o de um utensílio.', 'Meu nome tem três palavras e começa com M.', 'Escrevi sobre os "olhos de ressaca" de Capitu.',
    ] },
    { answer: 'Elvis Presley', clues: [
      'Nasci em Tupelo, no Mississippi, em 1935.', 'Meu irmão gêmeo nasceu morto.', 'Cantei gospel na igreja quando criança.', 'Fui caminhoneiro antes de ficar famoso.',
      'Gravei meu primeiro disco de presente para minha mãe.', 'Fui descoberto pela gravadora Sun Records.', 'Meu rebolado foi censurado na TV: só filmavam da cintura para cima.', 'Servi o Exército na Alemanha.',
      'Minha casa se chama Graceland, em Memphis.', 'Casei com Priscilla e tive uma filha, Lisa Marie.', 'Fiz mais de 30 filmes em Hollywood.', 'Cantei "Hound Dog" e "Jailhouse Rock".',
      'Cantei "Can\'t Help Falling in Love" e "Suspicious Minds".', 'Usava macacões brancos com pedras em Las Vegas.', 'Meu topete e minhas costeletas viraram símbolo.', 'Morri em 1977, no banheiro, aos 42 anos.',
      'Muita gente jura que ainda estou vivo.', 'Sou chamado de "Rei do Rock".', 'Meu nome tem 5 letras e começa com E.', 'Sou o cantor americano do topete.',
    ] },
    { answer: 'Cleópatra', clues: [
      'Nasci em 69 a.C., em Alexandria.', 'Minha família era grega, da dinastia dos Ptolomeus.', 'Fui a primeira da minha família a falar a língua do povo egípcio.', 'Falava nove línguas.',
      'Casei com meus dois irmãos, como era o costume.', 'Fui expulsa do trono e voltei escondida num tapete.', 'Conquistei Júlio César para retomar o poder.', 'Tive um filho com César, chamado Cesarião.',
      'Depois me apaixonei por Marco Antônio.', 'Perdi a batalha de Ácio para Otaviano.', 'Me matei, dizem, com a picada de uma serpente.', 'Fui a última rainha do Egito.',
      'Shakespeare escreveu uma peça sobre mim.', 'Elizabeth Taylor me interpretou num filme caríssimo de 1963.', 'Minha maquiagem nos olhos virou lenda.', 'Sou a rainha egípcia mais famosa.',
      'Fui a sétima com o meu nome, oficialmente.', 'Meu nome tem 9 letras e começa com C.', 'Meu nome termina com "patra".', 'Sou a rainha da serpente.',
    ] },
    { answer: 'Luciano Huck', clues: [
      'Nasci em São Paulo, em 1971.', 'Sou formado em Direito.', 'Comecei numa produtora com o amigo Tande, do vôlei.', 'Meu primeiro programa foi na Band, o "H".',
      'Fui para a Globo em 2000.', 'Sou casado com uma apresentadora loira, mãe de três filhos meus.', 'Minha esposa é Angélica.', 'Meu programa tinha "Lata Velha" e "Lar Doce Lar".',
      'Também tinha "Agora ou Nunca" e "Quem Quer Ser um Milionário".', 'Falaram que eu seria candidato a presidente.', 'Comandei o "Caldeirão" aos sábados por 21 anos.', 'Assumi o domingo da Globo em 2021.',
      'Substituí Faustão no domingo.', 'Meu programa de domingo tem meu nome e um "Domingão".', 'Sou dono de uma marca de roupas surfwear.', 'Meu sobrenome é alemão e tem 4 letras.',
      'Meu primeiro nome começa com L e tem 7 letras.', 'Sou um apresentador da Globo.', 'Sou o apresentador do "Domingão".', 'Meu sobrenome rima com "truck".',
    ] },
    { answer: 'Beethoven', clues: [
      'Nasci em Bonn, na Alemanha, em 1770.', 'Meu pai me batia para eu praticar piano.', 'Meu pai queria que eu fosse um novo Mozart.', 'Me mudei para Viena aos 21 anos.',
      'Estudei com Haydn.', 'Nunca me casei, mas escrevi cartas para uma "Amada Imortal".', 'Comecei a ficar surdo aos 26 anos.', 'Compus minhas maiores obras quase sem ouvir nada.',
      'Cortei a serra do meu piano para sentir as vibrações no chão.', 'Dediquei uma sinfonia a Napoleão e depois rasguei a dedicatória.', 'Compus a sonata "Ao Luar".', 'Compus "Für Elise", tocada em todo teclado de brinquedo.',
      'Minha Nona Sinfonia tem o "Hino à Alegria", o hino da União Europeia.', 'Minha Quinta Sinfonia começa com "pa-pa-pa-pam".', 'Compus nove sinfonias.', 'Um cão São Bernardo de filme tem meu nome.',
      'Sou o compositor surdo.', 'Sou um compositor alemão.', 'Meu sobrenome tem 9 letras e começa com B.', 'Meu nome completo começa com Ludwig van.',
    ] },
    { answer: 'Shakira', clues: [
      'Nasci em Barranquilla, na Colômbia, em 1977.', 'Meu pai é de origem libanesa.', 'Meu nome significa "grata" em árabe.', 'Fui rejeitada no coral da escola porque minha voz parecia de cabra.',
      'Gravei meu primeiro disco aos 13 anos.', 'Fiquei famosa com "Estoy Aquí" e "Ciega, Sordomuda".', 'Meu primeiro disco em inglês foi "Laundry Service".', 'Cantei "Whenever, Wherever".',
      'Cantei a música da Copa de 2010, "Waka Waka".', 'Namorei o filho do presidente da Argentina.', 'Fui casada com o zagueiro Gerard Piqué.', 'Tenho dois filhos: Milan e Sasha.',
      'Fiz uma música de vingança contra o ex, com o Bizarrap.', 'Sou famosa pela dança do ventre.', 'Cantei "Hips Don\'t Lie" com Wyclef Jean.', 'Meus quadris não mentem.',
      'Sou a cantora colombiana mais famosa do mundo.', 'Meu nome tem 7 letras e começa com S.', 'Sou loira, mas nasci morena.', 'Sou a cantora do "Waka Waka".',
    ] },
    { answer: 'Tiradentes', clues: [
      'Nasci em Minas Gerais, em 1746.', 'Fiquei órfão aos 11 anos.', 'Fui tropeiro, minerador e alferes.', 'Meu nome verdadeiro é Joaquim José da Silva Xavier.',
      'Meu apelido vem de uma profissão que eu exercia nas horas vagas.', 'Arrancava dentes das pessoas.', 'Me inspirei na independência dos Estados Unidos.', 'Conspirei contra a cobrança da "derrama" de Portugal.',
      'Fui traído por Joaquim Silvério dos Reis.', 'Fui preso em 1789 no Rio de Janeiro.', 'Fiquei três anos na prisão.', 'Fui o único conspirador condenado à morte.',
      'Fui enforcado e esquartejado em 21 de abril de 1792.', 'Minha cabeça foi exposta em Vila Rica, hoje Ouro Preto.', 'Sou o mártir da Inconfidência Mineira.', 'Meu feriado é 21 de abril.',
      'Meu retrato de barba e túnica branca parece Jesus.', 'Uma cidade de Minas tem meu apelido.', 'Meu apelido junta "tira" e "dentes".', 'Sou o herói da Inconfidência.',
    ] },
    { answer: 'Zeca Pagodinho', clues: [
      'Nasci em Irajá, no Rio de Janeiro, em 1959.', 'Meu nome verdadeiro é Jessé Gomes da Silva Filho.', 'Cresci em Xerém, em Duque de Caxias.', 'Comecei nas rodas de samba do Cacique de Ramos.',
      'Beth Carvalho me lançou, gravando "Camarão Que Dorme a Onda Leva".', 'Cantei "Deixa a Vida Me Levar".', 'Fiz um comercial de cerveja e troquei de marca no meio da campanha.', 'A polêmica da cerveja virou piada nacional.',
      'Sou famoso por amar cerveja.', 'Cantei "Verdade" e "Vai Vadiar".', 'Cantei "Maneiras" e "Judia de Mim".', 'Tenho uma feijoada famosa em Xerém.',
      'Meu apelido vem do estilo musical que canto.', 'Sou sambista e pagodeiro.', 'Meu primeiro nome artístico é um diminutivo de José.', 'Sou torcedor do Flamengo.',
      'Meu apelido termina com "inho".', 'Meu sobrenome artístico é o nome de um ritmo.', 'Meu nome artístico começa com Z.', 'Sou o rei do pagode de raiz.',
    ] },
    { answer: 'Steve Jobs', clues: [
      'Nasci em São Francisco, em 1955, e fui adotado.', 'Meu pai biológico era sírio.', 'Larguei a faculdade depois de um semestre.', 'Fiz um curso de caligrafia que inspirou as fontes dos computadores.',
      'Fui para a Índia buscar iluminação.', 'Fundei uma empresa numa garagem com um amigo chamado Wozniak.', 'Fui demitido da minha própria empresa em 1985.', 'Comprei uma empresa de animação chamada Pixar.',
      'Voltei para minha empresa em 1997 e a salvei da falência.', 'Lancei o iPod, o iPhone e o iPad.', 'Usava sempre a mesma roupa: blusa preta de gola alta e jeans.', 'Minha frase famosa era "one more thing".',
      'Fui interpretado por Ashton Kutcher e Michael Fassbender no cinema.', 'Morri de câncer no pâncreas, em 2011.', 'Minha empresa tem o nome de uma fruta.', 'Fundei a Apple.',
      'Meu sobrenome significa "empregos" em inglês.', 'Meu primeiro nome é um diminutivo de Steven.', 'Meu nome tem 9 letras e começa com S.', 'Sou o criador do iPhone.',
    ] },
    { answer: 'Homem-Aranha', clues: [
      'Nasci em 1962, numa revista chamada "Amazing Fantasy".', 'Fui criado por Stan Lee e Steve Ditko.', 'Sou órfão e fui criado pelos tios.', 'Meu tio Ben morreu por minha culpa.',
      'Minha tia se chama May.', 'Fui picado por um animal radioativo numa excursão.', 'Sou um adolescente nerd de Nova York.', 'Trabalho como fotógrafo no Clarim Diário.',
      'Meu chefe se chama J. Jonah Jameson e me odeia.', 'Minha namorada é Mary Jane, ou Gwen Stacy.', 'Meus inimigos são o Duende Verde e o Doutor Octopus.', 'Tenho um sentido que avisa do perigo.',
      'Minha frase é "com grandes poderes vêm grandes responsabilidades".', 'Solto teias dos pulsos.', 'Subo em paredes.', 'Uso um uniforme vermelho e azul.',
      'Meu nome verdadeiro é Peter Parker.', 'Sou um herói da Marvel.', 'Meu nome tem hífen e começa com "Homem".', 'Sou o herói do "amigão da vizinhança".',
    ] },
  ],
  L: [
    { answer: 'Veneza', clues: [
      'Fui fundada por refugiados que fugiam dos bárbaros.', 'Fui construída sobre estacas de madeira fincadas na lagoa.', 'Fui uma república poderosa por mil anos.', 'Marco Polo saiu de mim para a China.',
      'Tenho 118 ilhas ligadas por mais de 400 pontes.', 'Não tenho carros.', 'Meu governante se chamava doge.', 'Meu carnaval tem máscaras famosas.',
      'Tenho um festival de cinema com o Leão de Ouro.', 'Tenho uma ponte com lojas em cima, a Rialto.', 'Tenho a Ponte dos Suspiros.', 'Minha praça mais famosa é a de São Marcos, cheia de pombos.',
      'Estou afundando alguns milímetros por ano.', 'Minha "acqua alta" alaga a praça.', 'Meus barcos são pretos e compridos, com um remador.', 'Minhas ruas são canais.',
      'Sou a cidade das gôndolas.', 'Fico no nordeste da Itália.', 'Meu nome tem 6 letras e começa com V.', 'Sou a cidade que fica na água.',
    ] },
    { answer: 'Brasília', clues: [
      'Já estava prevista na Constituição de 1891.', 'Dom Bosco sonhou comigo no século 19.', 'Fui construída em 41 meses.', 'Fui feita no meio do cerrado, longe de tudo.',
      'Fui inaugurada em 21 de abril de 1960.', 'Fui o sonho de Juscelino Kubitschek.', 'Fui desenhada por Lúcio Costa e Oscar Niemeyer.', 'Meu formato visto de cima parece um avião ou uma borboleta.',
      'Meus bairros se chamam quadras e asas.', 'Meus operários foram chamados de candangos.', 'Tenho uma catedral com colunas curvas.', 'Tenho um lago artificial chamado Paranoá.',
      'Tenho o Palácio da Alvorada e o Palácio do Planalto.', 'Tenho um prédio com duas torres e duas cúpulas, uma para cima e outra para baixo.', 'O Congresso Nacional fica em mim.', 'Sou Patrimônio da Humanidade.',
      'Sou a capital do Brasil.', 'Fico no Distrito Federal.', 'Meu nome vem do nome do país.', 'Sou a capital que fica no Planalto Central.',
    ] },
    { answer: 'Muralha da China', clues: [
      'Comecei a ser construída no século 7 a.C.', 'Fui unida pelo primeiro imperador, Qin Shi Huang.', 'A maior parte de mim é da dinastia Ming.', 'Fui feita de terra, pedra, tijolos e até arroz na argamassa.',
      'Fui construída para barrar os mongóis e outros nômades.', 'Milhares de trabalhadores morreram me construindo.', 'Tenho torres de vigia a cada poucos metros.', 'Tenho mais de 20 mil quilômetros, contando todos os trechos.',
      'Dizem que sou visível da Lua, mas é mentira.', 'Sou uma das sete maravilhas do mundo moderno.', 'Meus trechos mais visitados ficam perto de Pequim.', 'Sou Patrimônio da Humanidade.',
      'Serpenteio por montanhas.', 'Sou a maior construção humana do mundo.', 'Sou uma parede gigante.', 'Fico no país mais populoso da Ásia.',
      'Sou chinesa.', 'Meu nome tem "China".', 'Meu nome começa com M.', 'Sou a muralha mais famosa do mundo.',
    ] },
    { answer: 'Copacabana', clues: [
      'Meu nome vem de uma santa boliviana.', 'Era uma praia isolada até o túnel de 1892.', 'Tenho um forte militar numa das pontas.', 'Meu hotel mais famoso é um palácio branco de 1923.',
      'Um hotel branco famoso, onde ficam as celebridades, fica em mim.', 'Minha calçada tem ondas de pedras portuguesas.', 'Meu calçadão foi desenhado por Burle Marx.', 'Meu réveillon reúne 2 milhões de pessoas.',
      'Meu réveillon tem fogos e roupa branca.', 'Rod Stewart fez um show para 3,5 milhões de pessoas em mim.', 'Madonna fez um show gratuito em mim em 2024.', 'Meu bairro é apelidado de "Princesinha do Mar".',
      'Tenho 4 km de extensão.', 'Barry Manilow fez uma música com meu nome.', 'Fico entre o Leme e o Arpoador.', 'Sou uma praia do Rio de Janeiro.',
      'Sou a praia mais famosa do Brasil.', 'Meu nome tem 10 letras.', 'Meu nome começa com "Copa".', 'Sou a praia do réveillon.',
    ] },
    { answer: 'Austrália', clues: [
      'Fui "descoberta" pelos holandeses, mas colonizada pelos ingleses.', 'Fui usada como colônia de prisioneiros.', 'Meus primeiros habitantes, os aborígenes, estão aqui há 60 mil anos.', 'Sou o único país que ocupa um continente inteiro.',
      'Tenho mais ovelhas que gente.', 'Tenho mais cangurus que pessoas.', 'Minha capital não é Sydney, é Camberra.', 'Tenho a maior barreira de corais do mundo.',
      'Tenho uma pedra sagrada gigante no meio do deserto, o Uluru.', 'Meus animais incluem coala, ornitorrinco e diabo-da-tasmânia.', 'Tenho as aranhas e cobras mais venenosas do mundo.', 'Sediei as Olimpíadas de 1956 e 2000.',
      'Meu teatro de ópera parece velas de barco.', 'Minha maior cidade é Sydney.', 'Meu Natal é no verão.', 'Meu apelido é "Oz" ou "Down Under".',
      'Sou o país dos cangurus.', 'Sou uma ilha-continente.', 'Meu nome começa com A e termina com "ália".', 'Sou o maior país da Oceania.',
    ] },
    { answer: 'Pão de Açúcar', clues: [
      'Sou um monólito de granito de 396 metros.', 'Meu nome vem do formato dos blocos de açúcar da época colonial.', 'Ou, dizem, do tupi "pau-nh-açuquã", "monte alto".', 'Fico na entrada da Baía de Guanabara.',
      'Meu vizinho menor é o Morro da Urca.', 'Meu bondinho foi inaugurado em 1912.', 'Fui o terceiro teleférico do mundo.', 'James Bond lutou no meu bondinho em "007 Contra o Foguete da Morte".',
      'Sou famoso para a escalada.', 'Tenho vista para a praia Vermelha e para o Cristo.', 'Meu bondinho anda em duas etapas.', 'Micos e tucanos vivem em mim.',
      'Sou um dos dois cartões-postais mais famosos do Rio.', 'Fico no bairro da Urca.', 'Meu nome é o mesmo de uma rede de supermercados.', 'Meu nome é um doce e um alimento.',
      'Fico no Rio de Janeiro.', 'Meu nome tem 3 palavras.', 'Meu nome começa com "Pão".', 'Sou o morro do bondinho.',
    ] },
    { answer: 'Índia', clues: [
      'Sou o berço do budismo e do hinduísmo.', 'Inventei o zero e o xadrez.', 'Fui uma colônia britânica até 1947.', 'Gandhi me libertou com a não-violência.',
      'Tenho mais de 20 línguas oficiais.', 'Sou o país mais populoso do mundo desde 2023.', 'Meus filmes são feitos em Bollywood.', 'Minhas vacas são sagradas.',
      'Minhas mulheres usam sari e um ponto na testa.', 'Meu festival das cores é o Holi.', 'Meu rio sagrado é o Ganges.', 'Tenho o Taj Mahal, um mausoléu de mármore branco.',
      'Meu prato mais famoso é o curry.', 'Minha capital é Nova Délhi.', 'Meu maior esporte é o críquete.', 'Fico no sul da Ásia.',
      'Cabral pensava que ia para mim quando chegou ao Brasil.', 'Sou o país do Taj Mahal.', 'Meu nome tem 5 letras e começa com Í.', 'Sou o país mais populoso do mundo.',
    ] },
    { answer: 'Ilha de Páscoa', clues: [
      'Fui batizada por um holandês que chegou a mim num domingo de festa religiosa.', 'Meu nome nativo é Rapa Nui.', 'Sou a ilha habitada mais isolada do mundo.', 'Fico a 3.700 km da costa mais próxima.',
      'Fui colonizada por polinésios há mil anos.', 'Meus habitantes derrubaram todas as árvores.', 'Pertenço ao Chile desde 1888.', 'Tenho três vulcões extintos.',
      'Tenho um alfabeto próprio que ninguém sabe ler, o rongorongo.', 'Tenho quase mil estátuas gigantes de pedra.', 'Minhas estátuas se chamam moais.', 'Meus moais têm cabeças enormes e olham para dentro da ilha.',
      'Ninguém sabe ao certo como os moais foram carregados.', 'Fico no Oceano Pacífico.', 'Sou chilena.', 'Sou Patrimônio da Humanidade.',
      'Sou a ilha das estátuas de pedra.', 'Meu nome tem a ver com uma festa cristã.', 'Meu nome começa com "Ilha".', 'Sou a ilha dos moais.',
    ] },
    { answer: 'Alasca', clues: [
      'Fui comprado da Rússia em 1867 por 7,2 milhões de dólares.', 'A compra foi chamada de "loucura de Seward".', 'Descobriram ouro em mim em 1896.', 'Virei estado americano em 1959, o 49º.',
      'Sou o maior estado dos Estados Unidos.', 'Sou maior que o Texas, a Califórnia e Montana juntos.', 'Tenho a montanha mais alta da América do Norte, o Denali.', 'Não faço fronteira com nenhum outro estado americano.',
      'Faço fronteira com o Canadá e quase toco a Rússia.', 'Minha capital, Juneau, não tem estrada de acesso.', 'Minha maior cidade é Anchorage.', 'Tenho ursos, alces e salmões.',
      'Tenho o Sol da meia-noite no verão.', 'A aurora boreal aparece em mim.', 'Minha corrida de trenós com cães se chama Iditarod.', 'Fico congelado boa parte do ano.',
      'Sou o estado gelado dos Estados Unidos.', 'Meu nome tem 6 letras e começa com A.', 'Meu nome termina com "asca".', 'Sou o estado americano do Ártico.',
    ] },
    { answer: 'Torre Eiffel', clues: [
      'Fui construída para a Exposição Universal de 1889.', 'Fui feita para durar só 20 anos.', 'Os artistas de Paris me odiavam e me chamavam de "monstro de ferro".', 'Fui salva porque servia como antena de rádio.',
      'Tenho 330 metros de altura.', 'Fui a estrutura mais alta do mundo por 41 anos.', 'Tenho 18 mil peças de ferro e 2,5 milhões de rebites.', 'Sou pintada a cada sete anos, com 60 toneladas de tinta.',
      'Cresço 15 centímetros no calor.', 'Santos Dumont deu a volta em mim com um dirigível.', 'Hitler quis me visitar, mas cortaram os cabos do elevador.', 'Brilho com luzes piscantes a cada hora à noite.',
      'Tenho três andares e um restaurante.', 'Sou o monumento pago mais visitado do mundo.', 'Tenho o nome do engenheiro que me construiu.', 'Fico às margens do rio Sena.',
      'Fico em Paris.', 'Sou uma torre de ferro.', 'Meu nome começa com "Torre".', 'Sou o símbolo da França.',
    ] },
    { answer: 'Lençóis Maranhenses', clues: [
      'Sou um parque nacional criado em 1981.', 'Tenho 155 mil hectares de dunas.', 'Não sou um deserto: chove muito em mim.', 'Minhas lagoas aparecem entre as dunas na época das chuvas.',
      'Minhas lagoas são azuis e verdes e somem na seca.', 'A Lagoa Azul e a Lagoa Bonita são minhas.', 'Peixes aparecem nas minhas lagoas, vindos de ovos que sobrevivem na areia.', 'Chega-se a mim pela cidade de Barreirinhas.',
      'Se visita com jipe 4x4 e a pé.', 'Minhas dunas parecem lençóis brancos estendidos, vistos de cima.', 'Fico na costa nordeste do Brasil.', 'Fico a 250 km de São Luís.',
      'Sou Patrimônio da Humanidade desde 2024.', 'Sou tão diferente que pareço outro planeta nas fotos.', 'Sou o cenário de fotos mais surreal do Brasil.', 'Fico no Maranhão.',
      'Meu nome tem a ver com roupa de cama.', 'Meu nome tem duas palavras.', 'Meu nome começa com L.', 'Sou as dunas com lagoas do Maranhão.',
    ] },
    { answer: 'Dubai', clues: [
      'Era uma vila de pescadores de pérolas há 60 anos.', 'Descobri petróleo em 1966.', 'Meu petróleo já quase acabou; vivo de turismo e negócios.', 'Sou um dos sete emirados de um país.',
      'Fico nos Emirados Árabes Unidos.', 'Tenho um hotel em forma de vela de barco, o Burj Al Arab.', 'Tenho ilhas artificiais em forma de palmeira.', 'Tenho uma pista de esqui dentro de um shopping.',
      'Tenho o maior shopping do mundo.', 'Tenho o prédio mais alto do mundo, com 828 metros.', 'O Burj Khalifa fica em mim.', 'Meus policiais dirigem Lamborghinis.',
      'Sou a cidade dos influenciadores e dos luxos.', 'Fica 45 graus no verão em mim.', 'Muitos brasileiros trabalham em mim.', 'Fico no Golfo Pérsico.',
      'Sou uma cidade árabe.', 'Meu nome tem 5 letras e começa com D.', 'Meu nome termina com "bai".', 'Sou a cidade do prédio mais alto do mundo.',
    ] },
  ],
  C: [
    { answer: 'Fósforo', clues: [
      'Meu nome vem do grego "portador de luz".', 'Também sou um elemento químico, o número 15.', 'Fui inventado na Inglaterra em 1826, por um farmacêutico.', 'Meus primeiros modelos acendiam sozinhos e envenenavam os trabalhadores.',
      'Minha versão "de segurança" é sueca.', 'Sou feito de madeira ou papelão, com uma cabeça química.', 'Preciso ser riscado numa lixa.', 'Minha marca mais famosa no Brasil é a Fiat Lux.',
      'Venho em caixinhas com 40 unidades.', 'Fui substituído pelo isqueiro.', 'Uma menina vendendo eu virou conto de Andersen.', 'Sou usado para acender o fogão e a vela.',
      'Meu palito queima rápido.', 'Sou um palito com cabeça vermelha.', 'Não posso ficar perto de crianças.', 'Faço fogo.',
      'Meu nome tem 7 letras e começa com F.', 'Meu nome termina com "foro".', 'Sou o palito que acende.', 'Sou o palito de fogo.',
    ] },
    { answer: 'Balão', clues: [
      'Meu ancestral era de papel e usado na China antiga.', 'Os irmãos Montgolfier me fizeram voar com pessoas em 1783.', 'Minha primeira tripulação foi uma ovelha, um pato e um galo.', 'Santos Dumont começou voando em mim.',
      'Posso ser de ar quente ou de gás hélio.', 'Sou o símbolo de festa de aniversário.', 'Estouro com alfinete.', 'Minha versão de festa é de látex.',
      'Faço voz fina quando o gás é inalado.', 'Posso ser feito de ar quente com um cesto.', 'Sou proibido no Brasil na versão de festa junina, porque causo incêndios.', 'Sou soltado em junho e é crime.',
      'Enfeito festas de criança.', 'Sou enchido com a boca ou com bomba.', 'Palhaços me transformam em cachorrinhos.', 'Flutuo.',
      'Sou de borracha e cheio de ar.', 'Meu nome tem 5 letras e começa com B.', 'Meu nome termina com "ão".', 'Sou o brinquedo que voa e estoura.',
    ] },
    { answer: 'Espelho', clues: [
      'Meu ancestral era uma poça de água parada.', 'Fui feito de bronze e prata polidos na Antiguidade.', 'Veneza me fabricou em vidro, no século 16, e guardou o segredo.', 'Quebrar-me dá sete anos de azar.',
      'Uma rainha má perguntava para mim quem era a mais bela.', 'Narciso morreu olhando um reflexo, como o meu.', 'Sou uma camada de prata ou alumínio atrás de um vidro.', 'Alice passou por mim para outro mundo.',
      'Inverto a esquerda e a direita.', 'Existo côncavo e convexo em telescópios.', 'Vampiros não aparecem em mim.', 'Fico embaçado depois do banho.',
      'Fico em banheiros, quartos e carros.', 'Tenho versão retrovisor.', 'Sou usado para se pentear e se maquiar.', 'Mostro seu rosto.',
      'Reflito imagens.', 'Meu nome tem 7 letras e começa com E.', 'Meu nome termina com "elho".', 'Sou o objeto onde você se vê.',
    ] },
    { answer: 'Bicicleta ergométrica', clues: [
      'Nasci no fim do século 18, como uma máquina de ginástica para nobres.', 'Minha versão moderna apareceu nos anos 1960.', 'Não saio do lugar.', 'Tenho pedais, selim e guidão, mas nenhuma roda no chão.',
      'Meço distância, tempo e calorias.', 'Tenho um botão de resistência.', 'Sou usada em aulas de spinning com música alta.', 'Existo em quase toda academia.',
      'Muita gente me compra e me usa de cabideiro.', 'Fico em frente à TV em muitas casas.', 'Sou boa para o joelho porque não tenho impacto.', 'Alguns modelos têm tela e aulas ao vivo.',
      'Sou um aparelho de exercício.', 'Simulo uma bicicleta.', 'Não ando.', 'Sou pedalada dentro de casa.',
      'Meu nome tem duas palavras.', 'A segunda palavra do meu nome vem do grego "medida do trabalho".', 'Meu nome começa com B.', 'Sou a bicicleta que fica parada.',
    ] },
    { answer: 'Panela de pressão', clues: [
      'Fui inventada por um francês chamado Denis Papin, em 1679.', 'Fui apresentada à Sociedade Real de Londres com um jantar.', 'Minha versão doméstica apareceu nos anos 1930.', 'Fiquei popular na Segunda Guerra, para economizar gás.',
      'Cozinho a 120 graus, mais que a água fervente.', 'Tenho uma borracha na tampa que veda tudo.', 'Tenho uma válvula que apita e gira.', 'Nunca devo ser aberta com vapor dentro.',
      'Já explodi em muitas cozinhas.', 'Cozinho feijão em 20 minutos.', 'Faço a carne desmanchar.', 'Meu apito assusta quem não está acostumado.',
      'Sou de alumínio ou de inox.', 'Tenho versão elétrica agora.', 'Sou uma panela.', 'Tenho tampa que trava.',
      'Cozinho com vapor preso.', 'Meu nome tem três palavras.', 'Meu nome começa com "Panela".', 'Sou a panela que apita.',
    ] },
    { answer: 'Escova de dentes', clues: [
      'Os babilônios usavam gravetos mastigados no meu lugar.', 'Minha primeira versão com cerdas foi chinesa, com pelos de porco.', 'Fui produzida em massa na Inglaterra em 1780, por um prisioneiro.', 'Minhas cerdas de náilon apareceram em 1938.',
      'Os soldados americanos me popularizaram depois da Segunda Guerra.', 'Devo ser trocada a cada 3 meses.', 'Devo ser usada 3 vezes por dia.', 'Existo em versão elétrica.',
      'Tenho cerdas macias, médias ou duras.', 'Combino com um creme com flúor.', 'Sou levada em toda viagem.', 'Não devo ser emprestada.',
      'Fico num copo no banheiro.', 'Tenho um cabo e uma cabeça com cerdas.', 'Sou usada com pasta.', 'Limpo a boca.',
      'Sou usada de manhã e antes de dormir.', 'Meu nome tem três palavras.', 'Meu nome começa com "Escova".', 'Sou a escova da boca.',
    ] },
    { answer: 'Chave', clues: [
      'Meu ancestral egípcio era de madeira e do tamanho de um braço.', 'Os romanos me faziam de bronze e me usavam como anel.', 'Minha versão moderna, com pinos, é de Linus Yale, em 1861.', 'Sou copiada em lojinhas de rua por poucos reais.',
      'Tenho versão de fenda e de boca, para apertar parafusos.', 'Também sou uma peça da eletricidade, que liga e desliga a luz.', 'Existo em versão de carro com botão.', 'Sou pendurada em argolas com enfeites.',
      'Quem perde a mim fica trancado fora de casa.', 'Tenho versão "mestra", que abre tudo.', 'Muita gente me esconde embaixo do tapete.', 'Vivo perdida no fundo da bolsa.',
      'Sou de metal e tenho dentes.', 'Entro numa fechadura.', 'Abro portas.', 'Também abro cadeados e carros.',
      'Sou dada ao comprador de uma casa nova.', 'Meu nome tem 5 letras e começa com C.', 'Meu nome termina com "ave".', 'Sou o que abre a porta.',
    ] },
    { answer: 'Cerveja', clues: [
      'Sou mais velha que o pão, segundo alguns.', 'Os sumérios me faziam há 6 mil anos e tinham uma deusa para mim.', 'Os egípcios pagavam os trabalhadores das pirâmides comigo.', 'Uma lei alemã de 1516 diz que só posso ter água, malte e lúpulo.',
      'Sou feita de cevada germinada.', 'Meu amargor vem do lúpulo.', 'Fermento com levedura.', 'Cheguei ao Brasil com a família real.',
      'A Oktoberfest é minha festa, na Alemanha e em Blumenau.', 'Minhas versões são pilsen, IPA, stout e weiss.', 'Zeca Pagodinho é meu maior fã.', 'No Brasil, gosto de ser "estupidamente gelada".',
      'Sou vendida em lata, garrafa e barril.', 'Faço espuma, o colarinho.', 'Meu "preço" no bar é polêmico.', 'Sou a bebida alcoólica mais consumida do mundo.',
      'Sou loira, ruiva ou preta.', 'Meu nome tem 7 letras e começa com C.', 'Meu apelido é "breja", "gelada" ou "loira".', 'Sou a bebida do churrasco.',
    ] },
    { answer: 'Micro-ondas', clues: [
      'Fui inventado por acidente em 1945.', 'Um engenheiro percebeu que uma barra de chocolate derreteu no bolso perto de um radar.', 'Percy Spencer é meu inventor.', 'Meu primeiro modelo pesava 340 kg.',
      'Cheguei às casas americanas nos anos 1970.', 'Aqueço a comida fazendo as moléculas de água vibrarem.', 'Não posso receber metal dentro.', 'Não posso aquecer ovo com casca: ele explode.',
      'Tenho um prato que gira.', 'Faço "bip" quando termino.', 'Minha porta tem uma grade metálica no vidro.', 'Faço pipoca em 3 minutos.',
      'Esquento o café e a marmita.', 'Fico na cozinha, em cima da bancada.', 'Sou um forno.', 'Descongelo comida.',
      'Uso ondas de rádio de alta frequência.', 'Meu nome tem hífen.', 'Meu nome começa com "Micro".', 'Sou o forno rápido.',
    ] },
    { answer: 'Guarda-chuva', clues: [
      'Nasci no Egito e na China antigos, para proteger do sol.', 'Os nobres tinham escravos para me segurar.', 'Fui considerado coisa de mulher na Europa por séculos.', 'Um inglês chamado Jonas Hanway me popularizou entre os homens, no século 18.',
      'Minha versão dobrável é de 1928.', 'Sou feito de tecido e varetas.', 'Abrir-me dentro de casa dá azar.', 'Viro do avesso no vento.',
      'Sou esquecido em todo lugar.', 'Sou vendido por camelôs em dias de chuva.', 'Mary Poppins voava com um.', 'Minha versão de praia é enorme e fica na areia.',
      'Meu irmão de sol se chama sombrinha.', 'Tenho um cabo curvo ou reto.', 'Abro e fecho.', 'Protejo da chuva.',
      'Sou levado em dias nublados.', 'Meu nome tem hífen e duas palavras.', 'Meu nome começa com "Guarda".', 'Sou o objeto da chuva.',
    ] },
    { answer: 'Ovo', clues: [
      'Sou o começo de todo pássaro.', 'Discutem se eu ou a galinha viemos primeiro.', 'Tenho uma casca de cálcio com milhares de poros.', 'Tenho clara e gema.',
      'Minha gema é rica em colesterol e vitaminas.', 'Um brasileiro come mais de 240 de mim por ano.', 'Posso ser de galinha, de codorna ou de avestruz.', 'Sou vendido em dúzia.',
      'Existo em versão de chocolate na Páscoa.', 'Fico chocado se ficar velho.', 'Sou quebrado na cabeça em brincadeiras.', 'Posso ser frito, cozido, mexido ou pochê.',
      'Sou a base do bolo e da omelete.', 'Sou branco ou marrom por fora.', 'Sou o alimento mais barato e completo.', 'Sou o café da manhã de quem faz academia.',
      'Sou amarelo por dentro.', 'Meu nome tem 3 letras.', 'Meu nome começa com O.', 'Sou o que a galinha põe.',
    ] },
    { answer: 'Carnaval', clues: [
      'Meu nome vem do latim "adeus à carne".', 'Sou a festa antes do jejum da Quaresma.', 'Cheguei ao Brasil com os portugueses, como "entrudo": guerra de água e farinha.', 'Meu primeiro baile no Brasil foi em 1840.',
      'Minhas marchinhas nasceram no começo do século 20.', 'Meus blocos de rua tomam as cidades.', 'Minha versão em Veneza tem máscaras.', 'Minha versão em Nova Orleans se chama Mardi Gras.',
      'Em Salvador, tenho trios elétricos e abadás.', 'Em Olinda, tenho bonecos gigantes e frevo.', 'Em Recife, tenho o Galo da Madrugada.', 'No Rio, tenho o Sambódromo.',
      'Minhas escolas de samba desfilam a noite inteira.', 'Sou julgado com notas de 9,7 a 10.', 'Termino na Quarta-feira de Cinzas.', 'Sou quatro dias de folia.',
      'Meu apelido é "a maior festa do mundo".', 'Meu nome tem 8 letras e começa com C.', 'Meu nome termina com "aval".', 'Sou a festa do samba e da fantasia.',
    ] },
  ],
  A: [

    { answer: '1930', clues: [
      'Neste ano Plutão foi descoberto.', 'Neste ano nasceu Neil Armstrong.', 'Neste ano nasceu Silvio Santos.', 'Gandhi fez a Marcha do Sal na Índia em mim.',
      'O mundo vivia a Grande Depressão em mim.', 'O primeiro Oscar de "Melhor Filme" para um filme falado foi em mim.', 'O Chile, a Argentina e o Uruguai disputavam a primeira Copa.', 'A primeira Copa do Mundo foi em mim, no Uruguai.',
      'O Uruguai ganhou a primeira Copa, contra a Argentina.', 'O Brasil foi eliminado na primeira fase da primeira Copa.', 'Júlio Prestes foi eleito presidente do Brasil, mas não tomou posse.', 'João Pessoa foi assassinado em mim, na Paraíba.',
      'Uma revolução saiu do Rio Grande do Sul em outubro de mim.', 'Os gaúchos amarraram os cavalos no obelisco do Rio.', 'Getúlio Vargas tomou o poder em mim.', 'A República Velha acabou em mim.',
      'Sou o ano da Revolução de 30.', 'Sou o ano da primeira Copa do Mundo.', 'Sou um ano redondo dos anos 30.', 'Termino com 30.',
    ] },
    { answer: '2001', clues: [
      'Neste ano a Wikipédia foi criada.', 'O primeiro iPod foi lançado em mim.', 'O primeiro filme de Harry Potter estreou em mim.', 'O primeiro "Senhor dos Anéis" estreou em mim.',
      'O filme "Shrek" é de mim.', 'A Argentina quebrou e teve cinco presidentes em duas semanas.', 'A China entrou na Organização Mundial do Comércio.', 'No Brasil, foi o ano do apagão e do racionamento de energia.',
      'Fernando Henrique Cardoso era presidente do Brasil.', 'Em mim o Brasil perdeu Cássia Eller.', 'George W. Bush tomou posse em janeiro de mim.', 'Em setembro de mim, aviões foram sequestrados nos Estados Unidos.',
      'Duas torres caíram em Nova York em mim.', 'O Pentágono também foi atingido.', 'Quase 3 mil pessoas morreram nos ataques.', 'Os Estados Unidos invadiram o Afeganistão em outubro de mim.',
      'Sou o ano do 11 de setembro.', 'Sou o primeiro ano do século 21, oficialmente.', 'Meus dígitos são 2, 0, 0 e 1.', 'Termino com 01.',
    ] },
    { answer: '1954', clues: [
      'Neste ano nasceram Oprah Winfrey e Jackie Chan.', 'O primeiro filme do Godzilla saiu em mim, no Japão.', 'Elvis Presley gravou seu primeiro single em mim.', 'A Suprema Corte dos Estados Unidos acabou com a segregação nas escolas.',
      'A Copa do Mundo foi na Suíça, e a Alemanha venceu.', 'O Brasil perdeu para a Hungria numa partida violenta, a "Batalha de Berna".', 'A cidade de São Paulo comemorou 400 anos em mim.', 'O Parque Ibirapuera foi inaugurado em mim, no aniversário de São Paulo.',
      'A TV Globo ainda não existia; a Tupi dominava.', 'Carlos Lacerda sofreu um atentado na rua Tonelero, no Rio.', 'Um major da Aeronáutica morreu no atentado.', 'Os militares pediram a renúncia do presidente.',
      'O presidente escreveu uma carta-testamento em mim.', 'Getúlio Vargas se matou em 24 de agosto de mim.', '"Saio da vida para entrar na história" foi escrito em mim.', 'Café Filho assumiu a presidência em mim.',
      'Sou o ano do suicídio de Getúlio.', 'Sou um ano dos anos 50.', 'Meus dígitos são 1, 9, 5 e 4.', 'Termino com 54.',
    ] },
    { answer: '1492', clues: [
      'Neste ano Granada, o último reino mouro da Espanha, foi conquistada.', 'Os judeus foram expulsos da Espanha em mim.', 'A primeira gramática de uma língua moderna, o castelhano, foi publicada em mim.', 'Os reis católicos Fernando e Isabel governavam a Espanha.',
      'Um navegador genovês convenceu os reis a financiar uma viagem.', 'Três caravelas saíram de Palos em agosto de mim.', 'Os navios se chamavam Niña, Pinta e Santa Maria.', 'A viagem durou mais de dois meses.',
      'Um marinheiro gritou "terra!" em 12 de outubro de mim.', 'A terra vista era uma ilha das Bahamas.', 'O navegador pensou ter chegado às Índias.', 'Por isso os nativos foram chamados de "índios".',
      'Cristóvão Colombo chegou à América em mim.', 'Sou o ano do "descobrimento" da América.', 'Sou o ano em que a Idade Média acabou, para os historiadores.', 'Sou o ano do fim da Reconquista espanhola.',
      'Sou um ano do fim do século 15.', 'Sou um ano bissexto.', 'Meus dígitos são 1, 4, 9 e 2.', 'Termino com 92.',
    ] },
    { answer: '1974', clues: [
      'Neste ano Richard Nixon renunciou por causa do escândalo de Watergate.', 'A Revolução dos Cravos acabou com a ditadura em Portugal, em abril de mim.', 'O grupo ABBA venceu o Eurovision com "Waterloo" em mim.', 'O Exército de Terracota foi descoberto na China em mim.',
      'Muhammad Ali venceu George Foreman no Zaire, na "luta do século".', 'A Copa do Mundo foi na Alemanha Ocidental.', 'A Holanda de Cruyff encantou com o "carrossel holandês".', 'A Alemanha venceu a Holanda na final.',
      'O Brasil ficou em quarto lugar na Copa, sem Pelé.', 'A ponte Rio-Niterói foi inaugurada em mim.', 'Ernesto Geisel assumiu a presidência do Brasil em mim.', 'A "abertura lenta, gradual e segura" começou em mim.',
      'O jornalista Vladimir Herzog seria morto no ano seguinte.', 'Fui um ano de crise do petróleo no mundo.', 'Sou o ano da Copa da Alemanha e da Laranja Mecânica.', 'Sou o ano da ponte Rio-Niterói.',
      'Sou um ano dos anos 70.', 'Sou um ano par.', 'Meus dígitos são 1, 9, 7 e 4.', 'Termino com 74.',
    ] },
    { answer: '2012', clues: [
      'Neste ano o mundo ia acabar, segundo o calendário maia. Não acabou.', 'O Facebook comprou o Instagram e abriu capital em mim.', 'Um homem pulou de paraquedas da estratosfera em mim.', 'O "Gangnam Style" foi o primeiro vídeo com 1 bilhão de visualizações.',
      'Barack Obama foi reeleito em mim.', 'O filme "Os Vingadores" estreou em mim.', 'O bóson de Higgs foi confirmado em mim.', 'No Brasil, o Corinthians ganhou a Libertadores e o Mundial em mim.',
      'A Copa do Mundo seria dois anos depois de mim, no Brasil.', 'A "Avenida Brasil" parou o país com a Carminha.', 'Em mim o Brasil aprovou as cotas nas universidades federais.', 'O julgamento do mensalão aconteceu em mim.',
      'As Olimpíadas foram em Londres.', 'Usain Bolt e Michael Phelps brilharam em Londres.', 'A rainha Elizabeth "pulou" de helicóptero com James Bond na abertura.', 'Sou o ano do fim do mundo que não aconteceu.',
      'Sou um ano bissexto.', 'Sou um ano da década de 2010.', 'Meus dígitos são 2, 0, 1 e 2.', 'Termino com 12.',
    ] },
    { answer: '1960', clues: [
      'Neste ano nasceram Diego Maradona e Ayrton Senna.', 'A pílula anticoncepcional foi aprovada em mim.', 'O filme "Psicose", de Hitchcock, é de mim.', 'John Kennedy foi eleito presidente dos Estados Unidos em mim.',
      'O primeiro debate de TV entre candidatos foi em mim.', 'Dezessete países africanos ficaram independentes em mim.', 'O terremoto mais forte já medido aconteceu no Chile, em mim.', 'As Olimpíadas foram em Roma.',
      'Em mim o Brasil vivia os "anos dourados" da bossa nova.', 'Juscelino Kubitschek era o presidente.', 'Jânio Quadros foi eleito com uma vassoura como símbolo.', 'Uma cidade foi inaugurada no meio do cerrado em abril de mim.',
      'A capital do Brasil mudou de cidade em mim.', 'O Rio de Janeiro deixou de ser capital em mim.', 'Brasília foi inaugurada em 21 de abril de mim.', 'Sou o ano da inauguração de Brasília.',
      'Sou o primeiro ano dos anos 60.', 'Sou um ano bissexto.', 'Meus dígitos são 1, 9, 6 e 0.', 'Termino com 60.',
    ] },
    { answer: '1932', clues: [
      'Neste ano Amelia Earhart cruzou o Atlântico sozinha de avião.', 'O bebê do aviador Lindbergh foi sequestrado em mim.', 'Franklin Roosevelt foi eleito presidente dos Estados Unidos em mim.', 'Neste ano o Brasil deu o direito de voto às mulheres.',
      'O Código Eleitoral de mim criou a Justiça Eleitoral.', 'As Olimpíadas foram em Los Angeles.', 'Santos Dumont morreu em julho de mim.', 'O Cristo Redentor tinha sido inaugurado no ano anterior.',
      'Getúlio Vargas governava o Brasil como chefe provisório.', 'Os paulistas queriam uma nova Constituição.', 'Quatro estudantes, MMDC, morreram num protesto em São Paulo.', 'São Paulo pegou em armas contra o governo em julho de mim.',
      'A guerra durou três meses e São Paulo perdeu.', 'O feriado de 9 de julho lembra de mim.', 'Sou o ano da Revolução Constitucionalista.', 'Sou o ano da "guerra paulista".',
      'Sou um ano dos anos 30.', 'Sou um ano bissexto.', 'Meus dígitos são 1, 9, 3 e 2.', 'Termino com 32.',
    ] },
    { answer: '1986', clues: [
      'Neste ano o ônibus espacial Challenger explodiu na decolagem.', 'O acidente nuclear de Chernobyl foi em abril de mim.', 'A Nintendo lançou "The Legend of Zelda" em mim.', 'O filme "Top Gun" é de mim.',
      'Em mim nasceram Lady Gaga e Usain Bolt.', 'No Brasil, o Plano Cruzado congelou os preços.', 'Os "fiscais do Sarney" fiscalizavam os supermercados.', 'A moeda brasileira passou de cruzeiro a cruzado em mim.',
      'A Copa do Mundo foi no México.', 'Um argentino fez um gol de mão contra a Inglaterra.', 'A "mão de Deus" foi em mim.', 'O mesmo argentino fez "o gol do século" no mesmo jogo.',
      'A Argentina foi campeã do mundo em mim.', 'Maradona foi o rei da Copa em mim.', 'O Brasil caiu nos pênaltis para a França, com Zico perdendo pênalti.', 'Sou o ano da Copa do Maradona.',
      'Sou o ano de Chernobyl.', 'Sou um ano dos anos 80.', 'Meus dígitos são 1, 9, 8 e 6.', 'Termino com 86.',
    ] },
    { answer: '2022', clues: [
      'Neste ano a Rússia invadiu a Ucrânia.', 'A rainha Elizabeth II morreu em setembro de mim, depois de 70 anos de reinado.', 'Will Smith deu um tapa no Oscar em mim.', 'Elon Musk comprou o Twitter em mim.',
      'O ChatGPT foi lançado em novembro de mim.', 'O Brasil completou 200 anos de independência em mim.', 'Lula foi eleito pela terceira vez, contra Bolsonaro.', 'Pelé morreu em dezembro de mim.',
      'A Copa do Mundo foi no Catar, em novembro e dezembro.', 'Foi a primeira Copa no inverno e num país árabe.', 'O Brasil caiu nos pênaltis para a Croácia.', 'O Marrocos foi a surpresa e chegou à semifinal.',
      'A final foi Argentina contra França, decidida nos pênaltis.', 'Mbappé fez três gols na final e mesmo assim perdeu.', 'Messi finalmente ganhou a Copa em mim.', 'Sou o ano da Copa do Catar.',
      'Sou o ano do tri argentino.', 'Sou um ano da década de 2020.', 'Meus dígitos são 2, 0, 2 e 2.', 'Termino com 22.',
    ] },
    { answer: '1937', clues: [
      'Neste ano o dirigível Hindenburg explodiu em Nova Jersey.', 'A ponte Golden Gate foi inaugurada em mim, em São Francisco.', 'Amelia Earhart desapareceu no Pacífico em mim.', 'Picasso pintou "Guernica" em mim.',
      'A Disney lançou o primeiro longa de animação, "Branca de Neve", em mim.', 'Tolkien publicou "O Hobbit" em mim.', 'O Japão invadiu a China em mim.', 'No Brasil, Getúlio Vargas era presidente eleito pela Constituinte.',
      'Um plano comunista falso, o "Plano Cohen", foi divulgado em mim.', 'A eleição de 1938 foi cancelada.', 'Vargas fechou o Congresso em novembro de mim.', 'Uma nova Constituição, a "Polaca", foi outorgada em mim.',
      'O Estado Novo começou em 10 de novembro de mim.', 'As bandeiras dos estados foram queimadas em cerimônia.', 'Sou o ano do golpe do Estado Novo.', 'Sou o ano em que Getúlio virou ditador.',
      'Sou um ano dos anos 30.', 'Sou um ano ímpar.', 'Meus dígitos são 1, 9, 3 e 7.', 'Termino com 37.',
    ] },
  ],
};
module.exports = { CARDS3 };
