// Lote 8 do Perfil — Anos. Cada carta: resposta + 20 dicas (da mais difícil para a mais fácil).
const CARDS8 = {
  A: [
    { answer: '1914', clues: [
      'Neste ano o Canal do Panamá foi aberto à navegação.', 'Um arquiduque austríaco foi morto a tiros em Sarajevo em junho de mim.', 'Esse arquiduque era Francisco Ferdinando.', 'Em julho de mim a Áustria-Hungria declarou guerra à Sérvia.',
      'Neste ano começou a guerra que ficou conhecida como "a Grande Guerra".', 'Meus exércitos entraram nas trincheiras achando que voltariam para casa no Natal.', 'No Natal de mim soldados inimigos pararam de atirar e jogaram futebol.', 'Essa cena ficou conhecida como a Trégua de Natal.',
      'Neste ano Charles Chaplin apareceu pela primeira vez no cinema.', 'O personagem Carlitos estreou em mim.', 'No Brasil, Venceslau Brás assumiu a presidência em mim.', 'No sul do Brasil a Guerra do Contestado estava em curso durante mim.',
      'Fui um ano com aviões ainda de madeira e lona sendo usados na guerra.', 'A cavalaria e a metralhadora dividiram o mesmo campo de batalha em mim.', 'Sou o primeiro ano da Primeira Guerra Mundial.', 'A guerra que comecei durou até 1918.',
      'Sou um ano da década de 1910.', 'Sou anterior à Revolução Russa.', 'Sou o ano em que o mundo mudou por causa de um tiro em Sarajevo.', 'Termino com 14.',
    ] },
    { answer: '1917', clues: [
      'Neste ano os Estados Unidos entraram na Primeira Guerra.', 'Em fevereiro de mim o czar russo foi derrubado.', 'Em outubro de mim os bolcheviques tomaram o poder na Rússia.', 'Lênin liderou essa segunda revolução.',
      'Neste ano três crianças disseram ter visto Nossa Senhora em Portugal.', 'Essas aparições aconteceram em Fátima.', 'O Brasil declarou guerra à Alemanha em outubro de mim.', 'O motivo foi o afundamento de navios brasileiros por submarinos alemães.',
      'Em São Paulo houve uma greve geral em julho de mim.', 'Essa greve foi puxada por operários anarquistas e imigrantes italianos.', 'Neste ano nasceu John F. Kennedy.', 'A Declaração Balfour, sobre um lar judeu na Palestina, é de mim.',
      'A gripe espanhola ainda não tinha chegado quando eu terminei.', 'Fui o ano do czar Nicolau II perder o trono.', 'Sou o ano da Revolução Russa.', 'Sou um ano da Primeira Guerra Mundial.',
      'Sou um ano da década de 1910.', 'Estou entre 1914 e 1918.', 'Sou o ano em que a Rússia virou comunista.', 'Termino com 17.',
    ] },
    { answer: '1918', clues: [
      'Neste ano nasceu Nelson Mandela.', 'Uma pandemia matou dezenas de milhões de pessoas em mim.', 'Essa pandemia ficou conhecida como gripe espanhola.', 'A doença não nasceu na Espanha: o país só noticiava porque não tinha censura de guerra.',
      'No Brasil a gripe matou o presidente eleito Rodrigues Alves.', 'A gripe fechou escolas, teatros e igrejas no Rio de Janeiro.', 'Em novembro de mim foi assinado um armistício num vagão de trem na França.', 'Esse armistício foi às 11 horas do dia 11 do mês 11.',
      'Neste ano caiu o império alemão e o Kaiser fugiu para a Holanda.', 'Também caíram os impérios austro-húngaro e otomano.', 'Neste ano a Polônia voltou a existir como país.', 'A Finlândia e a Estônia também declararam independência em mim.',
      'Fui o último ano da Grande Guerra.', 'As mulheres britânicas acima de 30 anos ganharam voto em mim.', 'Sou o ano do fim da Primeira Guerra Mundial.', 'Sou o ano da gripe espanhola.',
      'Sou um ano da década de 1910.', 'Venho logo depois da Revolução Russa.', 'Sou o ano em que a Primeira Guerra acabou.', 'Termino com 18.',
    ] },
    { answer: '1922', clues: [
      'Neste ano foi descoberta a tumba de Tutancâmon, no Egito.', 'Howard Carter fez essa descoberta em novembro de mim.', 'A União Soviética foi oficialmente criada em dezembro de mim.', 'O livro "Ulysses", de James Joyce, foi publicado em mim.',
      'Mussolini chegou ao poder na Itália em mim, com a Marcha sobre Roma.', 'No Brasil eu marquei os 100 anos da Independência.', 'O Partido Comunista Brasileiro foi fundado em mim.', 'A primeira transmissão de rádio do Brasil aconteceu em mim.',
      'Em julho de mim jovens oficiais se revoltaram no Rio de Janeiro.', 'Eles saíram marchando pela praia de Copacabana contra o governo.', 'Esse episódio ficou conhecido como os 18 do Forte.', 'Foi o começo do movimento tenentista.',
      'Em fevereiro de mim aconteceu um evento no Theatro Municipal de São Paulo.', 'Nesse evento, Mário e Oswald de Andrade foram vaiados.', 'Villa-Lobos e Anita Malfatti participaram desse evento.', 'Sou o ano da Semana de Arte Moderna.',
      'Sou o ano do centenário da Independência do Brasil.', 'Sou um ano da década de 1920.', 'Sou o ano em que o modernismo brasileiro começou.', 'Termino com 22.',
    ] },
    { answer: '1939', clues: [
      'Neste ano houve uma Feira Mundial em Nova York mostrando "o mundo de amanhã".', 'O personagem Batman apareceu pela primeira vez em mim.', 'Em agosto de mim Alemanha e União Soviética assinaram um pacto de não agressão.', 'Esse pacto é conhecido como Molotov-Ribbentrop.',
      'Em 1º de setembro de mim a Alemanha invadiu a Polônia.', 'Dois dias depois, França e Reino Unido declararam guerra à Alemanha.', 'Neste ano começou a Segunda Guerra Mundial.', 'A União Soviética invadiu a Finlândia em novembro de mim.',
      'Neste ano terminou a Guerra Civil Espanhola, com a vitória de Franco.', 'Neste ano estreou "O Mágico de Oz", com Judy Garland.', 'Também estreou "E o Vento Levou", vencedor de 8 Oscars.', 'Hattie McDaniel se tornaria a primeira negra a ganhar um Oscar por esse filme.',
      'Sigmund Freud morreu em Londres em setembro de mim.', 'No Brasil, Getúlio Vargas governava sob o Estado Novo.', 'Sou o primeiro ano da Segunda Guerra Mundial.', 'A guerra que comecei durou até 1945.',
      'Sou um ano do fim da década de 1930.', 'Sou o ano da invasão da Polônia.', 'Sou o ano em que a Segunda Guerra começou.', 'Termino com 39.',
    ] },
    { answer: '1941', clues: [
      'Neste ano estreou "Cidadão Kane", de Orson Welles.', 'Em junho de mim a Alemanha invadiu a União Soviética.', 'Essa invasão se chamou Operação Barbarossa.', 'O cerco de Leningrado começou em mim e durou quase 900 dias.',
      'Em 7 de dezembro de mim uma base americana no Havaí foi bombardeada.', 'Essa base é Pearl Harbor.', 'O ataque foi feito pelo Japão, sem declaração de guerra.', 'No dia seguinte os Estados Unidos entraram na Segunda Guerra.',
      'Neste ano nasceu Bob Dylan.', 'O Capitão América apareceu pela primeira vez em mim, dando um soco em Hitler na capa.', 'No Brasil, Getúlio criou a Companhia Siderúrgica Nacional em mim.', 'Essa siderúrgica ficaria em Volta Redonda.',
      'Neste ano o Brasil ainda era neutro na guerra.', 'A Carta do Atlântico, entre Roosevelt e Churchill, é de mim.', 'Sou o ano do ataque a Pearl Harbor.', 'Sou o ano em que os Estados Unidos entraram na Segunda Guerra.',
      'Sou um ano da década de 1940.', 'Estou no meio da Segunda Guerra Mundial.', 'Sou o ano do "dia da infâmia".', 'Termino com 41.',
    ] },
    { answer: '1950', clues: [
      'Neste ano começou a Guerra da Coreia.', 'Em setembro de mim a televisão chegou ao Brasil.', 'A primeira emissora brasileira foi a TV Tupi, de Assis Chateaubriand.', 'Getúlio Vargas foi eleito presidente de novo em mim.',
      'O Maracanã foi inaugurado em mim.', 'Neste ano o Brasil sediou uma Copa do Mundo pela primeira vez.', 'A Copa foi disputada em grupo final, sem final tradicional.', 'O Brasil só precisava de um empate no último jogo.',
      'Quase 200 mil pessoas foram ao estádio nesse dia.', 'Friaça abriu o placar para o Brasil.', 'Schiaffino empatou e Ghiggia virou o jogo.', 'O goleiro Barbosa foi injustamente culpado pelo resto da vida.',
      'O Uruguai venceu por 2 a 1 em 16 de julho de mim.', 'Esse jogo ficou conhecido como Maracanaço.', 'Sou o ano da maior tragédia do futebol brasileiro.', 'Sou o ano em que o Brasil perdeu a Copa em casa.',
      'Sou um ano do meio do século 20.', 'Sou um ano redondo, começo de década.', 'Sou o ano do Maracanaço e da chegada da TV ao Brasil.', 'Termino com 50.',
    ] },
    { answer: '1962', clues: [
      'Neste ano a Argélia conquistou independência da França.', 'Marilyn Monroe foi encontrada morta em agosto de mim.', 'Em outubro de mim o mundo quase teve uma guerra nuclear.', 'Essa crise foi por causa de mísseis soviéticos em Cuba.',
      'Os Beatles lançaram seu primeiro single, "Love Me Do", em mim.', 'John Glenn deu a primeira volta americana na órbita da Terra em mim.', 'O primeiro filme de James Bond estreou em mim.', 'No Brasil, Tom Jobim e Vinicius compuseram "Garota de Ipanema" em mim.',
      'Um show de bossa nova no Carnegie Hall aconteceu em mim.', 'Neste ano houve uma Copa do Mundo no Chile.', 'Pelé se machucou logo no início dessa Copa.', 'Garrincha assumiu o time e foi eleito o melhor jogador.',
      'Amarildo entrou no lugar de Pelé e fez gols decisivos.', 'A final foi contra a Tchecoslováquia, vencida por 3 a 1.', 'Sou o ano do bicampeonato mundial do Brasil.', 'Sou o ano da Crise dos Mísseis de Cuba.',
      'Sou um ano do começo da década de 1960.', 'Sou anterior ao golpe militar no Brasil.', 'Sou o ano do bi e da Garota de Ipanema.', 'Termino com 62.',
    ] },
    { answer: '1968', clues: [
      'Neste ano estreou "2001: Uma Odisseia no Espaço".', 'Estudantes e operários pararam Paris em maio de mim.', 'Tanques soviéticos invadiram Praga em agosto de mim.', 'Martin Luther King foi assassinado em abril de mim.',
      'Robert Kennedy foi assassinado em junho de mim.', 'A Apollo 8 deu a volta na Lua no Natal de mim.', 'A foto "Nascer da Terra" foi tirada nessa missão.', 'No Brasil, o estudante Edson Luís foi morto pela polícia em março de mim.',
      'A Passeata dos Cem Mil aconteceu no Rio em junho de mim.', 'Caetano e Gil lançaram o disco "Tropicália" em mim.', 'Caetano foi vaiado ao cantar "É Proibido Proibir" em mim.', 'A Zona Rural e a Zona Urbana viraram tema de música em mim.',
      'Em 13 de dezembro de mim foi assinado o ato mais duro da ditadura.', 'Esse ato fechou o Congresso e acabou com o habeas corpus.', 'Sou o ano do AI-5.', 'Sou chamado de "o ano que não terminou".',
      'Sou um ano da década de 1960.', 'Sou o ano das revoltas estudantis no mundo inteiro.', 'Sou o ano em que a ditadura brasileira endureceu de vez.', 'Termino com 68.',
    ] },
    { answer: '1970', clues: [
      'Neste ano os Beatles anunciaram o fim da banda.', 'Jimi Hendrix e Janis Joplin morreram em mim, os dois aos 27 anos.', 'A missão Apollo 13 teve uma explosão a caminho da Lua em mim.', 'A frase "Houston, tivemos um problema" é de mim.',
      'O primeiro Dia da Terra foi comemorado em mim.', 'No Brasil, o governo Médici era o mais repressivo da ditadura.', 'A Transamazônica começou a ser construída em mim.', 'Neste ano houve uma Copa do Mundo no México.',
      'Essa foi a primeira Copa transmitida em cores para o mundo.', 'O Brasil venceu todos os seis jogos que disputou.', 'Pelé cabeceou e Gordon Banks fez a defesa do século em mim.', 'O time tinha Pelé, Tostão, Gérson, Jairzinho e Rivelino.',
      'Carlos Alberto fez o quarto gol da final, depois de uma jogada coletiva.', 'A final foi contra a Itália, vencida por 4 a 1.', 'Sou o ano do tricampeonato mundial.', 'O Brasil ficou com a taça Jules Rimet para sempre em mim.',
      'Sou um ano redondo, começo de década.', 'Sou o ano da seleção considerada a melhor de todos os tempos.', 'Sou o ano do tri no México.', 'Termino com 70.',
    ] },
    { answer: '1972', clues: [
      'Neste ano a Apollo 17 fez a última viagem tripulada à Lua.', 'Um assalto a um edifício em Washington começou um escândalo em junho de mim.', 'Esse escândalo é o caso Watergate.', 'Atletas israelenses foram sequestrados e mortos nas Olimpíadas de Munique em mim.',
      'Mark Spitz ganhou sete medalhas de ouro na natação nessas Olimpíadas.', 'Nixon visitou a China comunista pela primeira vez em mim.', 'Estreou "O Poderoso Chefão" em mim.', 'O primeiro videogame doméstico, o Magnavox Odyssey, saiu em mim.',
      'O jogo Pong foi lançado em mim.', 'No Brasil, a televisão passou a transmitir em cores em mim.', 'A primeira transmissão colorida foi a Festa da Uva, em Caxias do Sul.', 'A novela "Selva de Pedra" fez o país parar em mim.',
      'O Clube de Roma publicou "Os Limites do Crescimento" em mim.', 'A primeira conferência da ONU sobre meio ambiente, em Estocolmo, foi em mim.', 'Sou o ano em que a TV brasileira ganhou cor.', 'Sou o ano do massacre de Munique.',
      'Sou um ano da década de 1970.', 'Estou entre o tri de 1970 e a Copa de 1974.', 'Sou o ano da última pisada humana na Lua.', 'Termino com 72.',
    ] },
    { answer: '1976', clues: [
      'Neste ano os Estados Unidos comemoraram 200 anos de independência.', 'Mao Tsé-Tung morreu em setembro de mim.', 'Um terremoto matou centenas de milhares em Tangshan, na China, em mim.', 'O avião supersônico Concorde começou a voar comercialmente em mim.',
      'A Apple foi fundada em 1º de abril de mim.', 'Steve Jobs e Steve Wozniak montaram o primeiro computador deles em mim.', 'Estreou o filme "Rocky, Um Lutador" em mim.', 'Estreou também "Taxi Driver", de Scorsese.',
      'As Olimpíadas foram em Montreal, no Canadá, em mim.', 'Nadia Comaneci tirou a primeira nota 10 da ginástica olímpica nessas Olimpíadas.', 'No Brasil, o governo Geisel enfrentava a linha dura da ditadura.', 'O Cruzeiro ganhou a Libertadores em mim.',
      'O primeiro surto conhecido de ebola aconteceu em mim.', 'Os Sex Pistols começaram a tocar em Londres em mim.', 'Sou o ano em que a Apple nasceu.', 'Sou o ano do bicentenário dos Estados Unidos.',
      'Sou um ano da década de 1970.', 'Sou um ano de Olimpíadas.', 'Sou o ano em que Mao morreu e a Apple nasceu.', 'Termino com 76.',
    ] },
    { answer: '1978', clues: [
      'Neste ano nasceu o primeiro bebê de proveta do mundo.', 'Esse bebê se chama Louise Brown e nasceu na Inglaterra.', 'Neste ano a Igreja Católica teve três papas.', 'Paulo VI morreu, João Paulo I durou 33 dias e João Paulo II foi eleito.',
      'João Paulo II foi o primeiro papa não italiano em mais de 400 anos.', 'O videogame Space Invaders foi lançado em mim.', 'Estreou o filme "Grease - Nos Tempos da Brilhantina" em mim.', 'Também estreou "Superman", com Christopher Reeve.',
      'Os acordos de Camp David, entre Egito e Israel, foram assinados em mim.', 'No Brasil, começaram as grandes greves dos metalúrgicos do ABC.', 'Um jovem líder sindical chamado Lula apareceu nessas greves.', 'A Copa do Mundo foi na Argentina, sob ditadura militar.',
      'O Brasil terminou essa Copa invicto, mas sem o título.', 'A Argentina venceu essa Copa em casa, em jogo suspeito contra o Peru.', 'Sou o ano do primeiro bebê de proveta.', 'Sou o ano dos três papas.',
      'Sou um ano da década de 1970.', 'Sou o ano da Copa da Argentina.', 'Sou o ano em que o Brasil foi campeão moral.', 'Termino com 78.',
    ] },
    { answer: '1980', clues: [
      'Neste ano o Monte Santa Helena entrou em erupção nos Estados Unidos.', 'O videogame Pac-Man foi lançado em mim.', 'A CNN, primeira TV de notícias 24 horas, estreou em mim.', 'As Olimpíadas de Moscou foram boicotadas por dezenas de países em mim.',
      'A Polônia viu nascer o sindicato Solidariedade em mim.', 'Começou a guerra entre Irã e Iraque em mim.', 'Jean-Paul Sartre morreu em mim.', 'No Brasil, o Partido dos Trabalhadores foi fundado em fevereiro de mim.',
      'O papa João Paulo II visitou o Brasil pela primeira vez em mim.', 'As greves do ABC levaram Lula à prisão em mim.', 'Estreou "Star Wars: O Império Contra-Ataca" em mim.', 'Nesse filme se descobre quem é o pai de Luke Skywalker.',
      'Em 8 de dezembro de mim um beatle foi morto a tiros em Nova York.', 'Esse beatle é John Lennon.', 'Sou o ano em que John Lennon foi assassinado.', 'Sou o ano de fundação do PT.',
      'Sou um ano redondo, começo de década.', 'Sou o primeiro ano dos anos 80.', 'Sou o ano do Pac-Man e da morte de Lennon.', 'Termino com 80.',
    ] },
    { answer: '1982', clues: [
      'Neste ano estreou o filme "E.T. - O Extraterrestre".', 'Também estreou "Blade Runner" em mim.', 'O primeiro CD comercial foi vendido no Japão em mim.', 'A Argentina invadiu as Malvinas em abril de mim.',
      'O Reino Unido retomou as ilhas em junho de mim.', 'Michael Jackson lançou "Thriller" em novembro de mim.', 'Esse disco viraria o mais vendido da história.', 'A princesa Grace Kelly morreu num acidente de carro em mim.',
      'No Brasil houve a primeira eleição direta para governador desde 1965.', 'A crise da dívida externa estourou no México e atingiu o Brasil em mim.', 'A Copa do Mundo foi na Espanha em mim.', 'O Brasil tinha Zico, Sócrates, Falcão, Éder e Cerezo.',
      'Esse time é lembrado como o mais bonito de se ver.', 'O Brasil precisava de um empate e perdeu de 3 a 2 para a Itália.', 'Paolo Rossi fez os três gols dessa partida.', 'Sou o ano da "Tragédia do Sarriá".',
      'Sou um ano da década de 1980.', 'Sou o ano do Thriller e da Guerra das Malvinas.', 'Sou o ano da seleção que encantou e não ganhou.', 'Termino com 82.',
    ] },
    { answer: '1984', clues: [
      'Meu número é o título de um romance famoso de George Orwell.', 'A Apple lançou o Macintosh em janeiro de mim, com um comercial dirigido por Ridley Scott.', 'As Olimpíadas foram em Los Angeles e sofreram boicote soviético em mim.', 'Indira Gandhi foi assassinada na Índia em mim.',
      'Um vazamento químico em Bhopal, na Índia, matou milhares em dezembro de mim.', 'Estreou "Os Caça-Fantasmas" em mim.', 'Estreou "O Exterminador do Futuro" em mim.', 'O primeiro caso do vírus HIV isolado foi anunciado em mim.',
      'No Brasil, milhões foram às ruas pedindo eleição direta para presidente.', 'Os comícios lotaram a Candelária, no Rio, e o Vale do Anhangabaú, em SP.', 'Esse movimento se chamava "Diretas Já".', 'A emenda que pedia eleição direta foi rejeitada na Câmara em abril de mim.',
      'Essa emenda era a Dante de Oliveira.', 'O Brasil acabaria elegendo o presidente pelo Colégio Eleitoral no ano seguinte.', 'Sou o ano das Diretas Já.', 'Sou o ano do lançamento do Macintosh.',
      'Sou um ano da década de 1980.', 'Sou um ano de Olimpíadas.', 'Sou o ano em que o Brasil pediu diretas e não conseguiu.', 'Termino com 84.',
    ] },
    { answer: '1988', clues: [
      'Neste ano o Irã e o Iraque encerraram uma guerra de oito anos.', 'As Olimpíadas foram em Seul, na Coreia do Sul.', 'Ben Johnson foi pego no doping depois de vencer os 100 metros nessas Olimpíadas.', 'Ayrton Senna ganhou seu primeiro título mundial de Fórmula 1 em mim.',
      'Senna venceu 8 das 16 corridas do ano pela McLaren-Honda.', 'Um avião da Pan Am explodiu sobre Lockerbie, na Escócia, em dezembro de mim.', 'Estreou "Rain Man" e "Uma Cilada para Roger Rabbit" em mim.', 'O anime "Meu Amigo Totoro" estreou no Japão em mim.',
      'No Brasil, em 5 de outubro de mim, foi promulgada uma nova Constituição.', 'Ulysses Guimarães ergueu o texto e chamou o país de "Constituição Cidadã".', 'Essa Constituição criou o SUS.', 'Em dezembro de mim um seringueiro foi assassinado no Acre.',
      'Esse seringueiro é Chico Mendes.', 'A morte dele chamou a atenção do mundo para o desmatamento da Amazônia.', 'Sou o ano da Constituição brasileira que vale até hoje.', 'Sou o ano do primeiro título de Senna.',
      'Sou um ano da década de 1980.', 'Venho logo antes da queda do Muro de Berlim.', 'Sou o ano da Constituição de 88.', 'Termino com 88.',
    ] },
    { answer: '1990', clues: [
      'Neste ano Nelson Mandela saiu da prisão, em fevereiro.', 'A Alemanha se reunificou oficialmente em outubro de mim.', 'O Iraque invadiu o Kuwait em agosto de mim.', 'O telescópio espacial Hubble foi lançado em mim.',
      'A internet como a conhecemos começou a nascer: a World Wide Web foi criada no fim de mim.', 'Tim Berners-Lee escreveu o primeiro navegador em mim.', 'Estreou a série "Twin Peaks" em mim.', 'No Brasil, um novo presidente eleito tomou posse em março de mim.',
      'Esse presidente era Fernando Collor de Mello.', 'No dia seguinte à posse, ele confiscou o dinheiro das cadernetas de poupança.', 'Esse plano econômico se chamava Plano Collor.', 'A abertura das importações começou em mim, com a fama dos "carros carroça".',
      'A Copa do Mundo foi na Itália em mim.', 'O Brasil caiu nas oitavas para a Argentina, com gol de Caniggia.', 'A Alemanha venceu essa Copa.', 'Sou o ano do confisco da poupança.',
      'Sou um ano redondo, começo de década.', 'Sou o primeiro ano dos anos 90.', 'Sou o ano em que Mandela foi solto e Collor assumiu.', 'Termino com 90.',
    ] },
    { answer: '1992', clues: [
      'Neste ano a União Europeia foi criada pelo Tratado de Maastricht.', 'As Olimpíadas foram em Barcelona em mim.', 'O "Dream Team" de basquete dos Estados Unidos jogou nessas Olimpíadas.', 'O Rio de Janeiro sediou uma conferência mundial sobre meio ambiente em junho de mim.',
      'Essa conferência ficou conhecida como Eco-92.', 'Em outubro de mim a polícia matou 111 presos numa penitenciária de São Paulo.', 'Esse episódio é o Massacre do Carandiru.', 'Estudantes saíram às ruas com o rosto pintado de verde e amarelo em mim.',
      'Eles ficaram conhecidos como "caras-pintadas".', 'O motivo do protesto eram denúncias do irmão do presidente e do tesoureiro da campanha.', 'Esse tesoureiro era PC Farias.', 'Em dezembro de mim o presidente renunciou durante o julgamento no Senado.',
      'Esse presidente era Fernando Collor.', 'Itamar Franco assumiu a presidência em mim.', 'Sou o ano do impeachment de Collor.', 'Sou o ano da Eco-92 e dos caras-pintadas.',
      'Sou um ano da década de 1990.', 'Sou um ano de Olimpíadas.', 'Sou o ano em que um presidente brasileiro caiu.', 'Termino com 92.',
    ] },
    { answer: '1995', clues: [
      'Neste ano a Microsoft lançou o Windows 95.', 'A campanha desse lançamento usou a música "Start Me Up".', 'A Amazon e o eBay começaram a funcionar em mim.', 'Estreou "Toy Story", o primeiro longa feito todo em computador.',
      'Estreou também "Se7en - Os Sete Crimes Capitais" em mim.', 'O atentado de Oklahoma City matou 168 pessoas em abril de mim.', 'Um ataque com gás sarin no metrô de Tóquio aconteceu em mim.', 'O primeiro-ministro israelense Yitzhak Rabin foi assassinado em novembro de mim.',
      'A guerra da Bósnia terminou com os acordos de Dayton em mim.', 'O DVD foi anunciado como formato em mim.', 'No Brasil, Fernando Henrique Cardoso assumiu a presidência em janeiro de mim.', 'O Plano Real completou um ano segurando a inflação em mim.',
      'A internet comercial chegou ao Brasil em mim.', 'A Embratel liberou o acesso discado ao público em mim.', 'Sou o ano do Windows 95.', 'Sou o ano em que o brasileiro comum entrou na internet.',
      'Sou um ano da década de 1990.', 'Venho logo depois do tetracampeonato.', 'Sou o ano do Toy Story e do Windows 95.', 'Termino com 95.',
    ] },
    { answer: '1996', clues: [
      'Neste ano nasceu a ovelha Dolly, o primeiro mamífero clonado.', 'O nascimento dela só seria anunciado no ano seguinte.', 'As Olimpíadas foram em Atlanta, comemorando 100 anos dos Jogos modernos.', 'Uma bomba explodiu no parque olímpico dessas Olimpíadas.',
      'Muhammad Ali acendeu a pira olímpica com as mãos trêmulas em mim.', 'O vôlei feminino brasileiro ficou com o bronze nessas Olimpíadas.', 'A dupla Jacqueline e Sandra ganhou o ouro no vôlei de praia em mim.', 'O Nintendo 64 foi lançado em mim.',
      'Os jogos Pokémon Vermelho e Verde saíram no Japão em mim.', 'Estreou "Independence Day" e "Trainspotting" em mim.', 'A boy band Backstreet Boys estourou no mundo em mim.', 'A música "Macarena" dominou as rádios em mim.',
      'No Brasil, sem-terra foram mortos pela polícia no Pará em abril de mim.', 'Esse episódio é o massacre de Eldorado dos Carajás.', 'Sou o ano do nascimento da ovelha Dolly.', 'Sou o ano das Olimpíadas do centenário.',
      'Sou um ano da década de 1990.', 'Sou um ano de Olimpíadas.', 'Sou o ano do Nintendo 64 e da Macarena.', 'Termino com 96.',
    ] },
    { answer: '1997', clues: [
      'Neste ano um computador venceu o campeão mundial de xadrez.', 'Esse computador era o Deep Blue, da IBM, e o campeão era Kasparov.', 'A ovelha Dolly foi anunciada ao mundo em fevereiro de mim.', 'O Reino Unido devolveu Hong Kong à China em 1º de julho de mim.',
      'O primeiro livro de Harry Potter foi publicado em junho de mim.', 'Em 31 de agosto de mim uma princesa morreu num acidente de carro em Paris.', 'Essa princesa era Diana.', 'Madre Teresa de Calcutá morreu poucos dias depois, em setembro de mim.',
      'Estreou "Titanic" em dezembro de mim.', 'Esse filme empataria o recorde de 11 Oscars.', 'Estreou também "O Quinto Elemento" e "Men in Black" em mim.', 'O Protocolo de Kyoto sobre clima foi assinado em mim.',
      'No Brasil, foi aprovada a emenda da reeleição em mim.', 'Ronaldo Fenômeno foi eleito melhor do mundo em mim.', 'Sou o ano da morte da princesa Diana.', 'Sou o ano do primeiro livro de Harry Potter.',
      'Sou um ano da década de 1990.', 'Venho logo antes da Copa da França.', 'Sou o ano do Titanic e da Diana.', 'Termino com 97.',
    ] },
    { answer: '1999', clues: [
      'Neste ano o mundo temia um bug de computador na virada do ano.', 'Esse medo ficou conhecido como "bug do milênio" ou Y2K.', 'O euro foi criado como moeda escritural em janeiro de mim.', 'Estreou "Matrix" em mim.',
      'Estreou também "Clube da Luta" e "O Sexto Sentido" em mim.', 'Star Wars voltou ao cinema com o Episódio I em mim.', 'O massacre da escola de Columbine aconteceu em abril de mim.', 'O Napster foi lançado e virou o pesadelo das gravadoras em mim.',
      'A novela "Terra Nostra" fez sucesso no Brasil em mim.', 'No Brasil, o real foi desvalorizado em janeiro de mim.', 'O país passou por apagões e crise cambial em mim.', 'O Brasil ganhou a Copa América em mim.',
      'Tony Hawk fez o primeiro "900" de skate em mim.', 'A banda Sandy e Junior lotava estádios no Brasil em mim.', 'Sou o último ano do século 20.', 'Sou o ano do bug do milênio.',
      'Sou um ano da década de 1990.', 'Sou o ano em que todo mundo esperou o ano 2000 chegar.', 'Sou o ano do Matrix.', 'Termino com 99.',
    ] },
    { answer: '2004', clues: [
      'Neste ano o Facebook foi criado num dormitório de Harvard.', 'O Google abriu capital na bolsa em agosto de mim.', 'O Gmail foi lançado em 1º de abril de mim e todos acharam que era piada.', 'A Grécia venceu a Eurocopa como zebra em mim.',
      'As Olimpíadas foram em Atenas, voltando ao país de origem dos Jogos.', 'O Brasil ganhou o ouro no vôlei masculino nessas Olimpíadas.', 'Estreou "Shrek 2" e "Os Incríveis" em mim.', 'A série "Lost" estreou em mim.',
      'O furacão Katrina ainda não tinha acontecido quando eu terminei.', 'Em 26 de dezembro de mim um terremoto no Índico gerou ondas gigantes.', 'Esse desastre matou mais de 200 mil pessoas em 14 países.', 'Esse é o tsunami do Oceano Índico.',
      'No Brasil, Lula estava no segundo ano do primeiro mandato.', 'O Brasil ganhou a Copa América em mim, nos pênaltis contra a Argentina.', 'Sou o ano do tsunami do Índico.', 'Sou o ano em que o Facebook nasceu.',
      'Sou um ano da primeira década dos anos 2000.', 'Sou um ano de Olimpíadas.', 'Sou o ano das Olimpíadas de Atenas.', 'Termino com 04.',
    ] },
    { answer: '2007', clues: [
      'Neste ano a Apple lançou um aparelho que mudou os celulares.', 'Steve Jobs apresentou o iPhone em janeiro de mim.', 'A Amazon lançou o Kindle em novembro de mim.', 'O último livro de Harry Potter foi publicado em julho de mim.',
      'A crise do subprime começou a estourar nos Estados Unidos em mim.', 'Estreou "Ratatouille" e "Eu Sou a Lenda" em mim.', 'A crise financeira que explodiria em 2008 já dava sinais em mim.', 'O jogo "Portal" e o "Rock Band" saíram em mim.',
      'O Rio de Janeiro sediou os Jogos Pan-Americanos em julho de mim.', 'A mascote desse Pan era o Cauê.', 'Em outubro de mim a Fifa anunciou o Brasil como sede da Copa de 2014.', 'O governo lançou o PAC, um programa de aceleração do crescimento, em mim.',
      'Um acidente aéreo em Congonhas chocou o país em julho de mim.', 'O Cristo Redentor foi eleito uma das Sete Maravilhas do Mundo Moderno em mim.', 'Sou o ano em que o iPhone foi lançado.', 'Sou o ano em que o Brasil ganhou o direito de sediar a Copa.',
      'Sou um ano da primeira década dos anos 2000.', 'Venho logo antes da crise financeira de 2008.', 'Sou o ano do primeiro iPhone.', 'Termino com 07.',
    ] },
    { answer: '2021', clues: [
      'Neste ano começou a vacinação em massa contra a covid-19.', 'A primeira vacinada no Brasil foi a enfermeira Mônica Calazans, em janeiro de mim.', 'Apoiadores de Trump invadiram o Capitólio em 6 de janeiro de mim.', 'Um navio entalou e travou o Canal de Suez em março de mim.',
      'O Facebook mudou o nome da empresa para Meta em mim.', 'A palavra "metaverso" virou moda em mim.', 'Bilionários fizeram voos turísticos ao espaço em mim.', 'Jeff Bezos e Richard Branson voaram nesses foguetes.',
      'O telescópio James Webb foi lançado no Natal de mim.', 'O Brasil teve uma CPI da Pandemia no Senado em mim.', 'A variante Delta e depois a Ômicron apareceram em mim.', 'Estreou "Round 6" na Netflix em mim.',
      'A Itália ganhou a Eurocopa e a Argentina ganhou a Copa América no Maracanã em mim.', 'As Olimpíadas de Tóquio aconteceram em mim, adiadas e sem público.', 'Rebeca Andrade ganhou ouro e prata nessas Olimpíadas.', 'Sou o ano das Olimpíadas de Tóquio, disputadas fora do ano do nome.',
      'Sou um ano da década de 2020.', 'Sou o segundo ano da pandemia.', 'Sou o ano da vacinação e do Round 6.', 'Termino com 21.',
    ] },
    { answer: '2025', clues: [
      'Neste ano Donald Trump voltou à Casa Branca.', 'Uma guerra comercial de tarifas mexeu com o mundo inteiro em mim.', 'O papa Francisco morreu em abril de mim.', 'Um novo papa foi eleito no conclave de maio de mim.',
      'Esse novo papa é Leão XIV, o primeiro americano a assumir o cargo.', 'A inteligência artificial virou assunto de todo dia em mim.', 'Modelos chineses de IA baratos assustaram o mercado no começo de mim.', 'O Brasil se preparou para sediar a COP30 em Belém em mim.',
      'O Palmeiras e o Flamengo disputaram o Mundial de Clubes ampliado nos Estados Unidos em mim.', 'O Chelsea venceu esse primeiro Mundial de 32 clubes em mim.', '"Ainda Estou Aqui" ganhou o Oscar de melhor filme internacional em mim.', 'Fernanda Torres ganhou o Globo de Ouro em janeiro de mim.',
      'O Brasil comemorou seu primeiro Oscar de filme em mim.', 'A seleção brasileira trocou de técnico e contratou Carlo Ancelotti em mim.', 'Sou o ano do primeiro Oscar do cinema brasileiro.', 'Sou o ano em que Ancelotti virou técnico do Brasil.',
      'Sou um ano da década de 2020.', 'Venho logo antes da Copa do Mundo de 2026.', 'Sou o ano do Oscar de "Ainda Estou Aqui".', 'Termino com 25.',
    ] },
  ],
};

module.exports = { CARDS8 };
