// Mais cartas do Perfil (lote 2). Mesma regra: 20 dicas, nenhuma entrega a resposta inteira.
const CARDS2 = {
  P: [
    { answer: 'Cristiano Ronaldo', clues: [
      'Nasci na Ilha da Madeira, em 1985.', 'Meu nome do meio é uma homenagem a um presidente americano.', 'Comecei no Andorinha e no Nacional, clubes da minha ilha.', 'Fui revelado pelo Sporting, em Lisboa.',
      'Sir Alex Ferguson me levou para a Inglaterra aos 18 anos.', 'Vesti a camisa 7 no Manchester United.', 'Ganhei a Champions League cinco vezes.', 'Fui campeão da Eurocopa em 2016 com meu país.',
      'Joguei nove anos no Real Madrid.', 'Tenho um museu com meu nome na minha ilha.', 'Joguei na Juventus, na Itália.', 'Minha comemoração é um salto com um grito: "Siuuu!".',
      'Sou o maior artilheiro da história das seleções.', 'Ganhei cinco Bolas de Ouro.', 'Joguei no Al-Nassr, na Arábia Saudita.', 'Meu rival eterno é um argentino baixinho.',
      'Sou português.', 'Minhas iniciais são C e R, seguidas do número 7.', 'Sou um atacante famoso por abdominais e cabeçadas.', 'Meu primeiro nome é o mesmo de um navegador genovês.',
    ] },
    { answer: 'Anitta', clues: [
      'Nasci em Honório Gurgel, no Rio de Janeiro, em 1993.', 'Meu nome verdadeiro é Larissa.', 'Cantei no coral da igreja quando criança.', 'Meu nome artístico veio de uma personagem da minissérie "Presença de Anita".',
      'Comecei no funk, com a Furacão 2000.', 'Minha primeira música famosa foi "Meiga e Abusada".', 'Cantei "Show das Poderosas" em 2013.', 'Fiz parceria com Madonna e com Cardi B.',
      'Tenho uma música com o nome de um bairro carioca de favela.', 'Cantei "Vai Malandra" e "Bang".', 'Fui a primeira brasileira solo a chegar ao top 1 do Spotify global.', 'Minha música "Envolver" virou dança na internet.',
      'Ganhei um VMA da MTV americana.', 'Fui jurada de programas de TV.', 'Canto em português, inglês e espanhol.', 'Sou a cantora brasileira mais famosa fora do país.',
      'Tenho uma série documental na Netflix.', 'Meu apelido tem um "A" no começo e um "A" no fim.', 'Meu nome artístico tem seis letras.', 'Sou uma cantora de funk e pop.',
    ] },
    { answer: 'Barack Obama', clues: [
      'Nasci no Havaí, em 1961.', 'Meu pai era do Quênia e minha mãe do Kansas.', 'Morei na Indonésia quando criança.', 'Estudei Direito em Harvard.',
      'Fui organizador comunitário em Chicago.', 'Fui senador por Illinois.', 'Meu discurso na convenção democrata de 2004 me lançou nacionalmente.', 'Meu slogan de campanha era "Yes, we can".',
      'Ganhei o Prêmio Nobel da Paz em 2009.', 'Fui presidente por dois mandatos.', 'Minha esposa se chama Michelle.', 'Tive um cachorro chamado Bo na Casa Branca.',
      'Fui o 44º presidente dos Estados Unidos.', 'Fui o primeiro presidente negro dos Estados Unidos.', 'Sucedi George W. Bush.', 'Fui sucedido por Donald Trump.',
      'Meu vice era Joe Biden.', 'Meu sobrenome rima com "Alabama".', 'Meu primeiro nome começa com B e significa "abençoado".', 'Sou um ex-presidente americano.',
    ] },
    { answer: 'Chico Buarque', clues: [
      'Nasci no Rio de Janeiro, em 1944.', 'Meu pai era o historiador Sérgio, autor de "Raízes do Brasil".', 'Cresci em São Paulo e estudei arquitetura.', 'Meu nome de batismo é Francisco.',
      'Fiquei famoso com "A Banda", em 1966.', 'Fui exilado na Itália durante a ditadura.', 'Usei o pseudônimo Julinho da Adelaide para enganar a censura.', 'Escrevi "Cálice" com Gilberto Gil.',
      'Escrevi as peças "Gota d\'Água" e "Ópera do Malandro".', 'Sou torcedor do Fluminense e jogo futebol até hoje.', 'Compus "Construção" e "Apesar de Você".', 'Ganhei o Prêmio Camões de literatura em 2019.',
      'Escrevi os romances "Budapeste" e "Leite Derramado".', 'Tenho olhos verdes famosos.', 'Compus "O Que Será" e "Roda Viva".', 'Sou considerado um dos maiores compositores brasileiros.',
      'Meu sobrenome completo tem "de Hollanda".', 'Sou cantor, compositor e escritor.', 'Meu apelido é um diminutivo de Francisco.', 'Meu nome artístico tem 12 letras.',
    ] },
    { answer: 'Marie Curie', clues: [
      'Nasci em Varsóvia, na Polônia, em 1867.', 'Meu nome de batismo é Maria Salomea.', 'Estudei em uma universidade clandestina, porque mulheres não podiam estudar.', 'Fui para Paris estudar na Sorbonne.',
      'Casei com um físico francês que trabalhava comigo.', 'Descobri dois elementos químicos: o polônio e o rádio.', 'Criei a palavra "radioatividade".', 'Perdi meu marido num acidente com uma carroça.',
      'Dirigi unidades móveis de raio X na Primeira Guerra.', 'Meus cadernos ainda são radioativos até hoje.', 'Morri de uma doença causada pela radiação.', 'Minha filha Irène também ganhou um Nobel.',
      'Fui a primeira mulher a ganhar um Nobel.', 'Sou a única pessoa com Nobel em duas ciências diferentes: Física e Química.', 'Fui a primeira professora mulher da Sorbonne.', 'Estou enterrada no Panteão de Paris.',
      'Sou a cientista mais famosa da história.', 'Meu sobrenome é o do meu marido, Pierre.', 'Meu primeiro nome tem 5 letras e começa com M.', 'Sou polonesa e francesa.',
    ] },
    { answer: 'Silvio Santos', clues: [
      'Nasci no Rio de Janeiro, em 1930.', 'Meu nome de batismo é Senor Abravanel.', 'Meus pais eram judeus, da Grécia e da Turquia.', 'Comecei como camelô, vendendo capas de documento.',
      'Fui locutor de rádio e animador de shows em navios.', 'Comprei o Baú da Felicidade, um carnê de compras.', 'Fundei uma rede de TV em 1981.', 'Tenho um banco e uma empresa de cosméticos.',
      'Meus programas tinham "Porta da Esperança" e "Topa Tudo por Dinheiro".', 'Jogava aviõezinhos de dinheiro para a plateia.', 'Minha plateia era famosa por ser só de mulheres.', 'Fui candidato a presidente em 1989, mas fui impedido.',
      'Meu bordão é "Quem quer dinheiro?".', 'Minha filha Patrícia também é apresentadora.', 'Sou o dono do SBT.', 'Tinha um programa dominical com meu nome que durava a tarde inteira.',
      'Morri em 2024, aos 93 anos.', 'Meu nome artístico tem dois "S".', 'Meu bordão de despedida era "Ha ha ha… é isso aí!".', 'Sou o apresentador mais famoso da TV brasileira.',
    ] },
    { answer: 'Napoleão Bonaparte', clues: [
      'Nasci na Córsega, em 1769, um ano depois de a ilha virar francesa.', 'Falava francês com sotaque italiano.', 'Estudei numa escola militar e virei oficial de artilharia.', 'Fiz uma campanha no Egito e levei cientistas comigo.',
      'A Pedra de Roseta foi achada pelos meus soldados.', 'Dei um golpe de estado em 1799.', 'Criei um código civil que existe até hoje.', 'Me coroei imperador em 1804, tirando a coroa da mão do papa.',
      'Minha primeira esposa se chamava Josefina.', 'Vendi a Louisiana para os Estados Unidos.', 'Invadi a Rússia com 600 mil homens e voltei com poucos.', 'Fui exilado na ilha de Elba e fugi.',
      'Perdi minha última batalha em Waterloo.', 'Morri exilado na ilha de Santa Helena.', 'Dizem que eu era baixinho, mas era de altura normal.', 'Fui imperador da França.',
      'Um retrato meu com a mão dentro do casaco virou clássico.', 'Meu sobrenome vem da família italiana Buonaparte.', 'Meu primeiro nome é o mesmo de uma cidade da Itália.', 'Sou o general mais famoso da história.',
    ] },
    { answer: 'Taylor Swift', clues: [
      'Nasci na Pensilvânia, em 1989.', 'Meu nome é uma homenagem a um cantor de folk americano.', 'Cresci numa fazenda de árvores de Natal.', 'Me mudei para Nashville aos 14 anos para fazer country.',
      'Meu primeiro disco tinha meu nome e saiu quando eu tinha 16 anos.', 'Kanye West interrompeu meu discurso no VMA de 2009.', 'Regravei meus discos antigos com "(versão da artista)" no nome.', 'Tenho vários gatos famosos, um chamado Meredith.',
      'Meus fãs têm um apelido que vem do meu sobrenome.', 'Cantei "Shake It Off" e "Blank Space".', 'Cantei "Love Story" e "Anti-Hero".', 'Minha turnê "Eras Tour" foi a maior da história.',
      'Namorei um jogador de futebol americano do Kansas City Chiefs.', 'Fui a Pessoa do Ano da revista Time em 2023.', 'Fiz shows no Brasil em 2023, no calor extremo.', 'Ganhei o Grammy de Álbum do Ano quatro vezes.',
      'Meu álbum "1989" tem o ano em que nasci.', 'Sou a cantora mais famosa do mundo hoje.', 'Meu primeiro nome também é sobrenome de muita gente.', 'Meu sobrenome significa "rápido" em inglês.',
    ] },
    { answer: 'Roberto Carlos', clues: [
      'Nasci em Cachoeiro de Itapemirim, no Espírito Santo, em 1941.', 'Perdi parte da perna num acidente de trem aos 6 anos.', 'Comecei cantando bossa nova e não deu certo.', 'Fiz sucesso com a Jovem Guarda, nos anos 60.',
      'Meu programa de TV era com Erasmo e Wanderléa.', 'Cantei "Quero Que Vá Tudo pro Inferno".', 'Fiz filmes de aventura no cinema, como "Em Ritmo de Aventura".', 'Minha música "Emoções" virou um hino.',
      'Cantei "Detalhes" e "Como É Grande o Meu Amor por Você".', 'Sou conhecido por não usar a cor marrom.', 'Faço um especial na Globo todo fim de ano.', 'Cantei "Jesus Cristo" e "Como Vai Você".',
      'Cantei "Além do Horizonte" e "Lady Laura", para minha mãe.', 'Faço cruzeiros com fãs todo ano.', 'Sou chamado de "Rei".', 'Sou torcedor do Vasco.',
      'Meu parceiro musical se chamava Erasmo.', 'Meu nome tem duas palavras, as duas nomes de pessoa.', 'Um lateral-esquerdo da Seleção tem o mesmo nome que eu.', 'Sou o cantor romântico mais famoso do Brasil.',
    ] },
    { answer: 'Sherlock Holmes', clues: [
      'Nasci na imaginação de um médico escocês.', 'Meu criador se chama Arthur Conan Doyle.', 'Apareci pela primeira vez em 1887, em "Um Estudo em Vermelho".', 'Toco violino e uso cocaína nos livros.',
      'Meu irmão mais inteligente se chama Mycroft.', 'Minha senhoria se chama Sra. Hudson.', 'Meu inimigo é o professor Moriarty.', 'Meu criador me matou nas cataratas de Reichenbach e teve que me ressuscitar.',
      'Meu melhor amigo é um médico que escreve minhas aventuras.', 'Meu amigo se chama Dr. Watson.', 'Uso o método da dedução para resolver crimes.', 'Moro no número 221B da Baker Street, em Londres.',
      'Uso um chapéu de caçador e um cachimbo.', 'Um cão gigante aparece num dos meus casos mais famosos.', 'Benedict Cumberbatch e Robert Downey Jr. já me interpretaram.', 'Sou o detetive mais famoso da literatura.',
      'A frase "Elementar, meu caro Watson" é atribuída a mim.', 'Meu primeiro nome é usado como apelido para gente esperta.', 'Meu nome tem duas palavras: a primeira começa com S e a segunda com H.', 'Sou um detetive inglês fictício.',
    ] },
    { answer: 'Ivete Sangalo', clues: [
      'Nasci em Juazeiro, na Bahia, em 1972.', 'Sou filha de um cantor de bar.', 'Comecei cantando em bares de Salvador.', 'Fui vocalista da Banda Eva por seis anos.',
      'Minha carreira solo começou em 1999.', 'Cantei "Sorte Grande", a música do "poeira".', 'Cantei "Festa" e "Se Eu Não Te Amasse Tanto Assim".', 'Lotei o Madison Square Garden, em Nova York.',
      'Sou jurada de programas de talentos na Globo.', 'Fiz a novela "Gabriela" como Maria Machadão.', 'Meu marido é nutricionista e me deu três filhos.', 'Meu filho mais velho se chama Marcelo.',
      'Comando um trio elétrico todo ano no carnaval de Salvador.', 'Sou chamada de "Veveta".', 'Ganhei vários Grammys Latinos.', 'Sou a maior cantora de axé do Brasil.',
      'Meu apelido tem "Veve" no começo.', 'Meu sobrenome termina com "galo".', 'Meu nome começa com I.', 'Sou uma cantora baiana.',
    ] },
    { answer: 'Mickey Mouse', clues: [
      'Nasci em 1928.', 'Fui criado depois que meu criador perdeu os direitos de um coelho chamado Oswald.', 'Meu nome quase foi Mortimer.', 'Meu primeiro filme com som foi "Steamboat Willie".',
      'Meu criador fez minha voz por quase 20 anos.', 'Tenho uma namorada com laço e sapatos altos.', 'Meu cachorro se chama Pluto.', 'Meus amigos são Pateta e Donald.',
      'Tenho um clube com meu nome que dura até hoje.', 'Uso luvas brancas e calção vermelho com dois botões.', 'Já fui feiticeiro aprendiz em "Fantasia".', 'Meu rosto está em relógios e nas orelhas dos turistas.',
      'Sou a mascote de uma empresa de cinema americana.', 'Tenho duas orelhas redondas gigantes.', 'Minha namorada se chama Minnie.', 'Sou um rato.',
      'Fui criado por Walt Disney.', 'Meu nome em português é "Camundongo".', 'Meu primeiro nome começa com M e o segundo também.', 'Sou o rato mais famoso do mundo.',
    ] },
  ],
  L: [
    { answer: 'Londres', clues: [
      'Fui fundada pelos romanos como Londinium.', 'Fui destruída por um grande incêndio em 1666.', 'Um relógio famoso na minha torre é chamado pelo nome do sino.', 'Tenho o metrô mais antigo do mundo, de 1863.',
      'Meus ônibus são vermelhos de dois andares.', 'Meus táxis são pretos.', 'Sediei os Jogos Olímpicos três vezes: 1908, 1948 e 2012.', 'Tenho uma roda-gigante às margens do rio.',
      'Meu rio se chama Tâmisa.', 'Uma ponte com duas torres abre para os navios passarem.', 'Sherlock Holmes mora em mim, na Baker Street.', 'Os Beatles gravaram em Abbey Road, um dos meus bairros.',
      'Minha rainha morou no Palácio de Buckingham.', 'Meus guardas usam chapéus pretos altos de pele.', 'Tenho o Big Ben.', 'Sou famosa pela chuva e pela neblina.',
      'Sou a capital da Inglaterra.', 'Sou a capital do Reino Unido.', 'Meu nome em inglês termina com "don".', 'Meu nome começa com L.',
    ] },
    { answer: 'Fernando de Noronha', clues: [
      'Sou um arquipélago de 21 ilhas.', 'Fui descoberto em 1503 e ganhei o nome de um nobre português.', 'Já fui presídio político.', 'Os americanos tiveram uma base militar em mim na Segunda Guerra.',
      'Pertenço a Pernambuco.', 'Fico a 545 km de Recife.', 'Só posso receber um número limitado de turistas por dia.', 'Cobro uma taxa de preservação ambiental de quem me visita.',
      'Sou Patrimônio Natural da Humanidade.', 'Tenho uma das melhores praias do mundo, a Baía do Sancho.', 'Tenho a Baía dos Golfinhos, onde eles aparecem todo dia.', 'Tenho o Morro Dois Irmãos, minha imagem mais famosa.',
      'Tubarões e tartarugas nadam nas minhas praias.', 'Sou o paraíso do mergulho no Brasil.', 'Sou um destino caro e disputado.', 'Sou uma ilha brasileira no Atlântico.',
      'Meu nome tem o nome de um homem.', 'Meu nome tem três palavras.', 'Meu nome tem 17 letras.', 'Sou o arquipélago mais famoso do Brasil.',
    ] },
    { answer: 'Grécia', clues: [
      'Sou o berço da democracia.', 'Inventei os Jogos Olímpicos, em 776 a.C.', 'Sócrates, Platão e Aristóteles nasceram em mim.', 'Meus deuses moravam no Monte Olimpo.',
      'Zeus, Atena e Poseidon são meus.', 'Alexandre, o Grande, saiu de mim para conquistar o mundo.', 'Minha capital tem um templo em ruínas no alto de uma colina.', 'O Partenon fica na Acrópole, em mim.',
      'Meu alfabeto tem alfa, beta e ômega.', 'Tenho milhares de ilhas, como Santorini e Mykonos.', 'Minhas casas mais famosas são brancas com portas azuis.', 'Meus pratos incluem moussaka, souvlaki e a salada com meu nome.',
      'Minha bandeira é azul e branca com uma cruz.', 'Sofri uma crise econômica enorme em 2010.', 'Fico no sul da Europa, nos Bálcãs.', 'Minha capital é Atenas.',
      'Sou o país da mitologia com Hércules e Odisseu.', 'Meu nome em português começa com G.', 'Sou um país europeu.', 'A maratona nasceu em mim.',
    ] },
    { answer: 'Chernobyl', clues: [
      'Meu nome vem de uma planta amarga, a absinta.', 'Fico ao norte da Ucrânia, perto da Bielorrússia.', 'Fazia parte da União Soviética.', 'Uma cidade nova chamada Pripyat foi construída para meus trabalhadores.',
      'Um teste de segurança deu errado numa madrugada de abril.', 'Meu acidente foi em 26 de abril de 1986.', 'Meu reator número 4 explodiu.', 'O governo demorou dias para avisar o mundo.',
      'Uma roda-gigante abandonada é meu símbolo.', 'Minha nuvem radioativa chegou até a Suécia.', 'Uma zona de exclusão de 30 km existe até hoje.', 'Meus "liquidadores" foram os homens que limparam a área.',
      'Uma série da HBO de 2019 conta minha história.', 'Meu reator foi coberto por um sarcófago de concreto e depois por um arco de aço.', 'Fui o pior acidente nuclear da história.', 'Fico na Ucrânia.',
      'Sou uma usina nuclear.', 'Meu nome começa com C e termina com L.', 'Sou o lugar mais radioativo do mundo.', 'Meu nome é sinônimo de desastre nuclear.',
    ] },
    { answer: 'Maracanã', clues: [
      'Fui construído para a Copa do Mundo de 1950.', 'Meu nome oficial homenageia o jornalista Mário Filho.', 'Meu nome vem de um pássaro, em tupi.', 'Recebi 200 mil pessoas na final de 1950.',
      'A derrota do Brasil para o Uruguai em mim virou um trauma nacional.', 'Pelé fez seu milésimo gol em mim.', 'Já fui o maior estádio do mundo.', 'Recebi shows de Frank Sinatra, Madonna e Paul McCartney.',
      'Fui reformado para a Copa de 2014.', 'A final da Copa de 2014 foi em mim: Alemanha 1 x 0 Argentina.', 'A abertura e o encerramento das Olimpíadas de 2016 foram em mim.', 'Neymar marcou o pênalti do ouro olímpico em mim.',
      'Flamengo e Fluminense mandam jogos em mim.', 'Fico na Zona Norte do Rio de Janeiro.', 'Tenho um metrô com meu nome.', 'Sou chamado de "Templo do Futebol".',
      'Sou um estádio brasileiro.', 'Meu nome começa com M e termina com ã.', 'Meu apelido é "Maraca".', 'Sou o estádio mais famoso do Brasil.',
    ] },
    { answer: 'Marte', clues: [
      'Meu nome é o do deus romano da guerra.', 'Tenho duas luas pequenas: Fobos e Deimos.', 'Meu dia dura 24 horas e 37 minutos.', 'Meu ano dura 687 dias terrestres.',
      'Tenho o maior vulcão do Sistema Solar, o Monte Olimpo.', 'Tenho um cânion maior que o Grand Canyon.', 'Tenho calotas polares de gelo.', 'Já tive rios e lagos.',
      'Vários robôs andam em mim: Curiosity e Perseverance.', 'Um helicóptero chamado Ingenuity voou em mim.', 'Elon Musk quer colonizar-me.', 'Um filme com Matt Damon plantando batatas se passa em mim.',
      'Sou o quarto planeta a partir do Sol.', 'Sou o vizinho de fora da Terra.', 'Meu apelido é "Planeta Vermelho".', 'Meus marcianos aparecem em muitos filmes.',
      'Tenho o nome de um deus da guerra.', 'Meu nome tem 5 letras.', 'Meu nome começa com M.', 'Sou um planeta.',
    ] },
    { answer: 'Gramado', clues: [
      'Fui fundada por imigrantes alemães e italianos.', 'Fico na Serra Gaúcha.', 'Fico a 115 km de Porto Alegre.', 'Minha vizinha é Canela.',
      'Tenho um lago com pedalinhos em formato de cisne.', 'Meu Lago Negro tem árvores trazidas da Floresta Negra alemã.', 'Tenho um festival de cinema desde 1973.', 'Meu troféu de cinema é um kikito.',
      'Tenho fábricas de chocolate por todo lado.', 'Tenho uma rua coberta chamada Rua Coberta.', 'Meu Natal dura de outubro a janeiro.', 'Meu "Natal Luz" é o evento de Natal mais famoso do Brasil.',
      'Meus hotéis parecem chalés suíços.', 'Sou o destino de inverno mais famoso do Brasil.', 'Faz frio em mim, e às vezes neva.', 'Fico no Rio Grande do Sul.',
      'Sou uma cidade turística de montanha.', 'Meu nome tem a ver com grama.', 'Meu nome começa com G.', 'Sou a cidade do Natal Luz.',
    ] },
    { answer: 'Sahara', clues: [
      'Meu nome significa "deserto" em árabe.', 'Há 10 mil anos eu era verde e cheio de lagos.', 'Sou quase do tamanho dos Estados Unidos.', 'Ocupo 11 países.',
      'Vou do Atlântico ao Mar Vermelho.', 'Minha areia chega à Amazônia pelo vento e fertiliza a floresta.', 'Tenho dunas de mais de 180 metros.', 'Tenho oásis e caravanas de camelos.',
      'Os tuaregues, "homens azuis", vivem em mim.', 'O Rali Dakar foi criado para me atravessar.', 'Faz 50 graus de dia e frio à noite.', 'O Egito, a Líbia e a Argélia estão em mim.',
      'Sou maior que o Brasil.', 'Fico no norte da África.', 'Sou o maior deserto quente do mundo.', 'Sou um deserto.',
      'Meu nome tem 6 letras.', 'Meu nome começa com S.', 'Meu nome termina com "ara".', 'Sou o deserto mais famoso do mundo.',
    ] },
    { answer: 'Roma', clues: [
      'Fui fundada em 753 a.C., segundo a lenda, por dois irmãos.', 'Os irmãos foram amamentados por uma loba.', 'Fui capital de um império que dominou a Europa.', 'Júlio César foi assassinado em mim.',
      'Fui construída sobre sete colinas.', 'Tenho um rio chamado Tibre.', 'Tenho um país inteiro dentro de mim.', 'O Vaticano fica dentro de mim.',
      'Tenho uma fonte onde se joga moeda para voltar.', 'A Fontana di Trevi fica em mim.', 'Tenho um anfiteatro onde gladiadores lutavam.', 'O Coliseu fica em mim.',
      'O Panteão, com um buraco no teto, fica em mim.', 'Sou chamada de "Cidade Eterna".', 'Todos os caminhos levam a mim.', 'Sou a capital da Itália.',
      'Meu nome tem 4 letras.', 'Meu nome ao contrário é "amor".', 'Meu nome começa com R.', 'Sou a cidade do Coliseu.',
    ] },
    { answer: 'Foz do Iguaçu', clues: [
      'Fico na tríplice fronteira: Brasil, Argentina e Paraguai.', 'Fico no oeste do Paraná.', 'Tenho uma ponte chamada Ponte da Amizade.', 'Do meu lado fica Ciudad del Este, cidade de compras.',
      'Tenho um templo budista e uma mesquita.', 'Tenho um parque de aves enorme.', 'Meu nome significa "água grande" em guarani.', 'Tenho um hotel dentro de um parque nacional.',
      'Tenho a maior usina hidrelétrica em produção de energia do mundo por muitos anos.', 'A usina de Itaipu fica em mim.', 'Tenho 275 quedas d\'água.', 'A "Garganta do Diabo" é minha queda mais famosa.',
      'Minhas cataratas são uma das sete maravilhas naturais do mundo.', 'Sou Patrimônio da Humanidade.', 'Sou o segundo destino mais visitado por estrangeiros no Brasil.', 'Fico no Paraná.',
      'Sou famosa pelas cataratas.', 'Meu nome tem 3 palavras e começa com F.', 'Meu nome tem o nome de um rio.', 'Sou a cidade das Cataratas.',
    ] },
    { answer: 'Hogwarts', clues: [
      'Fui fundada há mais de mil anos por quatro bruxos.', 'Meus fundadores se chamavam Godric, Helga, Rowena e Salazar.', 'Fico na Escócia, mas trouxas não conseguem me ver.', 'Tenho um lago com uma lula gigante.',
      'Meu teto do Salão Principal imita o céu.', 'Tenho 142 escadas que mudam de lugar.', 'Tenho uma floresta proibida.', 'Um chapéu falante escolhe as casas dos alunos.',
      'Chega-se a mim por um trem que sai da plataforma 9¾.', 'Tenho quatro casas: uma delas é a Sonserina.', 'Meu diretor mais famoso se chamava Dumbledore.', 'Meu guarda-caça se chama Hagrid.',
      'Meu zelador é o Filch, com a gata Madame Nora.', 'Tenho um jogo em vassouras chamado quadribol.', 'Harry Potter estudou em mim.', 'Sou uma escola de magia e bruxaria.',
      'Meu lema é "nunca cutuque um dragão adormecido", em latim.', 'Meu nome tem "wart" no meio.', 'Meu nome começa com H.', 'Sou a escola de bruxos mais famosa do mundo.',
    ] },
    { answer: 'Pantanal', clues: [
      'Sou a maior planície alagável do planeta.', 'Fico entre o Brasil, a Bolívia e o Paraguai.', 'Ocupo Mato Grosso e Mato Grosso do Sul.', 'Alago metade do ano e seco na outra metade.',
      'Meu rio principal é o Paraguai.', 'Tenho a maior concentração de onças-pintadas do mundo.', 'Tenho tuiuiús, minha ave símbolo.', 'Tenho jacarés aos milhares nas margens dos rios.',
      'Sou Patrimônio Natural da Humanidade.', 'Meus peões cuidam do gado a cavalo.', 'Tive queimadas terríveis em 2020.', 'Corumbá é minha cidade mais famosa.',
      'Uma novela da Globo com meu nome foi sucesso em 1990 e em 2022.', 'A novela tem Juma Marruá, que vira onça.', 'A "Estrada Parque" corta minha área.', 'Sou o paraíso da pesca e da observação de aves.',
      'Sou um bioma brasileiro.', 'Meu nome vem de "pântano".', 'Meu nome começa com P.', 'Sou a maior área alagada do mundo.',
    ] },
  ],
  C: [
    { answer: 'Internet', clues: [
      'Nasci nos Estados Unidos, em 1969, como um projeto militar.', 'Meu primeiro nome era ARPANET.', 'Minha primeira mensagem foi "LO", porque o sistema caiu antes de "LOGIN".', 'Um cientista inglês criou minha versão "web" em 1989.',
      'Tim Berners-Lee criou as páginas com "www".', 'Cheguei ao Brasil para o público em 1995.', 'No começo eu fazia barulho de modem discado.', 'Ocupava a linha do telefone.',
      'Uso endereços chamados IP.', 'Tenho um sistema de nomes com ".com" e ".br".', 'Cabos no fundo do mar me transportam entre continentes.', 'O Google, o YouTube e o WhatsApp vivem em mim.',
      'Posso ser de fibra, de rádio ou de satélite.', 'Preciso de Wi-Fi ou de dados móveis no celular.', 'Sem mim, este jogo não funciona.', 'Sou uma rede mundial de computadores.',
      'Meu apelido em português é "net".', 'Meu nome começa com "Inter".', 'Meu nome tem 8 letras.', 'Sou a rede que conecta o mundo.',
    ] },
    { answer: 'Violão', clues: [
      'Meus ancestrais vieram da Espanha e dos árabes.', 'Um espanhol chamado Antonio Torres me deu a forma atual, no século 19.', 'Sou o instrumento da bossa nova.', 'João Gilberto criou a "batida" da bossa nova em mim.',
      'Tenho versões com cordas de náilon e de aço.', 'Posso ser tocado com os dedos ou com palheta.', 'Tenho um buraco redondo no meio, a boca.', 'Meu corpo é de madeira e oco.',
      'Tenho um braço com casas e trastes.', 'Fico afinado em mi, lá, ré, sol, si, mi.', 'Sou o instrumento da roda de samba e da serenata.', 'Sou o instrumento mais fácil de achar numa fogueira de praia.',
      'Em outros países, me chamam de "guitarra clássica" ou "acústica".', 'Tenho seis cordas.', 'Sou o irmão sem eletricidade da guitarra.', 'Sou um instrumento de cordas.',
      'Meu nome vem de "viola".', 'Meu nome tem 6 letras.', 'Meu nome começa com V.', 'Sou o instrumento mais popular do Brasil.',
    ] },
    { answer: 'Sorvete', clues: [
      'Os chineses me faziam com neve e leite há 3 mil anos.', 'Marco Polo, dizem, me trouxe para a Itália.', 'Fui comida de reis e nobres por séculos.', 'Sou vendido em cones de biscoito desde 1904.',
      'Um vendedor italiano me trouxe para o Brasil em 1834, com gelo dos Estados Unidos.', 'Sou feito de leite, açúcar e creme, batidos e congelados.', 'Na Itália, sou chamado de "gelato".', 'Minha versão sem leite, só com fruta, é o sorbet ou picolé.',
      'Sou vendido de carrinho na praia e no bicicletário.', 'Dou dor de cabeça se comido rápido demais.', 'Meus sabores clássicos: chocolate, morango e flocos.', 'Fico em freezer.',
      'Posso vir na casquinha, no copinho ou no pote.', 'Sou o doce favorito do verão.', 'Derreto rápido no calor.', 'Sou gelado e cremoso.',
      'Sou servido com uma colher em formato de bola.', 'Meu nome vem de "sorver".', 'Meu nome começa com S.', 'Sou o doce gelado mais famoso do mundo.',
    ] },
    { answer: 'Relógio', clues: [
      'Meus ancestrais eram de sol e de água.', 'Os egípcios me usavam como obelisco, medindo sombras.', 'Meu primeiro modelo mecânico apareceu em torres de igreja.', 'Galileu descobriu que um pêndulo podia me controlar.',
      'Um brasileiro pediu ao amigo Cartier uma versão de pulso.', 'A Suíça é o país mais famoso por me fabricar.', 'Tenho versão de areia, com dois bulbos de vidro.', 'Tenho versão cuco, com um passarinho.',
      'Posso ser analógico ou digital.', 'Posso ser inteligente e medir batimentos.', 'Rolex e Casio são marcas minhas.', 'Meu maior modelo famoso fica numa torre em Londres.',
      'Tenho ponteiros ou números.', 'Tenho versão de parede, de mesa e de pulso.', 'Faço tique-taque.', 'Sirvo para mostrar as horas.',
      'Meu nome começa com R.', 'Meu nome tem 7 letras.', 'Meu nome termina com "ógio".', 'Sou o objeto que mede o tempo.',
    ] },
    { answer: 'Bola de futebol', clues: [
      'Meus primeiros modelos eram bexigas de porco cheias de ar.', 'Charles Goodyear criou minha versão de borracha em 1855.', 'Já fui de couro marrom e ficava pesada na chuva.', 'Minha versão preta e branca apareceu na Copa de 1970.',
      'Meu desenho clássico tem 32 gomos: 12 pentágonos e 20 hexágonos.', 'A Adidas me faz para as Copas do Mundo desde 1970.', 'A "Jabulani" da Copa de 2010 foi odiada pelos goleiros.', 'Na Copa de 2014 me chamaram de "Brazuca".',
      'Tenho um chip em algumas competições.', 'Meu tamanho oficial é o número 5.', 'Devo pesar entre 410 e 450 gramas.', 'Tenho uma válvula para encher com bomba.',
      'Sou chutada, cabeceada e defendida.', 'Só o goleiro pode me pegar com a mão.', 'Sou redonda.', 'Sou o objeto do esporte mais popular do mundo.',
      'Não posso ser tocada com a mão em campo.', 'Meu nome tem "bola".', 'Sou a "pelota" ou a "redonda".', 'Sou a bola do esporte de Pelé.',
    ] },
    { answer: 'Ar-condicionado', clues: [
      'Fui inventado em 1902 por Willis Carrier.', 'Fui criado para controlar a umidade numa gráfica.', 'Os cinemas foram os primeiros a me adotar para atrair público.', 'Cidades como Dubai e Singapura não existiriam como são sem mim.',
      'Uso um gás que muda de líquido para vapor.', 'Tenho uma parte dentro e outra fora do prédio.', 'Meu modelo mais comum hoje é o "split".', 'Sou medido em BTUs.',
      'Pingo água na cabeça de quem passa na calçada.', 'Minha versão inverter economiza energia.', 'Disparo a conta de luz no verão.', 'Preciso ter o filtro limpo.',
      'Existo também em carros.', 'Uso controle remoto.', 'Sou ligado a 23 graus nas brigas de escritório.', 'Refresco ambientes.',
      'Sou o aparelho que esfria o ar.', 'Meu nome tem duas palavras ligadas por hífen.', 'Meu nome começa com "Ar".', 'Sou o aparelho que salva o verão.',
    ] },
    { answer: 'Bombril', clues: [
      'Nasci em São Paulo, em 1948.', 'Fui criado por Roberto Sampaio, que copiou um produto americano.', 'Meu nome vem de "bom brilho".', 'Sou feito de fios finos de aço.',
      'Meu garoto-propaganda fez mais de 300 comerciais e entrou no Guinness.', 'Carlos Moreno foi meu garoto-propaganda por décadas.', 'Meu slogan dizia que eu tinha "1001 utilidades".', 'Sou usado para limpar panelas.',
      'Enferrujo se ficar molhado na pia.', 'Sou vendido em pacotes com várias unidades.', 'Sou o produto mais famoso de uma empresa que faz Limpol e Pinho Bril.', 'Meu nome virou sinônimo do produto, como "Gillette" e "Xerox".',
      'Cabelo muito crespo às vezes é comparado a mim, de forma maldosa.', 'Sou uma marca brasileira.', 'Sou uma esponja de aço.', 'Sou usado na cozinha.',
      'Meu nome começa com "Bom".', 'Meu nome tem 7 letras.', 'Meu nome termina com "bril".', 'Sou a palha de aço mais famosa do Brasil.',
    ] },
    { answer: 'Havaianas', clues: [
      'Nasci em 1962, inspiradas numa sandália japonesa.', 'Meu modelo é o zori, sandália de palha de arroz.', 'Fui criada pela Alpargatas.', 'Meus primeiros modelos eram só brancas com tiras azuis.',
      'Era chamada de "chinelo de pobre" nos anos 80.', 'Chico Anysio fez meus comerciais com o slogan "não deformam, não têm cheiro e não soltam as tiras".', 'Em 1994 lancei versões coloridas e virei moda.', 'Sou vendida em lojas de luxo em Paris e Nova York.',
      'Meu solado tem um desenho de grãos de arroz.', 'Tenho versões com a bandeira do Brasil na tira.', 'Fui usada por celebridades no tapete vermelho.', 'Tenho tiras em formato de Y.',
      'Sou de borracha.', 'Sou usada na praia e em casa.', 'Meu nome vem de uma ilha americana.', 'Sou um chinelo.',
      'Sou a sandália mais famosa do Brasil.', 'Meu nome termina com "anas".', 'Meu nome começa com H.', 'Sou o chinelo com o nome do Havaí.',
    ] },
    { answer: 'Cartão de crédito', clues: [
      'Fui imaginado num livro de ficção de 1888.', 'Nasci de verdade em 1950, num restaurante de Nova York.', 'Um homem esqueceu a carteira no jantar e teve a ideia.', 'Minha primeira marca foi o Diners Club.',
      'Cheguei ao Brasil em 1956.', 'Já fui de papelão, depois de plástico.', 'Tenho uma tarja magnética e hoje um chip.', 'Tenho 16 números na frente e 3 atrás.',
      'Tenho uma data de validade.', 'Cobro juros altíssimos se a fatura atrasa.', 'Posso pagar por aproximação.', 'Visa e Mastercard são minhas bandeiras.',
      'Meu limite é o sonho de muita gente.', 'Posso parcelar compras em 12 vezes.', 'Tenho uma fatura mensal.', 'Sou um retângulo de plástico.',
      'Sou usado para pagar sem dinheiro vivo.', 'Meu nome tem "cartão".', 'Meu nome termina com "crédito".', 'Sou o cartão que deixa você devendo.',
    ] },
    { answer: 'Pipoca', clues: [
      'Fui encontrada em cavernas do Peru com 6 mil anos.', 'Os astecas me usavam em colares e enfeites.', 'Meu nome vem do tupi: "pele estourada".', 'Os cinemas americanos me adotaram durante a Grande Depressão.',
      'Sou feita de um milho especial, mais duro.', 'Estouro porque a água dentro do grão vira vapor.', 'Estouro a 180 graus.', 'Um grão que não estoura é chamado de "piruá".',
      'Existo em versão de micro-ondas.', 'Posso ser doce, salgada ou com manteiga.', 'Sou vendida em carrinhos na porta das escolas.', 'Sou vendida em baldes gigantes nos cinemas.',
      'Fico presa nos dentes.', 'Sou a comida oficial do cinema.', 'Sou o milho que estoura.', 'Sou branca e leve.',
      'Meu nome começa com P.', 'Meu nome tem 6 letras.', 'Meu nome termina com "oca".', 'Sou a comida do filme.',
    ] },
    { answer: 'Avião', clues: [
      'Leonardo da Vinci me desenhou séculos antes de eu existir.', 'Meu primeiro voo, para os americanos, foi em 1903, na Carolina do Norte.', 'Para os brasileiros, meu primeiro voo foi em 1906, em Paris.', 'Os irmãos Wright e Santos Dumont brigam pela minha invenção.',
      'Fui usado na Primeira Guerra Mundial pela primeira vez.', 'Meu maior modelo de passageiros é o A380, com dois andares.', 'A Boeing e a Airbus me fabricam.', 'O Brasil tem uma fábrica minha: a Embraer.',
      'Voo por causa do formato das minhas asas.', 'Tenho uma caixa-preta que na verdade é laranja.', 'Meu piloto fica na cabine, com o copiloto.', 'Sirvo comida em bandejinhas.',
      'Tenho turbinas ou hélices.', 'Decolo e pouso em pistas.', 'Sou o meio de transporte mais seguro do mundo.', 'Tenho asas e não bato elas.',
      'Voo mais alto que as nuvens.', 'Meu nome começa com A.', 'Meu nome tem 5 letras e um acento.', 'Sou a máquina que voa.',
    ] },
    { answer: 'Coca-Cola', clues: [
      'Nasci em 1886, numa farmácia de Atlanta.', 'Fui criada por um farmacêutico chamado John Pemberton.', 'Meu criador me vendia como remédio para dor de cabeça.', 'Meu nome vem dos meus dois ingredientes originais: uma folha e uma noz.',
      'Minha receita é guardada num cofre.', 'Minha garrafa tem um formato curvo que dá para reconhecer no escuro.', 'Meu Papai Noel vermelho e gordinho virou o padrão do mundo.', 'Cheguei ao Brasil em 1942.',
      'Um urso polar aparece nos meus comerciais.', 'Minha versão "Zero" não tem açúcar.', 'Já tentei mudar a fórmula em 1985 e o povo revoltou.', 'Meu maior concorrente é azul.',
      'Sou vendida em quase todos os países do mundo.', 'Sou preta e cheia de gás.', 'Sou o refrigerante mais famoso do mundo.', 'Sou vermelha na lata.',
      'Meu nome tem hífen.', 'Meu nome tem duas palavras que começam com C.', 'Meu apelido tem 4 letras.', 'Sou o refrigerante de cola mais vendido.',
    ] },
  ],
  A: [
    { answer: '1964', clues: [
      'Neste ano os Beatles chegaram aos Estados Unidos e mudaram a música.', 'Cassius Clay virou campeão mundial de boxe e mudou o nome para Muhammad Ali.', 'Nelson Mandela foi condenado à prisão perpétua em mim.', 'O Japão inaugurou o primeiro trem-bala em mim.',
      'As Olimpíadas foram em Tóquio.', 'Martin Luther King ganhou o Nobel da Paz em mim.', 'O filme "Mary Poppins" é de mim.', 'A Ford lançou o Mustang em mim.',
      'A TV Globo seria fundada no ano seguinte a mim.', 'No Brasil, João Goulart era presidente.', 'Um comício na Central do Brasil, em março, assustou os militares.', 'A "Marcha da Família com Deus pela Liberdade" saiu às ruas em mim.',
      'Tropas saíram de Minas Gerais em 31 de março de mim.', 'O presidente fugiu para o Uruguai em abril de mim.', 'O marechal Castello Branco assumiu em mim.', 'Em mim começou um regime que durou 21 anos.',
      'Sou o ano do golpe militar no Brasil.', 'Sou um ano bissexto.', 'Sou um ano dos anos 60.', 'Termino com 64.',
    ] },
    { answer: '1945', clues: [
      'Neste ano Franklin Roosevelt morreu e Truman assumiu.', 'Anne Frank morreu num campo de concentração em mim.', 'Os aliados se reuniram em Ialta em mim.', 'A ONU foi fundada em mim, em São Francisco.',
      'Hitler se matou num bunker em abril de mim.', 'A Alemanha se rendeu em maio de mim.', 'O Brasil venceu na Itália com a FEB, os pracinhas.', 'Em mim Getúlio Vargas foi deposto e o Estado Novo acabou.',
      'Eurico Gaspar Dutra foi eleito presidente em mim.', 'A primeira bomba atômica foi testada no deserto do Novo México.', 'Duas cidades japonesas foram destruídas por bombas atômicas em mim.', 'Hiroshima e Nagasaki foram atacadas em agosto de mim.',
      'O Japão se rendeu em setembro de mim.', 'Sou o ano do fim da Segunda Guerra Mundial.', 'A Guerra Fria começou logo depois de mim.', 'Sou o ano do fim do conflito mais mortal da história.',
      'Sou um ano da década de 40.', 'Sou um ano do século 20.', 'Sou um ano ímpar.', 'Termino com 45.',
    ] },
    { answer: '2010', clues: [
      'Neste ano um vulcão da Islândia parou os voos da Europa.', 'Um terremoto no Haiti matou mais de 200 mil pessoas em mim.', 'O Instagram foi lançado em mim.', 'O iPad foi lançado em mim.',
      'O filme "A Origem", de Christopher Nolan, é de mim.', 'Em mim 33 mineiros ficaram 69 dias presos no Chile e foram resgatados.', 'A Primavera Árabe começou em dezembro de mim, na Tunísia.', 'Em mim o Brasil elegeu sua primeira presidente mulher.',
      'Dilma Rousseff venceu a eleição em mim.', 'A Copa do Mundo foi na África pela primeira vez.', 'As vuvuzelas fizeram barulho em todos os jogos.', 'O polvo Paul acertou os resultados dos jogos.',
      'A Espanha ganhou a Copa pela primeira vez, na África do Sul.', 'O Brasil caiu nas quartas contra a Holanda, com Dunga de técnico.', 'A música da Copa foi "Waka Waka", da Shakira.', 'Sou o ano da Copa das vuvuzelas.',
      'Sou o primeiro ano de uma década.', 'Sou um ano do século 21.', 'Meus dígitos são 2, 0, 1 e 0.', 'Termino com 10.',
    ] },
    { answer: '1929', clues: [
      'Neste ano Martin Luther King nasceu.', 'Neste ano nasceram Anne Frank e Audrey Hepburn.', 'O primeiro Oscar foi entregue em mim.', 'O Museu de Arte Moderna de Nova York, o MoMA, foi fundado em mim.',
      'Em mim o Vaticano virou um país, pelo Tratado de Latrão.', 'O gângster Al Capone mandou fazer o "Massacre de São Valentim" em mim.', 'O personagem Tintim foi criado em mim.', 'No Brasil, Washington Luís era presidente e Getúlio Vargas se preparava para a eleição.',
      'O preço do café brasileiro despencou em mim.', 'Em mim os Estados Unidos viviam a euforia dos "anos loucos".', 'Em outubro de mim a Bolsa de Nova York desabou.', 'A "Quinta-feira Negra" foi em 24 de outubro de mim.',
      'A "Terça-feira Negra" foi cinco dias depois.', 'Bancos quebraram e milhões perderam o emprego depois de mim.', 'Sou o ano do início da Grande Depressão.', 'Sou o ano da quebra da Bolsa de Nova York.',
      'Sou o ano da maior crise econômica da história.', 'Sou um ano do fim dos anos 20.', 'Sou um ano ímpar.', 'Termino com 29.',
    ] },
    { answer: '1998', clues: [
      'Neste ano o Google foi fundado numa garagem.', 'Em mim o Titanic, o filme, ganhou 11 Oscars.', 'Bill Clinton enfrentou o escândalo com Monica Lewinsky em mim.', 'O euro foi criado como moeda em mim, mas ainda sem notas.',
      'Frank Sinatra morreu em mim.', 'O Windows 98 foi lançado em mim.', 'O Nokia virou a maior fabricante de celulares do mundo.', 'Em mim Fernando Henrique Cardoso foi reeleito no primeiro turno.',
      'O Brasil quase quebrou com a crise da Rússia e pediu ajuda ao FMI.', 'A Copa do Mundo foi na França.', 'Ronaldo Fenômeno teve uma convulsão antes da final.', 'Zidane fez dois gols de cabeça na final.',
      'A França venceu o Brasil por 3 a 0 na final.', 'O Brasil ficou com o vice em mim.', 'Sou o ano da Copa da França.', 'Sou o ano do "mistério do Ronaldo".',
      'Sou um ano dos anos 90.', 'Sou um ano do século 20.', 'Meus dígitos são 1, 9, 9 e 8.', 'Termino com 98.',
    ] },
    { answer: '1789', clues: [
      'Neste ano George Washington tomou posse como primeiro presidente dos Estados Unidos.', 'Em mim a Constituição americana entrou em vigor.', 'O motim do navio Bounty aconteceu em mim, no Pacífico.', 'No Brasil, era a época da mineração de ouro em Minas Gerais.',
      'Um alferes foi preso em mim por conspirar contra Portugal.', 'A Inconfidência Mineira foi descoberta em mim.', 'Tiradentes foi preso em maio de mim.', 'Joaquim Silvério dos Reis delatou os inconfidentes em mim.',
      'Na França, o rei Luís XVI convocou os Estados Gerais em maio de mim.', 'O Terceiro Estado se declarou Assembleia Nacional em mim.', 'Uma prisão de Paris foi invadida pelo povo em 14 de julho de mim.', 'A Queda da Bastilha foi em mim.',
      'A Declaração dos Direitos do Homem e do Cidadão foi escrita em mim.', '"Liberdade, Igualdade e Fraternidade" nasceu em mim.', 'Sou o ano da Revolução Francesa.', 'Sou o ano que acabou com o absolutismo na França.',
      'Sou o ano que os historiadores usam para começar a Idade Contemporânea.', 'Sou um ano do século 18.', 'Sou um ano ímpar.', 'Termino com 89.',
    ] },
    { answer: '1958', clues: [
      'Neste ano a NASA foi criada.', 'Os Estados Unidos lançaram seu primeiro satélite, o Explorer 1.', 'O Lego com encaixe atual foi patenteado em mim.', 'Neste ano nasceram Michael Jackson, Madonna e Prince.',
      'O bambolê virou febre nos Estados Unidos em mim.', 'Elvis Presley entrou para o Exército em mim.', 'No Brasil, Juscelino Kubitschek construía Brasília.', 'João Gilberto lançou "Chega de Saudade" em mim.',
      'A bossa nova nasceu em mim.', 'Nelson Rodrigues chamou de "complexo de vira-lata" o medo do brasileiro na Copa.', 'A Copa do Mundo foi na Suécia.', 'Um garoto de 17 anos brilhou na Copa.',
      'Pelé fez dois gols na final contra a Suécia.', 'Garrincha e Pelé jogaram juntos pela primeira vez na Copa.', 'O Brasil venceu a Suécia por 5 a 2 na final.', 'Sou o ano da primeira Copa do Brasil.',
      'Sou um ano dos anos 50.', 'Sou um ano do século 20.', 'Meus dígitos são 1, 9, 5 e 8.', 'Termino com 58.',
    ] },
    { answer: '2008', clues: [
      'Neste ano Fidel Castro deixou o poder em Cuba.', 'O filme "Batman: O Cavaleiro das Trevas" é de mim.', 'A primeira loja de aplicativos, a App Store, abriu em mim.', 'O Bitcoin foi descrito num artigo em outubro de mim.',
      'O Brasil ganhou o grau de investimento das agências de risco em mim.', 'Em mim a Petrobras confirmou as reservas gigantes do pré-sal.', 'Usain Bolt quebrou os recordes dos 100 e 200 metros em mim.', 'Michael Phelps ganhou oito ouros numa só Olimpíada.',
      'As Olimpíadas foram em Pequim.', 'A abertura das Olimpíadas teve milhares de tambores.', 'A Rússia invadiu a Geórgia em agosto de mim.', 'Um banco americano chamado Lehman Brothers quebrou em setembro de mim.',
      'Lula disse que a crise chegaria ao Brasil como "uma marolinha".', 'Sou o ano da crise financeira mundial.', 'Barack Obama foi eleito em novembro de mim.', 'Sou o ano do primeiro presidente negro eleito nos Estados Unidos.',
      'Sou um ano bissexto.', 'Sou um ano do século 21.', 'Meus dígitos são 2, 0, 0 e 8.', 'Termino com 08.',
    ] },
    { answer: '1808', clues: [
      'Neste ano Beethoven apresentou a Quinta Sinfonia, em Viena.', 'Napoleão invadiu a Espanha em mim.', 'Os Estados Unidos proibiram a importação de escravos em mim.', 'Goethe publicou a primeira parte de "Fausto" em mim.',
      'Napoleão tinha invadido Portugal no fim do ano anterior.', 'Uma família inteira fugiu de Lisboa de navio, escoltada pelos ingleses.', 'Cerca de 15 mil pessoas atravessaram o Atlântico em mim.', 'A frota chegou a Salvador em janeiro de mim.',
      'Os portos do Brasil foram abertos "às nações amigas" em mim.', 'A frota chegou ao Rio de Janeiro em março de mim.', 'O Banco do Brasil foi criado em mim.', 'A Imprensa Régia, primeira gráfica do Brasil, nasceu em mim.',
      'O Jardim Botânico do Rio foi criado em mim.', 'O primeiro jornal do Brasil, o Correio Braziliense, saiu em mim.', 'Dom João VI chegou ao Brasil em mim.', 'Sou o ano da chegada da família real portuguesa ao Brasil.',
      'O Rio de Janeiro virou capital de um império europeu em mim.', 'Sou um ano do começo do século 19.', 'Meus dígitos são 1, 8, 0 e 8.', 'Termino com 08.',
    ] },
    { answer: '1977', clues: [
      'Neste ano Elvis Presley morreu, em Graceland.', 'A Apple foi fundada como empresa em mim.', 'O filme "Os Embalos de Sábado à Noite" lançou a febre da disco.', 'As sondas Voyager 1 e 2 foram lançadas em mim.',
      'Charlie Chaplin morreu no Natal de mim.', 'Em mim o Atari 2600 foi lançado.', 'No Brasil, o divórcio foi aprovado em mim.', 'Ernesto Geisel era presidente do Brasil em mim.',
      'A Copa do Mundo seria no ano seguinte, na Argentina.', 'Em mim Reinaldo brilhava no Atlético Mineiro.', 'Um filme de ficção com espadas de luz estreou em maio de mim.', 'Darth Vader apareceu pela primeira vez em mim.',
      'A frase "Que a Força esteja com você" nasceu em mim.', 'O primeiro "Star Wars" é de mim.', 'Sou o ano de "Guerra nas Estrelas".', 'Sou o ano da morte do Rei do Rock.',
      'Sou um ano dos anos 70.', 'Sou um ano ímpar.', 'Meus dois últimos dígitos são iguais.', 'Termino com 77.',
    ] },
    { answer: '2014', clues: [
      'Neste ano a Rússia anexou a Crimeia.', 'O vírus ebola assustou o mundo em mim.', 'Um avião da Malaysia Airlines sumiu no Oceano Índico em mim.', 'O desafio do balde de gelo tomou a internet em mim.',
      'O Facebook comprou o WhatsApp em mim.', 'O filme "Frozen" dominou o Oscar em mim.', 'Robin Williams morreu em mim.', 'Em mim Dilma Rousseff foi reeleita, contra Aécio Neves.',
      'A Operação Lava Jato começou em março de mim.', 'A Copa do Mundo foi no Brasil.', 'Neymar se machucou nas quartas de final.', 'A Alemanha venceu a Argentina na final, no Maracanã.',
      'O Brasil perdeu de 7 a 1 para a Alemanha em mim.', 'O 7 a 1 foi no Mineirão, em 8 de julho de mim.', 'Sou o ano do maior vexame do futebol brasileiro.', 'Sou o ano da Copa do Brasil.',
      'Sou um ano da década de 2010.', 'Sou um ano par.', 'Meus dígitos são 2, 0, 1 e 4.', 'Termino com 14.',
    ] },
    { answer: '1912', clues: [
      'Neste ano Alan Turing nasceu.', 'A Oreo foi lançada em mim.', 'O Arizona virou o 48º estado americano em mim.', 'As Olimpíadas foram em Estocolmo.',
      'O Brasil vivia a República Velha, do café com leite.', 'Hermes da Fonseca era presidente do Brasil.', 'A Guerra do Contestado começou em mim, no sul do Brasil.', 'O Santos Futebol Clube foi fundado em abril de mim.',
      'O Amazonas ainda vivia o fim do ciclo da borracha.', 'Um navio "inafundável" saiu de Southampton em abril de mim.', 'O navio era da companhia White Star Line.', 'O navio bateu num iceberg na madrugada de 15 de abril.',
      'Mais de 1.500 pessoas morreram no naufrágio.', 'O navio não tinha botes para todo mundo.', 'Sou o ano do naufrágio do Titanic.', 'Um filme de 1997 conta a história do que aconteceu em mim.',
      'Sou um ano da década de 1910.', 'Sou um ano bissexto.', 'Meus dígitos são 1, 9, 1 e 2.', 'Termino com 12.',
    ] },
  ],
};
module.exports = { CARDS2 };
