// Rabisco — banco de palavras por categoria.
// Cada entrada: 'palavra' ou 'palavra: parecida1, parecida2'.
// As "parecidas" NÃO valem como acerto: só fazem o jogo avisar "tá muito perto" (sinônimos, apelidos, diminutivos, nome em inglês).
'use strict';
const CATS = [
  { key: 'animais', name: 'Animais', emoji: '🐾' },
  { key: 'comida', name: 'Comida', emoji: '🍕' },
  { key: 'objetos', name: 'Objetos', emoji: '🔧' },
  { key: 'lugares', name: 'Lugares', emoji: '🗺️' },
  { key: 'profissoes', name: 'Profissões', emoji: '👩‍🚒' },
  { key: 'filmes', name: 'Filmes e séries', emoji: '🎬' },
  { key: 'jogos', name: 'Jogos', emoji: '🎮' },
  { key: 'memes', name: 'Memes', emoji: '😂' },
  { key: 'aleatorias', name: 'Aleatórias', emoji: '🎲' },
  { key: 'dificil', name: 'Difíceis', emoji: '🧠' },
];
const WORDS = {
  animais: [
    'cachorro: cão, cãozinho, cachorrinho, dog, totó',
    'gato: gatinho, felino, bichano',
    'capivara',
    'tucano',
    'onça: onça-pintada, jaguar',
    'bicho-preguiça: preguiça',
    'mico-leão',
    'cavalo: égua, pônei',
    'vaca: boi, touro',
    'porco: porquinho, suíno, leitão',
    'galinha: frango, galo, pinto',
    'pato: patinho, marreco',
    'ovelha: carneiro',
    'cabra: bode',
    'coelho: coelhinho, lebre',
    'rato: camundongo, ratinho',
    'elefante',
    'girafa',
    'leão: leoa',
    'tigre',
    'zebra',
    'macaco: mico, chimpanzé',
    'gorila',
    'urso: ursinho',
    'panda',
    'coala',
    'canguru',
    'camelo: dromedário',
    'hipopótamo',
    'rinoceronte',
    'jacaré: crocodilo',
    'cobra: serpente, jiboia, sucuri',
    'tartaruga: cágado, jabuti',
    'sapo: rã, perereca',
    'peixe: peixinho',
    'baleia',
    'golfinho: boto',
    'polvo: lula',
    'caranguejo: siri',
    'estrela-do-mar',
    'água-viva',
    'borboleta',
    'abelha: marimbondo, vespa',
    'formiga',
    'aranha',
    'joaninha',
    'caracol: lesma',
    'minhoca',
    'escorpião',
    'pinguim',
    'coruja',
    'águia: falcão',
    'papagaio: periquito',
    'arara',
    'flamingo',
    'pavão',
    'morcego',
    'lobo',
    'raposa',
    'veado: cervo',
    'esquilo',
    'tamanduá',
    'tatu',
    'lhama: alpaca',
    'foca: leão-marinho',
    'cisne',
    'avestruz: ema',
    'ouriço',
    'camaleão: lagarto',
    'mosquito: pernilongo, muriçoca',
    'libélula',
    'gafanhoto: grilo',
  ],
  comida: [
    'pizza',
    'hambúrguer: burger, lanche',
    'coxinha',
    'brigadeiro',
    'pão de queijo',
    'açaí',
    'feijoada',
    'pastel',
    'bolo',
    'sorvete: gelato',
    'chocolate',
    'pipoca',
    'batata frita: fritas',
    'cachorro-quente: hot dog',
    'macarrão: espaguete, massa, miojo',
    'arroz',
    'feijão',
    'ovo frito: ovo',
    'queijo',
    'pão: pãozinho, pão francês',
    'sanduíche: lanche',
    'salada',
    'sopa: caldo',
    'churrasco: espetinho',
    'linguiça: salsicha',
    'bife: carne, filé',
    'frango assado',
    'lasanha',
    'sushi',
    'taco',
    'panqueca: crepe',
    'waffle',
    'donut: rosquinha',
    'biscoito: bolacha',
    'picolé: sorvete de palito',
    'algodão-doce',
    'pudim',
    'beijinho',
    'tapioca: beiju',
    'acarajé',
    'farofa',
    'banana',
    'maçã',
    'laranja',
    'melancia',
    'abacaxi',
    'uva',
    'morango',
    'limão',
    'manga',
    'coco',
    'mamão',
    'cereja',
    'pera',
    'abacate',
    'cenoura',
    'tomate',
    'milho',
    'brócolis',
    'batata',
    'cebola',
    'alho',
    'pimenta',
    'cogumelo: champignon',
    'melão',
    'pêssego',
    'berinjela',
    'cuscuz',
    'empada',
    'esfiha: esfirra',
    'quindim',
    'canjica: curau',
  ],
  objetos: [
    'geladeira: refrigerador, freezer',
    'cadeira',
    'mesa',
    'sofá',
    'cama',
    'travesseiro',
    'cobertor: manta, coberta',
    'espelho',
    'relógio',
    'telefone',
    'celular: smartphone, telefone',
    'televisão: tv, tevê',
    'controle remoto: controle',
    'computador: pc, notebook, laptop',
    'teclado',
    'mouse',
    'fone de ouvido: headphone',
    'óculos',
    'guarda-chuva: sombrinha',
    'chave',
    'cadeado',
    'tesoura',
    'faca',
    'garfo',
    'colher',
    'prato',
    'copo',
    'xícara: caneca',
    'garrafa',
    'panela',
    'frigideira',
    'vassoura',
    'balde',
    'lixeira: lixo',
    'escova de dente',
    'pente',
    'sabonete',
    'toalha',
    'chuveiro: ducha',
    'vaso sanitário: privada, sanitário',
    'lâmpada',
    'vela',
    'ventilador',
    'ar-condicionado',
    'fogão',
    'micro-ondas',
    'liquidificador',
    'ferro de passar: ferro',
    'máquina de lavar: lavadora',
    'mochila',
    'mala',
    'carteira',
    'caneta',
    'lápis',
    'borracha',
    'caderno',
    'livro',
    'régua',
    'grampeador',
    'martelo',
    'chave de fenda',
    'serra',
    'escada',
    'cabide',
    'tapete',
    'cortina',
    'abajur: luminária',
    'tomada',
    'câmera: máquina fotográfica',
    'microfone',
    'violão',
    'lupa',
    'moeda',
  ],
  lugares: [
    'praia',
    'escola: colégio',
    'farol',
    'vulcão',
    'Cristo Redentor',
    'pirâmide',
    'hospital',
    'igreja',
    'castelo',
    'ponte',
    'montanha: serra, morro',
    'floresta: mata, bosque',
    'deserto',
    'ilha',
    'cachoeira',
    'caverna: gruta',
    'rio',
    'lago',
    'campo de futebol: gramado',
    'estádio',
    'shopping',
    'mercado: supermercado',
    'padaria',
    'farmácia',
    'banco',
    'aeroporto',
    'rodoviária',
    'estação de trem',
    'posto de gasolina',
    'biblioteca',
    'museu',
    'cinema',
    'teatro',
    'circo',
    'zoológico: zoo',
    'parque',
    'playground: parquinho',
    'piscina',
    'academia',
    'restaurante',
    'hotel',
    'fazenda: sítio',
    'iglu',
    'torre Eiffel',
    'Estátua da Liberdade',
    'Muralha da China',
    'Big Ben',
    'Coliseu',
    'Pão de Açúcar',
    'Machu Picchu',
    'Taj Mahal',
    'Amazônia',
    'Pantanal',
    'cemitério',
    'prisão: cadeia',
    'moinho',
    'selva',
    'savana',
    'geleira',
    'Disney',
    'Maracanã',
    'Cataratas do Iguaçu',
    'casa',
    'apartamento: prédio',
    'cozinha',
    'banheiro',
    'quarto',
    'Polo Norte',
  ],
  profissoes: [
    'bombeiro',
    'dentista',
    'astronauta',
    'pizzaiolo',
    'salva-vidas',
    'médico: doutor',
    'enfermeiro: enfermeira',
    'professor: professora',
    'policial: polícia',
    'cozinheiro: chef',
    'padeiro',
    'açougueiro',
    'motorista',
    'piloto',
    'comissário de bordo: aeromoça',
    'carteiro',
    'jardineiro',
    'pintor',
    'pedreiro',
    'eletricista',
    'encanador',
    'mecânico',
    'marceneiro: carpinteiro',
    'fazendeiro',
    'pescador',
    'marinheiro',
    'soldado',
    'juiz',
    'advogado',
    'cientista',
    'veterinário',
    'farmacêutico',
    'cabeleireiro',
    'manicure',
    'barbeiro',
    'costureiro: costureira',
    'fotógrafo',
    'jornalista',
    'repórter',
    'cantor',
    'dançarino: bailarino',
    'ator: atriz',
    'palhaço',
    'mágico',
    'DJ',
    'músico',
    'escritor',
    'garçom',
    'caixa',
    'vendedor',
    'faxineiro',
    'gari: lixeiro',
    'segurança',
    'detetive',
    'arquiteto',
    'engenheiro',
    'programador',
    'youtuber',
    'jogador de futebol',
    'árbitro',
    'treinador',
    'mergulhador',
    'taxista',
    'entregador: motoboy',
    'babá',
    'personal trainer',
    'padre',
    'freira',
  ],
  filmes: [
    'Titanic',
    'Shrek',
    'Toy Story',
    'Frozen',
    'Harry Potter',
    'Star Wars: guerra nas estrelas',
    'Bob Esponja',
    'Chaves',
    'Turma da Mônica',
    'Sítio do Picapau Amarelo',
    'Stranger Things',
    'Round 6: squid game',
    'Rei Leão',
    'Procurando Nemo',
    'Divertida Mente',
    'Carros',
    'Up',
    'Moana',
    'Encanto',
    'Aladdin',
    'Branca de Neve',
    'Cinderela',
    'Bela e a Fera',
    'Pinóquio',
    'Peter Pan',
    'Dumbo',
    'Bambi',
    'Mulan',
    'Enrolados',
    'Madagascar',
    'Kung Fu Panda',
    'Minions',
    'Meu Malvado Favorito',
    'Homem-Aranha: spider-man, aranha',
    'Batman: homem-morcego',
    'Superman',
    'Vingadores',
    'Homem de Ferro: iron man',
    'Hulk',
    'Thor',
    'Pantera Negra',
    'Mulher-Maravilha',
    'Jurassic Park',
    'King Kong',
    'Indiana Jones',
    'Matrix',
    'Avatar',
    'Piratas do Caribe',
    'Senhor dos Anéis',
    'Pokémon',
    'Dragon Ball',
    'Naruto',
    'Os Simpsons: simpsons',
    'Tom e Jerry',
    'Scooby-Doo',
    'Pica-Pau',
    'Mickey Mouse: mickey',
    'Peppa Pig',
    'Patrulha Canina',
    'Galinha Pintadinha',
    'Chapolin',
    'Show da Luna',
    'Friends',
    'Game of Thrones',
    'La Casa de Papel',
    'Carrossel',
    'Chiquititas',
    'Auto da Compadecida',
    'Cidade de Deus',
    'Tropa de Elite',
  ],
  jogos: [
    'Minecraft',
    'Tetris',
    'Pac-Man',
    'Super Mario: mario',
    'xadrez',
    'dominó',
    'UNO',
    'pipa: papagaio, raia',
    'bolinha de gude: bola de gude, gude',
    'amarelinha',
    'Fortnite',
    'Free Fire',
    'Roblox',
    'Among Us',
    'Sonic',
    'Zelda',
    'Pokémon GO',
    'FIFA',
    'GTA',
    'Angry Birds',
    'Candy Crush',
    'Fall Guys',
    'Mario Kart',
    'Donkey Kong',
    'Pong',
    'Space Invaders',
    'damas',
    'ludo',
    'Banco Imobiliário',
    'War',
    'jogo da velha',
    'forca',
    'baralho: cartas',
    'truco',
    'bingo',
    'dados',
    'quebra-cabeça: puzzle',
    'cubo mágico',
    'pião',
    'ioiô',
    'boneca: bonequinha',
    'carrinho',
    'bola',
    'pega-pega',
    'esconde-esconde',
    'pular corda',
    'cabra-cega',
    'elástico',
    'perna de pau',
    'balanço',
    'gangorra',
    'Lego',
    'Genius',
    'pebolim: totó',
    'sinuca: bilhar',
    'boliche',
    'dardos',
    'fliperama: arcade',
    'videogame: console',
    'Nintendo',
    'PlayStation',
    'Xbox',
    'Clash Royale',
    'Subway Surfers',
    'Plants vs Zombies',
    'Kirby',
  ],
  memes: [
    'cachorro caramelo: caramelo, vira-lata',
    'Nazaré confusa',
    'caixão dançante: caixão',
    'emoji: emoticon',
    'selfie: autorretrato',
    'figurinha: sticker',
    'live: transmissão',
    'unboxing',
    'story',
    'print: captura de tela, screenshot',
    'hashtag: jogo da velha',
    'curtida: like',
    'seguidor: follower',
    'influencer: digital influencer, blogueira',
    'viral',
    'dancinha',
    'filtro',
    'GIF',
    'podcast',
    'wi-fi: internet',
    'notificação',
    'bateria fraca',
    'sem sinal',
    'áudio: áudio longo',
    'grupo da família',
    'bom dia',
    'sextou',
    'WhatsApp: zap, zapzap',
    'Instagram: insta',
    'TikTok',
    'YouTube',
    'Facebook',
    'Netflix',
    'Uber',
    'iFood',
    'Pix',
    'QR code',
    'Flork',
    'Doge',
    'Cheems',
    'Troll Face',
    'Nyan Cat',
    'Grumpy Cat',
    'Baby Yoda: grogu',
    'Rickroll',
    'Pepe',
    'Tung Tung Sahur',
    'Moo Deng',
    'Tralalero Tralala',
    'Bombardiro Crocodilo',
    'meme',
    'fake news',
    'mico: vexame',
    'textão',
    'cancelado',
    'perfil',
    'trollagem: zoeira',
  ],
  aleatorias: [
    'arco-íris',
    'fantasma: assombração, alma',
    'foguete: nave espacial',
    'tatuagem: tattoo',
    'robô',
    'sereia',
    'dragão',
    'bolha de sabão: bolha',
    'unicórnio',
    'vampiro: drácula',
    'zumbi',
    'bruxa: feiticeira',
    'fada',
    'pirata',
    'ninja',
    'cavaleiro',
    'princesa',
    'rei',
    'rainha',
    'alienígena: ET, extraterrestre, marciano',
    'OVNI: disco voador',
    'dinossauro: tiranossauro',
    'múmia',
    'monstro',
    'lua',
    'sol',
    'estrela',
    'nuvem',
    'chuva',
    'raio: relâmpago',
    'neve',
    'boneco de neve',
    'fogo: chama',
    'tornado: furacão',
    'planeta',
    'cometa',
    'coração',
    'balão: bexiga',
    'presente',
    'Papai Noel: noel, bom velhinho',
    'árvore de Natal',
    'abóbora',
    'esqueleto',
    'caveira',
    'tesouro',
    'mapa do tesouro',
    'bandeira',
    'coroa',
    'espada',
    'escudo',
    'arco e flecha',
    'âncora',
    'barco',
    'navio',
    'submarino',
    'avião',
    'helicóptero',
    'trem',
    'ônibus',
    'carro',
    'moto',
    'bicicleta: bike, magrela',
    'skate',
    'balão de ar quente',
    'paraquedas',
    'fogueira',
    'castelo de areia',
    'flor',
    'cacto',
    'girassol',
    'bigode',
    'cartola',
    'peruca',
    'máscara',
    'ovo de páscoa',
  ],
  dificil: [
    'saudade',
    'gravidade',
    'eco',
    'eclipse',
    'fuso horário',
    'déjà vu',
    'engarrafamento: trânsito, congestionamento',
    'efeito dominó',
    'cócegas',
    'insônia',
    'ciúme: ciúmes',
    'vergonha',
    'tempo',
    'eletricidade: energia, corrente elétrica',
    'fotossíntese',
    'ciclo da água',
    'efeito estufa',
    'buraco negro',
    'big bang',
    'evolução',
    'inflação',
    'nostalgia',
    'ansiedade',
    'preguiça',
    'pesadelo',
    'sonho',
    'fome',
    'frio',
    'calor',
    'queda livre',
    'ilusão de ótica',
    'miragem',
    'sombra',
    'reflexo',
    'equilíbrio',
    'velocidade',
    'eternidade',
    'liberdade',
    'amizade',
    'sorte',
    'coincidência',
    'mentira',
    'segredo',
    'fofoca',
    'procrastinação',
    'ressaca',
    'nascer do sol: amanhecer',
    'maré',
    'aurora boreal',
    'ecossistema',
    'reciclagem',
    'poluição',
    'aquecimento global',
    'sistema solar',
    'Via Láctea: galáxia',
  ],
};
module.exports = { CATS, WORDS };
