// Palavra Secreta — banco de palavras em pt-BR (Mega Senha).
// Cada categoria guarda as palavras separadas por dificuldade (1 fácil, 2 médio, 3 difícil).
// "aleatorio" não é uma lista: quer dizer "todas as categorias".
const CATS = [
  { id: 'aleatorio', name: 'Aleatório' },
  { id: 'animais', name: 'Animais' },
  { id: 'objetos', name: 'Objetos' },
  { id: 'comidas', name: 'Comidas' },
  { id: 'filmes_series', name: 'Filmes e séries' },
  { id: 'musica', name: 'Música' },
  { id: 'esportes', name: 'Esportes' },
  { id: 'profissoes', name: 'Profissões' },
  { id: 'lugares', name: 'Lugares' },
  { id: 'brasil', name: 'Brasil' },
  { id: 'tecnologia', name: 'Tecnologia' },
  { id: 'cultura_pop', name: 'Cultura pop' },
  { id: 'corpo', name: 'Corpo humano' },
  { id: 'natureza', name: 'Natureza' },
  { id: 'transportes', name: 'Transportes' },
  { id: 'roupas', name: 'Roupas e acessórios' },
  { id: 'acoes', name: 'Ações' },
  { id: 'festas', name: 'Festas e datas' },
  { id: 'casa', name: 'Casa' },
  { id: 'escola', name: 'Escola' },
];

const BANK = {
  animais: {
    1: ["Cachorro", "Gato", "Cavalo", "Vaca", "Porco", "Galinha", "Pato", "Elefante", "Leão", "Tigre", "Macaco", "Urso", "Girafa", "Zebra", "Coelho", "Rato", "Cobra", "Peixe", "Tubarão", "Baleia", "Aranha", "Abelha", "Formiga", "Borboleta", "Pinguim", "Tartaruga", "Sapo", "Jacaré"],
    2: ["Golfinho", "Foca", "Lobo", "Raposa", "Veado", "Águia", "Coruja", "Papagaio", "Tucano", "Canguru", "Camelo", "Rinoceronte", "Hipopótamo", "Panda", "Gorila", "Morcego", "Ovelha", "Cabra", "Búfalo", "Avestruz", "Flamingo", "Pelicano", "Escorpião", "Lagarto", "Caranguejo"],
    3: ["Camaleão", "Preguiça", "Capivara", "Tamanduá", "Onça", "Puma", "Hiena", "Chacal", "Lhama", "Alpaca", "Polvo", "Caracol", "Água-viva", "Ouriço", "Gambá", "Quati", "Mico"],
  },
  objetos: {
    1: ["Mesa", "Cadeira", "Cama", "Sofá", "Televisão", "Geladeira", "Fogão", "Copo", "Prato", "Garfo", "Faca", "Colher", "Panela", "Chave", "Porta", "Janela", "Espelho", "Travesseiro", "Cobertor", "Toalha", "Sabonete", "Escova", "Pente", "Tesoura", "Guarda-chuva", "Chinelo", "Sapato", "Óculos"],
    2: ["Vassoura", "Escada", "Martelo", "Prego", "Parafuso", "Alicate", "Corda", "Balde", "Esponja", "Vela", "Fósforo", "Isqueiro", "Relógio", "Carteira", "Mochila", "Bolsa", "Cinto", "Boné", "Luva", "Cachecol", "Guarda-roupa", "Estante", "Almofada", "Ventilador", "Liquidificador"],
    3: ["Alfinete", "Dedal", "Pinça", "Lanterna", "Termômetro", "Extintor", "Cadeado", "Antena", "Chaveiro", "Abridor", "Espátula", "Peneira", "Rolo de macarrão", "Varal", "Cabide", "Sacola", "Cortina"],
  },
  comidas: {
    1: ["Pizza", "Hambúrguer", "Arroz", "Feijão", "Macarrão", "Batata frita", "Frango", "Carne", "Pão", "Bolo", "Sorvete", "Chocolate", "Pipoca", "Café", "Suco", "Leite", "Queijo", "Açaí", "Ovo", "Salada", "Feijoada", "Churrasco", "Coxinha", "Pastel", "Brigadeiro", "Refrigerante", "Água", "Banana"],
    2: ["Lasanha", "Risoto", "Sushi", "Lanche", "Vitamina", "Milkshake", "Cachorro-quente", "Empanada", "Torta", "Pudim", "Manga", "Abacaxi", "Melancia", "Morango", "Uva", "Maçã", "Laranja", "Limão", "Abacate", "Cenoura", "Tomate", "Cebola", "Alho", "Pepino", "Beterraba"],
    3: ["Estrogonofe", "Moqueca", "Vatapá", "Acarajé", "Tapioca", "Cuscuz", "Farofa", "Rapadura", "Paçoca", "Cocada", "Quindim", "Canjica", "Maionese", "Ketchup", "Mostarda", "Vinagre", "Azeite"],
  },
  filmes_series: {
    1: ["Titanic", "Frozen", "Toy Story", "Shrek", "Vingadores", "Batman", "Homem-Aranha", "Superman", "Star Wars", "Harry Potter", "Matrix", "Jurassic Park", "Chaves", "Friends", "Round 6", "Stranger Things", "Big Brother Brasil", "A Fazenda", "Turma da Mônica", "Sítio do Pica-pau Amarelo", "Rei Leão", "Aladdin", "Cinderela", "Branca de Neve", "Moana", "Coco", "Up", "Wall-e"],
    2: ["Avatar", "Gladiador", "Coringa", "Divertida Mente", "Procurando Nemo", "Carros", "Madagascar", "Zootopia", "Enrolados", "Malévola", "Rocky", "Rambo", "Duro de Matar", "De Volta para o Futuro", "Ghostbusters", "Karatê Kid", "Jumanji", "Homem de Ferro", "Pantera Negra", "Thor", "Hulk", "Capitã Marvel", "Wolverine", "Deadpool", "Esqueceram de Mim"],
    3: ["Avenida Brasil", "Chiquititas", "Malhação", "Caminho das Índias", "Roda a Roda", "Programa do Ratinho", "Domingão", "Fantástico", "Jornal Nacional", "Zorra Total", "Escrava Isaura", "Laços de Família", "O Auto da Compadecida", "Cidade de Deus", "Tropa de Elite", "Central do Brasil", "Bacurau"],
  },
  musica: {
    1: ["Violão", "Guitarra", "Bateria", "Piano", "Microfone", "Karaokê", "Rock", "Sertanejo", "Funk", "Pagode", "Samba", "Forró", "Rap", "Reggae", "Anitta", "Beyoncé", "Madonna", "Michael Jackson", "Elvis Presley", "Roberto Carlos", "Chico Buarque", "Caetano Veloso", "Gilberto Gil", "Pabllo Vittar", "Show", "Palco", "Disco", "Fone de ouvido"],
    2: ["Flauta", "Violino", "Saxofone", "Trompete", "Baixo", "Teclado", "Pandeiro", "Tambor", "Coral", "Banda", "Festival", "Ídolo", "Playback", "Refrão", "Melodia", "Ritmo", "Axé", "Bossa Nova", "MPB", "Rihanna", "Shakira", "Adele", "Elton John", "Queen", "Beatles"],
    3: ["Harpa", "Acordeão", "Cavaquinho", "Berimbau", "Trombone", "Clarinete", "Contrabaixo", "Sinfonia", "Ópera", "Maestro", "Partitura", "Turnê", "Autotune", "Freestyle", "Trap", "K-pop", "Beethoven"],
  },
  esportes: {
    1: ["Futebol", "Vôlei", "Basquete", "Tênis", "Natação", "Corrida", "Ciclismo", "Boxe", "Judô", "Karatê", "Skate", "Surfe", "Ginástica", "Pelé", "Neymar", "Messi", "Cristiano Ronaldo", "Olimpíadas", "Copa do Mundo", "Gol", "Pênalti", "Bola", "Chuteira", "Apito", "Juiz", "Time", "Estádio", "Medalha"],
    2: ["Handebol", "Rugby", "Golfe", "Boliche", "Xadrez", "Maratona", "Triatlo", "Halterofilismo", "Luta livre", "Esgrima", "Remo", "Iatismo", "Patinação", "Atletismo", "Vôlei de praia", "Muay Thai", "Jiu-jitsu", "Fórmula 1", "Motocross", "Arco e flecha", "Salto em distância", "Salto com vara", "Ronaldinho Gaúcho", "Zico", "Romário"],
    3: ["Taekwondo", "Squash", "Polo aquático", "Hipismo", "Nado sincronizado", "Sinuca", "Peteca", "Capoeira", "Bocha", "Frescobol", "Paraquedismo", "Escalada", "Rapel", "Crossfit", "Pilates", "Kart", "Windsurfe"],
  },
  profissoes: {
    1: ["Médico", "Professor", "Bombeiro", "Policial", "Dentista", "Advogado", "Engenheiro", "Cozinheiro", "Garçom", "Cabeleireiro", "Pedreiro", "Eletricista", "Encanador", "Motorista", "Piloto", "Enfermeiro", "Veterinário", "Padeiro", "Açougueiro", "Pescador", "Agricultor", "Costureira", "Faxineira", "Vendedor", "Caixa", "Segurança", "Jardineiro", "Mecânico"],
    2: ["Youtuber", "Fisioterapeuta", "Psicólogo", "Nutricionista", "Farmacêutico", "Contador", "Arquiteto", "Jornalista", "Fotógrafo", "Tradutor", "Bibliotecário", "Marceneiro", "Pintor", "Recepcionista", "Manicure", "Programador", "Designer", "Corretor de imóveis", "Sociólogo", "Diplomata", "Astronauta", "Locutor", "Personal trainer", "Influencer", "Ator"],
    3: ["Zootecnista", "Geólogo", "Astrônomo", "Meteorologista", "Oceanógrafo", "Paleontólogo", "Antropólogo", "Arqueólogo", "Cartógrafo", "Ourives", "Alfaiate", "Sapateiro", "Funileiro", "Tabelião", "Estivador", "Lobista", "Coveiro"],
  },
  lugares: {
    1: ["Praia", "Aeroporto", "Padaria", "Hospital", "Escola", "Igreja", "Mercado", "Farmácia", "Cinema", "Parque", "Shopping", "Restaurante", "Hotel", "Banheiro", "Cozinha", "Escritório", "Estádio", "Biblioteca", "Fazenda", "Floresta", "Montanha", "Rio", "Deserto", "Ilha", "Praça", "Zoológico", "Museu", "Ponte"],
    2: ["Paris", "Egito", "Japão", "Índia", "México", "Nova York", "Londres", "Roma", "Veneza", "Havaí", "Alasca", "Antártida", "Saara", "Groenlândia", "Polo Norte", "Vaticano", "Torre Eiffel", "Muralha da China", "Pirâmides", "Vulcão", "Cachoeira", "Caverna", "Vinhedo", "Savana", "Iceberg"],
    3: ["Machu Picchu", "Chernobyl", "Estreito de Bering", "Triângulo das Bermudas", "Monte Everest", "Fossa das Marianas", "Ilhas Galápagos", "Serengeti", "Sibéria", "Patagônia", "Mar Morto", "Estação Espacial", "Polo Sul", "Vinícola", "Catacumbas", "Observatório", "Planetário"],
  },
  brasil: {
    1: ["Carnaval", "Cristo Redentor", "Copacabana", "Samba", "Futebol", "Havaianas", "Ipanema", "Maracanã", "Amazônia", "Pantanal", "Favela", "Carioca", "Paulista", "Nordestino", "Gaúcho", "Baiano", "Mineiro", "Funk", "Sertanejo", "Axé", "Pagode", "Bloco de carnaval", "Trio elétrico", "Rede de dormir", "Chinelo", "Sunga", "Biquíni", "Escola de samba"],
    2: ["Capoeira", "Forró", "Bossa nova", "Bumba meu boi", "Boi-bumbá", "Jangada", "Cangaço", "Lampião", "Saci-pererê", "Curupira", "Boto cor-de-rosa", "Jeitinho brasileiro", "Pelourinho", "Sertão", "Cerrado", "Caatinga", "Boi de Parintins", "Fla-Flu", "Frevo", "Maracatu", "Berimbau", "Cuíca", "Repentista", "Cordel", "Vaquejada"],
    3: ["Umbanda", "Candomblé", "Orixá", "Quilombo", "Bandeirante", "Vaqueiro", "Tropicália", "Cangaceiro", "Iemanjá", "Zumbi dos Palmares", "Alforria", "Engenho", "Coronelismo", "Retirante", "Sesmaria", "Jangadeiro", "Pajelança"],
  },
  tecnologia: {
    1: ["Pix", "Wi-Fi", "Celular", "Senha", "Internet", "Computador", "Notebook", "Teclado", "Mouse", "Impressora", "Televisão", "Controle remoto", "Fone de ouvido", "Carregador", "Bateria", "Aplicativo", "WhatsApp", "Instagram", "Facebook", "Câmera", "Tablet", "E-mail", "Site", "Download", "Vídeo chamada", "Software", "Hardware", "Google"],
    2: ["Bluetooth", "Inteligência artificial", "Nuvem", "Criptomoeda", "Streaming", "Realidade virtual", "Impressora 3D", "Código de barras", "QR code", "Chip", "Placa-mãe", "Processador", "Servidor", "Antivírus", "Robô", "Satélite", "Drone", "GPS", "Fibra óptica", "Roteador", "Pendrive", "Biometria", "Criptografia", "Chatbot", "Firewall"],
    3: ["Blockchain", "Metaverso", "Big data", "Machine learning", "Realidade aumentada", "Nanotecnologia", "Semicondutor", "Firmware", "Kernel", "API", "Deep learning", "Reconhecimento facial", "Algoritmo", "Autenticação", "Token", "Open source", "Backend"],
  },
  cultura_pop: {
    1: ["Mario", "Pokémon", "TikTok", "Homem-Aranha", "Barbie", "Emoji", "Batman", "Superman", "Mickey Mouse", "Frozen", "Minecraft", "Naruto", "Pikachu", "Star Wars", "Harry Potter", "Netflix", "Meme", "Selfie", "Zumbi", "Vampiro", "Princesa", "Super-herói", "Vilão", "Dinossauro", "Desenho animado", "Novela", "Boneca", "Máscara"],
    2: ["Homem de Ferro", "Capitão América", "Hulk", "Thor", "Shrek", "Simpsons", "Bob Esponja", "Cinderela", "Branca de Neve", "Chapeuzinho Vermelho", "Lobisomem", "Bruxa", "Fada", "Dragão", "Roblox", "Fortnite", "GTA", "PlayStation", "Xbox", "Podcast", "Reels", "Hashtag", "Streamer", "Cosplay", "Gamer"],
    3: ["Anime", "Mangá", "Multiverso", "Nerd", "Geek", "Fandom", "Spoiler", "Crossover", "Prequela", "Sequência", "Remake", "Reboot", "Trailer", "Bilheteria", "Roteirista", "Dublagem", "Legendado"],
  },
};

// palavras a mais — somadas ao BANK acima (repetidas na mesma categoria são ignoradas)
const EXTRA = {
  animais: {
    1: ["Pássaro", "Papagaio", "Galo", "Pintinho", "Burro", "Mosquito", "Mosca", "Barata", "Minhoca", "Joaninha", "Peixinho", "Gatinho", "Filhote", "Ovelha", "Lagartixa", "Esquilo", "Hamster", "Canário", "Pombo", "Polvo", "Camarão", "Lagosta", "Cavalo-marinho", "Estrela-do-mar", "Leopardo", "Pantera", "Dinossauro", "Unicórnio", "Grilo"],
    2: ["Pavão", "Cisne", "Gaivota", "Pica-pau", "Beija-flor", "Arara", "Urubu", "Gavião", "Falcão", "Andorinha", "Periquito", "Peru", "Codorna", "Javali", "Texugo", "Castor", "Lontra", "Morsa", "Leão-marinho", "Orca", "Arraia", "Piranha", "Sardinha", "Salmão", "Atum", "Bacalhau", "Lula", "Ostra", "Mexilhão", "Libélula", "Vaga-lume", "Cigarra", "Gafanhoto", "Louva-a-deus", "Cupim", "Lesma", "Centopeia", "Carrapato", "Pulga", "Piolho", "Coala", "Chimpanzé", "Orangotango", "Guaxinim", "Doninha", "Iguana", "Sucuri", "Jiboia", "Cascavel", "Tatu"],
    3: ["Ornitorrinco", "Suricato", "Lêmure", "Tamanduá-bandeira", "Mico-leão-dourado", "Ariranha", "Peixe-boi", "Boto", "Jabuti", "Cágado", "Salamandra", "Axolote", "Musaranho", "Toupeira", "Furão", "Chinchila", "Porco-espinho", "Pangolim", "Gnu", "Antílope", "Gazela", "Bisão", "Iaque", "Alce", "Rena", "Narval", "Peixe-espada", "Baiacu", "Moreia", "Enguia", "Tarântula", "Viúva-negra", "Caranguejeira", "Louva-deus", "Bicho-preguiça", "Seriema", "Ema", "Carcará", "Jacu", "Sabiá", "Bem-te-vi", "João-de-barro", "Quero-quero", "Tico-tico", "Sagui", "Bugio", "Jaguatirica", "Lobo-guará", "Anta"],
  },
  objetos: {
    1: ["Caneta", "Lápis", "Borracha", "Caderno", "Livro", "Bola", "Boneca", "Carrinho", "Brinquedo", "Lâmpada", "Tomada", "Controle", "Celular", "Rádio", "Mala", "Caixa", "Garrafa", "Xícara", "Tigela", "Balão", "Presente", "Moeda", "Dinheiro", "Anel", "Colar", "Brinco", "Pulseira", "Chapéu", "Meia", "Escova de dente", "Pasta de dente", "Papel higiênico", "Shampoo", "Secador", "Ferro de passar", "Micro-ondas", "Torradeira", "Mesa de jantar", "Lixeira", "Tapete"],
    2: ["Agulha", "Linha", "Botão", "Zíper", "Fita adesiva", "Cola", "Grampeador", "Clipe", "Régua", "Calculadora", "Apontador", "Estojo", "Envelope", "Selo", "Carimbo", "Agenda", "Calendário", "Despertador", "Ampulheta", "Bússola", "Binóculo", "Lupa", "Microscópio", "Telescópio", "Megafone", "Apito", "Sino", "Campainha", "Maçaneta", "Fechadura", "Dobradiça", "Interruptor", "Extensão", "Pilha", "Serrote", "Furadeira", "Chave de fenda", "Trena", "Mangueira", "Regador", "Pá", "Enxada", "Carrinho de mão", "Tábua de passar", "Prendedor", "Rodo", "Pano de chão", "Espanador", "Aspirador de pó", "Batedeira"],
    3: ["Cafeteira", "Chaleira", "Coador", "Saleiro", "Paliteiro", "Galheteiro", "Fruteira", "Abajur", "Lustre", "Castiçal", "Porta-retrato", "Quadro", "Vaso", "Bumerangue", "Estilingue", "Pião", "Ioiô", "Bilboquê", "Cata-vento", "Pipa", "Bambolê", "Dominó", "Baralho", "Dado", "Tabuleiro", "Quebra-cabeça", "Cubo mágico", "Caleidoscópio", "Metrônomo", "Diapasão", "Estetoscópio", "Seringa", "Muleta", "Cadeira de rodas", "Andador", "Marreta", "Picareta", "Bigorna", "Torno", "Esquadro", "Compasso", "Transferidor", "Nível de bolha", "Pé de cabra", "Tesoura de poda", "Ralador", "Escumadeira", "Concha", "Pegador de massa"],
  },
  comidas: {
    1: ["Biscoito", "Bolacha", "Pão de queijo", "Misto-quente", "Sanduíche", "Cuscuz", "Mingau", "Iogurte", "Manteiga", "Requeijão", "Presunto", "Mortadela", "Salsicha", "Linguiça", "Bife", "Peixe frito", "Purê", "Sopa", "Miojo", "Torrada", "Panqueca", "Omelete", "Ovo frito", "Gelatina", "Picolé", "Bala", "Chiclete", "Pirulito", "Algodão-doce", "Maçã do amor", "Cachorro-quente", "Esfiha", "Kibe", "Empada", "Bolo de chocolate", "Coco", "Mamão", "Pera", "Goiaba", "Melão"],
    2: ["Nhoque", "Panetone", "Rabanada", "Polenta", "Escondidinho", "Bobó de camarão", "Galinhada", "Baião de dois", "Arroz carreteiro", "Picanha", "Costela", "Cupim", "Maminha", "Fraldinha", "Coração de frango", "Pão francês", "Croissant", "Waffle", "Crepe", "Churros", "Sonho", "Donut", "Cheesecake", "Mousse", "Pavê", "Petit gâteau", "Brownie", "Cupcake", "Macarons", "Beijinho", "Romeu e Julieta", "Goiabada", "Doce de leite", "Leite condensado", "Chantilly", "Granola", "Aveia", "Mel", "Geleia", "Amendoim", "Castanha", "Nozes", "Pistache", "Kiwi", "Pitaya", "Maracujá", "Caju", "Jabuticaba", "Acerola", "Tangerina"],
    3: ["Tacacá", "Maniçoba", "Pato no tucupi", "Buchada", "Sarapatel", "Caruru", "Arroz de cuxá", "Pamonha", "Curau", "Pé de moleque", "Baba de moça", "Bolo de rolo", "Cartola", "Queijo coalho", "Carne de sol", "Charque", "Paçoca de pilão", "Tutu de feijão", "Virado à paulista", "Torresmo", "Chimarrão", "Tereré", "Guaraná", "Caldo de cana", "Garapa", "Quentão", "Caipirinha", "Pinhão", "Cambuci", "Cupuaçu", "Bacuri", "Graviola", "Pequi", "Buriti", "Umbu", "Carambola", "Lichia", "Physalis", "Mexerica", "Fondue", "Paella", "Ratatouille", "Guacamole", "Burrito", "Taco", "Yakisoba", "Temaki", "Ceviche", "Falafel", "Homus"],
  },
  filmes_series: {
    1: ["Pinóquio", "Peter Pan", "Dumbo", "Bambi", "Mogli", "A Bela e a Fera", "A Pequena Sereia", "Rapunzel", "Os Incríveis", "Monstros S.A.", "Kung Fu Panda", "Minions", "Meu Malvado Favorito", "Sonic", "Pokémon", "Os Simpsons", "Bob Esponja", "Peppa Pig", "Patrulha Canina", "Galinha Pintadinha", "Mundo Bita", "Castelo Rá-Tim-Bum", "Pica-Pau", "Tom e Jerry", "Scooby-Doo", "Pernalonga", "Patolino", "Os Flintstones"],
    2: ["O Senhor dos Anéis", "Piratas do Caribe", "Indiana Jones", "Missão Impossível", "Velozes e Furiosos", "Transformers", "Exterminador do Futuro", "Tubarão", "E.T.", "Gremlins", "Os Goonies", "Forrest Gump", "O Poderoso Chefão", "Pulp Fiction", "Kill Bill", "Interestelar", "A Origem", "Barbie", "Oppenheimer", "Wandinha", "La Casa de Papel", "Breaking Bad", "Game of Thrones", "The Walking Dead", "Grey's Anatomy", "The Office", "Os Cavaleiros do Zodíaco", "Dragon Ball", "Naruto", "One Piece", "Todo Mundo Odeia o Chris", "Eu, a Patroa e as Crianças", "Um Maluco no Pedaço", "Chapolin", "Pantanal", "Mulan", "Pocahontas", "Hércules", "Tarzan", "Lilo & Stitch", "Valente", "Encanto", "Luca", "Soul", "Ratatouille", "Vida de Inseto", "Era do Gelo", "Rio", "Hotel Transilvânia", "Detona Ralph"],
    3: ["Cidadão Kane", "Casablanca", "Psicose", "O Iluminado", "Laranja Mecânica", "2001: Uma Odisseia no Espaço", "Blade Runner", "Alien", "O Silêncio dos Inocentes", "Clube da Luta", "Seven", "Os Bons Companheiros", "Taxi Driver", "Apocalypse Now", "O Labirinto do Fauno", "A Viagem de Chihiro", "Meu Amigo Totoro", "Parasita", "Ainda Estou Aqui", "Que Horas Ela Volta?", "Lisbela e o Prisioneiro", "Carandiru", "Dois Filhos de Francisco", "Se Eu Fosse Você", "Minha Mãe é uma Peça", "Tropa de Elite 2", "O Palhaço", "Bingo", "Marighella", "Vale Tudo", "Tieta", "Roque Santeiro", "Mulheres de Areia", "O Clone", "Senhora do Destino", "A Favorita", "Amor de Mãe", "Terra Nostra", "O Rei do Gado", "Sucessor", "Peaky Blinders", "Dark", "Lost", "Black Mirror", "Succession", "The Crown", "Sherlock", "Twin Peaks", "Seinfeld", "Os Sopranos"],
  },
  musica: {
    1: ["Cantor", "Cantora", "Música", "Canção", "Rádio", "Dança", "Balada", "Festa", "Ivete Sangalo", "Xuxa", "Luan Santana", "Gusttavo Lima", "Marília Mendonça", "Taylor Swift", "Justin Bieber", "Bruno Mars", "Lady Gaga", "Ed Sheeran", "Tim Maia", "Rita Lee", "Legião Urbana", "Mamonas Assassinas", "Sandy e Junior", "Parabéns pra você", "Hino nacional", "Ciranda", "Cantiga de roda"],
    2: ["Zezé Di Camargo", "Chitãozinho e Xororó", "Jorge e Mateus", "Henrique e Juliano", "Maiara e Maraisa", "Simone e Simaria", "Ludmilla", "IZA", "Gloria Groove", "Marisa Monte", "Djavan", "Milton Nascimento", "Elis Regina", "Gal Costa", "Maria Bethânia", "Cazuza", "Raul Seixas", "Titãs", "Paralamas do Sucesso", "Skank", "Jota Quest", "Charlie Brown Jr.", "Os Mutantes", "Sepultura", "Racionais MC's", "Emicida", "Seu Jorge", "Zeca Pagodinho", "Alcione", "Beth Carvalho", "Luiz Gonzaga", "Dominguinhos", "Daniela Mercury", "Claudia Leitte", "Bell Marques", "Metallica", "Nirvana", "Coldplay", "U2", "The Rolling Stones", "Pink Floyd", "Led Zeppelin", "AC/DC", "Bon Jovi", "ABBA", "Eminem", "Snoop Dogg", "Drake", "Dua Lipa", "Billie Eilish"],
    3: ["Tom Jobim", "Vinicius de Moraes", "João Gilberto", "Cartola", "Noel Rosa", "Pixinguinha", "Adoniran Barbosa", "Clara Nunes", "Jorge Ben Jor", "Belchior", "Fagner", "Alceu Valença", "Elba Ramalho", "Zé Ramalho", "Ney Matogrosso", "Secos & Molhados", "Novos Baianos", "Chico Science", "Nação Zumbi", "Cássia Eller", "Mozart", "Bach", "Chopin", "Vivaldi", "Villa-Lobos", "Carlos Gomes", "Orquestra", "Regente", "Tenor", "Soprano", "Barítono", "Dueto", "Quarteto", "Solo", "Improviso", "Acústico", "Unplugged", "Videoclipe", "Single", "Álbum", "Vinil", "Toca-discos", "Gramofone", "Xilofone", "Gaita", "Ukulele", "Bandolim", "Triângulo", "Zabumba", "Agogô"],
  },
  esportes: {
    1: ["Raquete", "Rede", "Cesta", "Piscina", "Trave", "Goleiro", "Atacante", "Zagueiro", "Torcida", "Uniforme", "Camisa 10", "Escanteio", "Cartão vermelho", "Cartão amarelo", "Impedimento", "Falta", "Campeonato", "Taça", "Pódio", "Ouro", "Prata", "Bronze", "Corrida de carro", "Pula-corda", "Pique-esconde", "Queimada", "Amarelinha", "Pega-pega"],
    2: ["Ayrton Senna", "Rebeca Andrade", "Marta", "Rayssa Leal", "Gabriel Medina", "Ítalo Ferreira", "Guga", "Oscar Schmidt", "Hortência", "Daiane dos Santos", "Popó", "Anderson Silva", "Usain Bolt", "Michael Phelps", "Serena Williams", "Roger Federer", "Michael Jordan", "LeBron James", "Tiger Woods", "Mike Tyson", "Muhammad Ali", "Maradona", "Mbappé", "Vinícius Júnior", "Kaká", "Ronaldo Fenômeno", "Cafu", "Garrincha", "Flamengo", "Corinthians", "Palmeiras", "São Paulo", "Vasco", "Grêmio", "Internacional", "Cruzeiro", "Atlético Mineiro", "Santos", "Botafogo", "Fluminense", "Libertadores", "Brasileirão", "Champions League", "Super Bowl", "NBA", "Wimbledon", "Tour de France", "Paraolimpíadas", "Ironman", "UFC"],
    3: ["Biatlo", "Pentatlo", "Decatlo", "Heptatlo", "Lançamento de dardo", "Arremesso de peso", "Lançamento de martelo", "Salto triplo", "Salto ornamental", "Canoagem", "Caiaque", "Rafting", "Bodyboard", "Kitesurfe", "Stand up paddle", "Wakeboard", "Snowboard", "Esqui", "Curling", "Hóquei no gelo", "Bobsled", "Badminton", "Beisebol", "Críquete", "Lacrosse", "Futebol americano", "Softbol", "Sumô", "Kung fu", "Krav maga", "Kickboxing", "Parkour", "Slackline", "Base jump", "Asa-delta", "Parapente", "Balonismo", "Tiro esportivo", "Levantamento de peso", "Fisiculturismo", "Futevôlei", "Futsal", "Beach tennis", "Padel", "Tênis de mesa", "Pingue-pongue", "Mountain bike", "BMX", "Patins", "Rolimã"],
  },
  profissoes: {
    1: ["Cantor", "Ator", "Palhaço", "Mágico", "Carteiro", "Lixeiro", "Porteiro", "Babá", "Taxista", "Pintor de parede", "Confeiteiro", "Chef", "Soldado", "Marinheiro", "Pirata", "Cowboy", "Rei", "Rainha", "Juiz", "Detetive", "Cientista", "Inventor", "Artista", "Escritor", "Dançarino", "Modelo", "Atleta", "Treinador"],
    2: ["Comissário de bordo", "Controlador de voo", "Maquinista", "Caminhoneiro", "Motoboy", "Entregador", "Frentista", "Guarda de trânsito", "Salva-vidas", "Guia turístico", "Sommelier", "Barista", "Bartender", "DJ", "Produtor musical", "Roteirista", "Diretor de cinema", "Dublador", "Apresentador", "Repórter", "Âncora", "Cartunista", "Ilustrador", "Escultor", "Tatuador", "Barbeiro", "Esteticista", "Maquiador", "Podólogo", "Ortodontista", "Pediatra", "Cardiologista", "Cirurgião", "Anestesista", "Parteira", "Fonoaudiólogo", "Terapeuta", "Biólogo", "Químico", "Físico", "Matemático", "Economista", "Administrador", "Gerente", "Secretária", "Promotor", "Delegado", "Juiz de futebol", "Vereador", "Prefeito"],
    3: ["Despachante", "Leiloeiro", "Perito criminal", "Legista", "Agrimensor", "Topógrafo", "Enólogo", "Apicultor", "Avicultor", "Piscicultor", "Seringueiro", "Garimpeiro", "Minerador", "Ferreiro", "Serralheiro", "Vidraceiro", "Gesseiro", "Azulejista", "Calceteiro", "Torneiro mecânico", "Soldador", "Ourives", "Relojoeiro", "Luthier", "Afinador de piano", "Taxidermista", "Embalsamador", "Ascensorista", "Ventríloquo", "Malabarista", "Equilibrista", "Trapezista", "Domador", "Contorcionista", "Atuário", "Auditor", "Escrivão", "Oficial de justiça", "Desembargador", "Ministro", "Embaixador", "Cônsul", "Senador", "Governador", "Astrofísico", "Neurocientista", "Geneticista", "Epidemiologista", "Sismólogo", "Vulcanólogo"],
  },
  lugares: {
    1: ["Casa", "Apartamento", "Quarto", "Sala", "Quintal", "Jardim", "Garagem", "Rua", "Calçada", "Esquina", "Ponto de ônibus", "Rodoviária", "Estação de metrô", "Posto de gasolina", "Banco", "Correio", "Delegacia", "Prefeitura", "Academia", "Piscina", "Clube", "Circo", "Parque de diversões", "Feira", "Sorveteria", "Lanchonete", "Pizzaria", "Salão de beleza", "Lavanderia", "Cemitério"],
    2: ["Hospital veterinário", "Pet shop", "Açougue", "Peixaria", "Quitanda", "Hortifruti", "Floricultura", "Livraria", "Papelaria", "Loja de brinquedos", "Joalheria", "Ótica", "Boate", "Teatro", "Estúdio", "Laboratório", "Fábrica", "Porto", "Cais", "Farol", "Castelo", "Palácio", "Templo", "Mesquita", "Sinagoga", "Catedral", "Mosteiro", "Convento", "Presídio", "Tribunal", "Quartel", "Embaixada", "Universidade", "Creche", "Asilo", "Orfanato", "Pousada", "Camping", "Resort", "Spa", "Chalé", "Cabana", "Iglu", "Oca", "Pântano", "Mangue", "Lagoa", "Oásis", "Canyon", "Geleira"],
    3: ["Grand Canyon", "Stonehenge", "Coliseu", "Partenon", "Acrópole", "Taj Mahal", "Petra", "Angkor Wat", "Chichén Itzá", "Ilha de Páscoa", "Cataratas do Iguaçu", "Lençóis Maranhenses", "Fernando de Noronha", "Chapada Diamantina", "Chapada dos Veadeiros", "Bonito", "Jalapão", "Pão de Açúcar", "Ouro Preto", "Brasília", "Manaus", "Salvador", "Recife", "Fortaleza", "Florianópolis", "Gramado", "Foz do Iguaçu", "Porto de Galinhas", "Jericoacoara", "Ilha Grande", "Torre de Pisa", "Big Ben", "Estátua da Liberdade", "Times Square", "Hollywood", "Las Vegas", "Disney", "Dubai", "Burj Khalifa", "Santorini", "Islândia", "Noruega", "Austrália", "Nova Zelândia", "Madagascar", "Kilimanjaro", "Rio Nilo", "Rio Amazonas", "Cordilheira dos Andes", "Himalaia"],
  },
  brasil: {
    1: ["Feijoada", "Brigadeiro", "Coxinha", "Pão de queijo", "Caipirinha", "Guaraná", "Seleção brasileira", "Pentacampeão", "Copa de 70", "Bandeira do Brasil", "Verde e amarelo", "Rio de Janeiro", "São Paulo", "Bahia", "Pernambuco", "Minas Gerais", "Festa junina", "Quadrilha", "São João", "Réveillon em Copacabana", "Novela das nove", "Silvio Santos", "Faustão", "Xuxa", "Pelé", "Zé Gotinha", "Turma da Mônica", "Cebolinha", "Cascão", "Magali"],
    2: ["Tiradentes", "Dom Pedro I", "Dom Pedro II", "Princesa Isabel", "Getúlio Vargas", "Juscelino Kubitschek", "Santos Dumont", "Oscar Niemeyer", "Tarsila do Amaral", "Portinari", "Machado de Assis", "Monteiro Lobato", "Jorge Amado", "Clarice Lispector", "Carlos Drummond", "Cecília Meireles", "Ariano Suassuna", "Chico Xavier", "Irmã Dulce", "Padre Cícero", "Independência", "Grito do Ipiranga", "Proclamação da República", "Abolição", "Descobrimento", "Cabral", "Caravela", "Pau-brasil", "Real", "Cruzeiro", "Mula sem cabeça", "Cuca", "Iara", "Boitatá", "Negrinho do Pastoreio", "Mapinguari", "Corpo seco", "Comadre Fulozinha", "Círio de Nazaré", "Festa do Peão", "Oktoberfest de Blumenau", "Parintins", "Galo da Madrugada", "Sapucaí", "Sambódromo", "Mangueira", "Portela", "Beija-Flor", "Salgueiro", "Viradouro"],
    3: ["Inconfidência Mineira", "Revolta da Vacina", "Revolta da Chibata", "Guerra de Canudos", "Antônio Conselheiro", "Guerra do Paraguai", "Farroupilha", "Cabanagem", "Balaiada", "Sabinada", "Estado Novo", "Diretas Já", "Plano Real", "Era Vargas", "República Velha", "Café com leite", "Ciclo do ouro", "Ciclo da borracha", "Bandeirantes", "Entradas e bandeiras", "Capitanias hereditárias", "Missões jesuíticas", "Sete Povos das Missões", "Aleijadinho", "Debret", "Anita Garibaldi", "Maria Quitéria", "Dandara", "Chica da Silva", "Marquês de Pombal", "Semana de Arte Moderna", "Antropofagia", "Cinema Novo", "Glauber Rocha", "Jovem Guarda", "Tropicalismo", "Mangue beat", "Baile funk", "Tecnobrega", "Carimbó", "Lundu", "Maxixe", "Choro", "Moda de viola", "Catira", "Congada", "Reisado", "Cavalhada", "Festa do Divino", "Literatura de cordel"],
  },
  tecnologia: {
    1: ["Videogame", "Joystick", "Console", "Smartphone", "Smartwatch", "Selfie", "Emoji", "Figurinha", "Áudio", "Print", "Story", "Live", "YouTube", "TikTok", "Netflix", "Spotify", "Uber", "iFood", "Mensagem", "Notificação", "Atualização", "Tela", "Touch", "Bateria fraca", "Pen drive", "Caixa de som", "Microfone", "Webcam"],
    2: ["Wi-Fi grátis", "Modo avião", "Hotspot", "Backup", "Login", "Logout", "Cadastro", "Captcha", "Cookie", "Spam", "Vírus", "Hacker", "Golpe do Pix", "Phishing", "Link", "Navegador", "Aba", "Favoritos", "Histórico", "Pesquisa", "Hashtag", "Algoritmo do Instagram", "Influenciador", "Seguidor", "Curtida", "Comentário", "Compartilhar", "Viralizar", "Cancelamento", "Fake news", "Deepfake", "Filtro", "Avatar", "NFT", "Bitcoin", "Carro elétrico", "Carro autônomo", "Assistente virtual", "Alexa", "Siri", "ChatGPT", "Smart TV", "Chromecast", "Tela dobrável", "Carregador por indução", "Power bank", "SSD", "HD externo", "Memória RAM", "Placa de vídeo"],
    3: ["Computação quântica", "Internet das coisas", "5G", "Edge computing", "Microsserviço", "Docker", "Banco de dados", "Compilador", "Linguagem de programação", "Python", "JavaScript", "HTML", "Linux", "Windows", "Android", "iOS", "Terminal", "Debug", "Bug", "Deploy", "Git", "Commit", "Pull request", "Cache", "Pixel", "Resolução", "Taxa de quadros", "Latência", "Banda larga", "Endereço IP", "DNS", "Protocolo", "Servidor em nuvem", "Data center", "Supercomputador", "Transistor", "Circuito", "Placa de circuito", "Silício", "Sensor", "Lidar", "Exoesqueleto", "Impressão 4D", "Holograma", "Teletransporte", "Neuralink", "Interface cérebro-máquina", "Engenharia reversa", "Código-fonte", "Inteligência artificial generativa"],
  },
  cultura_pop: {
    1: ["Sonic", "Luigi", "Yoshi", "Bowser", "Princesa Peach", "Pac-Man", "Tetris", "Free Fire", "Among Us", "Stitch", "Elsa", "Olaf", "Buzz Lightyear", "Woody", "Nemo", "Dory", "Relâmpago McQueen", "Shrek", "Burro do Shrek", "Gato de Botas", "Mulher-Maravilha", "Flash", "Aquaman", "Coringa", "Darth Vader", "Yoda", "Super Mario", "Goku"],
    2: ["Zelda", "Link", "Kirby", "Donkey Kong", "Crash Bandicoot", "Lara Croft", "Kratos", "Master Chief", "Street Fighter", "Mortal Kombat", "League of Legends", "Counter-Strike", "Valorant", "The Sims", "Animal Crossing", "Call of Duty", "Fifa", "Guitar Hero", "Just Dance", "Wolverine", "Tempestade", "Viúva Negra", "Gavião Arqueiro", "Doutor Estranho", "Thanos", "Loki", "Groot", "Rocket Raccoon", "Venom", "Arlequina", "Mulher-Gato", "Robin", "Lanterna Verde", "Liga da Justiça", "X-Men", "Quarteto Fantástico", "Tartarugas Ninja", "Power Rangers", "Jaspion", "Chaves", "Chiquinha", "Seu Madruga", "Kiko", "Dona Florinda", "Professor Girafales", "Senhor Barriga", "Chapolin Colorado", "Wandinha", "Mamonas", "Meme do caixão"],
    3: ["Easter egg", "Fan fiction", "Plot twist", "Cliffhanger", "Universo cinematográfico", "Spin-off", "Live-action", "Stop motion", "Animação 3D", "Cena pós-créditos", "Personagem secundário", "Anti-herói", "Arco narrativo", "Fã-clube", "Comic Con", "CCXP", "Oscar", "Globo de Ouro", "Grammy", "Emmy", "Festival de Cannes", "Tapete vermelho", "Paparazzi", "Celebridade", "Subcelebridade", "Reality show", "Paredão", "Eliminação", "Big Fone", "Prova do líder", "Anjo", "Monstro", "Biscoiteiro", "Lacrar", "Shippar", "Crush", "Stalkear", "Cringe", "Hype", "Trend", "Desafio viral", "Unboxing", "Review", "Gameplay", "Speedrun", "Esports", "Skin", "Battle royale", "Mundo aberto", "Chefão"],
  },
  corpo: {
    1: ["Cabeça", "Cabelo", "Olho", "Nariz", "Boca", "Orelha", "Dente", "Língua", "Pescoço", "Ombro", "Braço", "Mão", "Dedo", "Unha", "Barriga", "Umbigo", "Costas", "Perna", "Joelho", "Pé", "Coração", "Bochecha", "Testa", "Queixo", "Lábio", "Sobrancelha", "Cílios", "Bumbum", "Peito", "Cotovelo"],
    2: ["Pulmão", "Fígado", "Estômago", "Rim", "Intestino", "Cérebro", "Esqueleto", "Osso", "Músculo", "Sangue", "Veia", "Pele", "Tornozelo", "Calcanhar", "Punho", "Palma da mão", "Polegar", "Mindinho", "Dedão do pé", "Canela", "Coxa", "Quadril", "Cintura", "Axila", "Nuca", "Garganta", "Gengiva", "Bigode", "Barba", "Pinta", "Sarda", "Covinha", "Careca", "Franja", "Topete", "Trança", "Rabo de cavalo", "Ruga", "Cicatriz", "Espinha"],
    3: ["Clavícula", "Fêmur", "Tíbia", "Rótula", "Costela", "Coluna vertebral", "Crânio", "Mandíbula", "Pâncreas", "Baço", "Vesícula", "Bexiga", "Diafragma", "Traqueia", "Esôfago", "Laringe", "Faringe", "Amígdala", "Apêndice", "Tímpano", "Córnea", "Retina", "Pupila", "Íris", "Glândula", "Hormônio", "Neurônio", "Tendão", "Ligamento", "Cartilagem", "Medula", "Artéria", "Glóbulo vermelho", "Plaqueta", "DNA", "Célula", "Bíceps", "Tríceps", "Panturrilha", "Abdômen", "Glúteo", "Omoplata", "Pomo de adão", "Úvula", "Sinapse", "Metabolismo", "Digestão", "Respiração", "Batimento cardíaco", "Pressão arterial"],
  },
  natureza: {
    1: ["Sol", "Lua", "Estrela", "Nuvem", "Chuva", "Vento", "Neve", "Gelo", "Fogo", "Árvore", "Flor", "Folha", "Grama", "Pedra", "Areia", "Mar", "Onda", "Céu", "Arco-íris", "Trovão", "Raio", "Terra", "Planeta", "Rosa", "Girassol", "Cacto", "Lago", "Morro", "Fruta", "Semente"],
    2: ["Tempestade", "Furacão", "Tornado", "Terremoto", "Tsunami", "Enchente", "Seca", "Neblina", "Orvalho", "Granizo", "Geada", "Relâmpago", "Eclipse", "Cometa", "Meteoro", "Galáxia", "Via Láctea", "Constelação", "Lua cheia", "Pôr do sol", "Nascer do sol", "Aurora boreal", "Primavera", "Verão", "Outono", "Inverno", "Orquídea", "Margarida", "Tulipa", "Lírio", "Ipê", "Palmeira", "Coqueiro", "Bambu", "Samambaia", "Musgo", "Cogumelo", "Raiz", "Tronco", "Galho", "Espinho", "Pólen", "Cristal", "Diamante", "Ouro", "Petróleo", "Carvão", "Lava", "Recife de coral", "Duna"],
    3: ["Fotossíntese", "Clorofila", "Ecossistema", "Biodiversidade", "Cadeia alimentar", "Efeito estufa", "Aquecimento global", "Camada de ozônio", "Desmatamento", "Queimada", "Erosão", "Assoreamento", "Lençol freático", "Nascente", "Foz", "Delta", "Estuário", "Arquipélago", "Península", "Istmo", "Planalto", "Planície", "Cordilheira", "Cratera", "Gêiser", "Estalactite", "Estalagmite", "Fóssil", "Âmbar", "Quartzo", "Esmeralda", "Rubi", "Safira", "Ametista", "Turmalina", "Magma", "Placa tectônica", "Maré", "Corrente marítima", "Monção", "Solstício", "Equinócio", "Nebulosa", "Buraco negro", "Supernova", "Asteroide", "Satélite natural", "Órbita", "Gravidade", "Ano-luz"],
  },
  transportes: {
    1: ["Carro", "Ônibus", "Moto", "Bicicleta", "Avião", "Navio", "Barco", "Trem", "Metrô", "Caminhão", "Táxi", "Helicóptero", "Foguete", "Ambulância", "Viatura", "Caminhão de bombeiro", "Patinete", "Skate", "Cavalo", "Carroça", "Trator", "Lancha", "Canoa", "Elevador", "Escada rolante", "Carrinho de bebê", "Uber", "Van"],
    2: ["Submarino", "Iate", "Veleiro", "Jet ski", "Balsa", "Transatlântico", "Cruzeiro", "Bonde", "Teleférico", "Bondinho", "Funicular", "Monotrilho", "VLT", "Trem-bala", "Maria-fumaça", "Caminhonete", "Jipe", "Limusine", "Conversível", "Carro de corrida", "Kart", "Buggy", "Quadriciclo", "Motoneta", "Triciclo", "Riquixá", "Tuk-tuk", "Charrete", "Diligência", "Trenó", "Planador", "Ultraleve", "Dirigível", "Balão de ar quente", "Jatinho", "Caça", "Tanque de guerra", "Porta-aviões", "Guindaste", "Empilhadeira", "Retroescavadeira", "Betoneira", "Rolo compressor", "Caminhão-pipa", "Carreta", "Cegonha", "Guincho", "Ônibus espacial", "Disco voador", "Bicicleta elétrica"],
    3: ["Hovercraft", "Hidroavião", "Catamarã", "Gôndola", "Caravela", "Galeão", "Jangada de pesca", "Rebocador", "Quebra-gelo", "Petroleiro", "Draga", "Batiscafo", "Módulo lunar", "Sonda espacial", "Rover", "Estação espacial", "Ônibus articulado", "Ônibus de dois andares", "Motorhome", "Trailer", "Side-car", "Monociclo", "Segway", "Hoverboard", "Asa-delta", "Paraquedas", "Mochila a jato", "Hyperloop", "Maglev", "Bicicleta tandem", "Carro anfíbio", "Carro voador", "Pedágio", "Rodovia", "Viaduto", "Túnel", "Rotatória", "Semáforo", "Faixa de pedestre", "Lombada", "Radar", "Estacionamento", "Baliza", "Câmbio", "Embreagem", "Volante", "Retrovisor", "Para-brisa", "Pneu furado", "Estepe"],
  },
  roupas: {
    1: ["Camiseta", "Calça", "Bermuda", "Short", "Saia", "Vestido", "Blusa", "Casaco", "Jaqueta", "Moletom", "Pijama", "Cueca", "Calcinha", "Sutiã", "Tênis", "Sandália", "Bota", "Chinelo", "Boné", "Gorro", "Cachecol", "Luvas", "Óculos de sol", "Relógio", "Mochila", "Uniforme", "Fantasia", "Biquíni"],
    2: ["Terno", "Gravata", "Gravata-borboleta", "Smoking", "Vestido de noiva", "Véu", "Colete", "Suspensório", "Macacão", "Jardineira", "Avental", "Jaleco", "Capa de chuva", "Sobretudo", "Cardigã", "Regata", "Cropped", "Legging", "Jeans", "Saia longa", "Minissaia", "Maiô", "Sunga", "Roupão", "Camisola", "Pantufa", "Salto alto", "Rasteirinha", "Mocassim", "Galocha", "Chuteira", "Sapatilha", "Tiara", "Presilha", "Brinco de argola", "Piercing", "Tatuagem", "Peruca", "Leque", "Bengala", "Pochete", "Carteira", "Bolsa de mão", "Mala de rodinha", "Lenço", "Bandana", "Viseira", "Cartola", "Coroa", "Capacete"],
    3: ["Sari", "Quimono", "Kilt", "Poncho", "Bombacha", "Sombrero", "Turbante", "Burca", "Toga", "Beca", "Batina", "Hábito", "Farda", "Armadura", "Capa de super-herói", "Espartilho", "Anágua", "Crinolina", "Meia-calça", "Polaina", "Abotoadura", "Broche", "Gargantilha", "Pingente", "Monóculo", "Lenço de bolso", "Boina", "Chapéu-panamá", "Chapéu de palha", "Chapéu de cangaceiro", "Fedora", "Alpargata", "Tamanco", "Coturno", "Scarpin", "Anabela", "Oxford", "Plataforma", "Camisa polo", "Camisa xadrez", "Blazer", "Trench coat", "Parka", "Corta-vento", "Body", "Kaftan", "Pareô", "Saída de praia", "Tule", "Paetê"],
  },
  acoes: {
    1: ["Correr", "Pular", "Dançar", "Cantar", "Dormir", "Comer", "Beber", "Nadar", "Andar", "Rir", "Chorar", "Gritar", "Abraçar", "Beijar", "Escrever", "Ler", "Desenhar", "Pintar", "Cozinhar", "Dirigir", "Brincar", "Jogar", "Tomar banho", "Escovar os dentes", "Lavar louça", "Varrer", "Assobiar", "Bocejar", "Espirrar", "Tossir"],
    2: ["Escalar", "Mergulhar", "Patinar", "Pescar", "Acampar", "Surfar", "Remar", "Malhar", "Alongar", "Meditar", "Rezar", "Fofocar", "Paquerar", "Namorar", "Casar", "Viajar", "Mudar de casa", "Fazer as malas", "Tirar foto", "Gravar vídeo", "Mandar mensagem", "Ligar", "Desligar", "Esconder", "Procurar", "Achar", "Perder", "Ganhar", "Empatar", "Torcer", "Aplaudir", "Vaiar", "Piscar", "Cochilar", "Roncar", "Sonhar", "Acordar", "Espreguiçar", "Tropeçar", "Escorregar", "Cair", "Chutar", "Arremessar", "Agarrar", "Empurrar", "Puxar", "Carregar", "Costurar", "Tricotar", "Plantar"],
    3: ["Procrastinar", "Improvisar", "Negociar", "Barganhar", "Pechinchar", "Hesitar", "Gaguejar", "Sussurrar", "Murmurar", "Resmungar", "Cochichar", "Bisbilhotar", "Espionar", "Disfarçar", "Fingir", "Mentir", "Confessar", "Perdoar", "Agradecer", "Desculpar", "Comemorar", "Brindar", "Homenagear", "Discursar", "Debater", "Votar", "Protestar", "Fazer greve", "Hibernar", "Migrar", "Evaporar", "Derreter", "Congelar", "Ferver", "Fermentar", "Germinar", "Florescer", "Murchar", "Equilibrar", "Malabarizar", "Hipnotizar", "Levitar", "Teletransportar", "Desmaiar", "Ressuscitar", "Soluçar", "Arrotar", "Coçar", "Fazer careta", "Dar estrelinha"],
  },
  festas: {
    1: ["Natal", "Ano-novo", "Páscoa", "Carnaval", "Aniversário", "Festa junina", "Dia das mães", "Dia dos pais", "Dia das crianças", "Halloween", "Casamento", "Batizado", "Formatura", "Chá de bebê", "Papai Noel", "Coelhinho da Páscoa", "Ovo de Páscoa", "Árvore de Natal", "Presépio", "Fogos de artifício", "Bolo de aniversário", "Vela de aniversário", "Brigadeiro de festa", "Balões", "Confete", "Serpentina", "Fantasia", "Quentão"],
    2: ["Dia dos namorados", "Dia do professor", "Tiradentes", "Sete de setembro", "Finados", "Dia do trabalho", "Consciência negra", "Proclamação da República", "Sexta-feira santa", "Corpus Christi", "Quarta-feira de cinzas", "Réveillon", "Ceia de Natal", "Amigo secreto", "Panetone", "Peru de Natal", "Rabanada", "Chocotone", "Pisca-pisca", "Guirlanda", "Renas", "Trenó do Papai Noel", "Fogueira", "Pau de sebo", "Pescaria", "Correio elegante", "Bandeirinhas", "Casamento caipira", "Chá de panela", "Chá revelação", "Despedida de solteiro", "Bodas de ouro", "Lua de mel", "Buquê", "Daminha", "Padrinho", "Madrinha", "Festa à fantasia", "Festa do pijama", "Churrasco de domingo", "Happy hour", "Open bar", "Mesversário", "Debutante", "Valsa dos quinze anos", "Gostosuras ou travessuras", "Abóbora de Halloween", "Dia de Reis", "Dia da mentira", "Black Friday"],
    3: ["Hanukkah", "Diwali", "Ano-novo chinês", "Dia de los Muertos", "Ação de Graças", "Saint Patrick", "Oktoberfest", "Tomatina", "Festival das Lanternas", "Holi", "Ramadã", "Yom Kippur", "Pessach", "Pentecostes", "Advento", "Quaresma", "Epifania", "Folia de Reis", "Lavagem do Bonfim", "Festa de Iemanjá", "Bumba meu boi", "Cavalhadas", "Festa do Divino", "Círio de Nazaré", "Festival de Parintins", "Micareta", "Bloco de rua", "Abadá", "Camarote", "Desfile das escolas", "Comissão de frente", "Mestre-sala", "Porta-bandeira", "Bateria da escola", "Carro alegórico", "Samba-enredo", "Rainha de bateria", "Rei Momo", "Marchinha", "Baile de máscaras", "Réveillon na praia", "Sete ondas", "Lentilha", "Romã", "Uva-passa", "Roupa branca", "Contagem regressiva", "Simpatia", "Promessa de ano-novo", "Bolo de casamento"],
  },
  casa: {
    1: ["Quarto", "Sala", "Cozinha", "Banheiro", "Varanda", "Quintal", "Garagem", "Telhado", "Parede", "Chão", "Teto", "Escada", "Porta", "Janela", "Portão", "Muro", "Chuveiro", "Pia", "Vaso sanitário", "Torneira", "Banheira", "Armário", "Gaveta", "Prateleira", "Lâmpada", "Interruptor", "Campainha", "Capacho"],
    2: ["Sótão", "Porão", "Lavanderia", "Despensa", "Closet", "Escritório", "Área de serviço", "Churrasqueira", "Piscina", "Edícula", "Corredor", "Hall de entrada", "Sacada", "Chaminé", "Lareira", "Calha", "Rufo", "Telha", "Tijolo", "Cimento", "Azulejo", "Piso", "Rodapé", "Batente", "Persiana", "Veneziana", "Grade", "Interfone", "Caixa d'água", "Bomba d'água", "Aquecedor", "Ar-condicionado", "Ventilador de teto", "Cortina blackout", "Beliche", "Berço", "Rede", "Poltrona", "Pufe", "Rack", "Aparador", "Cristaleira", "Criado-mudo", "Penteadeira", "Sapateira", "Cabideiro", "Varal de chão", "Tanque", "Máquina de lavar", "Secadora"],
    3: ["Clarabóia", "Mezanino", "Pé-direito", "Laje", "Viga", "Pilar", "Alicerce", "Reboco", "Massa corrida", "Rejunte", "Gesso", "Sanca", "Forro de PVC", "Drywall", "Ralo", "Sifão", "Registro", "Disjuntor", "Quadro de luz", "Fiação", "Para-raios", "Antena parabólica", "Placa solar", "Cisterna", "Fossa", "Poço artesiano", "Cerca elétrica", "Concertina", "Olho mágico", "Tranca", "Ferrolho", "Pergolado", "Caramanchão", "Jardim de inverno", "Horta", "Composteira", "Canil", "Galinheiro", "Casinha de cachorro", "Escada caracol", "Elevador privativo", "Sauna", "Ofurô", "Hidromassagem", "Home theater", "Adega", "Brinquedoteca", "Quarto de hóspedes", "Suíte", "Lavabo"],
  },
  escola: {
    1: ["Professor", "Aluno", "Sala de aula", "Lousa", "Giz", "Carteira", "Mochila", "Lápis", "Caneta", "Borracha", "Caderno", "Livro", "Lancheira", "Recreio", "Merenda", "Prova", "Nota", "Lição de casa", "Férias", "Uniforme", "Diretor", "Pátio", "Quadra", "Fila", "Chamada", "Boletim", "Tesoura sem ponta", "Massinha"],
    2: ["Matemática", "Português", "História", "Geografia", "Ciências", "Inglês", "Educação física", "Artes", "Química", "Física", "Biologia", "Filosofia", "Redação", "Tabuada", "Ditado", "Cola", "Colar na prova", "Recuperação", "Reprovar", "Passar de ano", "Formatura", "Feira de ciências", "Excursão", "Biblioteca", "Laboratório", "Coordenador", "Inspetor", "Secretaria", "Cantina", "Bebedouro", "Apontador", "Estojo", "Marca-texto", "Corretivo", "Mapa", "Globo terrestre", "Dicionário", "Atlas", "Apostila", "Trabalho em grupo", "Seminário", "Vestibular", "ENEM", "Faculdade", "Mestrado", "Doutorado", "Bolsa de estudos", "Intercâmbio", "Matrícula", "Calouro"],
    3: ["Trigonometria", "Equação", "Fração", "Porcentagem", "Geometria", "Álgebra", "Logaritmo", "Teorema de Pitágoras", "Raiz quadrada", "Gramática", "Concordância", "Crase", "Ortografia", "Sujeito", "Predicado", "Verbo", "Adjetivo", "Substantivo", "Tabela periódica", "Átomo", "Molécula", "Célula-tronco", "Mitose", "Fotossíntese", "Evolução", "Revolução Francesa", "Idade Média", "Renascimento", "Iluminismo", "Guerra Fria", "Primeira Guerra Mundial", "Segunda Guerra Mundial", "Império Romano", "Grécia Antiga", "Egito Antigo", "Hemisfério", "Latitude", "Longitude", "Meridiano", "Trópico de Capricórnio", "Linha do Equador", "Fuso horário", "Relevo", "Clima", "Bioma", "TCC", "Monografia", "Banca", "Orientador", "Diploma"],
  },
};
for (const [cat, byDiff] of Object.entries(EXTRA)) {
  BANK[cat] = BANK[cat] || {};
  const seen = new Set(Object.values(BANK[cat]).flat().map(w => w.toLowerCase()));
  for (const [d, list] of Object.entries(byDiff)) {
    const novas = list.filter(w => { const k = w.toLowerCase(); if (seen.has(k)) return false; seen.add(k); return true; });
    BANK[cat][d] = (BANK[cat][d] || []).concat(novas);
  }
}

// lista plana { w, cat, d } — o jogo filtra por categoria e dificuldade
const WORDS = [];
for (const [cat, byDiff] of Object.entries(BANK)) for (const [d, list] of Object.entries(byDiff)) for (const w of list) WORDS.push({ w, cat, d: Number(d) });

module.exports = { CATS, BANK, WORDS };
