// Palavras do jogo, por categoria. pt-BR, coisas do dia a dia e atuais.
const CATEGORIES = [
  { id: 'comida', name: 'Comida', emoji: '🍕' },
  { id: 'animais', name: 'Animais', emoji: '🐾' },
  { id: 'lugares', name: 'Lugares', emoji: '🗺️' },
  { id: 'objetos', name: 'Objetos', emoji: '📦' },
  { id: 'profissoes', name: 'Profissões', emoji: '👩‍⚕️' },
  { id: 'famosos', name: 'Famosos', emoji: '⭐' },
  { id: 'filmes', name: 'Filmes e Séries', emoji: '🎬' },
  { id: 'esportes', name: 'Esportes', emoji: '⚽' },
  { id: 'marcas', name: 'Marcas', emoji: '🏷️' },
  { id: 'casa', name: 'Coisas de casa', emoji: '🏠' },
  { id: 'internet', name: 'Internet e memes', emoji: '🌐' },
  { id: 'musica', name: 'Música', emoji: '🎵' },
];

const WORDS = {
  comida: ['Pizza','Brigadeiro','Coxinha','Feijoada','Pastel','Churrasco','Lasanha','Hambúrguer','Sushi','Pão de Queijo','Açaí','Tapioca','Moqueca','Picanha','Farofa','Cocada','Pudim','Bolo de Chocolate','Sorvete','Salgadinho','Pipoca','Cachorro-Quente','Empada','Kibe','Esfirra','Yakisoba','Temaki','Lámen','Nhoque','Risoto','Panqueca','Waffle','Torta de Limão','Mousse','Paçoca','Quindim','Vatapá','Baião de Dois','Arroz Carreteiro','Escondidinho','Strogonoff','Maionese','Vinagrete','Guaraná','Caldo Verde','Canjica','Rabanada','Beijinho'],
  animais: ['Cachorro','Gato','Leão','Tigre','Elefante','Girafa','Macaco','Urso','Lobo','Raposa','Coelho','Cavalo','Vaca','Porco','Galinha','Pato','Tartaruga','Cobra','Jacaré','Tucano','Papagaio','Arara','Coruja','Águia','Tubarão','Baleia','Golfinho','Polvo','Peixe-Boi','Capivara','Onça','Jaguatirica','Preguiça','Tamanduá','Quati','Gambá','Morcego','Camundongo','Rato','Esquilo','Zebra','Hipopótamo','Rinoceronte','Panda','Coala','Canguru','Pinguim','Foca'],
  lugares: ['Praia','Escola','Shopping','Hospital','Aeroporto','Academia','Cinema','Igreja','Padaria','Farmácia','Banco','Praça','Parque','Zoológico','Museu','Biblioteca','Estádio','Restaurante','Supermercado','Feira','Metrô','Rodoviária','Delegacia','Cartório','Salão de Beleza','Barbearia','Consultório','Cachoeira','Fazenda','Montanha','Deserto','Floresta','Ilha','Vulcão','Castelo','Palácio','Favela','Condomínio','Universidade','Creche','Cemitério','Presídio','Boate','Feira Livre','Camping','Motel','Hotel','Aquário','Piscina','Teatro'],
  objetos: ['Celular','Carregador','Fone de Ouvido','Chave','Óculos','Relógio','Mochila','Carteira','Guarda-Chuva','Caneta','Caderno','Livro','Tesoura','Controle Remoto','Televisão','Geladeira','Fogão','Micro-ondas','Liquidificador','Ventilador','Espelho','Escova de Dente','Sabonete','Toalha','Travesseiro','Cobertor','Sofá','Cadeira','Mesa','Armário','Panela','Faca','Garfo','Colher','Copo','Prato','Vassoura','Rodo','Balde','Mala','Bicicleta','Skate','Patins','Câmera','Pilha','Fita Adesiva','Chaveiro','Cortina','Frigideira','Caneca','Almofada','Tablet','Pulseira','Freezer','Batedeira','Ar-Condicionado'],
  profissoes: ['Médico','Enfermeiro','Professor','Advogado','Engenheiro','Dentista','Veterinário','Policial','Bombeiro','Motorista','Piloto','Cozinheiro','Garçom','Cabeleireiro','Barbeiro','Eletricista','Encanador','Pedreiro','Pintor','Padeiro','Açougueiro','Farmacêutico','Fisioterapeuta','Psicólogo','Nutricionista','Contador','Jornalista','Fotógrafo','Ator','Cantor','Músico','Dançarino','Youtuber','Streamer','Influenciador','Programador','Designer','Arquiteto','Astronauta','Marinheiro','Agricultor','Pescador','Costureira','Zelador','Segurança','Recepcionista','Vendedor','Juiz','Economista'],
  famosos: ['Anitta','Neymar','Ivete Sangalo','Fátima Bernardes','Silvio Santos','Xuxa','Gusttavo Lima','Ludmilla','Pabllo Vittar','Whindersson Nunes','Luciano Huck','Ana Maria Braga','Marília Mendonça','Roberto Carlos','Caetano Veloso','Gilberto Gil','Sandy','Junior','Wesley Safadão','Claudia Leitte','Larissa Manoela','Bruna Marquezine','Sasha Meneghel','Pelé','Ronaldinho Gaúcho','Gabigol','Vini Jr','Rafinha Bastos','Fábio Porchat','Tirullipa','Casimiro','Felca','Cristiano Ronaldo','Lionel Messi','Taylor Swift','Beyoncé','Rihanna','Ariana Grande','Dua Lipa','Bad Bunny','Shakira','Elon Musk','Barack Obama','Oprah Winfrey','Selena Gomez','Justin Bieber','MrBeast','Zendaya','Tom Holland'],
  filmes: ['Vingadores','Homem-Aranha','Batman','Superman','Star Wars','Harry Potter','Senhor dos Anéis','Frozen','Toy Story','Shrek','Divertida Mente','Barbie','Duna','Coringa','John Wick','Matrix','Jurassic Park','Velozes e Furiosos','Missão Impossível','Stranger Things','Round 6','Wandinha','La Casa de Papel','Bridgerton','Friends','The Office','Breaking Bad','Game of Thrones','Vikings','Peaky Blinders','Chaves','A Grande Família','Avatar','Titanic','Karatê Kid','Homem de Ferro','Pantera Negra','Mulher Maravilha','Aquaman','Minions','Enrolados','Aladdin','Procurando Nemo','Rei Leão','Zootopia','Encanto','Vaiana','Wicked'],
  esportes: ['Futebol','Vôlei','Basquete','Handebol','Tênis','Natação','Corrida','Ciclismo','Skate','Surfe','Judô','Karatê','Boxe','MMA','Ginástica','Atletismo','Golfe','Beisebol','Rúgbi','Futsal','Vôlei de Praia','Xadrez','Sinuca','Boliche','Patinação','Esgrima','Remo','Vela','Triatlo','Maratona','Capoeira','Jiu-Jitsu','Taekwondo','Halterofilismo','Ginástica Artística','Polo Aquático','Hipismo','Tiro com Arco','Badminton','Squash','Escalada','Slackline','Skimboard','Motocross','Fórmula 1','Vôlei Sentado','Futebol Americano','Peteca'],
  marcas: ['Nike','Adidas','Puma','Coca-Cola','Pepsi','McDonald\'s','Burger King','Habib\'s','Netflix','Spotify','YouTube','Instagram','TikTok','WhatsApp','Facebook','Google','Apple','Samsung','Xiaomi','Motorola','Ifood','Uber','99','Nubank','Itaú','Bradesco','Havaianas','Natura','Boticário','Americanas','Magazine Luiza','Casas Bahia','Mercado Livre','Shopee','Amazon','Ford','Chevrolet','Fiat','Volkswagen','Honda','Yamaha','Red Bull','Guaraná Antarctica','Skol','Brahma','Heineken','Lacta','Nestlé','Danone'],
  casa: ['Sofá','Cama','Travesseiro','Cobertor','Lençol','Cortina','Tapete','Almofada','Espelho','Armário','Guarda-Roupa','Estante','Mesa de Centro','Geladeira','Fogão','Micro-ondas','Liquidificador','Máquina de Lavar','Ferro de Passar','Aspirador de Pó','Vassoura','Rodo','Pia','Torneira','Chuveiro','Vaso Sanitário','Escova de Dente','Sabonete','Shampoo','Toalha','Panela','Frigideira','Faca','Garfo','Colher','Prato','Copo','Xícara','Jarra','Luminária','Ventilador','Ar-Condicionado','Controle Remoto','Televisão','Wi-Fi','Tomada','Chinelo','Freezer','Batedeira','Secadora'],
  internet: ['Meme','Reels','Stories','Live','TikTok','Print','Stalker','Ship','Cringe','Hater','Fake News','Deepfake','Hashtag','Trend','Viral','Bug','Lag','Wi-Fi','Emoji','Sticker','Podcast','Vlog','Streamer','Youtuber','Influenciador','Cancelamento','Textão','Bafão','Zap','Grupo de Zap','Enquete','Curtida','Comentário','Compartilhar','Seguidor','Algoritmo','Feed','Chat','Pix','QR Code','VPN','FYP','Reação','Áudio de Zap','Nostalgia','Print da Conversa','Login','Senha','Notificação'],
  musica: ['Funk','Sertanejo','Pagode','Samba','Axé','Forró','MPB','Rock','Pop','Rap','Trap','Reggae','Reggaeton','Bossa Nova','Piseiro','Brega Funk','Gospel','Eletrônica','Hip Hop','Arrocha','Vanera','Sofrência','Chorinho','Frevo','Maracatu','K-pop','Jazz','Blues','Heavy Metal','Punk','Ópera','Violão','Guitarra','Bateria','Teclado','Microfone','Show','Festival','Karaokê','Playlist','Fone de Ouvido','Caixa de Som','Baile Funk','Roda de Samba','Clipe','Turnê','DJ','Banda'],
};

// Pares parecidos para o modo Mister White: [palavra dos inocentes, palavra do Mister White]
const PAIRS = {
  comida: [['Pizza','Lasanha'],['Coxinha','Kibe'],['Feijoada','Strogonoff'],['Pastel','Esfirra'],['Sushi','Temaki'],['Brigadeiro','Beijinho'],['Cocada','Paçoca'],['Bolo de Chocolate','Pudim'],['Sorvete','Açaí'],['Hambúrguer','Cachorro-Quente'],['Churrasco','Picanha'],['Nhoque','Risoto'],['Panqueca','Waffle'],['Quindim','Canjica'],['Mousse','Torta de Limão'],['Yakisoba','Lámen'],['Farofa','Vinagrete'],['Empada','Rabanada']],
  animais: [['Cachorro','Lobo'],['Gato','Onça'],['Leão','Tigre'],['Cavalo','Zebra'],['Vaca','Porco'],['Pato','Galinha'],['Águia','Coruja'],['Arara','Papagaio'],['Tubarão','Golfinho'],['Baleia','Peixe-Boi'],['Capivara','Quati'],['Preguiça','Tamanduá'],['Morcego','Gambá'],['Camundongo','Rato'],['Esquilo','Camundongo'],['Hipopótamo','Rinoceronte'],['Panda','Coala'],['Pinguim','Foca']],
  lugares: [['Praia','Piscina'],['Shopping','Feira'],['Hospital','Consultório'],['Escola','Universidade'],['Cinema','Teatro'],['Padaria','Restaurante'],['Banco','Cartório'],['Parque','Praça'],['Zoológico','Aquário'],['Museu','Biblioteca'],['Estádio','Academia'],['Cachoeira','Fazenda'],['Montanha','Vulcão'],['Deserto','Floresta'],['Castelo','Palácio'],['Favela','Condomínio'],['Presídio','Delegacia'],['Hotel','Motel']],
  objetos: [['Panela','Frigideira'],['Faca','Tesoura'],['Garfo','Colher'],['Copo','Caneca'],['Sofá','Cadeira'],['Mesa','Armário'],['Toalha','Cobertor'],['Travesseiro','Almofada'],['Vassoura','Rodo'],['Balde','Mala'],['Bicicleta','Skate'],['Celular','Tablet'],['Relógio','Pulseira'],['Geladeira','Freezer'],['Fogão','Micro-ondas'],['Liquidificador','Batedeira'],['Ventilador','Ar-Condicionado'],['Chave','Chaveiro']],
  profissoes: [['Médico','Enfermeiro'],['Advogado','Juiz'],['Pedreiro','Eletricista'],['Cabeleireiro','Barbeiro'],['Cozinheiro','Padeiro'],['Ator','Cantor'],['Youtuber','Streamer'],['Programador','Designer'],['Piloto','Motorista'],['Policial','Bombeiro'],['Veterinário','Dentista'],['Fisioterapeuta','Nutricionista'],['Jornalista','Fotógrafo'],['Agricultor','Pescador'],['Arquiteto','Engenheiro'],['Contador','Economista'],['Zelador','Segurança'],['Recepcionista','Vendedor']],
  famosos: [['Anitta','Ludmilla'],['Neymar','Vini Jr'],['Pelé','Ronaldinho Gaúcho'],['Cristiano Ronaldo','Lionel Messi'],['Taylor Swift','Ariana Grande'],['Beyoncé','Rihanna'],['Silvio Santos','Luciano Huck'],['Xuxa','Ana Maria Braga'],['Sandy','Claudia Leitte'],['Caetano Veloso','Gilberto Gil'],['Gusttavo Lima','Wesley Safadão'],['Whindersson Nunes','Fábio Porchat'],['Larissa Manoela','Bruna Marquezine'],['Justin Bieber','Tom Holland'],['Selena Gomez','Zendaya'],['Elon Musk','MrBeast'],['Shakira','Dua Lipa'],['Casimiro','Felca']],
  filmes: [['Vingadores','Homem de Ferro'],['Batman','Superman'],['Homem-Aranha','Pantera Negra'],['Mulher Maravilha','Aquaman'],['Star Wars','Duna'],['Harry Potter','Senhor dos Anéis'],['Frozen','Encanto'],['Toy Story','Shrek'],['Divertida Mente','Procurando Nemo'],['Enrolados','Aladdin'],['Rei Leão','Zootopia'],['John Wick','Matrix'],['Jurassic Park','Velozes e Furiosos'],['Stranger Things','Wandinha'],['La Casa de Papel','Round 6'],['Friends','The Office'],['Breaking Bad','Peaky Blinders'],['Game of Thrones','Vikings']],
  esportes: [['Futebol','Futsal'],['Vôlei','Vôlei de Praia'],['Basquete','Handebol'],['Judô','Jiu-Jitsu'],['Karatê','Taekwondo'],['Boxe','MMA'],['Natação','Polo Aquático'],['Ciclismo','Motocross'],['Skate','Slackline'],['Tênis','Badminton'],['Golfe','Squash'],['Corrida','Maratona'],['Remo','Vela'],['Sinuca','Boliche'],['Atletismo','Ginástica Artística'],['Esgrima','Tiro com Arco'],['Fórmula 1','Motocross'],['Triatlo','Maratona']],
  marcas: [['Nike','Adidas'],['Coca-Cola','Pepsi'],['McDonald\'s','Burger King'],['Instagram','TikTok'],['WhatsApp','Facebook'],['Samsung','Xiaomi'],['Ford','Chevrolet'],['Fiat','Volkswagen'],['Honda','Yamaha'],['Skol','Brahma'],['Nestlé','Danone'],['Americanas','Casas Bahia'],['Magazine Luiza','Mercado Livre'],['Shopee','Amazon'],['Nubank','Itaú'],['Uber','99'],['Natura','Boticário'],['Lacta','Nestlé']],
  casa: [['Cama','Sofá'],['Travesseiro','Almofada'],['Cobertor','Lençol'],['Cortina','Tapete'],['Armário','Guarda-Roupa'],['Estante','Mesa de Centro'],['Geladeira','Freezer'],['Fogão','Micro-ondas'],['Liquidificador','Batedeira'],['Máquina de Lavar','Secadora'],['Ferro de Passar','Aspirador de Pó'],['Vassoura','Rodo'],['Pia','Torneira'],['Chuveiro','Vaso Sanitário'],['Panela','Frigideira'],['Prato','Copo'],['Xícara','Jarra'],['Ventilador','Ar-Condicionado']],
  internet: [['Meme','Trend'],['Reels','TikTok'],['Stories','Live'],['Curtida','Comentário'],['Seguidor','Influenciador'],['Hater','Stalker'],['Fake News','Deepfake'],['Cringe','Bafão'],['Zap','Grupo de Zap'],['Podcast','Vlog'],['Youtuber','Streamer'],['Bug','Lag'],['Login','Senha'],['Emoji','Sticker'],['Pix','QR Code'],['Print','Print da Conversa'],['Feed','Algoritmo'],['Textão','Bafão']],
  musica: [['Funk','Brega Funk'],['Sertanejo','Piseiro'],['Samba','Pagode'],['Axé','Forró'],['Rap','Trap'],['Reggae','Reggaeton'],['Rock','Punk'],['Pop','K-pop'],['Jazz','Blues'],['Chorinho','Frevo'],['Violão','Guitarra'],['Bateria','Teclado'],['Show','Festival'],['Karaokê','Playlist'],['Baile Funk','Roda de Samba'],['Clipe','Turnê'],['DJ','Banda'],['Vanera','Sofrência']],
};

module.exports = { CATEGORIES, WORDS, PAIRS };
